### ISSUE TITLE
Sway and Wayland Window Decoration

### ISSUE THREAD

**Issue by joshuataylor** [Alex313031/thorium#102]
**System Details**
 - OS: ArchLinux (6.1.8), Wayland (1.21.0-2), Sway (r7058.36f627d0-1)
 - Thorium Version 109.0.5361.0

**Problem**
On Sway and Wayland, a weird border appears inside Thorium when running with Wayland enabled:
![2023-01-25_19-02](https://user-images.githubusercontent.com/225131/214548197-04d23d23-0bd4-475e-abaf-737cfac45c0b.png)

```sh
thorium-browser --ozone-platform-hint=auto
```

Running just `thorium-browser` runs in xwayland, and doesn't exhibit this behaviour.

Toggling "Use system title bar and border" in `chrome://settings/?search=Use+system+title+bar+and+border` fixes it, but it has to be toggled each time:

![123](https://user-images.githubusercontent.com/225131/214548391-58de082d-32b6-4062-b5de-9579a7d711c3.gif)

**Comment by Alex313031** [comment]
@joshuataylor Im not sure how to fix this.

**Comment by WingofaGriffin** [comment]
I am not able to reproduce this, as it looks fine on my machine. What I do find curious is that making a `.config/thorium-browser-flags.conf` doesn't work the same as chromium, instead manually adding the flag to the launcher in KDE.
