### ISSUE TITLE
Patch to allow Chromium zero-copy VaapiVideoDecoder to work when va-api exports dma-buf planes as disjoint, such as with AMD Mesa

### ISSUE THREAD

**Issue by joshuataylor** [Alex313031/thorium#103]
**Is your feature request related to a problem? Please describe.**
A patch was posted on the ArchLinux forums, where thubble has written a patch for AMDGPU issues with VAAPI & Chromium. I have tested it and it works.

See here: https://bbs.archlinux.org/viewtopic.php?pid=2080653#p2080653

**Describe the solution you'd like, including relevant patches or source**
Consider the patch for inclusion in Thorium. <3

**Comment by xangelix** [comment]
This patch is similarly required for VAAPI on my system, inclusion would be greatly appreciated!
ozoneplatform: x11

```
Trying display: wayland
vainfo: VA-API version: 1.18 (libva 2.17.1)
vainfo: Driver version: Mesa Gallium driver 23.0.2 for AMD Radeon RX 6900 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.0-rc6)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

**Comment by xangelix** [comment]
@gz83 from the patch author at the bbs link:

> I posted it in the original Chromium bug for VaapiVideoDecoder on Linux, but didn't get any feedback. It's not ready to submit for merge anyway (a lot of "hack" comments), and I'm not really sure about signing the CLA, so I don't know if I'm even going to try to submit it.

and in their update post https://bbs.archlinux.org/viewtopic.php?pid=2086202#p2086202 :

> It looks like the Chromium devs added some infrastructure for supporing AMD's disjoint VAAPI planes, but it's not yet complete. I tried using the helper methods they created to bind disjoint planes, but it actually caused a GPU reset. So, it still needs this hacky patch. Hopefully they'll get it actually working soon.
