### ISSUE TITLE
Brave features hangouts and media router and webtorrent

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#105]
Hello, it will be great to add some open source brave web browser features like : enbale/disable hangouts, enable/disable media router, enable/disable webtorrent and tor network ! it can make browseer more spped and add some enhancementswhen needed,  thank you !

**Comment by Alex313031** [comment]
@trimechee I think it would be possible to add a chrome://flags flag to disable media router. Hangouts is integrated in Thorium, and there is no reason to remove it. WebTorrent is specific to brave and not included with other chromium browsers.

**Comment by trimechee** [comment]
Wonderful !  Thank you !

**Comment by Alex313031** [comment]
@trimechee Latest release has a new flag chrome://flags/#media-router in the latest M111 linux and windows releases.

**Comment by trimechee** [comment]
Awesome ! Thank you :) 💯 🥇
