### ISSUE TITLE
thorium-browser-unstable should use flags

### ISSUE THREAD

**Issue by Henry-Hiles** [Alex313031/Thorium#106]
Hello there! This browser is great, and I have been using it for a while, but I have noticed that `~/.config/thorium-flags` is not loaded if you run `thorium-browser-unstable`. It would be great if this used the flags, especially as the `.desktop` file uses this by default. Thanks.

**Comment by Henry-Hiles** [comment]
Also, maybe make it so that incognito mode is not used by default, thanks.

**Comment by dmig** [comment]
In Arch that thing is implemented using launcher script:
```sh
!/bin/bash

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

# Allow users to override command-line options
if [[ -f $XDG_CONFIG_HOME/chrome-flags.conf ]]; then
   CHROME_USER_FLAGS="$(cat $XDG_CONFIG_HOME/thorium-flags.conf)"
fi

# Launch
exec /opt/chromium.org/thorium/thorium-browser-unstable $CHROME_USER_FLAGS "$@"
```

Just replace `/usr/bin/thorium-browser-unstable` with it.
If you're using deb-based distro and installed via repository, and want to keep launcher -- execute `dpkg-divert /usr/bin/thorium-browser-unstable`.

Nothing to be done in Thorium.

**Comment by Henry-Hiles** [comment]
Oh yes I see. Well then the desktop file should use the wrapped version by default.

**Comment by Alex313031** [comment]
@dmig @Henry-Hiles I will be adding this, as well as a desktop action to use a temporary profile to the next release. I will add it directly to the wrapper, so whether calling from the cmdline or using the desktop file it will use your args

**Comment by Alex313031** [comment]
@dmig @Henry-Hiles @gz83 Added: 
https://github.com/Alex313031/Thorium/commit/04ac4a38559bd191c422c339973c027138cf8a15#diff-a291eea3373fb3acc4c10841648a94f52d46f0b64f761d202a1ddb5145a37a84

**Comment by Henry-Hiles** [comment]
Thanks!
