### ISSUE TITLE
FYI: 

### ISSUE THREAD

**Issue by tomByrer** [Alex313031/thorium#109]
Jon Sneyers of JPEG XL is pushing Thorium:
(I might have been the one who let him know?)
](https://twitter.com/jonsneyers/status/1626878007091527680)

**Comment by ziemek99** [comment]
I'm pushing it as well from my [JPEG XL in Edge guide](https://gist.github.com/ziemek99/6295222469218427bb160cf849cdaa0c) since it became irrelevant because of JPEG XL's removal from Chromium.

**Comment by Alex313031** [comment]
@ziemek99 @tomByrer We are working on it as we speak. https://github.com/Alex313031/Thorium/issues/104

**Comment by Alex313031** [comment]
@tomByrer @ziemek99 @jonsneyers Thorium M110 is out, with full jpeg-xl support! (And it is built with libjxl 8.0, instead of 7.2) > https://github.com/Alex313031/Thorium/releases/tag/M110.0.5481.178
