### ISSUE TITLE
x86-64-v3 build should not use VAES instruction

### ISSUE THREAD

**Issue by ms178** [Alex313031/thorium#112]
Hey @Alex313031,

I've noticed that you used `-mvaes` in your x86-64-v3 config. Unfortunately that instruction is actually [not supported on Haswell](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html), if you don't care about lower-end Haswell SKUs, you could use `-maes` instead which is supported on Haswell-EP and mainstream i3 - i7 Haswell-CPUs but not on Pentiums and Celerons of that generation.

Have a look over here for some [additional changes](https://github.com/ms178/Thorium/commit/b19632e19c17e1e36b928cb56864bab2af267acc) to the Rust flags which you could also set with x86-64-v3. That way you get all the target features implied by the architecture without having to list all of them individually and only add some (like AES) that are not implied already. There might be more instructions that are supported by all x86-64-v3-compatible CPUs that could be added for making maximum use of the available CPU features. In the end it comes close to Haswell anyway (minus the ones AMD didn't support with their first AVX2-capable CPU). As I only care about Haswell-EP, I didn't bother to research that further.

**Comment by Alex313031** [comment]
@ms178 Actually, I am using that as per RobRich's guidance. I use it it in the regular builds too. I have run the regular builds on sandy bridge and the x86-64-v3 on haswell. Both configs have -maes and -mvaes. mvaes isn't a true instruction set, unlike most of the march flags that gcc/llvm accepts. All it does is promote certain aes instructions to use AVX registers. So, since all CPU's with AVX2 and most with AVX will support aes, it is not a problem to enable -mvaes.

**Comment by ms178** [comment]
I get an "illegal instruction" warning when using `-mvaes` to compile qt5-base though. I've tried it out with other projects and didn't notice any harm though. It is a bit strange that it isn't listed for other AVX2-supporting architectures in the GCC overview then which I linked above but is only mentioned explicitly for use on newer architectures.

**Comment by ms178** [comment]
@Alex313031 Do you have some documentation on this claim? I found the following paper on VAES which backs up the GCC documentation as it implies that the CPU needs to support VAES in hardware to be benefical and that it was first introduced with Ice Lake in 2018: https://eprint.iacr.org/2021/1493.pdf (see "History of VAES" section in the second row on the first page) which is way newer than the x86-64-v3 baseline. 

While using it on Thorium might not cause harm today on older CPU generations as it probably isn't generated or a no-op, I think it is better to follow the GCC documentation and hence should not be used on x86-64-v3. `-maes` is fine though for most CPUs that are compatible with x86-64-v3.

**Comment by Alex313031** [comment]
@ms178 Interesting. @RobRich999 what do you think about this.

**Comment by RobRich999** [comment]
AFAIK, I originally went by....

https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/X86/X86.td

def FeatureVAES    : SubtargetFeature<"vaes", "HasVAES", "true",
                       "Promote selected AES instructions to AVX512/AVX registers",
                        [FeatureAVX, FeatureAES]>;

...., which makes it look like AVX should be a baseline.

Though skimming further down,  FeatureVAES is conditioned on IceLake, Zen3, and later.

Interestingly enough "-mvaes" is even in my AVX builds, which target Sandybridge, so it is likely LLVM is not promoting any AES instructions to VEAS for Chromium source anyway. So, yeah, toss it from the build config.

I will change my diffs as well.

**Comment by Alex313031** [comment]
@RobRich999 @ms178 Thanks Robert. all thorium build configs will be updated

**Comment by Alex313031** [comment]
@ms178 Removed -mvaes from throughout the thorium tree. Now, all builds are built only with -mavx -maes and -pclmul. Any CPU supporting AVX is guaranteed to have at least these instructions.

**Comment by ms178** [comment]
@Alex313031 Great that I could be of help here! By the way, is there an ETA for a x86-64-v3 build and in which repo are you releasing such a version?

**Comment by ms178** [comment]
> Will there be a march=alderlake version? It's instruction set is close to zen3/zen4/tigerlake and these CPUs have vaes/sha-ni/avx2, zen4 and tigerlake also have avx512.

Instead of having a seperate build for every possible CPU architecture out there (which is hardly maintainable), it would make more sense to have a x86-64-v4 build for these newer architectures (maybe with some added instructions that are common on all of them) to stay compatible with a wider range of CPU architectures.

At least that was the intent when inventing these feature levels.

**Comment by ms178** [comment]
> v4 is just v3+avx512f, ≈march=skylake-avx512, early skylake-x does not have vaes/sha-ni. you can make it work for all CPUs with similar instruction sets with -march=alderlake -mtune=generic

You can make it work doesn't mean it is the best optimized for these more feature-rich architectures as x86-64-v4 mandates avx512f, avx512bw, avx512cd, avx512dq and avx512vl. Alder Lake client CPUs do not support any of those, so such an Alder Lake target would only serve a small subset of the overall user base and is close enough to x86-64-v3 to really matter. That's unfortunate for anyone owning one of these. So I totally get that you want to lobby for such an Alder Lake build, but the overall picture is rather grim for that happening as these are just too close to x86-64-v3; and if there were such an Alder Lake build, every Zen-owner would want his own build, too and Alex would end up with a big Zoo of builds to maintain. 

In the end, it is up to Alex to decide which CPU architectures he wants to maintain himself. I hope there will be a source PKGBUILD that people could customize with their favorite architecture/extra patches on their own as Alex and his team cannot possibly handle all theses whishes by himself.

**Comment by Alex313031** [comment]
@ms178 What CPU do you have, like what would you be running it on?

**Comment by Alex313031** [comment]
@ms178 @arm64-v9a The thing with AVX 512 is:

AVX and AVX2 will cause a CPU to downclock (the VEX offset frequency), but only when running "high intensity loads", the definition of which changes from CPU to CPU, firmware to firmware, and microcode to microcode. But I have never seen Thorium cause this. However, because of AVX512's even higher power draw when running, CPU's will downclock themselves whenever ANY avx512 instruction is running, even if it just one thread. While on some motherboards you can VEX offsets entirely (like what would be used for overclocking, and at the expense of heat and power draw), not everything supports this, especially mainstream laptops. The overall effect is that compiling Thorium for avx512 could very well cause it to actually perform *worse* than a vanilla Chromium build, with the decrease in processor speed outweighing any compiler benefits. This, coupled with the fact that a very large amount of users will not have CPUs that have AVX512 anyway, is why I would not make regular releases based on this. A PKGBUILD would not suffice, you would have to make a seperate BUILD.gn or .patch file. The relevant two files that control all of thoriums compiler optimizations are here > https://github.com/Alex313031/thorium/blob/main/src/build/config/compiler/BUILD.gn and here > https://github.com/Alex313031/thorium/blob/main/src/build/config/win/BUILD.gn

I ask what CPU you have, because I would be willing to make you a personal build tuned to your specific system. I have done that in the past a couple of time for people requesting a specific thing. Just dont expect me to make avx 512 releases all the time. I might make some v3 (i.e. avx2) releases for linux in the future, which is one of the original things you wanted.

**Comment by ms178** [comment]
> @ms178 What CPU do you have, like what would you be running it on?

I am on Haswell-EP, of course I'd love to see such a Haswell build making a return considering that you provided them in the past.

> @ms178 @arm64-v9a The thing with AVX 512 is:
> 
> AVX and AVX2 will cause a CPU to downclock (the VEX offset frequency), but only when running "high intensity loads", the definition of which changes from CPU to CPU, firmware to firmware, and microcode to microcode. But I have never seen Thorium cause this. However, because of AVX512's even higher power draw when running, CPU's will downclock themselves whenever ANY avx512 instruction is running, even if it is just one thread. While on some motherboards you can disable VEX offsets entirely (like what would be used for overclocking, and at the expense of heat and power draw), not everything supports this, especially mainstream laptops. The overall effect is that compiling Thorium for avx512 could very well cause it to actually perform _worse_ than a vanilla Chromium build, with the decrease in processor speed outweighing any compiler benefits. This, coupled with the fact that a very large amount of users will not have CPUs that have AVX512 anyway, is why I would not make regular releases based on this. A PKGBUILD would not suffice, you would have to make a seperate BUILD.gn or .patch file. The relevant two files that control all of thoriums compiler optimizations are here > https://github.com/Alex313031/thorium/blob/main/src/build/config/compiler/BUILD.gn and here > https://github.com/Alex313031/thorium/blob/main/src/build/config/win/BUILD.gn
> 

@Alex313031 I understand that x86-64-v4 builds are not a priority for now considering that these CPUs are not that widespread. But Phoronix testing has proven that your assumptions about power draw and AVX-512 are no longer valid with newer CPU architectures such as Zen 4 or Sapphire Rapids (which is not a consumer platform, but is still valid for bringing up that point and future Intel architectures). As an example, see the CPU power consumption graphs for NUMPY here: https://www.phoronix.com/review/zen4-avx512-7700x/11

AVX-512 is delivering higher performance for using less power there. And NUMPY is not the exception to this behavior, it has become the rule. That means using AVX-512 even saves power now on recent CPU architectures. This will be highly relevant for upcoming Zen 4 notebook chips.

AVX-512 has also proven to be beneficial for JSON parsing which could be interesting for a webbrowser: https://www.phoronix.com/review/simdjson-avx-512

That's not meant to push you to do such a build soon, I just wanted to present you some evidence to the contrary to your statements.

**Comment by Alex313031** [comment]
@ms178 Interesting. Does this mean recent CPU architectures no longer have a VEX offset.

**Comment by ms178** [comment]
@Alex313031 According to the CPU frequency numbers here: https://www.phoronix.com/review/amd-zen4-avx512/6 - the CPU frequency does not degrade on average with AVX-512 usage on Zen 4. And the CPU temperature is also lower on average with AVX-512.

**Comment by Alex313031** [comment]
@ms178 @arm64-v9a @gz83 AVX2 test build for linux > https://github.com/Alex313031/Thorium-AVX2/releases/tag/M110.0.5481.178-1

**Comment by ms178** [comment]
@Alex313031 I've tested it and it works fine. WebGL Aquarium benchmark at 10.000 fishes increases a bit from 80/81 to 83/84 fps. Everything else seems to work fine, I've tested Youtube videos and some other usual work in Google Drive etc.

**Comment by ms178** [comment]
As the original reported issue has been fixed, I'll close this one. Further build discussions could be made in a new issue.
