### ISSUE TITLE
Question: Does Thorium store all browser history? or only 90 days? i want to store it forever.

### ISSUE THREAD

**Issue by Username23453** [Alex313031/thorium#121]

**Comment by Alex313031** [comment]
@Intellectual234 Both the patches you are wanting are https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-close-confirmation.patch and https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-disable-local-history-expiration.patch

**Comment by Intellectual234** [comment]
@Alex313031 , Thanks! :D    How do i use them? install them? or whatever?

**Comment by Alex313031** [comment]
@gz83 @Intellectual234 We added the close confirmation patch.

I would like to add https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-disable-local-history-expiration.patch for thorium M113.

**Comment by tigelake** [comment]
Is it possible to use ADM/ADMX templates to configure SavingBrowserHistoryDisabled and other policies?
