### ISSUE TITLE
Suggestion: Relocate "Service Worker" from Profile to "Cache" location

### ISSUE THREAD

**Issue by al3xxx** [Alex313031/thorium#122]
Hello,
I've noticed that "Service Worker" dir under Profile contains mostly cached items, would it make more sense to relocate "Service Worker" to Cache? At least on Linux there is a way to keep Caches on RAM disk but "Service Worker" (as I understand it's PWA directories for apps like Skype, Twitter, Telegram) still residing under "profile" directory and not even cleared with "Clear browsing data".

**Comment by Alex313031** [comment]
@al3xxx This is a good idea, however, it would require __*significant*__ re-writing of source code. There also might be a reason they have not done this before. Best to file a bug upstream. 

What you might be able to do, is make that dir a symlink to an identically named dir that you put in a ram disk. Of course, you might want to set up a script or something to sync it to disk after browser close or before shutdown.

**Comment by al3xxx** [comment]
@Alex313031 Thank you for the idea (symlink) I'll give it a try.
