### ISSUE TITLE
Thorium now available via brew!

### ISSUE THREAD

**Issue by mietzen** [Alex313031/thorium#123]
Hey, 
Great project! I made a Homebrew cask for Thorium: https://github.com/Homebrew/homebrew-cask/pull/142509

As of today you can install thorium on mac via

`brew install --cask alex313031-thorium`

from the official cask tap. 

I didn’t open a PR since I didn’t now where to put the installation info, here or special.

**Comment by Alex313031** [comment]
@mietzen Thank you! Thorium is now available for linux, windows, macos, raspberry pi, and android.

And, as far as linux goes, we have .deb, .zip, .appimage, .flatpak, and arch AUR.

And now a cask for MacOS!

Only things left are to portentially make a .snap and .rpm for linux, and and auto-updateable .exe for windows.

@midzer Take a look sir.

**Comment by midzer** [comment]
Great news and thanks alot @mietzen 

I've installed Thorium via  brew and it installed just fine. It's previous version M109 though. Is this intentional?

We should put those instructions on Thorium website, too.

**Comment by mietzen** [comment]
@midzer I haven’t had time to update the cask. I will do so on the weekend, I already got a plan on how to automate this with GH-Actions.

**Comment by mietzen** [comment]
https://github.com/Homebrew/homebrew-cask/pull/142719 PR is on it's way. 

Turns out I don't have to do anything, some else already automated this 👍
