### ISSUE TITLE
I need a way to transfer my extensions & their settings to a clean version of Thorium, without having to use google accounts or their servers.

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/thorium#124]
I need a way to transfer my extensions & their settings to a clean version of Thorium, without having to use google accounts or their servers.  Browser extensions contain all kinds of sensitive information, including browser history,passwords,emails,phone #s, & endless other things.
I use many browser extensions heavily. I dont want to even have to create a google email/account, let alone have them store sensitive data or browser fingerprint data on me. Also, google emails/accounts requires you to give them a real phone #, so this means for every browser profile I create with Thorium, (I use 3 at the moment), I'd have to create a google account for each one & a phone #. Which is ridiculous. Also, I'm not interested in having google track me every time I use a different device,computer, phone #,IP address,or track my browser itself, etc.   So how can i transfer my extensions & settings to a newly installed browser?  Are there directory folders or files I can just copy & paste into the new program folder?  I've managed to transfer all my bookmarks for each profile from windows to linux successfully already.

**Comment by Intellectual234** [comment]
@Alex313031 , @gz83 , thanks guys i appreciate the guidance. So I just tested it & it works very well.
There is only one problem, all my saved browser passwords & email login info is erased & I'm logged out of all websites. Can we please solve this one problem?  -Thanks! :)

**Comment by Alex313031** [comment]
@Intellectual234 That, and moving the user data dir (with or without the new portability flags) can cause this. This is a security protection in chromium, and not something I would mess with. It is annoying sometimes, but it is there for good reason.
