### ISSUE TITLE
High CPU keystone updater

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#127]
Hello, some people talk about heavy cpu usage caused may be by keystone updater, does Thorium Browser use the same updater of Chrome  ?

https://bugs.chromium.org/p/chromium/issues/detail?id=1158402#c18

https://chromeisbad.com/

**Comment by Alex313031** [comment]
@trimechee Keystone updater is only installed on MacOS, and it is only applicable to builds which auto-update, like Chrome. Thorium has no auto updater for any of the platforms, so it is not something to worry about.

**Comment by trimechee** [comment]
Great ! Thank you :)
