### ISSUE TITLE
Thorium linux version, cant access https://ricochet.im/ , see screenshot, what should i do?  -Thanks!

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/thorium#129]
![image](https://user-images.githubusercontent.com/105397593/227530010-675cbf1e-72dd-44c3-b958-53946e7bbc2d.png)

![image](https://user-images.githubusercontent.com/105397593/227529856-240d0190-e4e1-4ea8-ad40-f54ee8cafca2.png)

**Comment by gz83** [comment]
> ![image](https://user-images.githubusercontent.com/105397593/227530010-675cbf1e-72dd-44c3-b958-53946e7bbc2d.png)
> 
> ![image](https://user-images.githubusercontent.com/105397593/227529856-240d0190-e4e1-4ea8-ad40-f54ee8cafca2.png)

@Intellectual234 

This problem has nothing to do with the browser. This error message means that the SSL certificate used by the website has expired. Please contact the website administrator and ask them to update the SSL certificate of the website.

**Comment by Intellectual234** [comment]
@gz83 , thanks, i already know that. How can one bypass this? There should be a way.

**Comment by People-11** [comment]
@Intellectual234 try typing "thisisunsafe" in this error page

**Comment by Intellectual234** [comment]
@People-11 , thank you, thank you! 🙏🙏 it worked. :)
