### ISSUE TITLE
Latest

### ISSUE THREAD

**Issue by necros2k7** [Alex313031/Thorium#13]
subj

**Comment by Alex313031** [comment]
@necros2k7 You can run ./thorium-browser or the thorium-browser.desktop file. Both need to be made executable with sudo chmod +x yourfilehere

**Comment by necros2k7** [comment]
I thought this build is for Win sorry, can you build Win version?

**Comment by Alex313031** [comment]
@necros2k7 In the readme, it says that windows builds are at https://github.com/Alex313031/Thorium-Win and builds for mac and other architectures are at https://github.com/Alex313031/Thorium-Special 
If you came here from https://chromium.woolyss.com it should auto detect your OS and offer downloads for it. Im always at the bottom with the AlexFrick tag. Linux and windows builds both come in an installer (.deb or .exe) or a portable .zip with a readme inside for how to use the scripts (.sh or .bat for win) to run it portably. Thanks for using Thorium!
