### ISSUE TITLE
extension manifest v2

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#130]
Hello, may be this extension could help to keep browser compatible with manifest v2 :  
https://github.com/belaviyo/v3tov2

**Comment by Alex313031** [comment]
@trimechee All that does is convert existing MV3 extensions to MV2. I will be enabling a source code hack to enable a policy to allow MV2 extensions when the time comes, to delay it as long as possible.

**Comment by trimechee** [comment]
Awesome !! 💯 🥇
