### ISSUE TITLE
Need to be able to choose if I want a bookmark icon to constantly phone home to its domain to check for new notifications.

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/thorium#131]
Facebook, instagram, twitter, reddit, & Matrix Element ICR,etc. 
Sometimes for example, I am not connected to a VPN but yet I have a single blank tab open in thorium, but yet my bookmarks are connecting to their domains somehow & checking for notifications, and the bookmark icon will show a "+1" on it, if new notification. I dont want these connections taking place without my knowing/choosing/configuration & without a VPN on, etc.
-Thanks.

**Comment by gz83** [comment]
> Facebook, instagram, twitter, reddit, & Matrix Element ICR,etc. Sometimes for example, I am not connected to a VPN but yet I have a single blank tab open in thorium, but yet my bookmarks are connecting to their domains somehow & checking for notifications, and the bookmark icon will show a "+1" on it, if new notification. I dont want these connections taking place without my knowing/choosing/configuration & without a VPN on, etc. -Thanks.

@Intellectual234 

I think you can solve this problem by adjusting the settings of these websites, or adjust the permissions of the websites through the chrome://settings/content page (for example: notifications)

**Comment by Intellectual234** [comment]
Thanks Ho! can i call you Ho?    I never was able to understand what "notifications" meant, i thought notifications like those meant, u have to keep the website tab open/active & having notifications "on" meant u will get a bell sound, & turning it off means u wont get notified=no bell sound.   You are certain that setting also is connected to the bookmark?

Also though, what if I always want the bell sound when my tab is open, but never the bookmark? 
maybe we should create a flag for this. :) "on" for 1st feature, "off" for the bookmark feature.

**Comment by gz83** [comment]
> Thanks Ho! can i call you Ho? I never was able to understand what "notifications" meant, i thought notifications like those meant, u have to keep the website tab open/active & having notifications "on" meant u will get a bell sound, & turning it off means u wont get notified=no bell sound. You are certain that setting also is connected to the bookmark?
> 
> Also though, what if I always want the bell sound when my tab is open, but never the bookmark? maybe we should create a flag for this. :) "on" for 1st feature, "off" for the bookmark feature.

Yes, of course you can call me Ho.

Notifications for chrome/chromium/thorium look like the image below

![image](https://user-images.githubusercontent.com/17492865/227717862-b077ba92-1ca9-400f-aa13-1a46346cf3c8.png)

At the same time, these notifications don't necessarily need to keep the tab open/active, YouTube's notifications are a good example, if you have YouTube's notifications turned on, it will push notifications to you even if you don't have YouTube open.

Also, what do you mean by bookmarks showing "+1", can you add more information? Also, if I am not mistaken, the chrome/chromium browser should not have the function you mentioned. If we need to implement this function, we may need to develop this function separately.

**Comment by Intellectual234** [comment]
Here is what i mean, recently for example, my Matrix Element bookmark here will show a +1 sign on top of it, when i today would get a message, bookmark notifications for me dont happen often & are glitchy in general & dont always work or sync (right?), so I didnt have a chance to take a screenshot, i will try to screenshot when i get a chance next time it happens, but here is exactly where the +1 shows up, right here:
![image](https://user-images.githubusercontent.com/105397593/227718812-8fa4cb81-d711-4dca-a72d-d5332e60ffe5.png)

**Comment by gz83** [comment]
> Here is what i mean, recently for example, my Matrix Element bookmark here will show a +1 sign on top of it, when i today would get a message, bookmark notifications for me dont happen often & are glitchy in general & dont always work or sync (right?), so I didnt have a chance to take a screenshot, i will try to screenshot when i get a chance next time it happens, but here is exactly where the +1 shows up, right here: ![image](https://user-images.githubusercontent.com/105397593/227718953-377f92e5-10cd-432b-93d3-e0d928b03cfd.png)

@Intellectual234 

I think you can try to clear the cache of these sites and see if the problem you encountered occurs again. Then, according to what I told you earlier, try to adjust the notification-related settings of these websites.

**Comment by Alex313031** [comment]
@gz83 @Intellectual234 Yeah this isn't a thorium issue. It is something you have configured for these sites.
