### ISSUE TITLE
More Patches from ungoogled-chromium

### ISSUE THREAD

**Issue by goodusername123** [Alex313031/thorium#132]
### There are some useful patches from ungoogled-chromium that are not currently present in Thorium (one/two of which that is somewhat preventing me from being able to use Thorium as a possible daily driver without)
some of these include:
[add-flag-to-disable-local-history-expiration.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-disable-local-history-expiration.patch) (This one I find personally very useful also Vivaldi has it as an option)
[add-flag-to-scroll-tabs.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-scroll-tabs.patch) (Vivaldi has this as an option and I currently have this setup in my instance of Waterfox and also Vivaldi back when I used it)
[add-flag-for-tab-hover-cards.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-tab-hover-cards.patch) (allows reverting back to basic tooltips for tabs)
[add-flag-for-tabsearch-button.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-tabsearch-button.patch) (allows disabling the tab search button)
[add-flag-for-disabling-link-drag.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-disabling-link-drag.patch)
[add-flag-to-configure-extension-downloading.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-configure-extension-downloading.patch)
[add-flag-to-close-window-with-last-tab.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-close-window-with-last-tab.patch)

if this is too many patches and you would rather have Thorium be on the more lighter-weight side when it comes to the total number of patches applied then at the very least please consider just the top 2 patches I linked.

**Comment by gz83** [comment]
> ### There are some useful patches from ungoogled-chromium that are not currently present in Thorium (one/two of which that is somewhat preventing me from being able to use Thorium as a possible daily driver without)
> some of these include: [add-flag-to-disable-local-history-expiration.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-disable-local-history-expiration.patch) (This one I find personally very useful also Vivaldi has it as an option) [add-flag-to-scroll-tabs.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-scroll-tabs.patch) (Vivaldi has this as an option and I currently have this setup in my instance of Waterfox and also Vivaldi back when I used it) [add-flag-for-tab-hover-cards.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-tab-hover-cards.patch) (allows reverting back to basic tooltips for tabs) [add-flag-for-tabsearch-button.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-tabsearch-button.patch) (allows disabling the tab search button) [add-flag-for-disabling-link-drag.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-disabling-link-drag.patch) [add-flag-to-configure-extension-downloading.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-configure-extension-downloading.patch) [add-flag-to-close-window-with-last-tab.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-close-window-with-last-tab.patch)
> 
> if this is too many patches and you would rather have Thorium be on the more lighter-weight side when it comes to the total number of patches applied then at the very least please consider just the top 2 patches I linked.

@goodusername123 

Thank you very much for your suggestion, we will evaluate it and decide which patches will be added to Thorium after evaluation, and you will see them in the commit log of the repo

**Comment by Alex313031** [comment]
@gz83 @goodusername123 This is strange. I am not getting this effect on my main machine or my HP machine which also happens to have 4790k and 32gb 1600 ram.

**Comment by Alex313031** [comment]
@goodusername123 I can add the history expiration patch. The scroll tabs patch seems unnecessary, there is already a flag to enable tab scrolling or not.

**Comment by goodusername123** [comment]
> I can add the history expiration patch. The scroll tabs patch seems unnecessary, there is already a flag to enable tab scrolling or not.

@Alex313031 The tab scrolling patch is to switch focus between currently opened tabs with the mousewheel while the tab scrolling flag(s) that come stock in chromium are to change tab overflow behavior and to allow mousewheel scrolling of the overflowed tabstrip not the tabs themselves.

**Comment by Alex313031** [comment]
@goodusername123 Are you on linux?

**Comment by goodusername123** [comment]
> @goodusername123 Are you on linux?

@Alex313031 no I am not currently but after doing some research it seems like tab switch scrolling is something that linux and seemly only linux has for chromium which is a bit strange but the patch I sent allows it to be used on other platforms (patch confirmed working on windows).

**Comment by gz83** [comment]
> > @goodusername123 Are you on linux?
> 
> @Alex313031 no I am not currently but after doing some research it seems like tab switch scrolling is something that linux and seemly only linux has for chromium which is a bit strange but the patch I sent allows it to be used on other platforms (patch confirmed working on windows).

@goodusername123 

Tab scrolling is not available on windows because chromium has set BUILDFLAG to enable this feature only for Linux systems, please see the link I posted below

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/defaults.cc;drc=debb5206b5dadf1c3e2c3a328e0e0763c6e1eb64;l =56

Lines 55 through 59 are the code that controls this function.

I think we should push upstream to get this functionality to all desktop platforms (kOsDesktop)

**Comment by gz83** [comment]
> > @goodusername123 Are you on linux?
> 
> @Alex313031 no I am not currently but after doing some research it seems like tab switch scrolling is something that linux and seemly only linux has for chromium which is a bit strange but the patch I sent allows it to be used on other platforms (patch confirmed working on windows).

@goodusername123 

I'm trying to extend the mouse wheel tab switching to all desktop platforms, here's a patch in WIP status

https://chromium-review.googlesource.com/c/chromium/src/+/4393282

**Comment by gz83** [comment]
> Would it be possible to add all UngoogledChromium patches as flags, and enable them all with just one flag? It would be pretty handy for all of us who care about privacy.

@xplshn 

We don't add all the patches from ungoogled-chromium, because there are some patches that are not needed and are not in line with Thorium's philosophy, and I think it is blind and irrational to add all the patches from ungoogled-chromium.

**Comment by josephnz** [comment]
can you please add [omnibox autocomplete filtering](https://raw.githubusercontent.com/ungoogled-software/ungoogled-chromium/master/patches/extra/ungoogled-chromium/add-flag-for-omnibox-autocomplete-filtering.patch)?

**Comment by Alex313031** [comment]
@gz83 Putting all of ungoogled's patches behind a single flag would be impossible. I add patches or I or @gz83 create patches on a case by case basis. 

Btw @goodusername123 thorium 113 has added the `add-flag-to-disable-local-history-expiration.patch`, `add-flag-to-scroll-tabs.patch`
