### ISSUE TITLE
something went wrong with your profile some features may be unavailable ???

### ISSUE THREAD

**Issue by al3xxx** [Alex313031/thorium#134]
**System Details**
 - OS: Archlinux 
 - Thorium Version while upgrading from 110.0.5481.178-1 to 111.0.5563.111-1

**Problem**
When started browser after an upgrade got this dialog message
Ublock Origin refuses to load, twitter or web.telegram.org refuse to load, lots of session cookies that shouldn't expire disappeared. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2903428/229168745-d0f55402-a2d8-4a15-a803-f80f3573b62b.png)

**Additional Notes**
I'm going to rollback until further notice

**Comment by Alex313031** [comment]
@al3xxx What OS and window manager are you using, it looks unique.

**Comment by al3xxx** [comment]
@Alex313031 that's resolved already - there was background thorium process that was locking profile. Once I stopped it the problem went away.
