### ISSUE TITLE
[Documentation] Recommendation for updates / auto-updates of thorium

### ISSUE THREAD

**Issue by rubyFeedback** [Alex313031/thorium#135]
Hey there Alex,

I am using thorium since some weeks a replacement for chrome/chromium/vivaldi. It's working very
well. One primary reason I went that route is because of video codec situation - for some reason the
variant I used with chrome/chromium did not support H265 (I think) out of the box. Vivaldi did but
I don't like the vivaldi interface that much; I found thorium by recommendation from someone else
then. It kind of "makes sense" to me to switch to thorium then (vivaldi played videos fine, so obviously
it was possible, but I was too lazy to research how to do so in chrome/chromium).

Anyway.

I am mostly using Linux myself and I, oddly enough, upgrade manually (but I also compile a lot of
things from source, so I am a rare case I think).

Now to the issue at hand here:

I see that thorium gets changes quite a lot, but most of these I probably may not absolutely need.
Still, some changes may be useful, so from this point of view one question I, and perhaps others,
may have is ... when to upgrade? What is a recommended path to upgrade?

I am thinking of something like "recommendation is to update once per month" or something
like that. I could probably use the auto-update thing (does it exist? I did not even check), but
the problem is that I only ever keep backups of the things I update manually. I crash my linux
system a LOT (fiddling around with things breaks stuff), so I adopted a policy to keep huge
backups regularly, about 1-2 times per week or even more - my second HDD is only to back
up the first HDD, for instance, and I then also use several external USB sticks for regular
snapshots. Don't want to lose hours of work after all.

To make this super-lengthy issue request easier:

Would it be possible for thorium to add either to the main README, or some other parts, e. g.
FAQ, or something like there, a recommendation as to **when** to update? I understand that
not all different use cases can be covered, but something that the official thorium team **may**
recommend, perhaps both for casual and "power" users alike. (Otherwise I tend to forget or
upgrade irregularly anyway). If it is e. g. once per month I may remember to do so more likely.
(I could update every day or every week, but this is not the only project I'd have to handle or
forget to handle, so I intend to add that information to a local file that gathers all thorium-specific
knowledge).

**Comment by Alex313031** [comment]
@rubyFeedback I also like to manually upgrade things and build things from source. (Building Chromium from source it actually what kinda kickstarted the thorium project). I usually make a release once a month, to that is usually good. You could also update every even version, as every even version of Chromium is a LTS branch.

Also, there is not auto-update on windows, however, I have made a deb repo for thorium, you can find info on it at the bottom of the site > https://thorium.rocks/#installation

However, please note that https://github.com/Alex313031/thorium/issues/145 it seems to be somewhat broken right now.
