### ISSUE TITLE
Thorium wont let me log into Reddit in regular or incognito mode. But firefox works fine.

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/thorium#136]
I am using ZorinOS. I tried two of my reddit acounts also, not just one.
![image](https://user-images.githubusercontent.com/105397593/229673851-b69f99e9-99ab-423c-ab9a-e8f96086e852.png)

**Comment by gz83** [comment]
> I am using ZorinOS. I tried two of my reddit acounts also, not just one. ![image](https://user-images.githubusercontent.com/105397593/229673851-b69f99e9-99ab-423c-ab9a-e8f96086e852.png)

@Intellectual234 

Have you checked your account and password? And were you previously able to log into Reddit at Thorium?

**Comment by Intellectual234** [comment]
@gz83 , if it was an account/password issue I wouldnt be able to login via firefox,but i am.....   I need someone to check & login to reddit on their side via thorium.

**Comment by gz83** [comment]
> @gz83 , if it was an account/password issue I wouldnt be able to login via firefox,but i am..... I need someone to check & login to reddit on their side via thorium.

@Intellectual234 

Clear your browser data and close all extensions, then try to log in again.

**Comment by Intellectual234** [comment]
@gz83 , i dont think i can clear browser data if I'm using thorium incognito, all i can do is close it down & restart incognito, which i just did.
Also, I disabled all extensions except Private Internet Access VPN browser extension as I **must** use that one. I cant login without it. It would help a ton if someone could login to reddit using their own thorium. @Alex313031

**Comment by gz83** [comment]
> @gz83 , i dont think i can clear browser data if I'm using thorium incognito, all i can do is close it down & restart incognito, which i just did. Also, I disabled all extensions except Private Internet Access VPN browser extension as I **must** use that one. I cant login without it. It would help a ton if someone could login to reddit using their own thorium. @Alex313031

@Intellectual234 

I have just reproduced the problem you encountered, and after my search, there is quite a lot of similar feedback on the Internet and reddit, you can first try to log in by referring to the methods provided on the Internet and reddit, this problem may be related to reddit itself.

**Comment by Intellectual234** [comment]
@gz83 , thanks Ho! just wanted to figure out the source of the problem.

**Comment by Intellectual234** [comment]
@gz83 Appears to be fixed now :)
