### ISSUE TITLE
a turn for hide experiments  icon

### ISSUE THREAD

**Issue by wacdev** [Alex313031/thorium#138]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/127726508/230258010-08fa8288-7795-45f6-a3b2-7a64d2cd38a2.png">
a turn for hide experiments  icon as image above

**Comment by gz83** [comment]
> this color is very ugly , and this icon is just a setting , not use in daily use

@wacdev 

Thanks for your suggestion, but whether to adopt your suggestion will be decided by the project leader Alex.

**Comment by jstdk** [comment]
I agree to (optionally) hide the icon as well, nothing better than a clean top bar

**Comment by im-tem** [comment]
chrome://flags/#chrome-labs
this is already an option if you're curious

**Comment by Alex313031** [comment]
@im-tem @jstdk Yeah, all I did was change the icon color, and set chrome://flags/#chrome-labs to true by default. Simply set that flag to disabled, and it will remove it from the toolbar.

**Comment by wacdev** [comment]
chrome://flags/#chrome-labs
disable works , thanks
