### ISSUE TITLE
RPM builds and repositories

### ISSUE THREAD

**Issue by demirdegerli** [Alex313031/thorium#139]
Thorium is a great project. It should have a place on Debian, Fedora and Arch repositories. At least please provide RPMs and other popular builds.

**Comment by gz83** [comment]
> Thorium is a great project. It should have a place on Debian, Fedora and Arch repositories. At least please provide RPMs and other popular builds.

@demirdegerli 

Thorium can now be installed via apt source under linux platform, and we also provide deb package, APPIMAGE package and portable version zip archive.

**Comment by demirdegerli** [comment]
Can we have RPMs?

**Comment by gz83** [comment]
> Can we have RPMs?

@demirdegerli 

I think Alex and midzer should be able to answer your question further.

@Alex313031 @midzer

**Comment by Alex313031** [comment]
@gz83 @demirdegerli the chromium repo does indeed have code and scripts to generate snap and rpm packages, on top of the deb we normally ship. I would need to test it, and it would probably need some tweaking like I had to do with the deb packaging.

**Comment by Alex313031** [comment]
@gz83 @demirdegerli @yochananmarqos  Thorium now has an official .rpm package! See latest M114 release.

**Comment by demirdegerli** [comment]
Thank you!
