### ISSUE TITLE
g sync not working?

### ISSUE THREAD

**Issue by JPratama7** [Alex313031/Thorium#14]
currently using my own pkgbuild.
windows version also not working

**Comment by JPratama7** [comment]
`--oauth2-client-id=77185425430.apps.googleusercontent.com 
--oauth2-client-secret=OTJgUOQcT7lO7GsGZq2G4IlT`

current workaround, add to .desktop file

**Comment by Alex313031** [comment]
Nice. What do you mean windows version not working? 
Would you be willing to share your package build?
And this is outlined in the readme. Thorium previously had no API Keys, but then I purchased a quota as API Keys without a quota are rate limited and so only good for personal use, not distribution like the packages I serve. So the Thorium repo has all source code needed, and the lines in args.gn are laid out with the lines to put your api keys, client secret, client id but they are empty. I dont want people using my paid for api keys outside of an already compiled binary/deb so.
Look in the args.gn and you will see at the top where to put them. This will bake them into the chrome executable and make it where you dont have to specify them as cmdline arguments or environment variables.
It looks like you already made some api keys for yourself (and you should edit that comment to remove them from public view). However if those dont work for you I would be willing to share with you my API Keys on the condition that you promise to only use them for personal builds that wont be redistributed outside of your own machines.

**Comment by JPratama7** [comment]
oh i see, i didnt know that, sorry
here my pkgbuild
https://github.com/JPratama7/test-cicd/blob/master/thorium/PKGBUILD

about that api key, i got it from a thread in stackoverflow
https://stackoverflow.com/questions/67459316/enabling-chromium-to-sync-with-google-account

**Comment by Alex313031** [comment]
Thats a nice packagebuild! Would you mind if I included it in the Thorium repo? I would credit you in the readme and in the file

**Comment by JPratama7** [comment]
sorry for late reply.

> @JPratama7 That's a nice packagebuild! Would you mind if I included it in the Thorium repo? I would credit you in the readme and in the file.
sure, no prob, i use debtap + google-chome pkgbuild + ms edge pkgbuild  to make that too



> @JPratama7 Also what do you mean about the windows version not working?
google sync

**Comment by JPratama7** [comment]
>  Also, those keys are most likely personal keys.

no, it's from chromium repository

**Comment by Alex313031** [comment]
@JPratama7 Hmm sync works in my testing, but I havent tested sync in the last two windows releases. I'll test my next release for sync and get back to you. And the chromium repo doesn't have public keys to enable sync? That would defeat the whole purpose of when they restricted api keys in march 15, 2021. Try Thorium on linux and win by themselves, the backed in API keys should work.

**Comment by JPratama7** [comment]
>  And the chromium repo doesn't have public keys to enable sync? That would defeat the whole purpose of when they restricted api keys in march 15, 2021. 

it's from an old commit in 2012.
here the link 
https://chromium.googlesource.com/experimental/chromium/src/+/b08bf82b0df37d15a822b478e23ce633616ed959/google_apis/google_api_keys.cc
