### ISSUE TITLE
Feature request : Add split window support

### ISSUE THREAD

**Issue by user858753257** [Alex313031/thorium#142]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like, including relevant patches or source**

MS edge has this feature of displaying tabs side by side already . 

Could also be implemented as a plug-in when there is no patch already available 

https://beebom.com/how-enable-split-screen-microsoft-edge/

**Comment by gz83** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like, including relevant patches or source**
> 
> MS edge has this feature of displaying tabs side by side already .
> 
> Could also be implemented as a plug-in when there is no patch already available
> 
> https://beebom.com/how-enable-split-screen-microsoft-edge/

@F3000 

My point is consistent with the previous feature request
https://github.com/Alex313031/thorium/issues/141

**Comment by yukendhiran** [comment]
https://sidebarr.net/

This one seems fine
