### ISSUE TITLE
Switch tabs with mouse scrollbar

### ISSUE THREAD

**Issue by GrabbenD** [Alex313031/thorium#146]
Brave browser allows you to switch tabs by hovering over the tabs bar and using the mouse scroll button (on Linux only). This is really useful when you quickly want to switch between tabs without having to hover the cursor and click on the desired tab.

This feature would be greatly appreciated!

**Comment by GrabbenD** [comment]
> For the design philosophy and product philosophy of chromium and the Linux desktop environment, chromium enables this feature by default on the Linux platform

Scrolling through tabs doesn't work for me with Thorium browser on NixOS, only in Brave.

Did you enable this feature with a flag?

**Comment by gz83** [comment]
> > For the design philosophy and product philosophy of chromium and the Linux desktop environment, chromium enables this feature by default on the Linux platform
> 
> Scrolling through tabs doesn't work for me with Thorium browser on NixOS, only in Brave.
> 
> Did you enable this feature with a flag?

@GrabbenD 

The relevant code you can see in the following link

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/defaults.cc?q=defaults.cc&ss=chromium%2Fchromium%2Fsrc

Focus on lines 55 to 59 of this file.

Also, as far as I remember thorium did not make changes to this feature.

**Comment by GrabbenD** [comment]
You're right @gz83, _scrolling_ between tabs works on Linux but not on Windows. However, I'm referencing to actually _switching_ tabs with the mouse scrollbar which Brave browser does. I can't find if that's a patch from Brave's side or if it's a feature flag in Chromium

**Comment by gz83** [comment]
This is brave's custom function. In fact, I could have implemented this in the form of a flag upstream (chromium codebase), but the chromium staff didn't support me in doing so.

**Comment by GrabbenD** [comment]
That's a shame @gz83.
Perhaps we could incorporate this featureflag into Thorium?

**Comment by gz83** [comment]
@GrabbenD 

你的建议很好，但是最终决定需要Alex来做。 @Alex313031

**Comment by Alex313031** [comment]
@gz83 Can you tell me the patch you made to enable this that was rejected. Thorium 113 has a new flag to enable the linux style behaviour on all platforms, or disable it entirely.

But Im not sure what @GrabbenD are talking about. When I scroll on the tabstrip on linux, it switches the active tab to the left or right. Like Im not sure what difference you are meaning between scrolling and switching.

**Comment by gz83** [comment]
We can use the patch below to enable mouse wheel tab switching on non-linux systems. Google rejects this patch on the grounds that enabling mouse wheel tab switching on non-linux systems is not in line with the design philosophy.

https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-to-scroll-tabs.patch

@Alex313031

**Comment by GrabbenD** [comment]
> But Im not sure what @GrabbenD are talking about. When I scroll on the tabstrip on linux, it switches the active tab to the left or right. Like Im not sure what difference you are meaning between scrolling and switching.

Brave actually switches the active tab when I use the scrollbar while Thorium only scrolls between tabs (meaning it doesn't change the active tab) on my end

**Comment by Alex313031** [comment]
@gz83 @GrabbenD Yes this is the exact patch that I added in thorium 113. It should work.

@GrabbenD Make sure that the one I added `chrome://flags/#scroll-tabs` is enabled.

And make sure that `chrome://flags/#scrollable-tabstrip` is either disabled or set to default. The two flags are mutually exclusive and interfere with each other.

**Comment by Alex313031** [comment]
@GrabbenD Is it working for you now.

**Comment by GrabbenD** [comment]
I'll make sure to update this issue asap, I can't try it out until I get a few things sorted 👍🏼

**Comment by GrabbenD** [comment]
@Alex313031 Thank you, mouse scrolling works as intended now!

Only bug I've encountered is if you have more tabs than can be fit on the screen (on e.g. low resolution display), they become hidden.

Brave browser actually adds a physical scrollbar when that's the case to combat this bug, it might be worth to consider that
