### ISSUE TITLE
Could I ask what is this and why?

### ISSUE THREAD

**Issue by People-11** [Alex313031/thorium#147]
https://github.com/Alex313031/thorium/blob/21397a7dbab9e1420eb1c6c977d410f7f5eb3c37/src/chrome/app/theme/theme_resources.grd#L194
https://github.com/Alex313031/thorium/blob/21397a7dbab9e1420eb1c6c977d410f7f5eb3c37/src/chrome/app/theme/default_100_percent/chromium/yiff.png

**Comment by Alex313031** [comment]
@People-11 LOL shhhh, its a secret easter egg. Don't hate me lol.

**Comment by People-11** [comment]
Alright

**Comment by Alex313031** [comment]
@People-11 Lol you knew about it when there was catgirl instead?

**Comment by People-11** [comment]
I know, im still using old version, its catgirl at the fridge

**Comment by Cyanide0210** [comment]
will this get removed?

**Comment by SnowzNZ** [comment]
degenerate

**Comment by damian101** [comment]
You should feel embarrassed distributing such a badly optimized PNG to many thousands of users.
Here, 17.1 % smaller:
![yiff](https://github.com/Alex313031/thorium/assets/37085490/21d42cd7-0e90-480a-8864-0eb4eaf9b8e8)
WebP or JXL would perform much better for lossless anyway, though. Not that lossless is reasonable here anyway...
