### ISSUE TITLE
Add option to remove the shortcut "Ctrl+Shift+Q" to close the browser

### ISSUE THREAD

**Issue by fabmazz** [Alex313031/thorium#148]
I always use a web app (which is Jupyter Server) in which the "Ctrl+Shift+Q" keyboard shortcut is used to close a window. With the new release of Thorium, it actually triggers the closing of the browser, which is kinda frustrating (especially since the web app is quite heavy, and I started using Thorium because the regular Chromium was not fast enough).

Could you add an option to toggle this feature of the browser?

**Comment by gz83** [comment]
@fabmazz 
Sorry for the inconvenience, is there a place on the Jupyter server where users can change keyboard shortcuts? If Jupyter Server can modify shortcut keys, you can temporarily circumvent this problem by first changing the keyboard shortcuts.

In addition, we need to contact the project  @Alex313031  to decide how to solve this problem (add controllable options or modify it to other shortcut keys).
