### ISSUE TITLE
Zip build of newest release SIGTRAP broken openSUSE

### ISSUE THREAD

**Issue by MANICX100** [Alex313031/thorium#150]
**System Details**
 - OS: [e.g.  OpenSUSE Leap 15.4]
 - Thorium Version [e.g.112.0.5615.166]

**Problem**
Using the zip build I get a terminated by signal SIGTRAP (Trace or breakpoint trap)
build 111 works fine
appimage works fine

**Comment by Alex313031** [comment]
@MANICX100 What CPU does this system have?

**Comment by MANICX100** [comment]
> @MANICX100 What CPU does this system have?

Intel i9 13900KS

**Comment by Alex313031** [comment]
HMM interesting.
