### ISSUE TITLE
Recent Searches on address bar won't get disabled :(

### ISSUE THREAD

**Issue by seb1406** [Alex313031/thorium#152]
![throium_screenshot](https://user-images.githubusercontent.com/80560080/235440522-8d86edfe-e073-4771-82c6-e51d07c43b5b.png)
**System Details**
 - OS: Windows 10
 - Thorium Version: 112.0.5615.166 (Official Build) (64-bit)

**Problem**
Recent searches on address bar won't get disabled! I've turned autocomplete off from settings. These was a flag to allow only bookmarks and not recent searches but that is nowhere to be found on chrome://flags.

**Screenshots**
Attached...

**Comment by gz83** [comment]
@seb1406 

Does this problem exist in the official stable version (version 112)?

**Comment by gz83** [comment]
@seb1406 

If the official release (chrome or chromium) also has this problem then it means it is an upstream problem

**Comment by Alex313031** [comment]
@gz83 @seb1406 Fixing it is something I could do, but it has the potential to break autocomplete features for those who want it.

I think it would be best to wait until upstream fixes it.
If it is not fixed by M114, then me or gz83 can file a bug on it with chromium

**Comment by seb1406** [comment]
> @gz83 @seb1406 Fixing it is something I could do, but it has the potential to break autocomplete features for those who want it.
> 
> I think it would be best to wait until upstream fixes it. If it is not fixed by M114, then me or gz83 can file a bug on it with chromium

On Chromium v113, this flag is available- just checked. Which in turn allows me to not got search history results on address bar.
![Uploading Screenshot_3.png…]()

**Comment by Alex313031** [comment]
@seb1406 Nice well thorium 113 just dropped, so you should be good to go now.
