### ISSUE TITLE
Thorium Homebrew Package

### ISSUE THREAD

**Issue by anuragrao04** [Alex313031/thorium#153]
As explained above, please add thorium as a homebrew package. I could try and make a PR adding this feature but it involves making a new repository according to a guide I found [here](https://betterprogramming.pub/a-step-by-step-guide-to-create-homebrew-taps-from-github-repos-f33d3755ba74) which I think is a little bit more personal. 

This would especially be useful for people who bought the new Apple silicon machines because of it's incredible hardware but are stuck with MacOS (Yes I've seen Asahi Linux but it isn't ready for daily use for me yet)

**Comment by Alex313031** [comment]
@anuragrao04 Thorium is already a homebrew package! > https://formulae.brew.sh/cask/alex313031-thorium

**Comment by anuragrao04** [comment]
Oh, That's awesome! Would this be updated less frequently, I notice that the latest build for M1 Mac is M111.0.5563.111 but the latest official release is M112.0.5615.166. 

You're doing an amazing job and this is exactly the browser I was looking for. Do let me know if I can lend a hand at anything!

**Comment by Alex313031** [comment]
@anuragrao04 I am releasing new mac builds today.

**Comment by anuragrao04** [comment]
Okay! I'll be waiting

**Comment by martin-braun** [comment]
I tried `brew install --cask throium` and it didn't end well. Might be worth adding this to the README or something. `brew install --cask alex313031-thorium` is the way to go.
