### ISSUE TITLE
Ctrl + tab to switch to most recently visited tab instead of cycling through tabs

### ISSUE THREAD

**Issue by JCerro01** [Alex313031/thorium#154]
**Premise**
I found myself often missing the functionality to  change the "ctrl + tab" behavior's from cycling through tabs in order to switch to the most recently visited tab, as can be found in other browser's settings such as Firefox or Brave. 

**Feature  request**
That being said, It would be nice if the user could change the "ctrl + tab" behavior's to go to most recent tab instead of cycling through tabs in order, through Thorium's settings.

**Bonus feature request**
This might not be a realistic ask since it appears to be more a lot more complex to implement but I personally really like the preview of all tabs that appears in Firefox when the user is holding "ctrl + tab" for a longer period. It then lets you choose precisely which tab you want to go to.

**Additional Notes**
If this functionality already exists in Thorium and I just did not find it, please let me know.

**Comment by Alex313031** [comment]
@JCerro01 I use a nice little open source extension called Last Tabs for this > https://chrome.google.com/webstore/detail/last-tabs/ehdbaonmnanalnmmlkgdnkkcdlppjhhc
