### ISSUE TITLE
No video hardware acceleration under native Wayland

### ISSUE THREAD

**Issue by Digitalone1** [Alex313031/thorium#155]
**System Details**
 - OS: Arch Linux
 - Driver: Mesa AMDGPU
 - Thorium Version 112.0.5615.166-1 from AUR

**Problem**
Reading `VAAPI on Wayland Patch` in the readme I thought the hardware acceleration would work under Wayland, but I still get FFMpegVideoDecoder.

Already searched past issues trying to set custom flags, but nothing changes.

**Comment by dmig** [comment]
I confirm, only software on wayland, hardare accelerated under X.org.

- OS: Ubuntu 23.04
- kernel: Linux 6.2.12-060212-generic
- driver: Mesa 23.0.2, Intel UHD
- thorium: 112.0.5615.166 (Official Build) stable, built on Linux (64-bit)

**Comment by dmig** [comment]
Oops... I seems, starting from 112 hwaccel is broken again under Xorg. Need more testing, can confirm only that chrome 115 has same issue.

**Comment by Digitalone1** [comment]
@Alex313031 No problem, I only reported it. At the moment it's working for me in XWayland. I wanted to test it on native Wayland, but no luck.

**Comment by dmig** [comment]
@Alex313031 sorry for misinformation, it's not chrome/thorium, it seems to be ubuntu 23.04 broken -- so expect a lot of reports here
