### ISSUE TITLE
Visual tabs glitch

### ISSUE THREAD

**Issue by dmig** [Alex313031/thorium#156]
**System Details**
 - OS: Ubuntu 23.04
 - Thorium Version 112.0.5615.166 (Official Build) stable, built on Linux (64-bit) 

**Problem**
Line under the tab bar gets a break in the wrong place -- width of pinned tabs is ignored. See screenshots for more details.

**Screenshots**
![Screenshot from 2023-05-07 11-30-38](https://user-images.githubusercontent.com/388564/236669543-c55eaca5-a358-44e7-8b57-9c2076968d13.png)
![Screenshot from 2023-05-07 11-30-31](https://user-images.githubusercontent.com/388564/236669545-4e6e4abe-77d2-4411-8381-9af95b50a95a.png)
![Screenshot from 2023-05-07 11-30-25](https://user-images.githubusercontent.com/388564/236669546-1c43dc89-3164-46c3-a800-b1b9bda67b94.png)
![Screenshot from 2023-05-07 11-30-13](https://user-images.githubusercontent.com/388564/236669547-2cccd955-4026-453b-9d6d-e5f3c54ac389.png)
![Screenshot from 2023-05-07 11-30-06](https://user-images.githubusercontent.com/388564/236669548-b39287f6-6041-49ef-8052-4a14bf668b59.png)
![Screenshot from 2023-05-07 11-30-00](https://user-images.githubusercontent.com/388564/236669549-fb0e909e-d1ac-4fa6-8d93-a0d1b202944b.png)
![Screenshot from 2023-05-07 11-32-51](https://user-images.githubusercontent.com/388564/236669571-240faf36-c250-4565-9ad2-3714cb98cf34.png)
![Screenshot from 2023-05-07 11-32-44](https://user-images.githubusercontent.com/388564/236669572-f20264d1-a161-4465-93f5-8c2747f85379.png)
![Screenshot from 2023-05-07 11-32-36](https://user-images.githubusercontent.com/388564/236669573-d92bac81-d1bb-483e-96b8-1bad2474d431.png)
![Screenshot from 2023-05-07 11-32-29](https://user-images.githubusercontent.com/388564/236669575-5cb9e156-8697-4250-8cd9-eba556a50df4.png)

**Comment by Alex313031** [comment]
@dmig This is related to a patch to enable tab outlines, but the bug is from upstream.

I enabled the patch because especially in lighter themes, it can sometimes be hard to tell what tab is selected. 

The fix would be to turn it off, but then you don't get the benefit from it. The better thing would be to wait until upstream fixes it, but IDK when that would be. I could file a bug on it if you want.

**Comment by dmig** [comment]
I see. Is it possible to add a feature flag for this?

**Comment by dmitriy-geels** [comment]
> The fix would be to turn it off...

@Alex313031 I mean, having a control over this would be nice

**Comment by Alex313031** [comment]
@dmig @dmitriy-geels @yochananmarqos Added in latest release. I re-added these features after chromium removed them, since I really like them in dark mode. While I was re-adding them, I figured I would put them behind a flag.

**Comment by dmig** [comment]
Thorium M48: the bug is still there and not dependent on `chrome://flags/#tab-outlines-in-low-contrast-themes` and `chrome://flags/#prominent-dark-mode-active-tab-title`

![Screenshot from 2023-06-04 22-09-02](https://github.com/Alex313031/thorium/assets/388564/2300186f-ca91-4e37-ae9c-ccfdbe0fad4c)

**Comment by Alex313031** [comment]
@dmig So you disabled both of those flags and still got this behavior?

What GPU do you have, and are you using X11 or wayland

**Comment by dmitriy-geels** [comment]
Intel Cometlake gpu, running X11

**Comment by dmig** [comment]
Release 50, bug is still there.
