### ISSUE TITLE
no av1 support , VaapiVideoDecodeLinuxGL seems to be broken

### ISSUE THREAD

**Issue by oksakhartman** [Alex313031/thorium#158]
**ubuntu, Thorium Version - latest**

`chrome://gpu` - **no av1 support , VaapiVideoDecodeLinuxGL seems to be broken**

` --enable-features=VaapiVideoDecoder,VaapiVideoDecodeLinuxGL`

**here is photo from my chromium - it have hw support all formats**

![image](https://github.com/Alex313031/thorium/assets/112954968/e91eabc3-ef20-49d9-af0e-0a05b986a0b7)

**same from thorium with same flags - `VaapiVideoDecodeLinuxGL` seems to be broken only in thorium**

![image](https://github.com/Alex313031/thorium/assets/112954968/85e316fc-4b1d-4629-b36b-e338f204ee47)

**Comment by dmig** [comment]
Please test this with ubuntu 22.10 or older (or other linux distro). 23.04 seems to be broken.

**Comment by oksakhartman** [comment]
> ubuntu 22.10 or older (or other linux distro)

the same on 22.10 and 22.04

this does not depend on the distribution in any way, this is most likely a problem of patches that break VaapiVideoDecoder

**Comment by richardm1** [comment]
Wayland?  Hardware video decode on linux/wayland with Chromium-based browsers[*] has been half-working for years  but it seems the last few releases broke it entirely for radeonsi users. Intel and nVidia users seem to be having mixed success.

`LIBVA_MESSAGING_LEVEL=2` in /etc/libva.conf yields nothing useful.  Chrome and Edge don't even try.  Thorium tries then falls back:
```
00:00:00.547 | kVideoDecoderName | "VDAVideoDecoder"
00:00:00.547 | kIsPlatformVideoDecoder | true
00:00:00.547 | info | "Selected VDAVideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [1920,1080], visible rect: [0,0,1920,1080], natural size: [1920,1080], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
00:00:00.547 | pipeline_state | "kPlaying"
00:00:00.547 | pipeline_state | "kSeeking"
00:00:00.547 | pipeline_state | "kPlaying"
00:00:00.551 | error | "VDA Error 4"
00:00:00.551 | warning | "video decoder fallback after initial decode error."
00:00:00.551 | info | "Cannot select VpxVideoDecoder for video decoding"
00:00:00.551 | info | "Cannot select Dav1dVideoDecoder for video decoding"
00:00:00.553 | kIsVideoDecryptingDemuxerStream | false
00:00:00.553 | kVideoDecoderName | "FFmpegVideoDecoder"
00:00:00.553 | kIsPlatformVideoDecoder | false
00:00:00.553 | info | "Selected FFmpegVideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [1920,1080], visible rect: [0,0,1920,1080], natural size: [1920,1080], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
```
This is `thorium-browser-bin 112.0.5615.166-1` from the Arch AUR with amdgpu (Polaris10).  Recently people started having success with `LIBVA_DRI3_DISABLE=1` but that too seems to have stopped working just within the past 1-2 weeks.



_* except for Firefox... ¯\_(ツ)_/¯

**Comment by richardm1** [comment]
Adding to the above, launching thorium from the terminal yields the following when playing an h264 vid:
```
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: Could not make the initialization pbuffer current.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: Could not make the initialization pbuffer current.
[46886:46886:0519/232242.038868:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: Could not make the initialization pbuffer current.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: Could not make the initialization pbuffer current.
ERR: Display.cpp:1019 (initialize): ANGLE Display::initialize error 12289: Could not make the initialization pbuffer current.
[46886:46886:0519/232242.040374:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: Could not make the initialization pbuffer current.
```

**Comment by oksakhartman** [comment]
> Wayland?

x11

on stock chromium - all works fine

**Comment by dmig** [comment]
For me it stopped working under X11, never worked under wayland. Intel video.

This is what I currently get in console:
```
[995740:995740:0520/145036.498882:ERROR:vaapi_wrapper.cc(2721)] vaPutSurface failed, VA error: invalid parameter
[995740:995740:0520/145036.498985:ERROR:vaapi_video_decode_accelerator.cc(287)] Failed putting surface into pixmap
[995740:995740:0520/145038.692706:ERROR:vaapi_wrapper.cc(2721)] vaPutSurface failed, VA error: invalid parameter
[995740:995740:0520/145038.692872:ERROR:vaapi_video_decode_accelerator.cc(287)] Failed putting surface into pixmap
```

**Comment by dmig** [comment]
And this seems to be the answer: https://bbs.archlinux.org/viewtopic.php?pid=2079752#p2079752

**Comment by oksakhartman** [comment]
> And this seems to be the answe

works in stock chrome
in this patch it does not work

**Comment by Alex313031** [comment]
@oksakhartman @dmig Also because of https://github.com/Alex313031/thorium/issues/162 it definitely has to do with those patches. I will remove them one by one and rebuild each time and test, to find the offending one. Then see if I can refactor it to fix, or just remove it all together.
