### ISSUE TITLE
Segfaults on some rolling release OSes

### ISSUE THREAD

**Issue by h4rldev** [Alex313031/thorium#159]
**System Details**
 - OS: Arch or Void Linux
 - Thorium Version [e.g.107.0.5347.0]: 
 Arch: 112.0.5615.166-1
 Void: latest tar

**Problem**
On thorium start, it segfaults.
```
$ thorium-browser
find: ‘/home/h4rl/.config/thorium/Crash Reports/pending/’: No such file or directory
[1]    4436 illegal hardware instruction (core dumped)  thorium-browser
```
**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/98224660/d48c4173-adef-4463-9485-bb63b8f370a6)

**Additional Notes**
This happens from both the tar and the aur package, It's very annoying

**Comment by Alex313031** [comment]
@h4rldev Your cpu probably does not support avx. What cpu do you have

**Comment by h4rldev** [comment]
It supports avx on windows

**Comment by h4rldev** [comment]
And on my laptop I got an intel i5-114something

**Comment by h4rldev** [comment]
@Alex313031

**Comment by Alex313031** [comment]
@h4rldev Hmm ok both of those cpus would support not only avx, but also avx2 lol so that is def not the issue.

**Comment by h4rldev** [comment]
On void linux it runs fine on M113

**Comment by h4rldev** [comment]
cheers
