### ISSUE TITLE
hevc support?

### ISSUE THREAD

**Issue by AnterCreeper** [Alex313031/Thorium#16]
hardware vaapi or software?

**Comment by Alex313031** [comment]
@AnterCreeper Although the build flags for HEVC are enabled, YMMV on whether it actually works. If it does work, it should use VAAPI. If you have an nvidia gpu and are using the nvidia proprietary drivers, however, the VDPAU patch in this repo will NOT apply. That patch only works with H.264 and VP8/VP9.

**Comment by Alex313031** [comment]
@AnterCreeper You there mate, I'm going through my issues that haven't had a response in a month.

**Comment by AnterCreeper** [comment]
![image](https://user-images.githubusercontent.com/30188772/167236607-494e8898-00b4-44eb-9f92-e206f82a46b8.png)

**Comment by AnterCreeper** [comment]
render_id: 7
player_id: 0
created: 2022-05-07 03:38:00.194 UTC
origin_url: http://10.129.197.39:8080/
kFrameUrl: http://10.129.197.39:8080/%E5%BD%B1%E7%89%87/E.T.%E5%A4%96%E6%98%9F%E4%BA%BA.tt0083866.mp4
kFrameTitle: 
url: http://10.129.197.39:8080/%E5%BD%B1%E7%89%87/E.T.%E5%A4%96%E6%98%9F%E4%BA%BA.tt0083866.mp4
kTextTracks: 
kTotalBytes: 0x10ae4c639
kIsStreaming: false
kIsSingleOrigin: true
kIsRangeHeaderSupported: true
kRendererName: RendererImpl
pipeline_state: kStopped
debug: Warning, FFmpegDemuxer failed to create a valid/supported audio decoder configuration from muxed stream, config:codec: ac3, profile: unknown, bytes_per_channel: 2, channel_layout: 5.1, channels: 6, samples_per_second: 48000, sample_format: Signed 16-bit, bytes_per_frame: 12, seek_preroll: 0us, codec_delay: 0, has extra data: false, encryption scheme: Unencrypted, discard decoder delay: true, target_output_channel_layout: NONE, target_output_sample_format: Unknown sample format, has aac extra data: false
info: FFmpegDemuxer: skipping invalid or unsupported audio track
error: [object Object]

**Comment by AnterCreeper** [comment]
{
  "properties": {
    "render_id": 7,
    "player_id": 0,
    "created": "2022-05-07 03:38:00.194 UTC",
    "origin_url": "http://10.129.197.39:8080/",
    "kFrameUrl": "http://10.129.197.39:8080/%E5%BD%B1%E7%89%87/E.T.%E5%A4%96%E6%98%9F%E4%BA%BA.tt0083866.mp4",
    "kFrameTitle": "",
    "url": "http://10.129.197.39:8080/%E5%BD%B1%E7%89%87/E.T.%E5%A4%96%E6%98%9F%E4%BA%BA.tt0083866.mp4",
    "kTextTracks": [],
    "kTotalBytes": "0x10ae4c639",
    "kIsStreaming": false,
    "kIsSingleOrigin": true,
    "kIsRangeHeaderSupported": true,
    "kRendererName": "RendererImpl",
    "pipeline_state": "kStopped",
    "debug": "Warning, FFmpegDemuxer failed to create a valid/supported audio decoder configuration from muxed stream, config:codec: ac3, profile: unknown, bytes_per_channel: 2, channel_layout: 5.1, channels: 6, samples_per_second: 48000, sample_format: Signed 16-bit, bytes_per_frame: 12, seek_preroll: 0us, codec_delay: 0, has extra data: false, encryption scheme: Unencrypted, discard decoder delay: true, target_output_channel_layout: NONE, target_output_sample_format: Unknown sample format, has aac extra data: false",
    "info": "FFmpegDemuxer: skipping invalid or unsupported audio track",
    "error": {
      "code": 14,
      "data": {},
      "group": "PipelineStatus",
      "message": "",
      "stack": [
        {
          "file": "media/filters/ffmpeg_demuxer.cc",
          "line": 1469
        }
      ]
    }
  },
  "events": [
    {
      "time": 0,
      "key": "created",
      "value": "2022-05-07 03:38:00.194 UTC"
    },
    {
      "time": 7.024000000208616,
      "key": "origin_url",
      "value": "http://10.129.197.39:8080/"
    },
    {
      "time": 7.03000000026077,
      "key": "kFrameUrl",
      "value": "http://10.129.197.39:8080/%E5%BD%B1%E7%89%87/E.T.%E5%A4%96%E6%98%9F%E4%BA%BA.tt0083866.mp4"
    },
    {
      "time": 7.032999999821186,
      "key": "kFrameTitle",
      "value": ""
    },
    {
      "time": 7.1289999997243285,
      "key": "url",
      "value": "http://10.129.197.39:8080/%E5%BD%B1%E7%89%87/E.T.%E5%A4%96%E6%98%9F%E4%BA%BA.tt0083866.mp4"
    },
    {
      "time": 7.13399999961257,
      "key": "kTextTracks",
      "value": []
    },
    {
      "time": 11.268000000156462,
      "key": "kTotalBytes",
      "value": "0x10ae4c639"
    },
    {
      "time": 11.27599999960512,
      "key": "kIsStreaming",
      "value": false
    },
    {
      "time": 11.276999999769032,
      "key": "kIsSingleOrigin",
      "value": true
    },
    {
      "time": 11.28099999949336,
      "key": "kIsRangeHeaderSupported",
      "value": true
    },
    {
      "time": 11.308000000193715,
      "key": "kRendererName",
      "value": "RendererImpl"
    },
    {
      "time": 22.656999999657273,
      "key": "pipeline_state",
      "value": "kStarting"
    },
    {
      "time": 162.0589999994263,
      "key": "debug",
      "value": "Warning, FFmpegDemuxer failed to create a valid/supported video decoder configuration from muxed stream, config:codec: hevc, profile: hevc main, level: not available, alpha_mode: is_opaque, coded size: [1920,1080], visible rect: [0,0,1920,1080], natural size: [1920,1080], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
    },
    {
      "time": 162.06499999947846,
      "key": "info",
      "value": "FFmpegDemuxer: skipping invalid or unsupported video track"
    },
    {
      "time": 162.0789999999106,
      "key": "debug",
      "value": "Warning, FFmpegDemuxer failed to create a valid/supported audio decoder configuration from muxed stream, config:codec: ac3, profile: unknown, bytes_per_channel: 2, channel_layout: 5.1, channels: 6, samples_per_second: 48000, sample_format: Signed 16-bit, bytes_per_frame: 12, seek_preroll: 0us, codec_delay: 0, has extra data: false, encryption scheme: Unencrypted, discard decoder delay: true, target_output_channel_layout: NONE, target_output_sample_format: Unknown sample format, has aac extra data: false"
    },
    {
      "time": 162.081999999471,
      "key": "info",
      "value": "FFmpegDemuxer: skipping invalid or unsupported audio track"
    },
    {
      "time": 162.08299999963492,
      "key": "error",
      "value": "FFmpegDemuxer: no supported streams"
    },
    {
      "time": 162.1469999998808,
      "key": "error",
      "value": {
        "code": 14,
        "data": {},
        "group": "PipelineStatus",
        "message": "",
        "stack": [
          {
            "file": "media/filters/ffmpeg_demuxer.cc",
            "line": 1469
          }
        ]
      }
    },
    {
      "time": 162.24399999994785,
      "key": "pipeline_state",
      "value": "kStopping"
    },
    {
      "time": 162.24799999967217,
      "key": "pipeline_state",
      "value": "kStopped"
    }
  ]
}

**Comment by AnterCreeper** [comment]
afaik, the patent of ac3 is out of date.

**Comment by Alex313031** [comment]
@AnterCreeper Are you using 16.04? Ahhhh the glory days lol.

**Comment by AnterCreeper** [comment]
Ubuntu MATE 20.04 LTS

**Comment by AnterCreeper** [comment]
A very fast old system on a modern hardware. Like using Windows XP on a AMD Ryzen or Intel 12th gen.

**Comment by Alex313031** [comment]
@AnterCreeper Oh well the color scheme and the fact the minimize/maximize/close buttons are on the left made it look like 16.04.

And thanks for providing all the info, but I don't know what to do with it. 
I don't know enough about H.265.

I had tried to use Nik's patches for Windows on linux a long time ago but they didn't work.

However, as of late, they are working on HEVC support upstream. It now works by default in Chromium on Windows and Android. While I have the args.gn flags for HEVC (like I said before), HEVC doesn't seem to work on Linux or ChromiumOS/ChromeOS yet. It will probably work in the future, at which point these args.gn flags will actually do something.
When it does, it should use the VAAPI, IntelHD, and VDPAU patches in Thorium to enable hardware acceleration just like H.264 and VP8/VP9. Your video card must support it though, but the above patches greatly increase the number of GPUS that it will accept for hardware acceleration.

**Comment by AnterCreeper** [comment]
@Alex313031 Thanks a lot!

**Comment by Alex313031** [comment]
Closing this issue.
