### ISSUE TITLE
Add support for Nvidia Video Super Resolution

### ISSUE THREAD

**Issue by tru** [Alex313031/thorium#160]
**Is your feature request related to a problem? Please describe.**

Chrome and Edge now supports Nvidia Video Super Resolution upscaling. This doesn't seem to work in Thorium. It would be nice if it did.

**Comment by gz83** [comment]
The VSR function is introduced in the 110 branch, does your graphics card support the VSR function?

@tru

**Comment by tru** [comment]
Yeah. It works fine in Edge, but with Thorium (I am using the avx2 build) it seems less sharp if I compare to edge - so I think VSR is not enabled. Is there a way to check for sure?

**Comment by gz83** [comment]
You can try to find any videos on the Internet that can test the VSR function

@tru

**Comment by Alex313031** [comment]
@tru Are your drivers 530 or higher, is thorium 111 or higher, and do you have vsr enabled in the nv control panel?

If your system is a laptop, make sure it is plugged in. Eventually this should not be necessary.
