### ISSUE TITLE
Turn on Energy Saver even when plugged in

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#171]
Hello, how are you ? sadly energy saver doesn't work when plugged in, my notebook is not very powerful and the battery can get tired...it will be great to add option to enable permanently energy saver even when plugged in, thank you so much !

https://support.google.com/chrome/answer/12929150?visit_id=638227751357191071-2548025678&p=chrome_memory_saver&rd=1#memory_saver&zippy=%2Cturn-memory-saver-on-or-off%2Cturn-energy-saver-on-or-off

**Comment by gz83** [comment]
Thanks for the suggestion, but I think it might be better for these changes to be done upstream

@trimechee

**Comment by trimechee** [comment]
@gz83 Great ! Thank you :)

**Comment by Alleop5** [comment]
Upvote!

**Comment by Alex313031** [comment]
@trimechee @Alleop5 They are still working on the Performance tab in settings. It was only recently released to stable. They will probably add some heuristic or system integration to allow memory saving or power saving when certain conditions are met.

**Comment by trimechee** [comment]
@Alex313031 Very interesting ! Thank you :)
