### ISSUE TITLE
some website open is slow

### ISSUE THREAD

**Issue by newyorkthink** [Alex313031/thorium#173]
![image](https://github.com/Alex313031/thorium/assets/87791643/6c712c9e-2d7e-4107-a5d5-18188e25815a)

when i use thorium open some website is slow ,
and i use chrome ,firefox,edge is ok

**Comment by gz83** [comment]
On chrome, firefox and edge, do you have the same or similar environment on the other two browsers (chrome, edge) except for firefox?

**Comment by newyorkthink** [comment]
![image](https://github.com/Alex313031/thorium/assets/87791643/d2c96598-9f34-4191-8469-e0646ce6d0e9)

i test 

i disable all extension , i test two browser

the thorium is cannot load github

**Comment by gz83** [comment]
Is there a proxy server set up on your computer or is there any relevant proxy extension installed in the browser?

@newyorkthink

**Comment by dutkulang** [comment]
did check your internet connection at the time of testing, sometimes it could be that you had poor network at one point or the other
