### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by QueenUlyana** [Alex313031/thorium#174]
**System Details**
 - OS: Windows 10 LTSC 21H2 19044.2486
 - Thorium Version 112.0.5615.166 (Without AVX2)

**Problem**
The browser closes completely with all pages open.

**Video**
https://github.com/Alex313031/thorium/assets/83131824/fa36e631-e017-4e76-8002-596843f1f405

**Comment by gz83** [comment]
Try uninstalling the current version of the browser and installing the latest avx version to see if it crashes again

@QueenUlyana

**Comment by QueenUlyana** [comment]
> Try uninstalling the current version of the browser and installing the latest avx version to see if it crashes again
> 
> Also, do you currently have experimental flags open, and if so, please provide them.
> 
> @QueenUlyana

How do I know if "experimental flags" are enabled?

**Comment by gz83** [comment]
Please open chrome://version and upload the content of this page

@QueenUlyana

**Comment by QueenUlyana** [comment]
> Please open chrome://version and upload the content of this page
> 
> @QueenUlyana

<html>
<body>


Thorium | 112.0.5615.166 (Официальная сборка) (64 бит)
Версия | acbb3bfa64b1ddaa36a4ba46bd58ad6f193ba9f9-refs/branch-heads/5615@{#1299}
ОС | Windows 10 Version 21H2 (Build 19044.2486)
JavaScript | V8 11.2.214.14
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Командная строка | "C:\Users\Maxim\AppData\Local\Thorium\Application\thorium.exe" --flag-switches-begin --enable-features=ScrollableTabStrip:minTabWidth/54 --flag-switches-end
Путь к исполняемому файлу | C:\Users\Maxim\AppData\Local\Thorium\Application\thorium.exe
Путь к профилю | C:\Users\Maxim\AppData\Local\Thorium\User Data\Default
Текущие изменения | 5e3a236d-59e286d0dc62934a-70ea8f25


</body>
</html>

**Comment by gz83** [comment]
Please open chrome://flags, find "Tab Scrolling", and set it to default, this experimental flag is not stable, don't enable it
@QueenUlyana

**Comment by QueenUlyana** [comment]
> Please open chrome://flags, find "Tab Scrolling", and set it to default, this experimental flag is not stable, don't enable it @QueenUlyana

That helped, thank you.
