### ISSUE TITLE
The quickest way to open up a link into a new tab has slowly stopped working completely. 

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/thorium#175]
The quickest way is to hold down Ctrl & click a link, & it will open into a new tab, this was very helpful, & can be done with many links in a row, en mass. I have noticed this shortcut has slowly started working less & less & now no longer works at all. What gives? why is this happening?
-Thanks.

**Comment by gz83** [comment]
There are no exceptions in the local tests, so why do you think this feature no longer works?

@Intellectual234

**Comment by Intellectual234** [comment]
what? i dont understand you. what do u mean there are no exceptions?

**Comment by gz83** [comment]
I mean I tested this function locally and there is no abnormality.

@Intellectual234

**Comment by Intellectual234** [comment]
okay, but what does that mean? Does the Ctrl button open a link into a new tab for you or not? u need to be more specific.

**Comment by gz83** [comment]
As I have explained before, there is no abnormality in this function, that is, a new tab can be opened normally through "ctrl+mouse click on the link"

@Intellectual234

**Comment by Intellectual234** [comment]
@gz83 , thanks for testing. It does work sometimes for me, even currently. I will post here the next website it doesnt work on

**Comment by Alex313031** [comment]
@Intellectual234 Yeah I cannot reproduce on linux or windows. Are you sure an extension is not interfering. Try with a fresh user profile and test again.

**Comment by m1m1s1ku** [comment]
Works great on macOS with Cmd + click on link

**Comment by Intellectual234** [comment]
@gz83 , @Alex313031 , @Aedon , @m1m1s1ku , I have come across the issue again, for sure. So, here is another example of the Ctrl + link + left click not opening up a link into a new browser. Go to /www.google.com/search?hl=en&q=instagram%20funny   AND try it on any link that has instagram.com as a domain, it wont work. And then try the other non instagram.com domains in those search results, the non-insta domains will work & open up a new tab.
Also you can try it with duckduckgo too, same results. 
https://duckduckgo.com/?q=instagram+funny&t=canonical&ia=web

**Comment by gz83** [comment]
I have tested the two URLs you provided, and I cannot reproduce the problem you encountered on my end

@Intellectual234

**Comment by Intellectual234** [comment]
@gz83 , thanks, i figured out what the issue was, i had an instagram extension installed. when i disabled it, the problem went away. Thank you for your generous time & help. Will post again when problem re-occurs again. :)

**Comment by gz83** [comment]
If you encounter other problems, it is recommended to do your own investigation first. If you really can’t solve it, then give feedback. This will be a better solution

@Intellectual234

**Comment by m1m1s1ku** [comment]
K Sent from Proton Mail for iOS Le ven. 30 juin 2023 à 06:40, Ho Cheung ***@***.***> a écrit :  
If you encounter other problems, it is recommended to do your own investigation first. If you really can’t solve it, then give feedback. This will be a better solution
@Intellectual234
