### ISSUE TITLE
Throws back to the beginning when you scroll through history

### ISSUE THREAD

**Issue by QueenUlyana** [Alex313031/thorium#176]
**System Details**
 - OS: Windows 10 LTSC 21H2 19044.2486
 - Thorium Version 112.0.5615.166 (Without AVX2)

**Problem**
When I scroll through the story, I'm thrown back to the beginning, it happens all the time. It pisses me off, the same bug is in Google Chrome.

**Additional Notes**
Help fix this, please.

Video: 

https://github.com/Alex313031/thorium/assets/83131824/09267d18-f287-486f-9f31-5fe657755034

**Comment by Alex313031** [comment]
@gz83 Can you test this on your windows machine.

**Comment by gz83** [comment]
I can't reproduce this problem in version 114, please update your browser to version 114 and try again

@QueenUlyana

**Comment by QueenUlyana** [comment]
> I can't reproduce this problem in version 114, please update your browser to version 114 and try again
> 
> @QueenUlyana

**I installed the latest version, but the bug is still there, it has not disappeared.** Only it has become less frequent.

<html>
<body>


Thorium | 114.0.5735.134 (Официальная сборка) (64 бит)
-- | --
Версия | 960a08e3d10d3a6911d6e7f4a38b2c73f4aa0fa3-refs/branch-heads/5735@{#1271}
ОС | Windows 10 Version 21H2 (Build 19044.2486)
JavaScript | V8 11.4.183.23
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Командная строка | "C:\Program Files\BIN\thorium.exe" --flag-switches-begin --flag-switches-end
Путь к исполняемому файлу | C:\Program Files\BIN\thorium.exe
Путь к профилю | C:\Users\Maxim\AppData\Local\Thorium\User Data\Default
Текущие изменения | 5e3a236d-59e286d0


</body>
</html>

**Comment by gz83** [comment]
If the same version of chrome/chromium also has the same problem, it may be a bug in the code or a problem with your system environment

@QueenUlyana
