### ISSUE TITLE
Repo troubles

### ISSUE THREAD

**Issue by pwn0r** [Alex313031/thorium#178]
Recently I recall there were troubles with the debian repo for thorium. they were fixed but now a funny thing:

```
Architectures: amd64
Codename: stable
Components: main
Date: Sat, 25 Jul 2023 19:28:23 +0000
Description: Thorium Browser packages
Label: thorium
Origin: dl.thorium.rocks
Suite: stable
```

**Comment by midzer** [comment]
Thanks for reporting, @pwn0r.

Day fixed! Please try again ;D

**Comment by pwn0r** [comment]
not updated, if the link is correct:

https://dl.thorium.rocks/debian/dists/stable/Release

accessing thru the browser still shows 25 jul 2023 in this file

**Comment by midzer** [comment]
D'oh, month was wrong, too...

Scripting this whole release mess would help probably.

**Comment by midzer** [comment]
Should work again^^

Feel fee to reopen if anything goes wrong with the repo again.
