### ISSUE TITLE
Gmail (Google Account)

### ISSUE THREAD

**Issue by QueenUlyana** [Alex313031/thorium#183]
**System Details**
 - OS: Windows 10 LTSC 21H2 19044.2486
 - Thorium Version: 114.0.5735.134

**Problem**
RPC executor service threw an error!

**Additional Notes**
I can't log in to my account, I get an error. I can log in through Google Chrome without any problems.

**Comment by gz83** [comment]
There is no abnormality in the local test using Thorium to log in to the Google account. You need to check the extensions you have installed and your network environment.

At the same time, there is a suggestion that when you encounter a problem, you can first check it yourself, and sometimes you will get a solution to the problem after you check it yourself

@QueenUlyana

**Comment by QueenUlyana** [comment]
> There is no abnormality in the local test using Thorium to log in to the Google account. You need to check the extensions you have installed and your network environment.
> 
> At the same time, there is a suggestion that when you encounter a problem, you can first check it yourself, and sometimes you will get a solution to the problem after you check it yourself
> 
> @QueenUlyana

How do I check? What should I check? I don't understand.
