### ISSUE TITLE
Suggestion: Is there any plans for the AWS lambda (ARM64) environment?

### ISSUE THREAD

**Issue by bysssss** [Alex313031/thorium#185]
hello :-)

I am doing web rendering in AWS lambda environment.
And I need high speed and HEVC codec support.
As a result I am trying to use "thorium".

By the way, does "thorium" work in the AWS lambda?
Can I get a binary file that works in AWS lambda (ARM64) environment?

**Comment by gz83** [comment]
We have provided the arm64 version, you can download the arm64 version in the repo

@bysssss

**Comment by bysssss** [comment]
@gz83 

hi, 
Are you referring to the "arm folder" for Raspberry Pi?
(https://github.com/Alex313031/thorium/tree/main/arm)

Does it work in AWS Lambda ARM64 environment?

**Comment by gz83** [comment]
Installers and portable versions of versions for arm64 architectures are not in this repository, but in

[Thorium-Special](https://github.com/Alex313031/Thorium-Special/releases)

**Comment by Alex313031** [comment]
@bysssss @gz83 The arm installers in there are for raspberry pi, but they should work with any arm64 linux, as long as the CPU has NEON extensions (almost all armv8 cpus)
