### ISSUE TITLE
New Integrated ad blocker trackers of the new duckduckgo web browser

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#186]
Hello, it looks like google might remove the google account of those who use an adblocker on youtube, so the solution seems to be "Duck Player," which shows (most) YouTube videos "without privacy-invading ads" and doesn't feed your recommendations"

duckduckgo is making a web browser for windows and mac in beta version with a lot of privacy tools!

https://arstechnica.com/gadgets/2023/06/duckduckgo-offers-its-privacy-centered-browser-in-a-windows-open-beta/

other developers make web browsers with an integrated adblock like the experimental uazo browser and the macchrome web browser..., maybe our beloved Thorium browser can integrate these options, thank you very much!

https://github.com/uazo/bromite-buildtools
https://duckduckgo.com/windows
https://duckduckgo.com/mac
https://github.com/duckduckgo/Android
https://github.com/duckduckgo/iOS
https://github.com/uazo/bromite
https://github.com/macchrome/winchrome/releases
https://github.com/macchrome/droidchrome/releases

**Comment by gz83** [comment]
You can try to solve the problem of web ads by installing ad filtering extensions, etc. If the site does not allow the use of ad filtering extensions, please consider complying with the site's rules if possible

@trimechee

**Comment by trimechee** [comment]
I already use ublock origin but i said to myself adblocker integrated natively in the browser would be even more efficient , and the new features of the new duckduckgo web browser are revolutionary....but i search and i can't find the source code of duckduckgo web browser for windows

**Comment by h4rldev** [comment]
duckduckgo is sadly quite "sus" in terms of security, since they seem to love violating their own privacy policy quite a lot

**Comment by m1m1s1ku** [comment]
https://github.com/yuliskov/SmartTubeNext
