### ISSUE TITLE
Small UI Tweak

### ISSUE THREAD

**Issue by People-11** [Alex313031/thorium#188]
The animation on the tab bar (opening new tab, closing tab and the spinning circle while loading) seems only 40-60 FPS or lower. Although it will hardly attract any attention, I still wish those animation can be the same frame rate as screen bcs thats smooth.

**Comment by gz83** [comment]
Thanks for your suggestions, we will make the Thorium browser better within the scope of our ability, including introducing more useful functions and modifications upstream and in the Thorium repo.

@People-11

**Comment by midzer** [comment]
@People-11 How did you detect those effects running at mentioned fps? Just askin as I'm curious.

My laptop is running at 60fps. Another TFT I use can do 144hz. Personally, I feel the smoothness differnce by moving mouse primarily (and in action oriented games).

**Comment by People-11** [comment]
@midzer I screen recorded with 120FPS and counts them frame by frame.
