### ISSUE TITLE
Linux arm64 releases

### ISSUE THREAD

**Issue by corford** [Alex313031/thorium#189]
Apologies if I've somehow missed it but, afaict, there are currently no linux arm64 releases of Thorium. Is this something that could be added? Use case is bundling Thorium in a multi-arch (amd64 and arm64) linux docker image (ubuntu).

**Comment by corford** [comment]
Just now saw this comment: https://github.com/Alex313031/thorium/issues/185#issuecomment-1627028570 - so looks like my use case is already satisifed :) 

Maybe the release docs could be modified to explicitly mention that the raspi arm64 release should also work on most linux arm64 systems.

**Comment by RobRich999** [comment]
Apple M-series chips are ARMv8 compatible, so they support NEON SIMD instructions.

Ubuntu has Chromium binaries for Linux on arm64.

https://launchpad.net/ubuntu/lunar/arm64/chromium-browser

In theory Thorium's RPI binaries "should" run under Linux on a M-series proc.

https://github.com/Alex313031/Thorium-Special

**Comment by Alex313031** [comment]
@RobRich999 @corford The raspi binaries will indeed run on any arm64 CPU with NEON, which every M series Mac has. However, it is tuned for the a-72 cores in the raspi 4, so might have slightly lower performance than one with generic tuning.

Also, it has a patch to enable hardware acceleration on the videocore4 GPU in the Pi 4. This *shouldnt* mess up GPU acceleration on other platforms, but it is possible that it might. As always, check chrome://gpu to verify.

**Comment by RobRich999** [comment]
Hardware GPU acceleration could be a huge YMMV. AFAIK, Asahi devs managed OpenGL ES 2 support on Apple Mx, but I am not sure about the current state of ES 3 support.

Anyway, I suspect Chromium software rendering performance should be decent on a M2 system.
