### ISSUE TITLE
some issues under XFCE

### ISSUE THREAD

**Issue by Unixware** [Alex313031/Thorium#19]
Its a bit strange but on debian sid (XCFE) this browser is not visible on the preferred apps (default browser) also by running the /usr/bin/thorium*  ("star" as  for a strange reason you install two scripts one as "stable" and the other as "umstable" ) it pauses the profile. I did the installation via your .deb file anyway. IMHO something is broken there or bad mix of scripts. thanks!

**Comment by Alex313031** [comment]
Reopened issue. Did you resolve it and if so, how? And there is thorium-browser which is a symlink to thorium-browser-unstable. There shouldn't be any file called thorium-browser-stable.

**Comment by Unixware** [comment]
thanks but no need to re-open , if I uninstall the firefox , then the thorium is the "default"
