### ISSUE TITLE
Old google image reverse search interface not working with thorium,may be a thorium flag issue.

### ISSUE THREAD

**Issue by Username23453** [Alex313031/thorium#194]
Google recently changed its google reverse images search interface, it sucks now. Supposedly theres a flag & changing it reverts back to the old version/design thats way better. However it has not worked for me in Thorium. See this reddit post for more details: 
https://www.reddit.com/r/chrome/comments/13cbnbj/comment/ju8lfdf/?context=3 

See this flag, it dont work in thorium, but does with chrome apparently, i tried it:
https://preview.redd.it/bxgue7quljeb1.png?width=1466&format=png&auto=webp&s=9377ed41d7cd9f35f787a358c3821876be1e52fa 

However i did find a solution amazingly that works awesome & brings back google's older version, its this github browser extension:
https://github.com/fanfare/disablegooglelens

However I'm bringing this up, because that github extension could break/stop working anytime, & I and many others are very dependant on google reverse image search, some people's jobs rely on the tool actually.
Yandex works okay, and is an "okay" substitute, but nothing compares really to google's reverse image search. 

Can someone please test this out on their side & try to verify this & solve it, and the flag issue? What google changed was this screenshot below, we no longer can natively find duplicate photos of a photo & all its varying sizes, which is incredibly helpful, of which the screenshot shows, what the screenshot shows is no longer natively available.
![image](https://github.com/Alex313031/thorium/assets/105397593/9452e154-f206-417f-b096-c2f9d8006dbb)

**Comment by Alex313031** [comment]
@Username23453 Interesting. There's no reason why the flag shouldn't work in Thorium. I have made no modifications to this feature or the flag that controls it.
