### ISSUE TITLE
User scripts support?

### ISSUE THREAD

**Issue by unit-404** [Alex313031/thorium#195]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like, including relevant patches or source**

I would like to support user-script on android, just like it is implemented in cromite browser. Would like something like customization for different sites.

**Comment by gz83** [comment]
Do the userscripts you mentioned need to be supported by extensions? If yes, currently the Android version of thorium cannot use extensions, so user scripts cannot be used for the time being

@unit-404
