### ISSUE TITLE
Only Mono output when playing WebRTC

### ISSUE THREAD

**Issue by zapf2000** [Alex313031/thorium#196]
**System Details**
 - OS:Ubuntu 22.04
 - Thorium Version 114.0.5735.134

**Problem**
When playing a WebRTC stream, the audio is only played in mono, even it shows 2 channels in webrtc internals and the offer from server side includes stereo=1. On Firefox it works normally in Stereo (sdp answer is correct). Thorium and also Chromium  defaults to Mono playback (sdp answer unsufficient). 

**Screenshots**
![Screenshot_20230804_133054](https://github.com/Alex313031/thorium/assets/52130927/95df812a-f7f0-4845-9fd3-437965f44856)

**Additional Notes**
SDP log:

offer on server side:
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 cbr=1;maxaveragebitrate=131072;minptime=10;sprop-stereo=1;stereo=1;useinbandfec=1

answer on browser side:
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1 <<< here i should see stereo=1 ... then stereo is put out. Chromium always answers like this, so only mono output.

**Comment by gz83** [comment]
If you have the same problem on chromium/chrome, it may be a bug or the corresponding code in the upstream is not fully written, you can try to report the problem you encounter to Google on crbug.

@zapf2000
