### ISSUE TITLE
Thorium crashes with SIGFPE when dragging tab with mouse

### ISSUE THREAD

**Issue by Kamillaova** [Alex313031/thorium#197]
**System Details**
 - OS: Arch Linux
 - Thorium Version: 114.0.5735.205

**Problem**
Thorium crashes with SIGFPE when dragging tab with mouse

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/54859825/cdeffe38-be80-46e1-856f-d2db1adeb707)

**Comment by dmig** [comment]
Why is it trying to access CPU governor settings???

**Comment by Kamillaova** [comment]
> Why is it trying to access CPU governor settings???

Official builds of Google Chrome too, that's not a problem
I've always had this "error"

**Comment by dmig** [comment]
What CPU do you have?

**Comment by Kamillaova** [comment]
> What CPU do you have? This error and Floating point exception make me think it's something not very popular

Ryzen 5 2600 AF @ stock clock

**Comment by dmig** [comment]
CPU Shouldn't be a problem. Maybe it's DE/theme related.

Do you use any theme?
System titlebar and borders?
What DE?

**Comment by Kamillaova** [comment]
> What DE?

sway + wlroots-git with xwayland hidpi patches

![image](https://github.com/Alex313031/thorium/assets/54859825/7bb7fdea-f421-4cbf-81ab-af0882b9435b)
![image](https://github.com/Alex313031/thorium/assets/54859825/dbf2309c-4eee-4e3c-a7b2-55b2fcc30b43)

**Comment by Kamillaova** [comment]
>Do you use any theme?

Just Black from chrome web store
>System titlebar and borders?

Yes
> What DE?

i3wm without compositing

**Comment by dmig** [comment]
Ok, does chrome/chromium with same settings crash?

**Comment by Kamillaova** [comment]
> Ok, does chrome/chromium with same settings crash?

chrome - no, dragging tabs works fine

**Comment by xtarlit** [comment]
Same issue here. Dragging tabs results in a crash. Seems to happen when one of them gets pulled out into a window?
![image](https://github.com/Alex313031/thorium/assets/141593384/bfca25fb-4d61-48a8-b43b-1e3c5ed1c354)

System Details:
- Ryzen 5 2500U w/ iGPU
- KDE Plasma (Wayland)
- (fully up-to-date) Arch Linux
- Not using system titlebar/borders
- Default dark theme

**Comment by gz83** [comment]
Do you have experimental flags turned on, and if so please provide them

@dmig @Kamillaova @xtarlit

**Comment by xtarlit** [comment]
I have a few enabled:
Smooth scrolling - Enabled
Overscroll history navigation - Enabled
Preferred Ozone platform - Wayland
Tab scrolling - Enabled (tabs shrink to medium width)
Enable the heuristics-based policy for Memory Saver Mode - Enabled (Balanced)

Additionally, Thorium is started with the argument: `'--enable-features=TouchpadOverscrollHistoryNavigation'`

**Comment by gz83** [comment]
Try turning off the `Tab scrolling` experimental flag and see if the browser crashes again.

This experimental flag has caused multiple crashes.

@xtarlit

**Comment by xtarlit** [comment]
Can confirm, disabling tab scrolling causes the crash to go away for me.

**Comment by xtarlit** [comment]
I've just tried it in Chromium with tab scrolling enabled, and the same issue is there too. Seems to be more related to Chromium than Thorium.

**Comment by Alex313031** [comment]
@
