### ISSUE TITLE
Replace native html5 player

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#198]
these html5 players add many wonderful features, it will be great to add them in the source code and thus use them for playback videos instead of native players, thank you very much!

https://haven.pages.dev/video-player/public/
https://haven.pages.dev/
https://github.com/ThaUnknown/pwa-haven

https://github.com/nt1m/media-player
https://nt1m.github.io/media-player/

https://github.com/inbasic/media-player

**Comment by Alex313031** [comment]
@trimechee I'm not going to add this because Chromium doesn't use HTML5 for it's player, but rather uses a backend that is specific to each platform.

**Comment by trimechee** [comment]
Interesting, thank you :)
