### ISSUE TITLE
Autoscroll functionality on Linux

### ISSUE THREAD

**Issue by nesper8** [Alex313031/thorium#199]
**Is your feature request related to a problem? Please describe.**
Hi. For a long time, Windows users have the middle click auto scroll feature in like forever and Linux (possibly Mac users too) needed to add the launch flag `--enable-blink-features=MiddleClickAutoscroll` to enable this feature. I tested this feature in Thorium and for sure it works on Thorium too.

https://github.com/Alex313031/thorium/assets/57890520/1c8c1944-7906-4afd-a5d8-d4e6b2097e83

But this has two problems. 

First one obviously is that this feature is behind a flag which can only be enabled through the above argument (not through `chrome://flags`)
Second, enabling this feature will always show a pop up saying "You are using an unsupported command-line flag"
![Screenshot from 2023-08-09 13-30-34](https://github.com/Alex313031/thorium/assets/57890520/4d33a20a-0118-42d0-8020-f90b85ab1b9d)

**Describe the solution you'd like, including relevant patches or source**
It would really be appreciated if you could enable this option by default on your Thorium releases or at least behind a flag which can be enabled through the `chrome://flags` options

**Additional Notes**
I found this solution on Brave browser's issue https://github.com/brave/brave-browser/issues/959
They also have a few talks on the Brave/Chromium code and stuff too

**Comment by gz83** [comment]
Thank you for your suggestion, this function is indeed as you said, it can be used normally on windows and I use this function on windows from time to time.

As for the automatic scrolling of non-windows desktop platforms, removing the #if guard and the new feature flag does not seem to be a difficult task, but it is necessary to ensure that doing so will not cause more bugs and affect the operation of some users.

There are also certain considerations for Google not actively dealing with this issue (usually considering factors such as design concepts of different platforms), just like the function of using the mouse wheel to switch tabs is only enabled by default on Linux.

@nesper8 @Alex313031

**Comment by nesper8** [comment]
It doesn't seem that the tab switching with scroll wheel function is in conflict with auto scroll function, nor any other functions in fact after using auto scroll for a fair amount of time.

**Comment by gz83** [comment]
You don't fully understand what I mean, what I mean is that the new features you mentioned need to be discussed and evaluated to avoid bringing more bugs and affecting users' daily use.

I mentioned the example of mouse wheel switching tabs to let you understand the considerations behind Google not enabling automatic scrolling on non-windows platforms.

@nesper8

**Comment by nesper8** [comment]
I apologise for not fully understanding your clarification

Thank you

**Comment by Alex313031** [comment]
@nesper8 Added! It is enabled by default for windows and linux now.

**Comment by nesper8** [comment]
Thank you very much 

Closing the issue now

**Comment by dmig** [comment]
@Alex313031 how to disable this feature?
In linux it is broken: when you try to paste, autoscroll turns on and page scrolls in random direction.

**Comment by gz83** [comment]
I have the impression that this function is turned on by default, and there is no switch for this function for the time being, and I or Alex313031 may bring a switch for this function in the future

@dmig

**Comment by Alex313031** [comment]
@gz83 @dmig @nesper8 I had a feeling someone would file a bug about this, thats why I said *please file issues encountered* on the latest releases. I would like to either add a commandline flag to enable this, or a chrome://flags flag

**Comment by Alex313031** [comment]
@nesper8 I removed it by default, however, I removed the annoying infobar warning. So now you can use the cmdline flag and it wont bug you on startup.

**Comment by p0358** [comment]
@dmig You can use left click at some empty space to disable it instead of middle click probably

**Comment by dmig** [comment]
@p0358 left click for what?
I often use middle click for pasting and this feature just breaks it.

**Comment by p0358** [comment]
To cancel the auto scroll after the first click and avoid it pasting the thing for the second time.

But in general I guess it's a Chromium bug sadly, as Firefox doesn't have that problem I think (and they expose the setting to the user normally)
