### ISSUE TITLE
problem with session / cookies or something ?

### ISSUE THREAD

**Issue by parisni** [Alex313031/Thorium#20]
Hello,

Sorry for this confuse issue, I am running thorium on ubuntu 20.04 installed with the deb package 
and something goes wrong with user sessions. Whenever I turn off thorium then I have to login 
in every single websites I was logged (eg: gmail)

I don't have this behavior with chromium. Any idea ? Otherwize everything works great, thanks for your work

**Comment by Alex313031** [comment]
@parisni Hmmm. Which version are you using? I will try to recreate in a 20.04 VM and investigate.

**Comment by parisni** [comment]
I am using `Version 101.0.4916.0 (Official Build) unstable (64-bit)`.

**Comment by Alex313031** [comment]
@parisni do a sudo apt purge thorium-browser-unstable, then move/rename/remove the ~/.config/thorium user profile folder, then install the latest release (101.0.4949.0) and see if the issue still happens.

**Comment by Bounty780** [comment]
I can confirm that the issue is also in Thorium-Win-AVX2, `Version 102.0.4952.0 (Official Build) (64-bit)`. It appears to be only with Google cookies.

**Comment by parisni** [comment]
I guess turning OFF `setting > profile > Allow Thorium sign-in`
helps me a lot

**Comment by Bounty780** [comment]
> I guess turning OFF `setting > profile > Allow Thorium sign-in` helps me a lot

Where is that?

**Comment by parisni** [comment]
> > I guess turning OFF `setting > profile > Allow Thorium sign-in` helps me a lot
> 
> Where is that?

its in `sync and google service`

**Comment by Alex313031** [comment]
@parisni @Bounty780 @midzer This has to do with the baked in api keys. Similar issue when trying to enable sync. Follow instructions at https://github.com/Alex313031/Thorium-Win/issues/9

**Comment by Alex313031** [comment]
@parisni @Bounty780 You could also turn sign in off if you don't use it.

**Comment by parisni** [comment]
On Sat Mar 26, 2022 at 1:11 AM CET, Alexander David Frick wrote:
> @parisni @Bounty780 You could also turn sign in off if you don't use it.

Yeah, that's what I did, and my troubles mostly disapeared on this side.
