### ISSUE TITLE
task scheduler updater and version checker

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#200]
I would like to recommend the wonderful Thorium browser to my friends, my family, and my twitter followers in sha Allah, the problem that many don't know how to update Thorium and would find too complicated to check and go to github... .

and even I can forget to go to the relaeses page to check if there is a new version....so our wish please is to add a task to the task scheduler as librewolf web browser did recently, an optional task that can be disabled in the installer, and the task scheduler update task will check once a month if there is a new version and display a message with a link to the Thorium releases page inviting the user to download the new version, thank you very much!

Also if we refuse to add task update to task scheduler, it will be great to add a version checker when we click on the "about" button of the browser and so Thorium will send us a warning message the version is outdated and it shows us a message with a link to the relaeses page of github when a new update is available! Thank you so much !

**Comment by Alex313031** [comment]
@trimechee Can you send a link to the librewolf task scheduler?

**Comment by trimechee** [comment]
The task scheduler of librewold was added recently, more or less a month ago, I use the 64bit windows version of librewolf, and in the installer there is a "librewolf updater" option which adds a task in the background to task scheduler which checks every 6 hours for new version , I seem to have read this info that every 6 hours there is version checking in their forum:

https://librewolf.net/installation/windows/

**Comment by ltguillaume** [comment]
Lol, I was looking for a way to update Thorium automatically, only to find this issue mentioning my project https://github.com/ltguillaume/librewolf-winupdater 😛

So yeah, I've just forked LibreWolf WinUpdater for Thorium: https://codeberg.org/ltguillaume/thorium-winupdater

- It should work for both the mini-installer (run it from anywhere) and the semi-portable zip file (put it next to `THORIUM.BAT`).
- **Doesn't** do a checksum verification of the download yet
- It defaults to the **Win-AVX2** build. For now, you can use the `Win`/`Win7` build by making a `Thorium-WinUpdater.ini` with the following:
    ```
    [Settings]
    Build = Win7
    ```
   @Alex313031 if there is a way to deduct the build from the files, I can probably automate this.

**Comment by trimechee** [comment]
@ltguillaume Sensational great amazing ! 🥇Thank you so much :)

**Comment by Alex313031** [comment]
@ltguillaume Unfortunately, there is no way right now to deduct the build, because the only differences are in the instruction set it's compiled with. However, I could add a file to each build, a file that has info about the build type.

**Comment by ltguillaume** [comment]
That or just embedding it in the version info of `thorium.exe` would be great!

**Comment by trimechee** [comment]
There is another updater : https://github.com/henrypp/chrlauncher

**Comment by ltguillaume** [comment]
Can't be used for Thorium, right?

**Comment by trimechee** [comment]
I haven't tested but it says :

"Supported browser:

     as launcher - Chromium based (like Google Chrome, Opera, Yandex Browser, Vivaldi, etc.) and Firefox based (Mozilla Firefox, Basilisk, Pale Moon, Waterfox, etc.)
     as updater - Chromium only
"

**Comment by ltguillaume** [comment]
It can't. I've used chrlauncher in the past, it allows you to choose from a few update channels in the ini file, Thorium isn't among them.

**Comment by trimechee** [comment]
Instructive to know, thank you :) 👍

**Comment by ltguillaume** [comment]
@trimechee I just came across the following: https://github.com/uazo/cromite#auto-update-setup-for-windows

So apparently it is possible to have a custom version updated by chrlauncher if someone (the project author) maintains an update text file.

**Comment by trimechee** [comment]
Interesting ! Thank you so much @ltguillaume  :) 💯  🥇

 I think the most important and capital is to be able to do a manual update quickly and simply without complications when we click on the "update" button of the web browser, because many web browsers based on chromium refer to the official site of chromium when we click on "about version" while it should send us to the relaeses page of github of the web browser based on chromium....
