### ISSUE TITLE
Bookmark favicons not displaying after M115.0.5790.172

### ISSUE THREAD

**Issue by turtlshell** [Alex313031/thorium#204]
**System Details**
 - OS: Manjaro (testing branch, Kernel 6.4.11) & 2 different installations of Windows 11. All with latest updates.
 - Thorium Version M115.0.5790.172

**Problem**
Bookmarks show the default greyed-out globe placeholder favicon instead of site-specific favicons post-update to M115.0.5790.172. 

This first happened on my Manjaro install after updating Thorium-Bin from AUR. Upon starting Thorium I was greeted with a popup warning that something in my profile couldn't be read (different wording, but that was the premise) and I noticed this issue.

I also updated Thorium AVX2 on my Windows 11 install on the same machine, and on a different W11 machine, and observed the same problem, this time with no popup related to a profile issue.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/47285125/de1b79a2-002c-4ac7-bb41-4691a91fee45)

**Comment by turtlshell** [comment]
Tracked down the exact profile warning I got on Manjaro:
![image](https://github.com/Alex313031/thorium/assets/47285125/b471d955-feeb-4caa-b259-3b15b07580ba)

**Comment by Alex313031** [comment]
@turtlshell Were you using the portable flags?

**Comment by turtlshell** [comment]
> @turtlshell Were you using the portable flags?

No, I wasn't

**Comment by gz83** [comment]
Please use the new user data, and only import bookmarks, and then check whether the favicons of bookmarks can be displayed normally

@turtlshell
