### ISSUE TITLE
Why hardcoding to HOME directory ??

### ISSUE THREAD

**Issue by LeOS-GSI** [Alex313031/thorium#205]
Why hard coding to HOME directory ?? That makes no sense, A lot of users are using different places for building. I'm using an second SSD. 

Hard coding in a script is never a good way for coding

Sorry, but your build tutorial is not working.

**Comment by Alex313031** [comment]
@LeOS-GSI You're right
I recently added an environment variable so that you could set the location of chromium/src, I should do this for the thorium source as well.

See https://github.com/Alex313031/thorium/blob/main/setup.sh#L38

I could add a similar 'TH_DIR' variable.

**Comment by LeOS-GSI** [comment]
I'm building my LeOSium browser and webview for Android and Linux ( deb)

 I have seen that you have some interesting patches included, but no patch repo :(
 Your build I can't use, because it has to much google shit on board. So I thought I can use some of your build script and remove some if the google stuff.

But your script no able to use the actual 18.xxx sources which I'm using.

**Comment by Alex313031** [comment]
@LeOS-GSI You can use trunk.sh to check out tip of tree. You can use version.sh to check out any version, just change the THOR_VER variable. setup.sh copies the source files. I prefer to have a tree mirroring the chromium one, with the actual files in it, rather than .patch files. If you want info on all the patches used, see [PATCHES.md](https://github.com/Alex313031/thorium/blob/main/infra/PATCHES.md)

**Comment by LeOS-GSI** [comment]
Ok, that means, all patched files are in your repo? No 'apply patches'? 

And sure I have checked the patch.md file. But I can't believe that are all patches. I'm using around 150 patches in my full ungoogled LeOSium browser.

**Comment by Alex313031** [comment]
@LeOS-GSI Yes all patches files are in the src/ dir in the repo. And where is your LeOSium browser?

**Comment by LeOS-GSI** [comment]
My LeOSium Linux browser is still in Alpha and only stored local. 

my LeOSium Android webview and browser repo is located here https://gitlab.com/leos1/leosium
