### ISSUE TITLE
[Wayland] Dropdown menu bugged

### ISSUE THREAD

**Issue by GrabbenD** [Alex313031/thorium#207]
**System Details**
 - OS: Arch Linux
 - Thorium Version: Version 115.0.5790.172

**Problem**
With Wayland (Sway), drop down menus are difficult to use, e.g. in `chrome://flags`
- Hovering over items highlights the wrong item in the array (but it's right when you click)
- Drop down menu is flickering and leaving artifacts from mouse highlight
- After selection, the menu leaves borders on the screen

For reference, Thorium is started with:
```console
$ thorium-browser --ozone-platform=wayland
```

**Screenshots**
N/A

**Additional Notes**
N/A

**Comment by crthpl** [comment]
I am on Hyprland and the `chrome://flags` dropdowns work fine for me. What compositor are you using?

**Comment by GrabbenD** [comment]
@crthpl Here's what I noticed:

1. On first start after entering (Sway) compositor, it works but if you restart the browser this bug starts to happen
2. `WLR_RENDERER` doesn't make a difference (default vs vulkan)
3. I could reproduce this with Hyprland
4. This only happens if Wayland mode is used (as default seems to be XWayland): `--ozone-platform=wayland`

**Comment by Alex313031** [comment]
@GrabbenD @crthpl Wayland has too many bugs and inconsistencies for me to even keep track of. I am getting to the point of personal frustration (not directed at any users, I appreciate bug reports), that I kind of feel like throwing my hands up and just labeling every wayland bug as a WontFix, letting upstream chromium sort through the mess that is wayland. Wayland is great for the things that it does, but apps need to catch up as far as wayland support, and wayland compositors could do a better job of standards compliance. It's frustrating I know. All I can say is try different things, look here in the issues or on the internet for workarounds, wait for new releases, or use XWayland or just revert to X.org.

**Comment by Alex313031** [comment]
@GrabbenD @crthpl That being said, if you have a specific thing that you know works in a Chromium build at the exact same revision as Thorium, but is broken in Thorium, let me know, because then I know that it is likely on my end in the //content/ dir of the source code

**Comment by Alex313031** [comment]
@gz83 What is your take on this?

**Comment by GrabbenD** [comment]
You're right @Alex313031
I haven't seen this issue or any at all in Wayland since Thorium 116.0.5845.169!

For reference, now I'm using using Sway 1.9-dev + wlroots 0.17-dev with these launch parameters if anyone is curious:

```console
# Alternatively use ~/.config/thorium-flags.conf
thorium-browser --ozone-platform=wayland --enable-zero-copy --enable-features=VaapiVideoDecoder --enable-features=CanvasOopRasterization --enable-gpu-rasterization --use-vulkan
```

> Graphics Feature Status
> Canvas: Hardware accelerated
> Canvas out-of-process rasterization: Enabled
> Direct Rendering Display Compositor: Disabled
> Compositing: Hardware accelerated
> Multiple Raster Threads: Enabled
> OpenGL: Enabled
> Rasterization: Hardware accelerated on all pages
> Raw Draw: Disabled
> Skia Graphite: Disabled
> Video Decode: Hardware accelerated
> Video Encode: Hardware accelerated
> Vulkan: Enabled
> WebGL: Hardware accelerated
> WebGL2: Hardware accelerated
> WebGPU: Disabled

P.S. there's massive input delay with `--enable-native-gpu-memory-buffers`
