### ISSUE TITLE
I hope to adapt to the native scroll bar of Windows 11

### ISSUE THREAD

**Issue by Malus-risus** [Alex313031/thorium#208]
As the title

reference style：
![image](https://github.com/Alex313031/thorium/assets/69906215/0f439ab5-cf88-498a-b7b8-7d2c5c7c0cd4)

 the style is from Microsoft edge

**Comment by gz83** [comment]
Thorium is currently based on version 115. I have the impression that chromium already supports this style of scrollbar in a newer version, so we just need to wait for Thorium to update to the version that supports this style of scrollbar.

@Cryberghost

**Comment by Cryberghost** [comment]
> Thorium is currently based on version 115. I have the impression that chromium already supports this style of scrollbar in a newer version, so we just need to wait for Thorium to update to the version that supports this style of scrollbar.
> 
> @Cryberghost

real?

**Comment by gz83** [comment]
You can check whether there are related experimental flags in the canary or chromium version, in my impression there are related experimental flags

@Cryberghost

**Comment by Alex313031** [comment]
@Cryberghost Yeah. You might try the overlay scrollbars flag.
