### ISSUE TITLE
system notifications cannot take effect

### ISSUE THREAD

**Issue by Malus-risus** [Alex313031/thorium#209]
**System Details**
 - OS: [Windows 11]
 - Thorium Version [116.0.5845.169(AVX2)]

**Problem**
The system notifications cannot take effect.

**Screenshots**

1. wrong(Thorium)
![image](https://github.com/Alex313031/thorium/assets/69906215/c6971d5c-d7c3-4230-bad2-6610cff4cfc3)
2. normal(Chrome)
![image](https://github.com/Alex313031/thorium/assets/69906215/6ac8d9fd-4af3-49c1-9abc-b78a3cb6df20)

**Additional Notes**
"Enable system notifications.(chrome://flags/#enable-system-notifications)" This feature is enabled by default in chrome, and Thorium displays it by default, so I enabled it but it didn't take effect. I hope it will be fixed as soon as possible.
![image](https://github.com/Alex313031/thorium/assets/69906215/56d70272-ca0d-4e54-85cc-436166af470e)

**Comment by gz83** [comment]
Please use chrome/chromium with the same version as Thorium for testing

@Cryberghost

**Comment by Cryberghost** [comment]
> Please use chrome/chromium with the same version as Thorium for testing
> 
> @Cryberghost

Also like this

**Comment by Cryberghost** [comment]
> Please use chrome/chromium with the same version as Thorium for testing
> 
> @Cryberghost

I tested a few more versions, chrome and even 100 can be used.

**Comment by gz83** [comment]
What is the effect of using the same version of chromium as Thorium?

@Cryberghost

**Comment by Cryberghost** [comment]
> What is the effect of using the same version of chromium as Thorium?
> 
> @Cryberghost

The effect is the same as 105, except that in my test sample, the effect above 100 is the same and normal.

**Comment by gz83** [comment]
I'm not very clear about the meaning of your replies, can you list all the test results of different versions? Just put it in one reply.

@Cryberghost

**Comment by Cryberghost** [comment]
> I'm not very clear about the meaning of your replies, can you list all the test results of different versions? Just put it in one reply.
> 
> @Cryberghost

same version of chromium as Thorium works normal.

**Comment by gz83** [comment]
Keep Thorium's configuration the same as Chromium's and test again

@Cryberghost

**Comment by Cryberghost** [comment]
> Keep Thorium's configuration the same as Chromium's and test again
> 
> @Cryberghost

The result is the same.

**Comment by Cryberghost** [comment]
The latest version has been updated, but the problem still exists!

**Comment by Cryberghost** [comment]
@Alex313031

**Comment by gz83** [comment]
It is recommended that you test other third-party compiled versions of Chromium and report the test results again in this issue.

@Cryberghost

**Comment by Alex313031** [comment]
@gz83 Can you try on your machine? I can also try on my Windows 10 machine.

**Comment by gz83** [comment]
I also found this problem in previous tests, but it seems that this problem is specific to Chromium?

@Alex313031

**Comment by Malus-risus** [comment]
The issue still persists with the latest version of Thorium. I tried triggering notifications using both Chrome and Thorium simultaneously, and Chrome continues to work properly, while Thorium still produces an error.

@gz83 @Alex313031

**Comment by gz83** [comment]
> The issue still persists with the latest version of Thorium. I tried triggering notifications using both Chrome and Thorium simultaneously, and Chrome continues to work properly, while Thorium still produces an error.
> 
> @gz83 @Alex313031

Try the effect of Chromium, don't try it in Chrome. If the same is true for Chromium, it is a limited function in Chrome.

Note, do not test with other Chromium-based browsers, but with the original version of Chromium.

@Malus-risus

**Comment by Malus-risus** [comment]
> > The issue still persists with the latest version of Thorium. I tried triggering notifications using both Chrome and Thorium simultaneously, and Chrome continues to work properly, while Thorium still produces an error.
> > @gz83 @Alex313031
> 
> Try the effect of Chromium, don't try it in Chrome. If the same is true for Chromium, it is a limited function in Chrome.
> 
> Note, do not test with other Chromium-based browsers, but with the original version of Chromium.
> 
> @Malus-risus

Indeed, it is true that Chromium doesn't have it either. Are there any plans to implement system notifications?

**Comment by gz83** [comment]
> > > The issue still persists with the latest version of Thorium. I tried triggering notifications using both Chrome and Thorium simultaneously, and Chrome continues to work properly, while Thorium still produces an error.
> > > @gz83 @Alex313031
> > 
> > 
> > Try the effect of Chromium, don't try it in Chrome. If the same is true for Chromium, it is a limited function in Chrome.
> > Note, do not test with other Chromium-based browsers, but with the original version of Chromium.
> > @Malus-risus
> 
> Indeed, it is true that Chromium doesn't have it either. Are there any plans to implement system notifications?

This means it's a Chrome specific feature

@Malus-risus
