### ISSUE TITLE
Thorium messes up with VS Code installation

### ISSUE THREAD

**Issue by h1zardian** [Alex313031/thorium#210]
**System Details**
 - OS: Fedora Linux 38 (Linux 6.4.12-200.fc38.x86_64)
 - Thorium Version 115.0.5790.172

**Problem**
Why does the **Thorium Browser** has a dependency on a certain version of **VSCode**?

**Screenshots**
![Installing Thorium](https://github.com/Alex313031/thorium/assets/53666693/80ba902d-56d6-4840-b9c2-b68982a62d19)

**Additional Notes**
After installation, if I run **system update**, vscode installs the **exploration** and **insiders** build. removing which also removes **Thorium Browser**

![Removing dependencies](https://github.com/Alex313031/thorium/assets/53666693/47279c82-69f2-4f2b-aade-d8845514aa11)

**Comment by Alex313031** [comment]
@h1zardian Thats really weird. I will see if there are any conflicting dependencies on the AUR page. However, I do not maintain the AUR builds of Thorium. If it still causes issues, I recommend using the .appimage or .zip (although I know it wont auto update)
