### ISSUE TITLE
Hardware video acceleration gone after update

### ISSUE THREAD

**Issue by dmig** [Alex313031/thorium#212]
**System Details**
 - OS: Ubuntu 22.04
 - Thorium Version 116.0.5845.169

**Problem**
After updating from build 50 checked with `intel_gpu_top` -- hardware video decoding is not being used anymore.

**Additional Notes**
```
ANGLE (Intel, Mesa Intel(R) UHD Graphics (CML GT2), OpenGL 4.6 (Core Profile) Mesa 23.1.6 - kisak-mesa PPA)
```
```
Video Acceleration Information
Decoding
Encoding
Encode h264 baseline
321x241 to 4096x4096 pixels, and/or 30.000 fps.
Encode h264 main
321x241 to 4096x4096 pixels, and/or 30.000 fps.
Encode h264 high
321x241 to 4096x4096 pixels, and/or 30.000 fps.
Encode vp8
321x241 to 4096x4096 pixels, and/or 30.000 fps.
```

**Comment by lgdsgd2000** [comment]
From [M116.0.5845.169](https://github.com/Alex313031/thorium/releases/tag/M116.0.5845.169)"The old VaapiVideoDecodeAccelerator path was [completely removed](https://source.chromium.org/chromium/chromium/src/+/6fb414a7d51f46940cf9c45df04f6ee398f8da1b) upstream, in favour of the new VDAVideoDecoder backend that now powers both Chromium and ChromiumOS. Consequently, the VAAPI and Intel HD patches were removed. The VDPAU patch is now the only remaining graphics patch, for Nvidia users. This should hopefully fix issues people have been having with VAAPI and Wayland. Indeed some people have commented in https://github.com/Alex313031/thorium/issues/162 saying that a vanilla graphics backend works better than Thorium with all of the patches applied."

**Comment by dmig** [comment]
Well, Google Chrome Dev -- hardware acceleration works flawlessly, Thorium -- doesn't even try to use it according to intel_gpu_top.

**Comment by Alex313031** [comment]
@dmig @lgdsgd2000 M117 removes the VDPAU patch too. So now the video decoding backend is mostly stock chromium, and so should work/not work in the same scenarios as Chrome 117.

**Comment by lgdsgd2000** [comment]
So maybe x11/xwayland hardware decoding available on intel platforms? As far as I know, the amd platform ones have been broken since chromium 116 and may return in 119

**Comment by gz83** [comment]
Thorium's current behavior should be consistent with Chromium 117's behavior on x11/xwayland

@lgdsgd2000

**Comment by lgdsgd2000** [comment]
I got this error on M117 with my intel pc ```"VaapiVideoDecoder: failed Initialize()ing the frame pool"``` this error always appears on amd cards. @gz83

**Comment by gz83** [comment]
If Thorium 117 and Chromium 117 behave the same on your computer, that's normal.

Chromium's support for hardware acceleration on Linux is not as complete as other platforms and versions. It requires the help of many things to have the opportunity to enable hardware acceleration.

@lgdsgd2000

**Comment by lgdsgd2000** [comment]
@gz83 it now works on my archlinux, the previous error appeared in debian. Not sure what the difference is,anyway thanks
