### ISSUE TITLE
[Pick a theme color] Add arbitrary colour selections

### ISSUE THREAD

**Issue by rubyFeedback** [Alex313031/thorium#213]
Not sure if this is a useful request, but I'll just do it.

Right now we can pick a theme from perhaps 20 default ones.

e. g. in

chrome://settings/manageProfile

The default is nice but I want a light green instead. This one is
not so easily available. Could we add a colour-chooser widget
there? That way we could pick arbitrary colours rather than
the defaults.

**Comment by Alex313031** [comment]
@rubyFeedback This will be coming in Chromium 118, so I dont wanna put the work in to backport it since it is coming out soon anyway.
