### ISSUE TITLE
Browser's viewport is not utilised properly

### ISSUE THREAD

**Issue by xd003** [Alex313031/thorium#215]
**System Details**
 - OS: Windows 11
 - Thorium Version 116.0.5845.169

The elements on a webpage don't utilise the the whole viewport properly and appear sort of zoomed out. It is something that happens on all websites but i am taking youtube as example here as its easier to identify the differences here. Just open YouTube and play any video. On this page, there is screen space being wasted on the left and right side like there's some sort of margin. It doesn't seem to happen on Chrome or even chromium based browser like Brave. I am attaching a screenshot to better explain the issue. Interestingly this same issue also seems to happen on Ungoogled Chromium for some reason.

Chrome/Brave
![IMG_20230908_232837_131](https://github.com/ungoogled-software/ungoogled-chromium/assets/26503185/2ee49caa-b2cf-479b-90e2-f6e3f29d85a6)

Thorium/Ungoogled Chromium
![IMG_20230908_232841_964](https://github.com/ungoogled-software/ungoogled-chromium/assets/26503185/8bb52f50-b709-4f5a-b8be-9e8595c5cb24)

**Comment by gz83** [comment]
Please try your best to ensure that the version numbers and configurations between different browsers are consistent before testing.

In addition, I also saw that you did not log in to your Google account when testing in Thorium. You still need to log in to your Google account to test.

@xd003

**Comment by xd003** [comment]
@gz83 The configuration between both the browsers were same. Disabling the bookmarks toolbar has seemingly fixed the problem, the web pages are rendered properly now.

**Comment by vanboom** [comment]
I am seeing this issue in Zammad which appears to have a height: 100% on the body element. 

URL: https://zammaddemo.agitos.de/#dashboard
Sign in using the demo credentials: 

In Chromium and Firefox, the viewport height works...
![image](https://github.com/Alex313031/thorium/assets/251706/af02b12e-f038-4455-b889-e87da0b4259a)

In Thorium, the height does not stop at the viewport limit so you have to scroll all the way down...

![image](https://github.com/Alex313031/thorium/assets/251706/db61f094-0a1f-44f5-9229-5d35189ba0c8)
![image](https://github.com/Alex313031/thorium/assets/251706/cc9e44ff-2d53-40d7-9aaf-1d79cc87502c)

This seems like a CSS compatibility issue - shouldn't the behavior match what Chromium is doing here?   Thanks!

**Comment by vanboom** [comment]
I was seeing a similar issue in Zammad but found that a spelling check extension was adding some CSS to the main body [contenteditable].  Removing the spell check extension solved the issue.
