### ISSUE TITLE
Dash

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#216]
Hello, Thorium has Experimental MPEG-DASH support, may be this library  can help : 

https://github.com/shaka-project/shaka-player

**Comment by Alex313031** [comment]
@trimechee That it for the server side, for websites to implement. Thorium has HLS and MPEG-DASH enabled by default, but it is up to the site to implement it properly for it to work. YMMV.

**Comment by trimechee** [comment]
@Alex313031 Interesting ! Thank you :)
