### ISSUE TITLE
Running version.sh, update_pgo_profiles.py doesn't exist

### ISSUE THREAD

**Issue by qoijjj** [Alex313031/thorium#218]
**System Details**
 - OS: Ubuntu 22.04
 - Thorium Version: latest main

**Problem**

```
Chromium tree is checked out at tag: 116.0.5845.184

Downloading PGO Profiles for Linux, Windows, and Mac...

python3: can't open file '/var/home/name/thorium/tools/update_pgo_profiles.py': [Errno 2] No such file or directory
```

**Screenshots**

**Additional Notes**
I am following building.md

**Comment by qoijjj** [comment]
tools directory doesn't exist at all

**Comment by gz83** [comment]
I'm not sure whether you pulled the chromium source code correctly, whether you followed the compilation guide, and whether you modified this script? Under normal circumstances, there should not be any error prompts when using this script.

@qoijjj

**Comment by qoijjj** [comment]
closed, user error :)

**Comment by Alex313031** [comment]
@qoijjj Simplest way to compile Thorium would be to `git clone --recursive https://github.com/Alex313031/thorium.git` in $HOME, then follow the Chromium docs to clone depot_tools and the chromium src in $HOME.

Then you should just be able to run `trunk.sh`, `version.sh`, `setup.sh`, then set your `gn args out/thorium` from within the chromium/src dir, then running `build.sh #` from within the thorium dir, where # is the number of jobs, which should equal your CPU threads.

**Comment by qoijjj** [comment]
> @qoijjj Simplest way to compile Thorium would be to `git clone --recursive https://github.com/Alex313031/thorium.git` in $HOME, then follow the Chromium docs to clone depot_tools and the chromium src in $HOME.
> 
> Then you should just be able to run `trunk.sh`, `version.sh`, `setup.sh`, then set your `gn args out/thorium` from within the chromium/src dir, then running `build.sh #` from within the thorium dir, where # is the number of jobs, which should equal your CPU threads.

Thanks! Yeah, that's what I did.

This ticket can remain closed though as it's a duplicate of https://github.com/Alex313031/thorium/issues/219

**Comment by Alex313031** [comment]
@qoijjj Ok
