### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by jestxfot** [Alex313031/thorium#22]
Will the cookie decryption feature ever be added to give the browser full portability?

**Comment by jestxfot** [comment]
The browser does not have a portable version. And I would like to have it in the first place, and secondly, in it did not leave the accounts. @Alex313031

**Comment by Alex313031** [comment]
@jestxfot Each release has a portable .zip with scripts inside, .desktop files for desktop integration, and a readme.txt on usage.

**Comment by Alex313031** [comment]
@jestxfot How's it coming?

**Comment by jestxfot** [comment]
I'm not quite sure how this helps me with the portable version, but I'll try to figure it out. I'll write later @Alex313031

**Comment by jestxfot** [comment]
Yes, I do, but it doesn't help me much in this case anyway. It doesn't move active account sessions @Alex313031

**Comment by Alex313031** [comment]
@jestxfot Make sure you are added to this google group as per this instruction from previous release.

To enable sync on these releases, please add your google account to https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts as per the official documentation at https://www.chromium.org/developers/how-tos/api-keys/#signing-in-to-chromium-is-restricted

**Comment by jestxfot** [comment]
@Alex313031 I found dll to make the chromium portable. No more settings needed

**Comment by Alex313031** [comment]
@jestxfot Interesting, could you share?

**Comment by jestxfot** [comment]
https://github.com/jestxfot/chrome_plus The most important thing is that the file is open-source and you do not need to worry that it can be dangerous (unlike other browsers)

**Comment by jestxfot** [comment]
From which version did you add these flags? @Alex313031

**Comment by gz83** [comment]
> From which version did you add these flags? @Alex313031

The latest portable version has added chrome://flags/#disable-machine-id and chrome://flags/#disable-encryption

**Comment by gz83** [comment]
> > From which version did you add these flags? @Alex313031
> 
> The latest portable version has added chrome://flags/#disable-machine-id and chrome://flags/#disable-encryption

@jestxfot
