### ISSUE TITLE
[Suggestion] Automated security fix releases

### ISSUE THREAD

**Issue by qoijjj** [Alex313031/thorium#221]
**Is your feature request related to a problem? Please describe.**

The releases of thorium are unfortunately lagging behind the backported security fixes into the extended stable channel. I understand the headache involved with keeping up with these, but I'm hoping there's a way to come up with a solution here.

**Describe the solution you'd like, including relevant patches or source**
Currently, I am doing this myself locally by modifying version.sh and generating rpms for myself, but this only helps me and not all users.

**Additional Notes**
As an example, this vivaldi release pulls in a security fix that thorium doesn't have yet https://vivaldi.com/blog/desktop/minor-update-three-6-2/

**Comment by qoijjj** [comment]
@Alex313031 question related to this, do you already have some sort of CI/CD for the deb packaging for that repo? Or are you manually uploading debs.

**Comment by gz83** [comment]
Currently no automated compilation is used, which would make the entire compilation process more uncontrollable and lengthy

@qoijjj
