### ISSUE TITLE
New options : disable BackForwardCache and snapshots

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#224]
Hello, it will be great to add these features and flags to save battery, thank you ! 

https://github.com/uazo/cromite/blob/master/build/patches/00Disable-BackForwardCache.patch

https://github.com/uazo/cromite/blob/master/build/patches/00Add-option-to-disable-snapshots.patch

**Comment by intrnl** [comment]
disabling bfcache saves memory but does not save battery

**Comment by trimechee** [comment]
"Enable showing a page preview during back/forward navigations." preview page doesn' drain battery ? even a small amount of energy ?

**Comment by Alex313031** [comment]
@trimechee @intrnl A primary goal of Thorium is performance and speed, and this includes *perceived* responsiveness as well. Disabling the back/forward cache will not save any battery, only a small amount of RAM. Therefore, I am not going to add it to Thorium. The snapshots patch is only applicable to Android, but I can look into adding it for the Android versions for next release.

**Comment by trimechee** [comment]
Interisting ! Thank you :) 👍
