### ISSUE TITLE
No more captcha

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#226]
Hello, I noticed Google Chrome has added a new parameter in "site permissions" which allows the permanent deletion of captcha, and I frequently use this site which displays a captcha each time in anime which have 700 episodes and it is painful but with this new chrome setting, there is no more captcha on this site, I tried with micorosft edge browser and it's the same thing, the captcha has disappeared on this site, we hope our beloved Thorium browser will find a way to add this revolutionary functionality that eliminates captcha, thank you :)
we also hope there will be no more captchas in Quark Player :)

https://v5.voiranime.com/

**Comment by gz83** [comment]
In which version did you find this change?

@trimechee

**Comment by trimechee** [comment]
@gz83 : for weeks there has been this addition :  chrome://settings/content/autoVerify


Automatic validation
The sites you access can verify that you are a person and not a robot

**Comment by gz83** [comment]
Please give a specific version number. This feature may be added in the new version. After the new Thorium is released, upstream updates will be synchronized.

@trimechee

**Comment by trimechee** [comment]
@gz83 I always try keeping my softwares update, i use last version of chrome Google Chrome 117.0.5938.132 (64-bit) , and last version of microsoft edge

**Comment by gz83** [comment]
Then the next version of Thorium should have this function.

https://github.com/Alex313031/thorium/commit/c0fdd16fa733af2cdd294c57bd7bc8dc578ab218

@trimechee

**Comment by trimechee** [comment]
In sha Allah ! Great , thank you :)

**Comment by NotJuba** [comment]
@trimechee wtf bro you're profile is 100% issues

**Comment by gz83** [comment]
Does version 117 thorium already have the features you want?

@trimechee

**Comment by trimechee** [comment]
Oops sorry, since I read webgl can be dangerous and webassembly:

Is WebGL a security concern?

https://security.stackexchange.com/questions/13799/is-webgl-a-security-concern

and above all I noticed when I install several web browsers based on chromium, there is a folder named chromium common to these browsers C:\Users\Asus\AppData\Local/chromium, and when I install these browsers at the same time time, my settings and preferences are canceled and not saved because browsers based on chromium use the same folder, I avoid installing and using these browsers at the same time, so currently I am exploring other browsers, I I uninstalled Thorium browser and Cromite browser and explored another chromium browser based on ungoogled chroimum.... unfortunately there is no google safe browsing protection and I would very much like to go back to Thorium browser but I am waiting for it 'option to deactivate webassembly and webgl is implemented natively, thank you :)

**Comment by trimechee** [comment]
but in the web browser that I am testing based on ungooled chromium, the option to delete the captcha has been implemented so I suppose this is also the case in Thorium so I close the issue :)
