### ISSUE TITLE
How do I migrate from Edge to Thorium?

### ISSUE THREAD

**Issue by Zero3K** [Alex313031/thorium#227]
*subject*

I tried copying the contents of the User Data directory used by Edge to the USER_DATA directory used by Thorium. After doing that, clicking on Thorium.bat results in the bat running but no UI being shown.

**Comment by Zero3K** [comment]
I figured out how to fix it. It turned out to be a problem with the Secure Preferences file in the Default sub-directory of the User Data directory where Edge keeps its profile. After deleting it, Thorium shows up with my settings mostly intact.

**Comment by gz83** [comment]
The user data of edge may not be completely applicable to Thorium. It is not recommended to directly overwrite the user data of different browsers.

@Zero3K

**Comment by Zero3K** [comment]
It is working fine after doing that.

**Comment by Alex313031** [comment]
@Zero3K @gz83 While it MAY work, I really only reccomend migrating profiles between ungoogled chromium, chromium, chrome, and thorium. Trying to migrate profiles from more heavily modified Chromium forks like Edge or Opera may cause unexpected/undesirable results. However, if it worked for you, thats cool.
