### ISSUE TITLE
which arg for android

### ISSUE THREAD

**Issue by LeOS-GSI** [Alex313031/thorium#228]
You have linux and win args in your repo. which are you using for android ??

I have read the 
/ABOUT_GN_ARGS.md
but it's to global and more explanations for Linux/Win/Mac  (I think)

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/blob/main/arm/android/android_ARM32_args.gn

https://github.com/Alex313031/thorium/blob/main/arm/android/android_ARM64_args.gn

https://github.com/Alex313031/thorium/blob/main/arm/android/android_x64_args.gn

https://github.com/Alex313031/thorium/blob/main/arm/android/android_x86_args.gn

4 of the above

@LeOS-GSI

**Comment by LeOS-GSI** [comment]
Nice, thanks

________________________________
Von: Ho Cheung ***@***.***>
Gesendet: Sonntag, 1. Oktober 2023 17:19
An: Alex313031/thorium ***@***.***>
Cc: harvey186 ***@***.***>; Mention ***@***.***>
Betreff: Re: [Alex313031/thorium] which arg for android (Issue #228)


https://github.com/Alex313031/thorium/blob/main/arm/android/android_ARM32_args.gn

https://github.com/Alex313031/thorium/blob/main/arm/android/android_ARM64_args.gn

https://github.com/Alex313031/thorium/blob/main/arm/android/android_x64_args.gn

https://github.com/Alex313031/thorium/blob/main/arm/android/android_x86_args.gn

4 of the above

@LeOS-GSI<https://github.com/LeOS-GSI>

**Comment by LeOS-GSI** [comment]
Nice, thx
