### ISSUE TITLE
Can you add the ability to close tabs with right click?

### ISSUE THREAD

**Issue by yangchen158158** [Alex313031/thorium#235]
Can you add the ability to close tabs with right click?

**Comment by gz83** [comment]
Thank you for your suggestion, but there are currently many ways to close tabs, including clicking the close button to close, using shortcut keys to close, double-clicking to close, etc. I do not support the introduction of other ways to close tabs at this stage.

In addition, if the right-click is introduced to close the tab, it will conflict with the context menu of the tab and this function is not in line with the system and software concepts.

@yangchen158158

**Comment by yangchen158158** [comment]
Can SHIFT+right click open the context menu? Or can you add a function to enable it for those who need it? I have seen many browsers, such as BaiFen Browser, that have this feature, which is very convenient to use.

**Comment by gz83** [comment]
My reasons for opposing this feature have been clearly stated earlier, and the thorium development team couldn't care less about what features other browsers have.

Also, from the image you provided, it looks like that browser introduced the feature you're talking about through the settings page, which would require a lot of modifications to add any new entries to the settings page, which would also add to the development burden.

@yangchen158158
