### ISSUE TITLE
Right click on Reload Button to hard reload not working

### ISSUE THREAD

**Issue by People-11** [Alex313031/thorium#237]
**System Details**
 - OS: Windows 11
 - Thorium Version 117.0.5938.157 AVX2

**Problem**
From Thorium Version 117.0.5938.157 AVX2, the 'Enable new Menu UI when right clicking the Reload button. (Adds 'Normal Reload', 'Hard Reload', and 'Clear Cache and Hard Reload')' feature is not working

**Screenshots**

**Additional Notes**
The problem is fixed 2 days ago, so this issue can be ignored, just wait for the AVX2 version.

**Comment by gz83** [comment]
This feature was not added in previous updates to the repo, and as you can see, it was added back in the commits of the last few days.

The Windows version should not be recompiled at this time.  But there is a workaround, you can use this feature by opening devtools.

@People-11

**Comment by nbooba** [comment]
I need to reload HARD soon thank you/

**Comment by gz83** [comment]
> I need to reload HARD soon thank you/

Temporary solutions have been given previously

@nbooba
