### ISSUE TITLE
Side Bar for productivity

### ISSUE THREAD

**Issue by yukendhiran** [Alex313031/thorium#239]
**Is your feature request related to a problem? Please describe.**
How to mimic Opera Side bar in both thorium and mercury, I tired few extension from chrome store like manganum but it didn't work well for productivity, the side bar that in opera one is perfect, I want to mimic that exact thing particularly in mercury browser ( firefox based ) , This is the only thing that keep me from using mercury or thorium or any other firefox fork

Thanks for your time to read this request;

**Comment by gz83** [comment]
Thank you for your suggestion, but at this stage it is recommended that you try to find out whether there is an extension that can achieve your needs.

@yukendhiran

**Comment by yukendhiran** [comment]
> Thank you for your suggestion, but at this stage it is recommended that you try to find out whether there is an extension that can achieve your needs.
> 
> @yukendhiran

Thank you for the response , I will search , If i found I will post here, but is there any possibility for that in near future?
