### ISSUE TITLE
.desktop file symlink 

### ISSUE THREAD

**Issue by Neucher** [Alex313031/Thorium#24]
ln -s /home/user/Downloads/thorium-browser_102.0.4976.0-1_amd64/thorium-browser.desktop /home/user/.local/share/thorium-browser.desktop and in /usr/share/applications doesn't work for me. Did anyone manage to get it working ?

**Comment by Alex313031** [comment]
The .desktop file is designed for portable mode, and will only work properly without modification from within the thorium dir.
See > https://github.com/Alex313031/Thorium/blob/main/portable/README.linux

You should edit the Exec lines to point to the actual location of thorium including the --user-data-dir part, and you can do the same for the Icon lines to point to the actual location in the thorium dir of 'product_logo_128.png'

I.E. for your case you could edit the Exec line to

Exec=/home/user/Downloads/thorium-browser_102.0.4976.0-1_amd64/chrome --user-data-dir=/home/user/Downloads/thorium-browser_102.0.4976.0-1_amd64/.config/thorium --no-default-browser-check --use-gl=desktop --enable-experimental-web-platform-features --new-canvas-2d-api --show-component-extension-options --autoplay-policy=user-gesture-required --enable-features=VaapiVideoDecoder,PageInfoAboutThisSite,ParallelDownloading %U

And the icon line to 
Icon=/home/user/Downloads/thorium-browser_102.0.4976.0-1_amd64/product_logo_128.png

**Comment by gz83** [comment]
> @Lehner82 The .desktop file is designed for portable mode, and will only work properly without modification from within the thorium dir. See > https://github.com/Alex313031/Thorium/blob/main/portable/README.linux
> 
> You should edit the Exec lines to point to the actual location of thorium including the --user-data-dir part, and you can do the same for the Icon lines to point to the actual location in the thorium dir of 'product_logo_128.png'
> 
> I.E. for your case you could edit the Exec line to
> 
> Exec=/home/user/Downloads/thorium-browser_102.0.4976.0-1_amd64/chrome --user-data-dir=/home/user/Downloads/thorium-browser_102.0.4976.0-1_amd64/.config/thorium --no-default-browser-check --use-gl=desktop --enable-experimental-web-platform-features --new-canvas-2d-api --show-component-extension-options --autoplay-policy=user-gesture-required --enable-features=VaapiVideoDecoder,PageInfoAboutThisSite,ParallelDownloading %U
> 
> And the icon line to Icon=/home/user/Downloads/thorium-browser_102.0.4976.0-1_amd64/product_logo_128.png
> 
> You could also select one of the 16,24,32,48,64,or 256 px 'product_logo* .pngs depending on your screen resolution and/or DPI setting if it looks funky. Using the .deb installs the icons for various sizes and the DE selects it, but when using portably only one size can be used. 128 works for most cases i.e. 1080p screen at normal DPI in most DE's like GNOME, XFCE, KDE, OPENBOX. Also, if you're going to be running it consistently on the system anyway you might consider the .deb. It will only use a couple MB more space, and will allow for full integration with the DE. The portable version is really only for people who wanna run it from a USB drive, or keep the user profile dir not on the system where other people could look at it. In the latter case, you could also install the .deb, but edit the .desktop file in /usr/share/applications to point the --user-data-dir to a USB drive or other drive. NOTE: Setting it to a network drive will cause Thorium to periodically crash. This is a limitation of Chromium. Only Google Chrome can use network drives for the user data dir, and only on windows, and only after configuring a user policy. Really only used for windows domains/enterprise.

Alex, I would like to ask, does version 103 fix the problem of setting search and need to use compatibility mode to open the browser?

**Comment by Alex313031** [comment]
@Lehner82 Did that fix your issue?
And Im actually building it right now, and then I will test.

**Comment by Lehner82** [comment]
> @Lehner82 Did that fix your issue? And Im actually building it right now, and then I will test.

Sadly not I'm using arch linux and I'm trying to make thorium show up in my run launcher dmenu. So far I can only launch it via terminal

**Comment by Alex313031** [comment]
@Lehner82 Did you modify the .desktop file? If you dont want to, I can do it for you, as long as you provide your home folder name i.e. mine is /home/alex/ and where you're going to store thorium i.e. /home/alex/bin

**Comment by Alex313031** [comment]
@Neucher Hows it coming. I can still help with your .desktop file.

**Comment by Neucher** [comment]
I gave up on .desktop files after the app image because available. Thanks
