### ISSUE TITLE
[Feature Request] Post-Link Optimizations (BOLT, Propeller)

### ISSUE THREAD

**Issue by AndreVallestero** [Alex313031/thorium#240]
This is a copy of https://github.com/Alex313031/Mercury/issues/52

I didn't notice any mention of these optimization techniques in the docs. Could we also apply them to squeeze out a few percentage points of performance? From what I've seen, BOLT can improve performance by 3% for binaries already optimized with PGO and LTO.

**Comment by ms178** [comment]
While this is a very interesting topic, I wonder if it is practical at the moment to pursue it downstream. I think it would be up to Google to roll out support for it in upstream builds first. 

Getting a good profile is time-consuming and there would be even more work needed to integrate BOLT support in the build system. For PGO, there is an official PGO-file from Google that Thorium also uses which makes it quite easy to use. I am not aware of such a provided profile for BOLT.

**Comment by gz83** [comment]
BOLT optimization doesn't seem to be available in Chromium's compilation at the moment

@AndreVallestero
