### ISSUE TITLE
Crashes when dragging a tab

### ISSUE THREAD

**Issue by matheorism** [Alex313031/thorium#242]
**System Details**
 - OS: Ubuntu 22.04.3
 - Thorium Version 116.0.5845.169
 - Kernel 6.2.0-34-generic

**Problem**
The thorium browser crashes and will close immediately when I drag a tab and move it to another screen or monitor. It happens in a sporadic manner

**Screenshots**
n/a

**Additional Notes**
I'm using a Dell Precision 5550 / Intel i7-10850H laptop

**Comment by matheorism** [comment]
> **System Details**
> 
> * OS: Ubuntu 22.04.3
> * Thorium Version 116.0.5845.169
> * Kernel 6.2.0-34-generic
> 
> **Problem** The thorium browser crashes and will close immediately when I drag a tab and move it to another screen or monitor. It happens in a sporadic manner
> 
> **Screenshots** n/a
> 
> **Additional Notes** I'm using a Dell Precision 5550 / Intel i7-10850H laptop

Seems like it happens only on Thorium refresh 2023 (new desktop design). I reverted it to default and it works fine now.

**Comment by stefan-matic** [comment]
I experience these issues when the tab scrolling is enabled. Let me know if I can provide some logs to help you debug this.

**Comment by eramax** [comment]
I experience these issue it crashes when dragging a tab

**Comment by gz83** [comment]
Please do not use the tab scrolling function. There have been many reports of this feature causing browser crashes. This issue is also listed in the upstream as a bug to be fixed.

**Comment by matheorism** [comment]
I haven't had any issues with the latest release.
