### ISSUE TITLE
60 fps VP9 HW accelerated Youtube playback consistently dropping frames.

### ISSUE THREAD

**Issue by Pihkal82** [Alex313031/thorium#245]
**System Details**
 - OS:  Manjaro 23.0.4 / Kernel: 6.1.55-1-MANJARO
 - Thorium Version: 117.0.5938.157 (Official Build) stable, built on Linux (64-bit)
 - CPU: Ryzen 5 3600
 - GPU: RX 5700XT

**Problem**
Consistently dropping frames when playing 60 fps  Youtube videos (VP9 codec), couple of frames per second of playback.
Not happening with 30 fps playback.
Not happening when playing the same video on Firefox.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/44177026/c8f18582-f93a-4445-8719-8cd58482c76e)

**Additional Notes**

HW acceleration enabled
VAAPI:
Trying display: wayland
vainfo: VA-API version: 1.20 (libva 2.20.0)
vainfo: Driver version: Mesa Gallium driver 23.1.9-manjaro1.1 for AMD Radeon RX 5700 XT (navi10, LLVM 16.0.6, DRM 3.49, 6.1.55-1-MANJARO)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc

Anything else you need, feel free to ask.
Kudos btw for having VAAPI working OOTB , this is the first Chromium based browser that didn't make me jump through hoops to get VAAPI working.
It's not perfect, hence the frame drops, but it still beats most other Chromium browsers OOTB experience by far!
I'm also really impressed by the performance of your browser, it's amazing compared to Firefox, once again: great job! Thank you!

**Comment by gz83** [comment]
Does Chrome also have this problem?

@Pihkal82

**Comment by Pihkal82** [comment]
Hi,

Since there is no Chrome in the repo's of my distro I tested it on its closest relative, Chromium.

Test video: https://www.youtube.com/watch?v=8KKE-7BzB_M

Results after 30 seconds of playback:

Chromium
![image](https://github.com/Alex313031/thorium/assets/44177026/14a6a534-5752-4dd7-a46c-c65d49e23a57)

Thorium
![image](https://github.com/Alex313031/thorium/assets/44177026/e1941362-4097-4e22-8695-b7ffcecda2d9)

Both of them used HW decoding (VAAPI).
Must admit it wasn't as bad on Thorium as it was yesterday but still more than on Chromium, which only dropped 2 frames during initial loading of the video.

**Comment by yokoffing** [comment]
I can't use hardware acceleration at all on my AMD Ryzen 9 5900X 12-Core Processor. Settings transition slowly and YouTube playback is drops frames and loses connection.

HW off
![hw acel off](https://github.com/Alex313031/thorium/assets/11689349/4d89f735-40b6-4d1a-8aa9-d39c3c6d0b83)

 HW on
![had acel on](https://github.com/Alex313031/thorium/assets/11689349/6c7c2446-6063-49ee-aa3c-c9043bda19e6)

**Comment by 4NXIE7Y** [comment]
> I can't use hardware acceleration at all on my AMD Ryzen 9 5900X 12-Core Processor. Settings transition slowly and YouTube playback is drops frames and loses connection.
> 
> HW off ![hw acel off](https://user-images.githubusercontent.com/11689349/277186221-4d89f735-40b6-4d1a-8aa9-d39c3c6d0b83.png)
> 
> HW on ![had acel on](https://user-images.githubusercontent.com/11689349/277186225-6c7c2446-6063-49ee-aa3c-c9043bda19e6.png)
> 
> I have a beefy gaming machine, so turning HW acceleration off isn't the end of the world, but it shouldn't happen.

Can confirm even I face stutters in my Legion Laptop with an AMD Ryzen 7 6800H. Turning off hardware acceleration fixes the dropped frames on YouTube..
