### ISSUE TITLE
Reopen closed tab in the tab context menu

### ISSUE THREAD

**Issue by S0ulDrag0n** [Alex313031/thorium#246]
I like to reopen closed tabs by right-clicking the current tab I am on. It's a bit more convenient as opposed to moving my cursor to an empty space on the title bar, which is heavily populated already. Also, I am on an ultrawide which makes it a further distance.

It would be great if the `Reopen closed tab` option was available when opening the context menu (right-clicking) on a tab and title bar.

**Comment by gz83** [comment]
Thanks for the suggestion.

@S0ulDrag0n

**Comment by windroidtech2** [comment]
@S0ulDrag0n all you have to do is right click on either the + or blank tab and select Reopen Closed Tab. Hope this helps!
