### ISSUE TITLE
Thorium takes forever to load chrome web store.

### ISSUE THREAD

**Issue by CrabbyDisk** [Alex313031/thorium#247]
- OS: Garuda linux
 - Thorium Version 117.0.5938.157

When visiting the chrome web store, it can take up to a minute for it to load. White screen when loading

**Comment by gz83** [comment]
Local testing does not reproduce the problem you are experiencing, please consider whether it is a network issue

@CrabbyDisk

**Comment by CrabbyDisk** [comment]
It shouldn't be a networking issue, opening it in firefox and brave is fine.

**Comment by gz83** [comment]
Local testing cannot reproduce the problem you are encountering.  Also, have you installed the extension on Thorium?

@CrabbyDisk

**Comment by CrabbyDisk** [comment]
Which extension?

**Comment by gz83** [comment]
I mean, do you have any extensions installed on Thorium? Or you can take a screenshot of the chrome://extensions page and upload it here, and I will help you troubleshoot the problem.

@CrabbyDisk

**Comment by CrabbyDisk** [comment]
I have some
![image](https://github.com/Alex313031/thorium/assets/69647964/1da7878c-d055-47f3-a380-59abd489f41b)

**Comment by gz83** [comment]
Disable the extensions that can be disabled one by one, and then check whether the problem you encountered still occurs.

@CrabbyDisk

**Comment by CrabbyDisk** [comment]
Disabling the extensions did not work but the networking tab in developer tools is interesting
![image](https://github.com/Alex313031/thorium/assets/69647964/ae94c5eb-1c72-481f-a69d-82d35340920c)

**Comment by gz83** [comment]
You should check the specific information of the web resource where the error occurred

**Comment by CrabbyDisk** [comment]
Sorry for the trouble, the problem was because of a local application called Safing Portmaster, but, it is weird that this problem only affects thorium.

**Comment by gz83** [comment]
It is recommended that you try to investigate more factors
