### ISSUE TITLE
Crashes after trying to login to google account

### ISSUE THREAD

**Issue by stipemihaljevic** [Alex313031/thorium#249]

**Comment by gz83** [comment]
Are you logging into your Google account through the browser itself or are you logging into your Google account through a web page? Can you describe the problem in more detail?

@stipemihaljevic

**Comment by stipemihaljevic** [comment]
So, i transfered my .config Brave browser data into thorium directory and .cache data from Brave to thorium. After that every website worked, but there were some bugs with passwords saved in browser not transfering over, and google web site worked fine until i tried to login to my account. After confirming 2-FA whole browser froze and just exited without loging into account. Loging in does work when browser doesnt have any configs copied over.
