### ISSUE TITLE
Some suggestions and resquests

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium#25]
Hello, thank you very much for this awesome and wonrderful Browser !

Please I have sommes suggestion request to make Thorium Browser even more wonderful ! it will be goog idea to add a new options not found in other browsers, add a button on the main bar to easily enable the Auto Dark Mode for Web Contents chrome flag and quickly disable it, enable reader mode flag  recently deleted by chromium (may be integrate brave browser reader open source), buffer whole full video media streaming because some users have a slow internet connection and we need the video loads completely to avoid jerks, so it will be amazing to force have option to force buffer whole full HTML5 Audio/Video for Uninterrupted Playback , and include ad blocker dns by default like controld dns, bancuh dns, adguard dns.....

https://github.com/krisnoble/Mediabuffer

https://stackoverflow.com/questions/18251632/another-force-chrome-to-fully-buffer-mp4-video

https://forum.videohelp.com/threads/400542-How-to-force-full-buffer-videos-on-all-platforms

and an option to control the size of the cache and an option to deactivate the disk cache and activate memory ram cache for more speed because some HDDs are worn and old....

and make a version that uses the same version of chromium used by chrome browser in order to have the latest security patches.....

Thank you very much :)

**Comment by Alex313031** [comment]
@trimechee I will work on a dark mode button, I'll look into the reader mode flag, I will look into full buffer streaming.
About having an ad blocker dns, that would be difficult to add and maintain, and everyone has there own idea about what blocklist to use. I will probably not implement that.

And what do you mean the same version?
Thorium is based on tip-of-tree chromium, so the latest. Roughly equivalent to the canary channel of chrome.
Chrome has stable, beta, dev, and canary channels. Chromium doesn't have "channels" but rather you select the release tag/branch in the source tree before building.

**Comment by trimechee** [comment]
@Alex313031  Great !! Thank you very much for your wonderful efforts and kindness to make this excetopnal browser !


The main problem is that chromium and other web browsers do not buffer enough when you have a weak wifi connection and the video is in high resolution HD, so force buffer video can solve this problem for those who do not have a connection weak internet, i found two methods how to force firefox to buffer the full video until the end, but for chromium, i tried several methods, flag.....but i failed, the only solution is to go to the console in devtools and tweak html5 audio video and I found posts on that by searching but I did not understand anything how to do it because it is beyond my skills because I am not a developer and a computer scientist.. ...



the only improvement that improved the loading of the media buffering a little bit on Chromium is when I added these line commands: --disk-cache-size=10 --media-cache-size=10, the media buffering got a little improved but i wish all the video is loaded, so we could watch the videos without internet since the videos are fully loaded....






people say in order to have a smooth streaming playback without jerking on streaming sites, you have to increase the cache to 1Gb minimum, while the current cache is 220mb, and also I noticed that my browser sometimes freezes and I think of limit the dc ache size to 50mb or less for faster browsing so the browser doesn't need to scan a lot of cache anymore when I only regularly use facebook, youtube, twitter....I wish the browser cache only these sites and not other sites or videos to reduce cache size and reduce cache wear avoid disk writes .......






* May be it would  helps, here are my 2 methods I discover for firefox browser alhadoulilAllah to force buffer the full video, .i tested in this streaming site first video link : 


https://wiflix.city/serie-en-streaming/19929-lattaque-des-titans-saison-4.html




set browser.cache.disk.enable, 
browser.cache.disk.smart_size.enabled, 
browser.cache.disk_cache_ssl and browser.cache.offline.enable to false

    activate the entry browser.cache.memory.enable -> true

    set the entry browser.cache.memory.capacity to -1 for automatic adjustment

Reason: Writing down every data to the HDD/SSD is slow & costs lifetime (SSD).
Using DRAM is much faster than fastest M.2 SSDs and saves TBW of SSDs!



Buffer full video or make buffer bigger

There is an easy fix for it just increase media.cache_readhead_limit to 9999 and media.cache_resume_treshold also to 9999. This was also puzzling me since firefox 54 would buffer till the end of the video but firefox 55 wouldn't, so I went trough the about:config and found those two lines once I chagned their values ​​from (60, 30) to those above every single video I opened in firefox so far buffered till the end, you don't even need to restart the firefox just refresh the page for changes to take the effect. Hope this helped.




cache_readahead_limit: 60
cache_resume_threshold: 30
 

to


cache_readahead_limit: 999999
cache_resume_threshold: 999999




Set media.cache_readahead_limit and media.cache_resume_threshold to 99999

Increase the size of media.cache_size

Set media.mediasource.enabled to false so it works on Youtube

**Comment by trimechee** [comment]
@Alex313031 Yes i undersatand, thank you :) 


I just point out that chromium has a "secure dns" section where there is a default list of secure dns like the one from couldflare, google dns, cleanbrowsing, open dsn, this is a good list that block viruses but don't block ads, d 'where my suggestion to add another ad blocker dns for simplicity, because sometimes the dns become heavy or have false posts and block certain legitimate sites so you can change between the different dns with a single click, for example this dns says it blocks crypto currency mining sites and malware, so with these awiesome dns we no longer need to use anti virus which can weigh down the computer, extensions that block ads are good but the dns blocks ads and malware at source i.e. ads are not loaded at all whereas for ad blocker extensions, ads are loaded by the system and blocked by the adblock extension.....

for exemple this rare dns blocks in the source  the ads, the crypto currency minig and manu malware websites.....

Ultimate.Hosts.Blacklist
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/issues/590

and OpenNIC

https://servers.opennic.org/




I mean with the same version of chrome, I meant it will be great to have the same version of chromium and ungoogled chromium made by Marmadruke and Hibbiki 101.0.4951.54 (982481), because I see the enews sites that say google chrome has discovered serious security breaches and it is urgent to update google chrome and google chrome uses the chromium version 101.0.4951.54 and not the chromium version 103.0.5036.0 currently used by our beloved Thorium Browser....

**Comment by Alex313031** [comment]
@trimechee Thorium is always newer than the other releases on woolyss.com. This means Thorium will actually get fixes faster than the others. The Thorium version corresponds with the Chromium version.  And yeah I might look into dns lists.

**Comment by trimechee** [comment]
Awesome fantastic ! Tahnk you very much :) I will try to I will try to install it in sha Allah !

if I understand correctly, version 103.0.5036.0 is as secure as version 101.0.4951.54? and version 103.0.5036.0 has the same security patches as version 101.0.4951.54? I thought the chromium version 103.0.5036.0 is an experimental version or beta alpha version....

in this site, it says that the chrome version is Google Chrome 101.0.4951.54 (64-bit), so this site got it wrong and google chrome uses the chromium version 103.0.5036.0?

**Comment by Alex313031** [comment]
@trimechee No, they are not equivalent. The upstream source tree is always ahead of the stable releases. See here > https://chromiumdash.appspot.com/schedule

So Thorium has *more* patches than chrome, it is just not as stable.

**Comment by trimechee** [comment]
Interesting, thank you for these clarifications :) iforget to post the website : https://www.filehorse.com/download-google-chrome/


another question please, is Thorium Browser based on Ungoogled-Chromium or classic chromium?

**Comment by trimechee** [comment]
In Woolyss site there is 2 version of Thorium Borwser, one with fma and avx2n and an outher version with avx, i dont"t knows with version is better with my notebook Asus i3 X541U year 2017, can my computeur work fine with fma and avx without bugs ? is this version compatible with windows 10 version 21H1?

**Comment by trimechee** [comment]
"includes installer patches and files to include ChromeDriver and content_shell, with a .desktop file being provided for content_shell", can you explain us the usefulness of this option please?


i discover how to download video without using video extension addon, i go to devtools, network/media, but it's it's tiring boring to make several clicks, can you please add a button on the bookmarks bar so  we can enable the devtools quickly and easily find the network/media section ?

**Comment by trimechee** [comment]
Another pelase question, why did Thorium choose to use the chromium project and not firefox? it seems to me that firefox is less strict and more flexible and allows several things prohibited by chrome, for example I can easily deactivate cache disk in firefox and the cache is stored only in the ram for faster navigation if we have an old hard disk HDDs,

you can even disable memory cache....I was able to check it by going to firefox about:cache: Information about the Network Cache Storage Service.....


I was able to figure out how to fully disable the cache on chromium by adding the line command:

--disk-cache-dir=/dev/null


but I don't know if the cache is stored in ram memory or the cache is totally disabled, because I searched and it says that you have to use special software to put the chromium cache in ram memory when using chrome.. ...


that's why we hope that this option will be added to Thorium, because some sites require to cache certain element and we would like to put the cache on the memory and not on the disk ....

**Comment by Alex313031** [comment]
The AVX one makes use of AVX and AES instructions, the AVX2 one uses those as well, but builds on top of that and has AVX2 and FMA instructions. https://en.wikipedia.org/wiki/Advanced_Vector_Extensions & https://en.wikipedia.org/wiki/AES_instruction_set & https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2 & https://en.wikipedia.org/wiki/FMA_instruction_set

Your machine has a 7th gen core i3, so it has all of these and can take advantage of the avx2 version.

Thorium is compatible with all the platforms chromium is. Windows 7/8/8.1/10/11 and Linux 4.4+ and MacOS 10.12+

There is a program called chromedriver used for testing and debugging, the release includes it. There is also another program called content_shell, which loads a minimalist single windows browser. On linux there is a shorcut, but on windows and macos I havent found how to make the installer install the shortcut. So you can run content shell and chromedriver by going to the thorium install dir at C:\Users\$USERNAME\AppData\Local\Thorium\Application You can make shortcuts yourself by right lcicking and selecting create shortcut. There is also an icon in there that you can use to set for the shortcut for content shell, its called thorium-devtools.ico

And about Chromium vs Firefox, they each have their strengths and weaknesses, but developing on Chromium was easier, I had used it for a long time and learned the ins and outs of it, and it is faster and has a better sandboxing mechanism. As far as web standards compliance, they are about equal. As far as development tools, chromium has more. As far as media support, and modifying the browser/extra settings, firefox is better.

I will look into the cache problem you are describing.

I will *not* be looking into changing the devtools UI though, sorry. I'm not experienced enough to go about doing that, but I also dont want to change the UI too much, as Thorium should always be recognizably Chromium in the major UI.

**Comment by trimechee** [comment]
Ohhhh thank you very much for your precious advise et and help and efforts to make these amazing fantastic softwares ! 


plesae another question, I'm afraid to buy a chromebook because apparently I can't install the usual classic software that I know and we are limited by the software present in the chrome store, is that true?

but i hear chromium os has a linux kernel and recently google added support for linux desktop apps, so can all computers made in 2022 run linux distro without issue and bug? on chromeboos, can uninstall chrome os and install ThoriumOS?


about the devtools, I don't need this option anymore since someone on the woolys site gave me a much quicker tip, I just open "chrome://media-internals/", then I go on my favorite streaming site and i play the video and voila, on chrome media internals i can find the url of the video easily and download it alhamdulilAllah, but here is the problem, sr the second video player link on this page, the player dood stream, i can't find the url of the video, i tried to activate el devtool then i play the video but the video shows me "paused in debbuger", so i can't see the network section /media in the devtools, do you know how to solve this problem please? does this video have some sort of scrambling encryption against the devtools and how do you shoot that?


https://wiflix.city/serie-en-streaming/19929-attack-of-the-titans-saison-4.html



other question pease, i found this rare exceptional sound which is the amazing combination of White Noise + Rain which cancels the ambient noise, i tried to download using yt dlp and video extensions like videodownloadhlper but i did not succeed, i did not I only managed to download a little piece of 15 seconds sound.....
can we find in devtools of Thorimu browser a way to download this rare sound please? I just want to download this sound and not the other sounds on the site, this sound is free but I still have to be connected to the internet that's why I want to download it for offline use.... extension video downloadhelper extension but i can only download 15 or 30 seconds.....i tried the excellent media-downloader
 made by Mr Mhogomchungu but i have only 15 seconds downloaded, is there a way to download the full sound via devtools of Thorium browser?
/
thank you very much :)

https://mynoise.net/NoiseMachines/whiteRainNoiseGenerator.php

**Comment by trimechee** [comment]
it will be great if Thorium browser can automatically play media in external media player like qutebrowser, here what i find :"

"qutebrowser is highly [configurable](https://qutebrowser.org/doc/help/configuring.html) and the [Arch Linux Wiki](https://wiki.archlinux.org/index.php/Qutebrowser) has a nice guide.

qutebrowser currently has a limited extensibility, but it does come with a basic support for ad blocking using a DNS styled host file. Ad blocking on YouTube doesn't work, but it is possible to configure qutebrowser to open videos links up in a media player like [mpv](https://mpv.io/) in combination with [youtube-dl](https://youtube-dl.org/), which works extremely well."


https://unixsheikh.com/articles/choose-your-browser-carefully.html#librewolf


https://github.com/woodruffw/ff2mpv

**Comment by Alex313031** [comment]
@trimechee Chromebooks are nice. You can run chrome apps, extensions, and android apps and linux apps in crostini (the name for the built in linux vm). You could also install ChromiumOS or ThoriumOS on it, although only ChromeOS supports android apps.

For both of those sites, they seem to be using EME (Encrypted Media Extensions) probably through the WidevineCDM. This is specifically designed so that you CANT download them. I'm sorry.

And this is possible, but it is not something I can do in Thorium. Rather the developer of qutebrowser needs to make a handler that can register with Chromium to open the URL externally. This is similar to how you can open a zoom url or an itunes url, and it will open it in the native desktop zoom or itunes app on windows.

**Comment by trimechee** [comment]
Interesting, merci bcp pour ces clarifications et explications :) other question plesa sans voulir t'ennuyer, can Thorium browser can be based on fushia and dahlia which is open source "dahliaOS is a modern, secure, lightweight and responsive operating system, combining the best of GNU/Linux and Fuchsia OS" ?

**Comment by trimechee** [comment]
Mr @jacob755 posted these valuable and awesome tips about memory cache !

https://github.com/Eloston/ungoogled-chromium/issues/1940#issuecomment-1121236111

**Comment by Alex313031** [comment]
@trimechee See new thorium website and debian repo > https://thorium.rocks/

**Comment by trimechee** [comment]
Excellent ! It's very good to rename chromium;exe to thoirium.exe because I installed chromium from justclueless, hibbiki, mamaduke, and when I install them together, I lose my references and I hope that renaming chromium.exe to thoirium.exe will allow solve this problem ! thank you very much for all your efforts to improve the web browser!

**Comment by trimechee** [comment]
Hello, about my request to play video with external palyer, i finally have found many scripts and tools : 


open with
https://github.com/akiirui/userscript/tree/play-with-mpv
https://greasyfork.org/en/scripts/416271-play-with-mpv
https://github.com/akiirui/mpv-handler
https://github.com/raingart/youtube-to-smplayer
https://github.com/nsinister/videothumb2mpv
https://github.com/nsinister/mpv-url-handler
https://sourceforge.net/projects/mpv-player-windows/files/
https://sourceforge.net/projects/mpv-player-windows/
https://github.com/yt-dlp/yt-dlp/blob/master/README.md#format-selection
https://github.com/yt-dlp/yt-dlp/blob/master/README.md#sorting-formats
https://openuserjs.org/scripts/nsinister/Click_on_video_thumbnail_to_play_in_MPV
https://akii.work/
