### ISSUE TITLE
[Feature Request] Option for auto hiding the toolbox when not hovering over it

### ISSUE THREAD

**Issue by KA4I** [Alex313031/thorium#251]
As the title says I love this feature of the Firefox CSS hacks which auto hides your toolbox if you are not hovering over it, I have attached at the bottom the specific CSS which does it. 

The only Chromium based browser and honestly the only other browser to my knowledge that has this feature is Yandex browser when you are in fullscreen mode. I know that Yandex uses their own custom shell and that such feature could be a big ask requiring a lot of code change, but I'm leaving it as an idea.

Here is a video of how the feature looks in the Yandex Browser:
https://github.com/Alex313031/thorium/assets/68722028/c48f7853-ae1c-4789-b63c-686beb90ba2f

**Additional Notes**
The CSS file which create the effect in Firefox
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css

**Comment by gz83** [comment]
Thanks for the advice

@KA4I
