### ISSUE TITLE
Thorium contains possible malware/trojan virus?

### ISSUE THREAD

**Issue by rohitsaha29** [Alex313031/thorium#254]
- OS: [Windows 11]
 - Thorium Version [e.g.M117.0.5938.157] AVX2

**Problem**
Windows 11 Windows security has flagged thorium as a threat and instantly removed quarantined it. 
Win32/DefenseEvasion.A!ml - was flagged as a trojan
Win32/Bearfoos.A!ml - was flagged as a trojan

I have been using Thorium for many months now to almost a year and this is pretty concerning to a loyal user. Hoping to get some explanation from the devs as to what this is and what this means. Have done my fair share of research on both of these "trojans" and from what im reading it, it is infact a virus/trojan but I have also read that there are some false positives with other programs in relation. 

![image](https://github.com/Alex313031/thorium/assets/89363390/38cee3c0-a919-4d62-a985-a73aa57a3652)
![image](https://github.com/Alex313031/thorium/assets/89363390/201db52b-cccf-4db2-8c04-1b3b4622788f)

Hoping to get some explaination from the devs because this is a worrying concern. Will be uinstalling for the time being with the threat removed.

**Comment by GuevaraStrings** [comment]
Got the same thing just today, is very concerning, I installed AVX2 version from the mini-installer, since I did not compiled it by myself I'm kinda worry about it, I guess is best to use another browser while this gets resolved.

![Screenshot 2023-10-17 231645](https://github.com/Alex313031/thorium/assets/18198905/7fc25494-bf6d-4804-80c3-cde94b63332e)

![Screenshot 2023-10-17 232407](https://github.com/Alex313031/thorium/assets/18198905/3c0595ee-5c41-4dbf-a5c5-4cda4a7b9f45)

**Comment by gz83** [comment]
The same issue is already reported in Thorium-Win repo or Thorium-AVX2 repo, mark this issue as duplicate

**Comment by Rollo33** [comment]
found 1 threat last week today 3 threats

|Name|Type|Description|ID|Hash|
Gen:Variant.Lazy.509733, file, C:\Program Files\Thorium\Application\chrome_proxy.exe, 0, cf158e44c1eb49bda56ac5d17d499d39
Gen:Variant.Lazy.509733, file, C:\Program Files\Thorium\Application\122.0.6261.132\chrome_pwa_launcher.exe, 0, 8ab84f3beccd6da83c6e4f13eb625378
Gen:Variant.Lazy.510014, file, C:\Program Files\Thorium\Application\122.0.6261.132\notification_helper.exe, 0, 7ae04416d23ad20f5836b1fe0b255c8a
 
?   halp

**Comment by gz83** [comment]
Microsoft has cleared the false positive

`
Analyst comments:

At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
Run "MpCmdRun.exe -SignatureUpdate"
Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
`

@alsdfjldafsjalsfjk
