### ISSUE TITLE
PDF document icon change

### ISSUE THREAD

**Issue by GuevaraStrings** [Alex313031/thorium#255]
Windows 11
Version 117.0.5938.157 (Official Build) (64-bit) AVX2

Hello, I have html and pdf files and I recently changed to Thorium all good, except then in edge PDF documents had their own icon that resembled a document, on Thorium looks like another .html and cannot distinguish between them.

Is there a way for me to change the icon to a more pleasing document-like shaped icon instead of the default Thorium?, I already uninstalled Edge in its totality so I don't want to deal with the install of it anymore, I would like to open pdf's on thorium I just would like the icon to be a document, yet I haven't found a solution to do it on windows.

Thank you so much for your help.

**Comment by gz83** [comment]
This problem seems to be related to Windows' own file association mechanism and icon mechanism

@GuevaraStrings

**Comment by GuevaraStrings** [comment]
Alright
