### ISSUE TITLE
[Feature Request] Randomized Fingerprint

### ISSUE THREAD

**Issue by Insidevk18** [Alex313031/thorium#256]
**Is your feature request related to a problem? Please describe.**

One feature that the "Brave" browser has but Thorium does not is "randomize fingerprinting", please consider adding this feature.

**Describe the solution you'd like, including relevant patches or source**

https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
https://community.brave.com/t/fingerprinting-how-do-we-know-its-actually-working/134536

**Additional Notes**
Website: https://coveryourtracks.eff.org/

BRAVE
![image](https://github.com/Alex313031/thorium/assets/94028610/a6725d8c-15c9-468f-a821-8423f58ee801)

THORIUM
![image](https://github.com/Alex313031/thorium/assets/94028610/27158162-e78d-4cd2-87e7-75ad2ffa4aa4)

You might also consider using browser extensions that perform this function.

**Comment by gz83** [comment]
Marked as a duplicate

https://github.com/Alex313031/thorium/discussions/244
