### ISSUE TITLE
Illegal instruction crash on Debian 12

### ISSUE THREAD

**Issue by sam1946** [Alex313031/thorium#258]
**System Details**
 - OS: Debian 12, KDE desktop
 - Thorium Version: Thorium_Browser_117.0.5938.157_x64

**Problem**
The app does not open using the debian apt repo or using the AppImage.
Opening the desktop app does nothing.
Using AppImage via command line says "Illegal instruction (core dumped)"

**Comment by KRTirtho** [comment]
Same thing is happening on Ubuntu 23.04.

Usually when apps are run on wrong architecture this exception is thrown. Not sure why is this happening. Unless wrong arch binary was package

**Comment by sam1946** [comment]
Thanks. My architecture is amd64.

**Comment by gz83** [comment]
What processor are you using?

@sam1946

**Comment by sam1946** [comment]
Intel(R) Pentium(R) CPU G2030 @ 3.00GHz

It's an older PC, 8 years old. All other browesers (Chrome/FFox/Brave/Vivaldi/Chromium) run fine

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157

Please try this version

@sam1946

**Comment by sam1946** [comment]
Hi, thanks @gz83. That works.

Is there a debian apt repo that has this version in it - so I can stay up to date?

**Comment by midzer** [comment]
Might be linked to https://github.com/Alex313031/thorium/issues/266
