### ISSUE TITLE
[Feature Request] Please add middle-click on taskbar [tabsbar?] to create new tab.

### ISSUE THREAD

**Issue by akhirkhopdikakharchakyahai** [Alex313031/thorium#260]
I understand that I am weird, but I always add new tabs even to go to websites I am still on, and I use the middle mouse button to add/remove tabs. Clicking on the add tab button is really unnecessary and pointlessly precise, I just want to middle click on the space where there are no tabs and get a new tab open.

This is the ONLY reason Firefox is my main browser because no other browser does this.

I have used your browser for about 5-6 hours now, and I really like how snappy it feels. Please add this feature, I would appreciate it more than you might think.

P.S.- Yes I am a pleb with no knowledge of programming, and I got here after watching Chris Titus's video. I even made a github account specifically to say this, because I really like how this browser runs, and I would love to make this my main browser. Thank you!

**Comment by gz83** [comment]
Thanks for the advice.

@akhirkhopdikakharchakyahai

**Comment by akhirkhopdikakharchakyahai** [comment]
Well, this works on Mercury, so I am going to use that for now.
