### ISSUE TITLE
Just need a link for a Linux installer or guide

### ISSUE THREAD

**Issue by savaged** [Alex313031/thorium#261]
Such a brilliant project and was keen to try this out. As a LInux only user I struggled to find a prebuilt installer or installation guide. I am reluctant to do a full build from source, although that seems at first glance to be the only way.

**Comment by ms178** [comment]
The provided deb and rpm files in the Github release section are easily installable on most distributions. There are also PKGBUILDs in the AUR for Arch-based distros that convert these and integrate them into their packaging system.

While a couple of sentences might help newcomers, this is IMHO required basic knowledge when using Linux.

**Comment by savaged** [comment]
Thank you. I would suggest, if you're interested in new comers that the doco is as simple and obvious as possible.
