### ISSUE TITLE
Welcome to Thorium Discussions!

### ISSUE THREAD

**Issue by paulindr** [Alex313031/thorium#262]
Hi.
I installed Thorium and didn't change a thing (just to try it as was).
Searched for an image theme. Found an image that was appropriate.
Tried to download it (standard right click and SAVE IMAGE --- just a harmless jpg.
AVAST immediately reported that "Thorium is trying to change the file or delete it".
What's that about? Never had that before with a browser. Not reassuring!
(I checked --- went to the same address and downloaded the same file with Firefox. No problem. No malicious content.)

Suggestions appreciated.

**Comment by gz83** [comment]
Since you are downloading and saving images through Thorium, isn't it up to Thorium to try to change or delete the files?

If you're not sure, you can do the same with Chrome and see if your antivirus program shows you a similar message.

@paulindr

**Comment by Andythem23** [comment]
How to install crx extensions? It doesn't work in debian linux sid with drag and drop

**Comment by gz83** [comment]
> How to install crx extensions? It doesn't work in debian linux sid with drag and drop

Please open the chrome://extensions page, turn on the developer mode in this page, and then drag the crx file into it

@Andythem23

**Comment by Andythem23** [comment]
I tried that @gz83 , but dragging and dropping just doesn't do anything. 
[Grabación de pantalla desde 2023-10-18 14-46-25.webm](https://github.com/Alex313031/thorium/assets/67170467/178fb7fe-486f-49bd-914d-b780d47e2992)

**Comment by gz83** [comment]
Can Chrome browser install extensions through DND?

@Andythem23 

> I tried that @gz83 , but dragging and dropping just doesn't do anything. [Screen record of the issue](https://github.com/Alex313031/thorium/assets/67170467/178fb7fe-486f-49bd-914d-b780d47e2992)

**Comment by Andythem23** [comment]
No, I just tried it now
