### ISSUE TITLE
windows defender smartscreen protection to be trusted application

### ISSUE THREAD

**Issue by paulolascience63** [Alex313031/thorium#264]
**Is your feature request related to a problem? Please describe.**
When I try to start Thorium on Windows 11 windows defender smartscreen protection pop up and I need to accept installation or starting app by BAT file

**Describe the solution you'd like, including relevant patches or source**
Be recognize as a trusted application

**Comment by gz83** [comment]
Marked as a duplicate

You can see the same or similar issue in the Thorium-Win repo

@paulolascience63
