### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Adithyan007hack** [Alex313031/thorium#266]
**System Details**
 - OS: Zorin os 16.3 (ubuntu 20.04)
 - Thorium Version 116.0.5845.169-1

**Problem**
It just doesn't start

**Additional Notes**
Terminal output : find: ‘/home/adithyan/.config/thorium/Crash Reports/pending/’: No such file or directory
[1]    13716 illegal hardware instruction  thorium-browser

**Comment by Adithyan007hack** [comment]
> What processor are you currently using?
> 
> @Adithyan007hack

Intel , do you want specific model name

**Comment by gz83** [comment]
> > What processor are you currently using?
> > @Adithyan007hack
> 
> Intel , do you want specific model name

Yes, I need a specific model. Different models will have different instruction set support.

@Adithyan007hack

**Comment by Adithyan007hack** [comment]
> > > What processor are you currently using?
> > > @Adithyan007hack
> > 
> > 
> > Intel , do you want specific model name
> 
> Yes, I need a specific model. Different models will have different instruction set support.
> 
> @Adithyan007hack

Intel(R) Celeron(R) N4000

**Comment by gz83** [comment]
Please use this version

https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157

@Adithyan007hack

**Comment by gz83** [comment]
> > Please use this version
> > https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157
> > @Adithyan007hack
> 
> Is there a way to get automatic update with that version like a repo so i dont have to download it again if a new version come out

This request requires assistance from Alex and midzer

@Adithyan007hack @Alex313031 @midzer

**Comment by midzer** [comment]
It's possible to create a new `apt` repo for Linux SSE3 releases.

I maintain the regular AVX Linux version repo.

**Comment by Adithyan007hack** [comment]
> It's possible to create a new `apt` repo for Linux SSE3 releases.
> 
> I maintain the regular AVX Linux version repo.

So as of now, there is no available repo for SSE3 releases? (correct me if I am wrong.)

**Comment by midzer** [comment]
Yes, right now, manual update is required for Linux SSE3.

**Comment by Adithyan007hack** [comment]
> Yes, right now, manual update is required for Linux SSE3.

So I will be using brave for now until  SSE3 get a repo, then i will switch  :)

**Comment by gz83** [comment]
The SSE3 version has already been released

@Adithyan007hack
