### ISSUE TITLE
adding "show autocomplete suggestions in address bar"

### ISSUE THREAD

**Issue by ArabSkills** [Alex313031/thorium#267]
This feature is important to me cause it annoy me when I'm searching and an old search from browsing history come up.
**Additional Notes**
![Screenshot_2](https://github.com/Alex313031/thorium/assets/47276499/de55409b-b6d2-438e-b318-36d6f575ea9d)

**Comment by ndpm13** [comment]
What happened here? I assumed this issue was closed as complete, but I can't find this option anywhere T^T
