### ISSUE TITLE
Default Styles for `:focus`-ed elements 

### ISSUE THREAD

**Issue by ndom91** [Alex313031/thorium#268]
I'm a bit confused as to the intense browser default styling for the `focus`-ed elements. Seems a bit like overkill. The `padding` on the inside and the `border` (i'm assuming that's what that is instead of an `outline` :thinking:) feel way too big for me. Although the `transition`-ed fade is at least nice :blush: 

Is there any way to modify this without recompiling changes to the default stylesheet (i.e. somethign like in the https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css)

See:

![image](https://github.com/Alex313031/thorium/assets/7415984/8009a1f6-0ab9-45f5-86ae-b7883b644a6d)

**Comment by gz83** [comment]
This issue has nothing to do with the browser. If you don't like this style or have ideas for improvement, please give feedback to Github

@ndom91

**Comment by ndom91** [comment]
Ahh sorry I thought it was a Thorium default issue. Just did some more digging and turns out it was an accessibility setting :facepalm: 

Thanks for the quick response, closing!
