### ISSUE TITLE
It simply does not launch

### ISSUE THREAD

**Issue by Gabitoxxic** [Alex313031/thorium#269]
I saw a similar report, but as it was suggested to give specific hardware info, I am pulling a new request. For more info, it is a Ideapad 100-15IBY

**System details**
OS: Arch Linux 2023.10.14
Kernel: 6.5.7-arch1-1 (64-bit)
Graphics: X11 (using the Mesa drivers)

**Hardware**
Processor: Intel Celeron N2840 2.16GHz
Memory: 4G

**Additional notes**
I installed it the same way on a desktop computer (using yay) and it worked just fine. Htop shows that it does not open at all

**Comment by ms178** [comment]
According to https://www.pc-erfahrung.de/fileadmin/php-skripte/cpu_tabelle_info.php?ID=2067, your CPU doesn't support AVX, which is mandatory for the normal Thorium build. There are special Thorium builds for SSE3 and SSE4 machines which you can find under https://github.com/Alex313031/Thorium-SSE3/releases - I suggest you try the most recent SSE3 build.

**Comment by Gabitoxxic** [comment]
This was the solution, thank you very much!
