### ISSUE TITLE
Vaultwarden does not work with Android version

### ISSUE THREAD

**Issue by Tryfos** [Alex313031/thorium#270]
**System Details**
 - OS: Android 12
 - Thorium Android Version

**Problem**
As per title. Vaultwarden prompt for password etc. does not appear in all websites (logins) in Thorium. Same Vaultwarden app works perfectly in the same phone with Chrome Android and Brave Android. I don't know if it's a Thorium or a Vaultwarden thing.
Thanks in advance.

**Comment by gz83** [comment]
Will Vaultwarden work on browsers other than Chrome?

@Tryfos

**Comment by Tryfos** [comment]
@pritkr Where can I find the list of supported browsers for Bitwarden?
@gz83 Bitwarden is working in Brave (Android) for me. It's not working in Thorium (Android) and Opera (Android).
If it's indeed  a Bitwarden thing, we will have to wait a lot, given that Thorium is not well known yet.
