### ISSUE TITLE
Program crashes upon startup

### ISSUE THREAD

**Issue by bheeshmpita** [Alex313031/thorium#271]
**System Details**
 - OS: Linux Mint 21 xfce
 - Thorium Version: 117.0.5938.157_amd64.deb
 
**Problem**
Program crashes upon startup

**Screenshots**
NA

**Additional Notes**
Error code
```
thorium-browser 
[8093:8093:1019/111322.372279:ERROR:policy_logger.cc(154)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
[1019/111322.805291:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1019/111322.806049:ERROR:elf_dynamic_array_reader.h(64)] tag not found
fish: Job 1, 'thorium-browser' terminated by signal SIGILL (Illegal instruction)
```
I tried the appimage version but that too crashes and don't start

**Comment by gz83** [comment]
What processor are you currently using?

@bheeshmpita

**Comment by bheeshmpita** [comment]
> What processor are you currently using?

i3-3110m with igpu

**Comment by TheChosen7** [comment]
Same thing on Kubuntu  23.04 - Celeron 5100
Didn't look up the error code but it crashed on startup

**Comment by Burnedoutgreenery** [comment]
> > What processor are you currently using?
> 
> i3-3110m with igpu

I was having the same problem then came across the M117.0.5938.157 - SSE3 Linux Release
[https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157](url)

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157

try this version

**Comment by bheeshmpita** [comment]
> https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157
> 
> try this version

yes, this one works.
Thanks for the help.
How is it different from the one i used?

**Comment by Burnedoutgreen** [comment]
CPU is too old to work with the non SSE3 version
