### ISSUE TITLE
Weird top bar behavior on KDE plasma

### ISSUE THREAD

**Issue by NightMare-Vortex** [Alex313031/thorium#273]
**System Details**
 - OS: Arch linux
 - Thorium Version: Version 117.0.5938.157 (Official Build) stable, built on Linux (64-bit)
 - KDE Plasma Version: 5.27.8
 - KDE Frameworks Version: 5.110.0
 - Qt Version: 5.15.10
 - Kernel Version: 6.5.3-arch1-1 (64-bit)
 - Graphics Platform: X11

**Problem**
Unlike chromium, the top bar shows up, and all controls are handed over to the desktop managers topbar

**Screenshots**
![Bad Bar](https://github.com/Alex313031/thorium/assets/93774088/5e0829d4-9d16-4282-a606-08df452b4f05)
![Good Bar](https://github.com/Alex313031/thorium/assets/93774088/dcc5b18e-2570-4ade-b7dd-5c74896ee5b0)

**Comment by BekYahia** [comment]
You just need to disable the system title bar in Thorium settings:

`Settings > Appearance > Use system title bar and borders`

@NightMare-Vortex
