### ISSUE TITLE
Installer can't run

### ISSUE THREAD

**Issue by Aramrahgozar** [Alex313031/thorium#274]
Hi
I downloaded bot exe and zip Windows installer, but both couldn't launch.

Windows 11 21H2

**Comment by gz83** [comment]
What processor are you using?

@Aramrahgozar

**Comment by Aramrahgozar** [comment]
G3240

**Comment by gz83** [comment]
please use this version

https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1

@Aramrahgozar
