### ISSUE TITLE
Package header is not signed?

### ISSUE THREAD

**Issue by ElijahHW** [Alex313031/thorium#275]
**System Details**
 - OS: OpenSuse Tumbleweed:latest
 - Thorium Version:latest

**Problem**
Integrity check fails during install. Package header is not signed. Downloaded the .rpm file and ran it through Yast software manager. It gives the following message:
This message can be ignored and it completes the install. But I thought I'd mention this as I didnt see another issue about this.

**Screenshots**
![Screenshot_20231019_103516](https://github.com/Alex313031/thorium/assets/53635291/41f4e434-ffb5-4e68-acd9-8878045411c8)

**Comment by Gabriel-Rocha7** [comment]
Hi, I have the same question about this, I'm installing weasis on opensuse, and I get the following message: 
INVALID:weasis-4.5.1-1.x86_64 (file-33d3550b): Signature verification failed [6-File is unsigned]
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    MD5 digest: OK
    Package header is not signed!
I wanna know what this error means.
