### ISSUE TITLE
Adding New Search Engines

### ISSUE THREAD

**Issue by ralmond** [Alex313031/thorium#276]
**Is your feature request related to a problem? Please describe.**
I'm trying to add the search engine `startpage.com` to be the default in the search bar.  However, the list of search engines is fixed.

**Describe the solution you'd like, including relevant patches or source**
Under settings it would be good to be able to add a new search engine to the list.  Also, `none` would be a useful choice (I often get annoyed when I type a URL into the address bar and get a search result and not the requested page).

**Additional Notes**
There is a Chrome store add-in which sets `startpage.com` as the default in Chromium, but it does not appear to work in Thorium.

**Comment by gz83** [comment]
thanks for your advice

@ralmond
