### ISSUE TITLE
add package to scoop.sh 

### ISSUE THREAD

**Issue by bcookatpcsd** [Alex313031/thorium#277]
scoop is a windows cmd line way to discover/install/manage a large collection of windows programs. 

https://scoop.sh/

https://scoop.sh/#/apps
Found 5284 applications.

(for example)

![image](https://github.com/Alex313031/thorium/assets/55087301/8f5731a0-3964-476d-a65c-3c0c894d7176)

Google link'd me to a Chris Titus video.. scoop install thorium didn't work 

:) 

Thank you for taking the time to read this.

**Comment by gz83** [comment]
thanks for your advice

@bcookatpcsd

**Comment by SViN24** [comment]
in my experience you need to inform scoop instead.

**Comment by louie-github** [comment]
Seems like someone already made pull requests to Scoop for both Thorium-Win and Thorium-AVX2:
https://github.com/ScoopInstaller/Extras/pull/12078
https://github.com/ScoopInstaller/Versions/pull/1438

If you want to use Thorium right now, though, someone already seems to have made a bucket with a Thorium manifest:
https://github.com/epoweripione/scoop-bucket/blob/master/bucket/Thorium.json
