### ISSUE TITLE
Thorium lag/freeze issue

### ISSUE THREAD

**Issue by m2rk1312** [Alex313031/thorium#279]
**System Details**
 - OS: Arch Linux
 - Kernel and Environment: 6.5.7-arch1-1, i3wm
 - Hardware: Intel i5-12500H, Intel Alder Lake-P GT2 [Iris Xe Graphics]
 - Driver: intel-media-driver
 - Thorium Version [117.0.5938.157-1](https://aur.archlinux.org/packages/thorium-browser-bin)

**Problem**
After 1-2 hours of continuous use, the Thorium browser begins to lag significantly. When I try to close or terminate the browser, the entire system freezes, with only the cursor remaining responsive. This requires a manual system restart using the power button.

**Additional Notes**
- The issue appears to primarily occur during video playback on YouTube/Twitch; haven't experienced it while only browsing without any video playback.
- Haven't observed this behaviour in other browsers like Brave. Thorium is the only browser where hardware accelerated decoding works, so that could be the potential issue If I had to guess.

**Comment by dagolinuxoid** [comment]
can confirm such a behavior although sometimes waiting for a while can undone the hanging (info: arch | xfce | intel cpu | nvidia discrete gpu disabled via udev rules )

**Comment by rushin236** [comment]
System Details

- 1. Version	23H2
- 2. OS build	22631.2506

Problem 
Browser is randomly freezing, have to close the browser and start it again, but it again freezes randomly.

**Comment by przemec** [comment]
Unfortunately same issue on Debian 12 with Thorium version [M117.0.5938.157](https://github.com/Alex313031/thorium/releases/tag/M117.0.5938.157). The longer the browser is opened, the longer the freeze (up to the point that it's better to restart whole system than to wait)
