### ISSUE TITLE
Add functionality to open without saving when downloading a file

### ISSUE THREAD

**Issue by StinkyVoet** [Alex313031/thorium#281]
**Is your feature request related to a problem? Please describe.**
I have been using this browser for a few days now and it's a great experience. There is one thing that I'm missing which is when downloading something, there is no option to just open the file like many other browsers (chrome, edge, firefox, etc.) have.

**Describe the solution you'd like, including relevant patches or source**
How this feature usually works in other browsers is that the downloaded file is downloaded to a tmp folder and when the user closes the file/browser (I'm not sure which), it gets deleted.

**Additional Notes**
![image](https://github.com/Alex313031/thorium/assets/44726280/edb13cdb-e965-4ee8-8ffd-72525df6024d)
This is an example of how Edge does this. It prompts the user to either open, save or choose a location. It'd be great to see something like this implemented into Thorium.

I'm also not sure why this browser doesn't have this as Chromium has this feature as far as I know. Was it removed deliberately?

**Comment by gz83** [comment]
Try going to chrome://settings/downloads and opening the options related to storage location to see if it meets your needs.

@StinkyVoet

**Comment by StinkyVoet** [comment]
Thanks, but I have already looked through the settings. In the download settings you can either always download to the downloads folder or choose a location yourself. There is nothing about opening without saving.

@gz83
