### ISSUE TITLE
There always backdoor guys 

### ISSUE THREAD

**Issue by Elexander91** [Alex313031/thorium#283]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like, including relevant patches or source**

**Additional Notes**

**Comment by gz83** [comment]
What are you talking about?

**Comment by Idlefase** [comment]
@gz83 I think he is talking about a virustotal scan of the windows fork of thorium.

Trend micro flagged  chrome.7z as gen.ransomeware magniber.

https://www.trendmicro.com/vinfo/us/security/news/ransomware-spotlight/ransomware-spotlight-magniber

https://www.virustotal.com/gui/file/43a77172254de9d72b7f123d97e85257dadc47275a4dc9c377ed9a767d98d724

also virustotal flags the excecution parent of chrome.7z ( CRX file ) Extensions.zip as a file that creates a Direct input object which has links to a URI like ejemplo.com 

https://www.virustotal.com/gui/url/970a801286bca2bc1392af854d43bec880b4951840adca2bfd7ece2c3d760cd9

**Comment by qoijjj** [comment]
> @gz83 I think he is talking about a virustotal scan of the windows fork of thorium.
> 
> a engine at virustotal flagged chrome.7z as gen.ransomeware magniber.
> 
> https://www.trendmicro.com/vinfo/us/security/news/ransomware-spotlight/ransomware-spotlight-magniber
> 
> https://www.virustotal.com/gui/file/43a77172254de9d72b7f123d97e85257dadc47275a4dc9c377ed9a767d98d724
> 
> also virustotal flags the excecution parent of chrome.7z ( CRX file ) Extensions.zip as a file that creates a Direct input object which has links to a URI like ejemplo.com. which is a parked domain.
> 
> https://www.virustotal.com/gui/url/970a801286bca2bc1392af854d43bec880b4951840adca2bfd7ece2c3d760cd9

This is yet another reason why #221 would be a good idea. An auditable CICD pipeline that anyone can view would ensure that the code in the repo is the code used to build the packages in github releases.
