### ISSUE TITLE
Add ability to change New Tab Site

### ISSUE THREAD

**Issue by SHU-red** [Alex313031/thorium#284]
**Is your feature request related to a problem? Please describe.**
I always want to have the same starting page, no matter if
- Browser is opened
- New Tab is created

Right now it seems, that the only things that can be set is
- Starting page
- Home-Page

**Describe the solution you'd like, including relevant patches or source**
I would like to have the option to use for new Tabs
- Tew Tab Page
- Home Page
- Specific url

**Additional Notes**
Maybe i did oversee some stuff but could not find a possibility to change the new tab page

**Comment by gz83** [comment]
thanks for your advice

**Comment by Fiveshooter** [comment]
Paste below into address bar and click enter. You will find the solution in the advanced settings.

chrome://flags/#custom-ntp
