### ISSUE TITLE
Congratutlations

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#285]
@Alex313031  Congratulations for this video from this well-known YouTuber who praises Thorium browser as the Best browser in the world and calls for you to sponsor you 💯 but I do not agree with the terms he used when he spoke about your interest for windows 7 ! 

The Best Web Browser

https://www.youtube.com/watch?v=naDYUVFs1-8

**Comment by imdigitalashish** [comment]
Well It's true... !

**Comment by trimechee** [comment]
@imdigitalashish  Thank you :)
