### ISSUE TITLE
2FAS Browser extension not working

### ISSUE THREAD

**Issue by Pyro2677** [Alex313031/thorium#287]
**System Details**
 - OS: Windows 11 
 - Thorium Version 117.0.5938.157 

**Problem**
Hi all, I have installed Thorium Browser and when I try to add the 2FAS browser extension it just has 3 dots in the middle of the page (Loading ) and a popup notification  Extension storage is corrupted We will try to fix it for you. Please Wait. This just repeats and never goes away. I have Chrome, Opera and Brave and the extension works perfectly for them.

**Screenshots**
![Screenshot 2023-10-20 203615](https://github.com/Alex313031/thorium/assets/43083936/2448cb2c-5f27-4dc5-9de0-4f71a953d159)

**Additional Notes**
2FAS extension working perfectly on Chrome, Brave, Opera and Edge.

**Comment by gz83** [comment]
It may be that the 2FA extension cannot properly recognize the Thorium browser. Please contact the 2FA extension developer for help.

@Pyro2677

**Comment by dcgsteve** [comment]
Same issue here as well - will jump on to 2FAS Discord and see if anyone else has raised issue

**Comment by Pyro2677** [comment]
> Same issue here as well - will jump on to 2FAS Discord and see if anyone else has raised issue

I went on their discord to ask them but I thought it was a Thorium issue. How did you go with them?

**Comment by dcgsteve** [comment]
Ok, in all honesty a little confused but basically I think it's up to devs on 2FAS now to decide whether or not to support Thorium. A couple of guys did try and get it working but no joy - so I left a post in the #suggestions channel about including Thorium as supported.

Suspect it's not a Thiorum issue as they had the same problem with ungoogled-chromium too

**Comment by mluckau** [comment]
i have the same problem under manjaro in the chromium browser.

**Comment by Skellington** [comment]
The extension developers are aware of the issue, and they've assured us that [it'll be resolved in the upcoming update, version 1.4.6](https://github.com/twofas/2fas-browser-extension/issues/21).
