### ISSUE TITLE
which version i should use as windows 10 user

### ISSUE THREAD

**Issue by iskander93** [Alex313031/thorium#288]
i have 
winows 10 pro
version: 1909
os build: 18363
cpu: i3

**Comment by gz83** [comment]
Please provide specific processor model

**Comment by gz83** [comment]
Please try the following version

https://github.com/Alex313031/Thorium-Win/releases/tag/M117.0.5938.157

If the above version doesn't work, try using the SSE3 version

https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1

**Comment by iskander93** [comment]
the SSE3 version ,work for me thnx

**Comment by iskander93** [comment]
the SSE3 version ,work for me thnx
> https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1
