### ISSUE TITLE
Auto-Update Feature in Thorium Windows

### ISSUE THREAD

**Issue by thistechguy** [Alex313031/thorium#289]
**Is your feature request related to a problem? Please describe.**
It's cumbersome to have to check for updates on the repo when using the Windows build. It also presents possible security issues if the user forgets to check for and install updates to Thorium.

**Describe the solution you'd like, including relevant patches or source**
Having the ability for auto-updates upon launch in Windows and/or by clicking About Thorium similar to how Google Chrome handles update checks/installations.

**In Google Chrome:**
![image](https://github.com/Alex313031/thorium/assets/86990020/ed8564e3-7ba4-4b4b-ba10-d57ae925fb65)

**In Thorium:**
![image](https://github.com/Alex313031/thorium/assets/86990020/74be2a8c-f3f8-4511-9f17-64441c520d94)

**Comment by gz83** [comment]
Thorium itself does not have an automatic update function. Please consider using Thorium-Winupdater. This software can be found in other issues.

**Comment by thistechguy** [comment]
Is there a reason why it does not have an automatic update function? I understand this can be facilitated on Linux through the package managers but this is a major drawback when using it on Windows.

**Comment by gz83** [comment]
This is intentional by Google, and the automatic update feature is not available by default on Chromium.
