### ISSUE TITLE
Passkeys

### ISSUE THREAD

**Issue by arnold-c** [Alex313031/thorium#290]
At present, it doesn't appear that passkeys can be created on Thorium for Google or GitHub accounts (I haven't tried for other accounts, so I can't speak to those). I have managed to create passkeys for both using Edge browser.

I'm not sure if it is possible (I imagine it's not simple), but it would be great if we could create passkeys using Thorium as that's one of the few missing features I notice from an otherwise excellent experience (so thanks for building this)!

Screenshots below (Google, then GitHub).

<img width="953" alt="SCR-20231020-lmlo" src="https://github.com/Alex313031/thorium/assets/24391445/103dd987-ac9b-459d-868d-178f65b780d2">

<img width="469" alt="SCR-20231020-lnpp" src="https://github.com/Alex313031/thorium/assets/24391445/c4268660-8db2-4b16-980d-c9f70af29b16">

**Comment by gz83** [comment]
Thorium can successfully register and set up passkeys on my side, please check if there are any problems with your operation or Internet connection. Also, keep your security key connected to your computer (if you have one).

**Comment by arnold-c** [comment]
Thanks for a quick response. I'm afraid that I am able to create one using Edge, but not Thorium. I created it using Edge minutes after trying with Thorium, so I don't think it's an issue with my internet connection. I do not have a physical security key (e.g., YubiKey), so am using my phone as the authenticator.

This is what I see in the GitHub settings page.

<img width="940" alt="image" src="https://github.com/Alex313031/thorium/assets/24391445/b5e6af14-ef93-43c7-aa07-14d29690b398">

 Is it possible that there are some settings I need to configure in Thorium to allow passkeys?

**Comment by gz83** [comment]
Are you using a 2FA app on your phone for verification?

@arnold-c

**Comment by arnold-c** [comment]
I do have Bitwarden Premium that I use for TOTP 2FA, but the passkeys are being generated on my (Android 14) phone with the Google Password Manager. @gz83

**Comment by gz83** [comment]
Can you talk about your operation process? I will test it on my side according to your operation process (you can hide some sensitive information)

@arnold-c

**Comment by arnold-c** [comment]
Thanks for your quick responses and support @gz83.

Below is the process I use to try and add a passkey to my Google account (I am signed in through Thorium).

In https://myaccount.google.com/security 

<img width="1903" alt="image" src="https://github.com/Alex313031/thorium/assets/24391445/f140930b-db97-4678-a6d7-bd034b6adf42">

<img width="929" alt="image" src="https://github.com/Alex313031/thorium/assets/24391445/7f928a15-bf34-43fb-b404-006a6b1eac6b">

<img width="915" alt="image" src="https://github.com/Alex313031/thorium/assets/24391445/d69406f9-0839-4ca9-9a40-fa730ac2c786">

I actually managed to create and use a passkey with GitHub (it turns out a long time ago, just as passkeys were being rolled out, I had added my phone as a security key, which was interfering with passkey generation) and some other sites, so this only seems to be an issue in Google for me, making me think there's an issue with how I'm doing this (as you suggested).

**Comment by gz83** [comment]
I tested it on my computer and I can successfully register and set the passkey in github and be able to log in to github using the passkey.

But I cannot register and set the passkey in my Google account, whether I use Thorium or my own compiled Chromium for testing.

Based on the above, I think this may be because Google does not allow third-party compiled Chromium browsers to register and set passkeys, and the help information provided by Google also states that Chrome needs to be used to register and set passkeys normally.

@arnold-c

**Comment by arnold-c** [comment]
Thanks for looking into this - that's unfortunate about Google not allowing this. I'll close this as it sounds like there's nothing that can be done for the time being.
