### ISSUE TITLE
There should be a way to import bookmarks form other browsers.

### ISSUE THREAD

**Issue by 1Codealot** [Alex313031/thorium#292]
There should be a way to be able to import bookmarks (maybe other things too) from other browsers, such as FireFox.

Maybe something like an import bookmarks button.

**Comment by gz83** [comment]
Thanks for your suggestion, we are still trying to implement the functionality you mentioned.  At the same time, this feature is also what Google wants to implement.

**Comment by 1Codealot** [comment]
Okay thanks.
