### ISSUE TITLE
Webapp needs to be opened twice for it to be in its own instance

### ISSUE THREAD

**Issue by uinguzero** [Alex313031/thorium#296]
**System Details**
 - OS: Opensuse tumbleweed kde wayland
 - Thorium latest version

**Problem**
I have created a bunch of webapps. , open in new window, and pinned them to the task bar.

Whenever I open one. It opens as thorium and not as the webapp... If I open it a second time it opens as the webapp and then I close the first one. And now it stays open as a webapp. 
If I close that webapp I again need to open it twice again ....

**Screenshots**
Not at my PC atm. Will try to remember to get some screenshots on monday

**Additional Notes**
Love your work, keep it up.

**Comment by gz83** [comment]
Is this also the case with chrome?

@uinguzero
