### ISSUE TITLE
Debian sudo apt update not picking up updates - Ignored

### ISSUE THREAD

**Issue by oluijks** [Alex313031/thorium#298]
I followed the installation instructions on the website:

```
wget https://dl.thorium.rocks/debian/dists/stable/thorium.list
sudo mv thorium.list /etc/apt/sources.list.d/
sudo apt update
sudo apt install thorium-browser
```

But when updating it says 'Ignored', so it's not picking up new releases...

```
╭─ Updating Package List ──────────────────────────────────────────────────────────────────────────╮
│No Change: https://security.debian.org/debian-security bookworm-security InRelease                │
│No Change: https://ftp.debian.org/debian bookworm InRelease                                       │
│No Change: https://download.docker.com/linux/debian bookworm InRelease                            │
│No Change: https://ftp.debian.org/debian bookworm-backports InRelease                             │
│No Change: https://dl.google.com/linux/chrome/deb stable InRelease                                │
│No Change: https://ftp.debian.org/debian bookworm-proposed-updates InRelease                      │
│No Change: https://ftp.debian.org/debian bookworm-updates InRelease                               │
│No Change: https://repo.steampowered.com/steam stable InRelease                                   │
│Ignored:   https://dl.thorium.rocks/debian stable InRelease                                       │
│No Change: https://dl.thorium.rocks/debian stable Release                                         │
│Ignored:   https://dl.thorium.rocks/debian stable Release.gpg                                     │
│Fetched 0 Bytes in 1s (0 bytes/s)                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by midzer** [comment]
Hi @oluijks 

Debian repo has been updated just a couple of minutes ago. Sorry for the delay. Vacation time =]

**Comment by oluijks** [comment]
@midzer Thanks, I got the update (we all need a holiday), however, it still says: Ignored. Is that something on my side, or an apt issue?

**Comment by midzer** [comment]
```
Get:7 https://dl.thorium.rocks/debian stable Release [752 B]
Get:9 https://dl.thorium.rocks/debian stable/main amd64 Packages [1,261 B]
```
Works for me. Try `sudo apt clean cache` and try again.

**Comment by mkleehammer** [comment]
Happening for me also, even after cleaning cache.  Any way to get more specifics of the error?

**Comment by bipindr123** [comment]
same issue on ubuntu 22

**Comment by midzer** [comment]
@oluijks 

> Ignored:   https://dl.thorium.rocks/debian stable InRelease
> Ignored:   https://dl.thorium.rocks/debian stable Release.gpg

Yes, current apt thorium releases are *not* GPG signed, currently we still use `[trusted=yes arch=amd64]` in `thorium.list` source file. If someone knows how to sign our releases those ignore messages might disappear.

When  you've installed Thorium 117.0.5938.157 as of today, you're using latest version.

**Comment by craigccfl** [comment]
👍  Thanks.

**Comment by joshcangit** [comment]
Seems Debian/Ubuntu is expecting a GPG key.
Hopefully the Thorium deb repository gets signed eventually.

**Comment by ringofyre** [comment]
`Err:6 https://dl.thorium.rocks/debian stable InRelease                                                                                                       
  Cannot initiate the connection to dl.thorium.rocks:443 (2a03:4000:5c:3f::1). - connect (101: Network is unreachable) Could not connect to dl.thorium.rocks:443 (202.61.237.11). - connect (111: Connection refused)`

Been happening for a couple of days. 

`dl.thorium.rocks`

404's in a browser - site down?

**Comment by midzer** [comment]
@ringofyre `thorium.list` has been updated to

```
sudo rm -fv /etc/apt/sources.list.d/thorium.list && \
sudo wget --no-hsts -P /etc/apt/sources.list.d/ \
http://dl.thorium.rocks/debian/dists/stable/thorium.list && \
sudo apt update

sudo apt install thorium-browser
```
