### ISSUE TITLE
Right Alt key removes newlines

### ISSUE THREAD

**Issue by GrimPixel** [Alex313031/thorium#300]
**System Details**
 - OS: Manjaro Linux
 - Thorium Version 117.0.5938.157 (Official Build) (64-bit)

**Problem**
After pressing AltGr (right Alt) in a text box, the newline characters are removed.

**Additional Notes**
Same things happened on Chromium.

**Comment by gz83** [comment]
If chromiun also has this problem, it may be intentional by Google, or there may be a bug.

It is recommended that you report this issue again on crbug.

@GrimPixel
