### ISSUE TITLE
Thorium not creating profile on fresh install

### ISSUE THREAD

**Issue by dwlamb** [Alex313031/thorium#301]
I am running Kubuntu 22.04 and trying Thorium for the first time. I downloaded the thorium-browser_117.0.5938.157_amd64.deb package and installed it using `dpkg -i`.

Launching the browser from the menu system resulted in nothing.  Launching `thorium-browser` in a bash command prompt generated:

    find: ‘/home/daniel/.config/thorium/Crash Reports/pending/’: No such file or directory
    Illegal instruction (core dumped)  

Performing `ls -l ~/.config/thorium` yielded no path for thorium was created. I tried creating the profile path with `mkdir -p "/home/daniel/.config/thorium/Crash Reports/pending/"` and tried launching the browser again.  Same  error.

There were no unsatisfied dependencies on the install.

**Comment by gz83** [comment]
Everything works fine in the local test. Please check whether you have sufficient permissions and whether the owner of the relevant directory is correct.

Also, what processor are you currently using?

@dwlamb

**Comment by dwlamb** [comment]
As the sole user of this system, `~/.config` has appropriate permissions.  No other software installation has generated this kind of error of not creating a profile.  The OS has been installed for more than 6 months,

Abridged output of `lscpu` is Intel(R) Xeon(R) CPU   X5677  @ 3.47GHz

**Comment by umsongb** [comment]
I've just finished setting up a new PopOS machine with Thorium today (Oct. 21) and am experiencing identical problem.  I've been using Thorium on other PopOS and Arch machines without a problem so far.  

the New PopOS machine in question is an old Lenovo N22 with Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz

**Comment by Tiger-afk** [comment]
ive just installed thorium browser on my debian install today but i too am experiencing the same problem
i have an Intel(R) Celeron(R) CPU N4000 @1.60GHZ 
thorium installed through dpkg -i

**Comment by IronJaeger** [comment]
I have the same exact issue .

OS: OpenSuse Tumbleweed (rpm file)
Thorium Version : 117.0.5938.157
CPU : Intel Celeron N4120

**Comment by gz83** [comment]
please try to use this version

https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157

**Comment by dwlamb** [comment]
This works. :-)
> please try to use this version
> 
> https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157

**Comment by gz83** [comment]
The replies below this issue may be similar to your problem. We need to wait until they indicate that the problem no longer exists or has been alleviated, and then we will close this issue.

@dwlamb

**Comment by kakayzai** [comment]
Hello, i am using MXLinux and i am facing this problem. i download appimage of thorium change its permission so it can execute but when i try to run it is not executing, then i download and install latest version of thorium .deb package which is
thorium-browser_117.0.5938.157_SSE3.deb 
Thorium is not opening, when i try to run it from terminal it shows 
find: ‘/home/dexter/.config/thorium/Crash Reports/pending/’: No such file or directory
Illegal instruction

**Comment by gz83** [comment]
> Hello, i am using MXLinux and i am facing this problem. i download appimage of thorium change its permission so it can execute but when i try to run it is not executing, then i download and install latest version of thorium .deb package which is thorium-browser_117.0.5938.157_SSE3.deb Thorium is not opening, when i try to run it from terminal it shows find: ‘/home/dexter/.config/thorium/Crash Reports/pending/’: No such file or directory Illegal instruction
> 
> Note : other chormium based browser are working properly

Please use the SSE3 version mentioned in the reply above

@kakayzai
