### ISSUE TITLE
Where is M117.0.5938.157 - 53rd Release in the deb repo?

### ISSUE THREAD

**Issue by greengeckowizard** [Alex313031/thorium#302]
**Add all the stuffz here**
Hello, I'm using the deb repo to install Thorium and I see that there's a new release but version M117.0.5938.157 - 53rd Release is not available. I see that there is an auto updater included but I am still on Version 116.0.5845.169 when I click on the about in the browser. I just really want to stay up to date and having the deb repo updated every time a new release is out would be nice. Thank you very much for making this amazing project!!

**Comment by Alex313031** [comment]
@greengeckowizard It's not? It should be

**Comment by Alex313031** [comment]
@greengeckowizard You're right, it's not. @midzer Can you upload new .deb to repo?

**Comment by midzer** [comment]
Ooops, I forgot to upload before my vacation^^

Should be up now. Thanks for filing @greengeckowizard :)

**Comment by greengeckowizard** [comment]
> Ooops, I forgot to upload before my vacation^^
> 
> Should be up now. Thanks for filing @greengeckowizard :)

Thanks much!
