### ISSUE TITLE
Windowed Fullscreen

### ISSUE THREAD

**Issue by schaefsteven** [Alex313031/thorium#303]
Perhaps this feature is not within the scope of this project, but I'll suggest it and let you decide.

I like to use Thorium with the Vimium extension, which allows you to browse using vim-like keybindings. 
When browsing this way, the url and tab bars are redundant, as everything contained within them can be done with the keyboard. 

In Firefox, there is a setting called full-screen-api.ignore-widgets, which when set to true allows you to put firefox in fullscreen mode, hiding the nav bar at the top, but Firefox stays within the bounds of its window, so it can be tiled, resized, and moved.

For more details, see this [article](https://ssweb.services/blog/how-to-hide-the-navbar-in-firefox/) I wrote about how to do this in Firefox. 

It would be very nice to have the ability to enable this in Thorium.

**Comment by gz83** [comment]
thanks for your advice
