### ISSUE TITLE
[Feature Request] Option to open bookmarks in background tab with left click.

### ISSUE THREAD

**Issue by parademovie** [Alex313031/thorium#305]
It would be nice to have option to open bookmarks in background tab with left click.

It's actually a left-click instead of ctrl+left-click when opening the bookmarks ( ctrl+left-click feels inconvenient and inefficient), and keep the bookmark folder popup window from disappearing when you open a bookmark from the bookmarks folder, so you can open multiple bookmarks at once, which is very convenient.

This will give users more convenient ways to open bookmarks, and it can be a unique feature of thorium, which is what makes thorium different from other browsers.

I hope this will be accepted and thanks to the developers for the hard work 🙏

**Comment by gz83** [comment]
thanks for your advice
