### ISSUE TITLE
[Feature Request] Allow copying for copy protected pdfs

### ISSUE THREAD

**Issue by camelCaseAlt** [Alex313031/thorium#308]
I always hated that the default chrome pdf viewer wont allow copying text on copy protected pdfs (they are so annoying why do they existtt). I currently use firefox's pdf viewer on chrome from the webstore cause it can bypass the copy protect. But if Thorium can add this natively then it would be really awesome.

**Comment by gz83** [comment]
Adding this feature will bring convenience to some extent, but it may bring the risk of infringement.
