### ISSUE TITLE
Netflix (streaming) does not work

### ISSUE THREAD

**Issue by Blazzycrafter** [Alex313031/thorium#311]
**System Details**
 - OS: win 11
 - Thorium Version : 117.0.5938.157 (Offizieller Build) (64-Bit) 

**Problem**
no streaming for netflix
no widewine error? idk

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/39300111/e8151763-8bc0-40ae-92e3-92d82de85ef8)

**Additional Notes**
https://help.netflix.com/en/node/61874

**Comment by Blazzycrafter** [comment]
tested in icocnito and normal mode

**Comment by gz83** [comment]
please see
https://github.com/Alex313031/Thorium-Win/issues/73#issuecomment-1771990676
