### ISSUE TITLE
1Password unable to connect to desktop application (works with Chrome)

### ISSUE THREAD

**Issue by emiellr** [Alex313031/thorium#316]
**System Details**
 - OS: Windows 11 22H2 (Tiny11)
 - Thorium Version 117.0.5938.157

**Problem**
I have 1Password desktop installed and functional. When I install 1Password browser extension in Thorium, the expected behaviour is that it grabs the login credentials and session from the desktop application to log in. That means you won't have to sign in again and you will be unlocking the browser extension using the desktop application when necessary. When doing the same with the regular Chrome browser, it works as expected. When doing it with Thorium, it will just ask me for credentials, indicating that 1P in thorium is unable to communicate with the desktop application. I suspect that either Thorium is sandboxed or the application being called 'Thorium' is throwing it off.

**Screenshots**
Problem description suffices, no supporting screenshots necessary.

**Additional Notes**
None.

**Comment by gz83** [comment]
please see

#287
