### ISSUE TITLE
How to update Zorin/Ubuntu Thorium? I installed the .deb successfully & restarted, but my browser still shows Version 111.0.5563.111.

### ISSUE THREAD

**Issue by Username23453** [Alex313031/thorium#318]
Please help, thank you.  Also, did the directory file path that Thorium installs in change, compared to the old version i have?

**Comment by gz83** [comment]
Please backup all user data, completely delete the current version, and try installing the new version again

**Comment by gz83** [comment]
Please open chrome://version, which will record the storage location of user data.
