### ISSUE TITLE
Why this "Flag option isn't available in Thorium"?

### ISSUE THREAD

**Issue by RyanOrigens** [Alex313031/thorium#321]
![image](https://github.com/Alex313031/thorium/assets/103891807/78606093-b34d-418f-9a3b-882f6aa4b3bc)

**Comment by gz83** [comment]
Please make sure that the theme you are currently using is officially provided by Google, also are you using the CR23 style?

**Comment by RyanOrigens** [comment]
I'm using GTK Theme, but i was also using it on Ungoogledchromium and it worked fine.

This option is just not showing up on the config...

**Comment by gz83** [comment]
Oh, I partially misunderstood the meaning of your issue.

Thorium currently does not have this experimental flag.

@RyanOrigens

**Comment by RyanOrigens** [comment]
@gz83 

Is it going to be added? the dark mode is burning my eyes.

**Comment by gz83** [comment]
We will explain it in the release log when it is added.

@RyanOrigens

**Comment by devingubler1** [comment]
yeah around here we really love dark mode enabled when it works. not understood why it doesnt actually provide dark mode like chrome does, its like as if its still not enabled even though it says enabled, relaunch, and all that.
