### ISSUE TITLE
Widevine is not installed

### ISSUE THREAD

**Issue by Lukas-drz** [Alex313031/thorium#322]
**System Details**
 - OS: Ubuntu 22.04
 - Thorium Version 117

**Problem**
Widevine DRM/CDM is not installed as mentioned in the README.md.
It's installing I don't know how after some time spending on the browser and reboots.
It's very frustrating and not really suited for my usage because I install the browser many times and need to have DRMs activated each time I boot it up after install, I tried to copy the folder in .config but it do not works every time. Can you provide a solution to this problem ? For example to install it with the installer ?
I'm generally testing DRMs on Spotify.

Thanks

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Win-AVX2/issues/84#issuecomment-1627702006
