### ISSUE TITLE
Start/ execution on macOS 14 not possible

### ISSUE THREAD

**Issue by micalx** [Alex313031/thorium#324]
**System Details**
 - OS: macOS 14.0 
 - Thorium Version 116 (latest build for macOS as of 2023-10-23)

**Problem**
After installation of Thorium the system doesn't start the application because it cannot check it for malicious software. (see screenshot).

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/83414837/475a5280-48e9-4bd4-81cb-8a68e683dcc3)

**Additional Notes**
Tested on Macbook Pro 16" (M2 pro) and Macbook Air (M1)

**Comment by micalx** [comment]
@Alex313031 
sorry, I created the issue here. maybe it would be better to raise the ticket in the other repo?
https://github.com/Alex313031/Thorium-MacOS

Please let me know if I should create the ticket over there.

Best regards
Michael

**Comment by calebchongc** [comment]
https://support.apple.com/en-sg/guide/mac-help/mchleab3a043/mac
follow the steps to solve the problem

**Comment by downlz** [comment]
@micalx Go to System preferences - > Privacy & Security. Scroll to the button there you will find Thorium. You need to give permission from there. It should work
