### ISSUE TITLE
Video error - Udemy

### ISSUE THREAD

**Issue by jmr85** [Alex313031/thorium#329]
**System Details**
 - OS: Windows 10 22H2 x64
 - Thorium Version 117.0.5938.157

**Problem**
Can't play video on Udemy
There was a problem with your system settings. To check your settings, visit our [System Requirements](https://support.udemy.com/hc/en-us/articles/229231047) and [How to Troubleshoot Audio & Video Issues](https://support.udemy.com/hc/en-us/articles/229231227) pages. If the problem continues, contact our support team.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/2564998/56cded85-fc0d-40fb-b3d5-63fa7d067083)

**Comment by gz83** [comment]
please see

https://github.com/Alex313031/Thorium-MacOS/issues/11#
