### ISSUE TITLE
Add arm to Linux repos

### ISSUE THREAD

**Issue by llcool** [Alex313031/thorium#332]
Added to my repo:-
`wget https://dl.thorium.rocks/debian/dists/stable/thorium.list`
`sudo mv thorium.list /etc/apt/sources.list.d/`
`sudo apt update`
`sudo apt install thorium-browser`

Result:-
`Reading package lists... Done`
`Building dependency tree... Done`
`Reading state information... Done`
`Package thorium-browser is not available, but is referred to by another package.`
`This may mean that the package is missing, has been obsoleted, or is only available from another source`

Workaround:-
[thorium-browser_117.0.5938.157_arm64.deb](https://github.com/Alex313031/Thorium-Raspi/releases/download/M117.0.5938.157/thorium-browser_117.0.5938.157_arm64.deb)

My Linux:-
`Linux penguin 6.1.55-06866-g0ae6faaa0d86 #1 SMP PREEMPT Fri Sep 29 19:51:21 PDT 2023 aarch64 GNU/Linux`

**Comment by ezequielramos** [comment]
It doesn't work for my version of linux arm. (I'm using fedora).

I tried to use the raspi version rpm and AppImage, but it also didn't work.

I tried too build it from scratch. But the documentation seems a bit old (the default build steps tells me that it will only work on x86 arch, and the arm build steps tells me that I should use the default build steps when using Linux ARM. lol)

I think it would be nice to have an ARM AppImage package together with the others packages on releases.

Default builder:
![image](https://github.com/Alex313031/thorium/assets/11296869/aac75a05-7aa3-4a79-8031-0727217ed306)

ARM builder:
![image](https://github.com/Alex313031/thorium/assets/11296869/889a4742-6f60-4f5c-bb67-9784b535360f)

My Linux:
`Linux fedora 6.6.3-413.asahi.fc39.aarch64+16k #1 SMP PREEMPT_DYNAMIC Sat Jan 27 17:19:54 UTC 2024 aarch64 GNU/Linux`
