### ISSUE TITLE
[Feature Request] Add undo last closed tab

### ISSUE THREAD

**Issue by dels07** [Alex313031/thorium#336]
**Is your feature request related to a problem? Please describe.**
Add undo recently closed tab in tab right click, several browser already implemented this.

**Comment by andersmmg** [comment]
You can already right click in the tab bar and select "Reopen closed tab." Is this what you were looking for?

**Comment by dels07** [comment]
> You can already right click in the tab bar and select "Reopen closed tab." Is this what you were looking for?

Ah yes, not noticing that since usually the option available via tab right click in other browser, closed. 

Thanks
