### ISSUE TITLE
[Feature Request] Add indicator for suspended tab

### ISSUE THREAD

**Issue by dels07** [Alex313031/thorium#337]
**Is your feature request related to a problem? Please describe.**
Since Thorium have memory saver feature, would be great if suspended inactive tab has some indicator to differentiate with active tab

**Describe the solution you'd like, including relevant patches or source**
Vivaldi & Edge grayed-out favicon and lowered opacity of suspended tab label

**Additional Notes**

**Comment by jcv-** [comment]
I believe this is the setting that you are looking for under chrome://flags:

Enable discarded tab treatment for Memory Saver Mode.
When enabled, discarded tabs will have a modified favicon to indicate that state. – Mac, Windows, Linux, ChromeOS, Fuchsia, Lacros

**Comment by dels07** [comment]
Thanks @jcv- don't know it available in the flags
