### ISSUE TITLE
Add option to keep window after closing last tab

### ISSUE THREAD

**Issue by andersmmg** [Alex313031/thorium#338]
**Is your feature request related to a problem? Please describe.**
I often close the last tab but I don't want to window to close. Firefox supports this, but Chrome still doesn't and it's the main reason I don't use Chrome or forks like Thorium right now.

**Describe the solution you'd like, including relevant patches or source**
An option in settings or a flag to allow the window to stay open when closing the last tab, just opening a new tab instead.

**Additional Notes**
There are a few extensions in the store that kinda do this but they add a pinned tab to accomplish it and it doesn't always work right or even at all at times.

**Comment by Smgit5** [comment]
Yes, I also came here to say this. This feature is available in brave browser, in vivaldi too maybe. It would be great if Thorium also gets this feature.

**Comment by Alex313031** [comment]
@andersmmg @Smgit5 Added! Available in the latest M120 release.
