### ISSUE TITLE
No Audio 

### ISSUE THREAD

**Issue by pakosaan** [Alex313031/thorium#339]
**System Details**
 - OS: Fedora 38
 - Hardware Model : Lenovo IdeaPad 3 15ALC6
 - Kernel Version: Linux 6.5.7-200.fc38.x86_64
 - Thorium Version 117.0.5938.157 

**Problem**
The video is playing but no audio.

**Comment by gz83** [comment]
Check whether your sound card driver is normal and whether the web page or system is set to mute.

**Comment by robotictacos** [comment]
Same issue here.  On Arch btw.  I can play videos with sound with no issues using Edge and Firefox, just not Thorium.  Otherwise the browser works wonderfully.

**Comment by midzer** [comment]
What kind of Audio is inside the video?

**Comment by robotictacos** [comment]
Any audio, any kind.  I'm using YouTube as a baseline because all browsers should handle that.  No, the tab is not muted, nor is the video muted.

**Comment by mwolfinspace** [comment]
I have this bug with HDMI + Speaker + Headphone (multiple outputs available). However, if I disconnect the HDMI and headphone, leaving only the speaker connected, the sound returns.
