### ISSUE TITLE
Stutter when using a second window while a fullscreen video is playing

### ISSUE THREAD

**Issue by StinkyVoet** [Alex313031/thorium#342]
**System Details**
 - OS: Windows 11
 - Thorium Version 117.0.5938.157

**Problem**
I have Youtube playing in fullscreen on my main monitor and a second window open on my second monitor. When using the second window (typing or scrolling as far as I've tested) while the video is playing, both the video and the second window stutter.

**Additional Notes**
When the video is obstructed by another window or not in fullscreen, this doesn't happen. 
Hardware doesn't seem to be under much load either, so it's not my pc dying.

**Comment by Hamza12700** [comment]
Have you tried this on other browsers?

**Comment by StinkyVoet** [comment]
I have. I only have Edge to test it with and this issue doesn't seem to happen there. I'd be happy to try more browsers if you need me to

**Comment by Hamza12700** [comment]
Try it [Chromium](https://www.chromium.org/chromium-projects/), and if it's not happening in **Chromium** then the issue is with **Thorium**.
