### ISSUE TITLE
[Feature Request] Enhancing Thorium PDF Reader with Text Highlighting, Read-Aloud, and More for an Improved User Experience

### ISSUE THREAD

**Issue by anishshobithps** [Alex313031/thorium#343]
**Is your feature request related to a problem? Please describe.**
I mainly rely on digital documents, especially PDFs, for my studies as an engineering student. For me, being able to highlight and color-code crucial content in these documents is a crucial function. Having this option enabled me to separate crucial knowledge from less important during exam preparation, which was quite helpful. While various browsers can read PDFs in a rudimentary way, only Microsoft Edge has the extensive feature set I want, like text highlighting and two-page viewing.

**Describe the solution you'd like, including relevant patches or source**
I would really want to see Thorium, the PDF reader I've been using, incorporate some of the great features found in Microsoft Edge. For me, thorium has shown to be a dependable tool, and I intend to keep using it. Thorium would become much more adaptable and user-friendly by including these features.

**Additional Notes**
N/A

**Comment by QWERTIOX** [comment]
I run into same issue, for now solution is using forks of pdf.js from mozilla like [this](https://chrome.google.com/webstore/detail/pdf-viewer-open-in-pdf-re/ldaohgblglnkmddflcccnfakholmaacl) and [this](https://chrome.google.com/webstore/detail/pdf-viewer/jdlkkmamiaikhfampledjnhhkbeifokk) but they are laggy and unconvinient to use

**Comment by gz83** [comment]
Thanks for the advice.
