### ISSUE TITLE
Hardware Acceleration not working properly

### ISSUE THREAD

**Issue by 4NXIE7Y** [Alex313031/thorium#348]
**System Details**
 - OS: [Windows 11 22H2 Build: 22621.2428]
 - Thorium Version 117.0.5938.157 (Official Build) (64-bit)
 - Device: Legion 5 Pro Gen7
 - CPU: AMD Ryzen 7 6800H
 - GPU: RTX 3070 Mobile

**Problem**
Lots of dropped frames when watching videos on YouTube.
Disabling HW acceleration seems to fix the issue, but that is not a permanent and proper solution to the problem.

**Screenshots**
Both screenshots are after 15-20s of YouTube 4k 60fps playback.
HW acceleration off - Thorium
![image](https://github.com/Alex313031/thorium/assets/98228741/114abf0c-698c-4957-8e77-ce66a6b4bfc9)

HW acceleration on - Thorium
![image](https://github.com/Alex313031/thorium/assets/98228741/fce927c9-2be3-49fd-babc-99af9d40891e)
**Additional Notes**

**Comment by ms178** [comment]
On Linux, with RDNA2 GPU, I also see only software video decoding (FFMPGVideoDecoder) with Thorium 117.*.157 (tested H.264 and also VP9 on Youtube).

**Comment by JND94** [comment]
@ms178 This is an upstream issue for AMD cards
You need either a patched Chromium or a patched Mesa
Compiling Mesa is way easier
https://bbs.archlinux.org/viewtopic.php?pid=2125225#p2125225

**Comment by ms178** [comment]
@JND94 Many thanks, I followed the instructions and could get it to work with a patched Mesa. Decent VAAPI support on Linux is a neverending story with a lot of pain. :)
