### ISSUE TITLE
Choppy scrolling if using Wayland

### ISSUE THREAD

**Issue by Mihuy1** [Alex313031/thorium#351]
**System Details**
 - OS: Kubuntu 23.10 & Debian 12 (KDE)
 - Thorium Version [117.0.5938.157]

**Problem**
When using Thorium via Wayland instead of Xorg (Preferred Ozone platform) on "Auto" or "Wayland", scrolling becomes very laggy (choppy?).

**Additional Notes**
I do recall having this on Vivaldi about 3-4 months ago, but when I was using brave I did not encounter this issue. I am dual booting Debian and Kubuntu and on Debian I first encountered this and decided to also try this on Kubuntu and had it on there also.

**Comment by Hamza12700** [comment]
I don't feel any choppiness when using **Thorium** on Wayland.
Fun fact I'm using [Hyprland](https://hyprland.org/) and still don't feel any choppiness or lag when **Thorium** on Wayland.

Please provide more information about your system because this issue is not related to **Thorium**.

**Comment by Mihuy1** [comment]
Yeah, I was actually running Hyprland a little bit ago (Probably rare to see going from Arch to Debian / *buntu) and there Brave was really well with wayland on even compared to arch with kde for some reason.

**Comment by binboupan** [comment]
Hardware accelleration is disabled on Wayland, check about://gpu
