### ISSUE TITLE
Reload Right Click not working

### ISSUE THREAD

**Issue by thorrrr** [Alex313031/thorium#355]
HI
In the notes it says "Enable new Menu UI when right clicking the Reload button. (Adds 'Normal Reload', 'Hard Reload', and 'Clear Cache and Hard Reload')"
This does not work on my machines Linux or Windows ????

**Comment by gz83** [comment]
When updating version 117, the code modifications involved here were accidentally deleted, and version 118 will have this feature again.

You can now use this feature by opening devtools.

@thorrrr

**Comment by thorrrr** [comment]
> When updating version 117, the code modifications involved here were accidentally deleted, and version 118 will have this feature again.
> 
> You can now use this feature by opening devtools.
> 
> @thorrrr

How do i switch it on in dev tools  ?

**Comment by gz83** [comment]
Open devtools, then right-click the reload icon in the upper left corner, and you can see those functions.

@thorrrr
