### ISSUE TITLE
UI problem (captions in tab bar got cut)

### ISSUE THREAD

**Issue by treblahy** [Alex313031/thorium#358]
It's not really bug, just a UI problem. When Thorium Refresh 2023 theme enabled, the captions in tab bars got cut(can be seen in the image, usually 'g','y','p','q' is really obvious), but this does not happen when Thorium Refresh 2023 theme disabled.

I'm using xmonad tiling manager, so it could be me setting up things wrong though, but it's a problem only happens in one theme, thus I issued a general feedback here.

![Oct28:120553](https://github.com/Alex313031/thorium/assets/88468988/726334ca-1a36-407d-9f30-e5e2bf80a791)
![Oct28:120602](https://github.com/Alex313031/thorium/assets/88468988/e9a97f50-2bd7-435f-960a-ef00b57ffebe)

**Comment by gz83** [comment]
I think this should be an upstream problem, and this problem should be alleviated in subsequent versions.

**Comment by treblahy** [comment]
Get it, thanks for the answer! <3
