### ISSUE TITLE
FR: Web Apps

### ISSUE THREAD

**Issue by tim-gromeyer** [Alex313031/thorium#359]
**Is your feature request related to a problem? Please describe.**
If I add a website as a app and open the app, it simply opens a new tab with the web page, not like in edge where it opens another window which look different than the browser

**Describe the solution you'd like, including relevant patches or source**
Web apps like in MS Edge

**Additional Notes**
Here an image of how it looks with edge when you install and open a web app:
![image](https://github.com/Alex313031/thorium/assets/58736434/f3f6f4dc-ca61-415a-91ca-1f0407096fb2)

Here a video where you can see what it looks like in thorium vs edge:
https://github.com/Alex313031/thorium/assets/58736434/daaebb5b-6815-482f-bd69-725c4209095e

**Comment by gz83** [comment]
You can try installing YouTube's dPWA application in Thorium, which should achieve similar effects.

Also, you should compare it to Chromium, not Edge

**Comment by tim-gromeyer** [comment]
That's what I did... I did it again and it works now (sort of). I don't know why it didn't work the first time. It looks like this now:

![image](https://github.com/Alex313031/thorium/assets/58736434/5b5534e9-54e3-4a3a-a4c6-90963edbb8e2)

Do you know how to fix this? It happend after the updates I did today (over 400, Mesa was also updated)

**Comment by gz83** [comment]
![image](https://github.com/Alex313031/thorium/assets/17492865/c31a51e8-855c-4298-8ce5-6133555679ba)

![image](https://github.com/Alex313031/thorium/assets/17492865/3d76e7d2-44c6-4fae-acbb-c561ab4ce80f)

I tested on Kubuntu 22.04 system and the YouTube dPWA application works fine, please see the screenshot above

It is recommended that you troubleshoot the browser extensions currently installed, and try clearing browser data, uninstalling and reinstalling the browser, etc. to see if the problem you are encountering can be solved.

**Comment by tim-gromeyer** [comment]
I enabled Vulkan and this fixed it. I also tried deleting the mesa shader cache and all the other shader/cache folders in the `~/.config/thorium`
