### ISSUE TITLE
Bitwarden Chrome Extension Can't Connect To Desktop App

### ISSUE THREAD

**Issue by henrychea** [Alex313031/thorium#363]
**System Details**
 - OS: [MacOs 14.0 (23A344)]
 - Thorium Version [Version 116.0.5845.169 (Official Build) (arm64)]

**Problem**
Unable to link Bitwarden extension's fingerprint login.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/40254517/0cae2e34-95b8-429f-a812-f9a026f280ab)

**Additional Notes**
Doesn't seem to be an issue with the Fingerprint authentication when using the built-in chrome password manager to authenticate and view/edit saved passwords.

**Comment by gz83** [comment]
Try adjusting the path to the native messaging hosts in Bitwarden to see if it works.

In addition, there are already multiple identical or similar problem reports in the thorium repo. It is recommended to search before reporting a problem.

**Comment by henrychea** [comment]
Thanks for pointing me in the right direction @gz83 , for anyone else that needs help you can create `~/Library/Application Support/Thorium/NativeMessagingHosts/com.8bit.bitwarden.json` and place this in the file

```json
{
  "name": "com.8bit.bitwarden",
  "description": "Bitwarden desktop <-> browser bridge",
  "path": "/Applications/Bitwarden.app/Contents/MacOS/Bitwarden",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://nngceckbapebfimnlniiiahkandclblb/",
    "chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/",
    "chrome-extension://ccnckbpmaceehanjmeomladnmlffdjgn/"
  ]
}
```

**Comment by chengnan049** [comment]
What about Windows？

**Comment by jhongyu** [comment]
Inspired by @henrychea's comment, I copied `~/Library/Application Support/Chromium/NativeMessagingHosts/com.8bit.bitwarden.json
` to `~/Library/Application Support/Thorium/NativeMessagingHosts/`, and it all works.
Here's the content:
```json
{
  "name": "com.8bit.bitwarden",
  "description": "Bitwarden desktop <-> browser bridge",
  "path": "/Applications/Bitwarden.app/Contents/MacOS/desktop_proxy",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://nngceckbapebfimnlniiiahkandclblb/",
    "chrome-extension://hccnnhgbibccigepcmlgppchkpfdophk/",
    "chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/",
    "chrome-extension://ccnckbpmaceehanjmeomladnmlffdjgn/"
  ]
}
```
