### ISSUE TITLE
pinch to zoom in and zoom out

### ISSUE THREAD

**Issue by kannakalyan05** [Alex313031/thorium#365]
can you please add a pinch to zoom feature
Like that is Brave Browser
I shouldn't magnify the screen 
For example when i use youtube if i found any thin interesting and zoom in using pinch gesture it should zoom on the object behind the cursor

I have been using thorium recently and really miss this feature
Thank you.

**Comment by gz83** [comment]
Try turning on touch ui in chrome://flags to see if it can fully or partially meet your needs?

**Comment by SuperCowProducts** [comment]
> Try turning on touch ui in chrome://flags to see if it can fully or partially meet your needs?

@gz83 I have tried enabling `chrome://flags/#top-chrome-touch-ui` but it has no effect, am I missing something here? (`chrome://flags/#captured-surface-control` doesn't work either)

**Comment by SuperCowProducts** [comment]
> > Try turning on touch ui in chrome://flags to see if it can fully or partially meet your needs?
> 
> [@gz83](https://github.com/gz83) I have tried enabling `chrome://flags/#top-chrome-touch-ui` but it has no effect, am I missing something here? (`chrome://flags/#captured-surface-control` doesn't work either)

Downloading AppImage (not `.rpm`, which appeared to be broken, likely due to (new) missing deps) of [new version](https://github.com/Alex313031/Thorium-Raspi/releases/tag/M144.0.7559.254) worked for me :)
