### ISSUE TITLE
Bugged Google signin loop on mobile

### ISSUE THREAD

**Issue by hanifnau092** [Alex313031/thorium#366]
**System Details**
 - OS: [Android 12 go edition]
 - Thorium Version [e.g.117.0.5938.157]

**Problem**
When You Login to Thorium with Google account On Desktop, It syncs. but if your using android it will crash. And if you try to sign in again, it will tell you this account already exists on your device.

**Screenshots**
Sorry i dont have any screenshots

**Additional Notes**
i am using thorium 32bit build for android I will switch to your browser when this bug gets fixed.

**Comment by gz83** [comment]
This issue has been mentioned repeatedly in multiple repo
