### ISSUE TITLE
Unable to log in in Bitwarden Extension

### ISSUE THREAD

**Issue by LorisTecnology** [Alex313031/thorium#369]
**System Details**
 - OS: Windows 11
 - Thorium Version 117.0.5938.157 (Developer Build c21e4e9edb491c1fa84b08af66d88f3fa45beaa2-refs/branch-heads/5938@{#1553} Windows)

**Problem**

Unable to log in in Bitwarden Extension, throw this error
Cannot read properties of null (reading
'iterations')

**Comment by gz83** [comment]
The issue with this extension has been mentioned several times and this issue is now marked as a duplicate.
