### ISSUE TITLE
Ozone wayland vaapi support

### ISSUE THREAD

**Issue by MarkGhanz** [Alex313031/thorium#37]
This is both a feature request and a question. Is it possible to add a patch to support VAAPI on the pure Wayland backend (ozone-platfrom=wayland)? Also, how to apply custom patches to chromium?
Patch link: https://github.com/OSSystems/meta-browser/blob/master/meta-chromium/recipes-browser/chromium/files/chromium-wayland/0001-ozone-add-va-api-support-to-wayland.patch

**Comment by Alex313031** [comment]
@pierro78 @MarkGhanz @mzinner @midzer @gz83  I added that patch as well as an omnibox patch!! https://github.com/Alex313031/Thorium/commit/08267e6810b4b0c3b17b060378531b0036da4feb and https://github.com/Alex313031/Thorium/commit/9a289261833dca49db59542684f541e02330e9c7

**Comment by StarterX4** [comment]
Doesn't work for me with 106.0.5212.0.
Tried to combine with other flags, like --ignore-gpu-blocklist, but videos are still black. Had to turn VAAPI off with `--disable-features=VaapiVideoDecoder`.
Repacked deb version, CachyOS (Arch-based). Mesa 22.1.4.
