### ISSUE TITLE
Disable PWA and "Ask for password" by default

### ISSUE THREAD

**Issue by skorakora** [Alex313031/thorium#372]
I did not know that something like PWA even exists, until today when thorium asked me to install some app.
It is not annoying, just a simple button. But I did research and many people hate it, so maybe it should be disabled by default...

Another annoying thing, that I have to disable in basically every single browser, is browser asking to save a password.
It maybe nice for computer noobs, but let's say it. This browser is not for average user, and at least for me, browser that pop ups annoying windows all the time is annoying and should be disabled by default. (or even removed, as I don't think anyone would use it here, less code is always better)

**Comment by gz83** [comment]
Thorium Browser currently has no way to close dPWA apps (if I'm not missing anything).

Regarding password saving issues, please go to chrome://password-manager/settings to adjust the settings.
