### ISSUE TITLE
Ungoogled Thorium?

### ISSUE THREAD

**Issue by zx331645** [Alex313031/thorium#373]
**Is your feature request related to a problem? Please describe.**
I've been using Thorium for a few days now, and I'm really annoyed about all the "Google smarts" embedded in the browser. I don't want to be spied on.

**Describe the solution you'd like, including relevant patches or source**
A version of Thorium (mac pls) based on ungoogled-chromium. It's a drop-in replacement for Chromium, so it might be easy? idk?

**Comment by gz83** [comment]
#115
