### ISSUE TITLE
Google maps street view black with a tiny street view box (FIXED)

### ISSUE THREAD

**Issue by NotOriqi** [Alex313031/thorium#375]
![Screenshot 2023-10-30 140746](https://github.com/Alex313031/thorium/assets/149315232/382e1c08-8dfc-44d4-9396-a04bb7bdfc8a)
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]

**Problem**
I was looking at some shop and wanted to see the street view and clicked on the location and went to street view and the screen was black.

**Screenshots**

**Additional Notes**

**Comment by gz83** [comment]
Can you provide more information about the operating system you are currently using, the version of Thorium and the URL where the problem is occurring?

@NotOriqi

**Comment by NotOriqi** [comment]
Im using windows 11 home and using this version of thorium "https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1". I was searching up for shops near me on google as seen in the picture, and i would click one of those locations as seen in the 2nd picture and click on the pictures then street view and in the picture provided in the post it would show up as a black screen
![image](https://github.com/Alex313031/thorium/assets/149315232/4657a1e3-f689-47a2-a43b-85df6884f957)
![image](https://github.com/Alex313031/thorium/assets/149315232/15ef93ae-2343-47f1-8c21-f559f7ee2a8b)

**Comment by gz83** [comment]
I tested it under the Linux version and found that Street View loaded normally, but it took about 5 seconds longer than usual to load a web page (I think this may be related to the network or the size of Street View).

Have you tried incognito mode? Also, have you turned on any experimental flags (can be seen in chrome://flags)?

@NotOriqi

**Comment by NotOriqi** [comment]
Ive tried incognito mode and i havent turned on any experimental flags and its still showing up as a black screen. I loaded the same street view on Edge and it loaded perfectly.

**Comment by NotOriqi** [comment]
it only seems to be happening when you search for a location and click on the locations that google provides and not when you go to google maps directly and find a location.

**Comment by sip-for-telegram-com** [comment]
![image](https://github.com/Alex313031/thorium/assets/112954968/f6306817-55e1-4ba7-adf9-595e41401699)

**Comment by NotOriqi** [comment]
I found the problem hardware acceleration was disabled and when i enabled it then the black screen went away
