### ISSUE TITLE
screen sharing in zoom upside down

### ISSUE THREAD

**Issue by sip-for-telegram-com** [Alex313031/thorium#377]
in regular chrome everything works fine
and in this one the screen demonstration is flipped 180 degrees
you can test this for yourself
How to fix it?

**Comment by gz83** [comment]
Is there a specific test case?

**Comment by sip-for-telegram-com** [comment]
just open zoom web and see

**Comment by sip-for-telegram-com** [comment]
https://www.google.com/maps

here the movement also does not work properly

it's the other way around
