### ISSUE TITLE
Remove Tab Search ▼ button

### ISSUE THREAD

**Issue by benstone326** [Alex313031/thorium#379]
Is there any option to remove the Tab Search button from the top bar?
I tried to find it in the settings and also searched for flags but no result :(

**Comment by gz83** [comment]
I have the impression that Thorium does not have this function for the time being.

**Comment by benstone326** [comment]
Then I suggest this feature :)
It's not super annoying just I like to hide the unused buttons.
![image](https://github.com/Alex313031/thorium/assets/44802165/1db5a909-5821-4bfc-8c87-8e88f2eadc18)

Also need an option to **Remove / Hide Thorium Experience** button <3

**Comment by gz83** [comment]
> Then I suggest this feature :) It's not super annoying just I like to hide the unused buttons. [![image](https://user-images.githubusercontent.com/44802165/279313626-1db5a909-5821-4bfc-8c87-8e88f2eadc18.png)](javascript:void(0))
> 
> Also need an option to **Remove / Hide Thorium Experience** button <3

Thank you for your suggestion, we will consider it but may not necessarily implement this feature.

The Thorium Experience icon can turn off the Chrome labs experimental flag in chrome://flags

@benstone326

**Comment by benstone326** [comment]
@gz83 Thank you, it worked! Have a nice day!

**Comment by People-11** [comment]
I wish this could be hidden too.

**Comment by Alex313031** [comment]
@People-11 @benstone326 @yochananmarqos Sorry people but probably wont add this until next release.

**Comment by People-11** [comment]
@Alex313031 I am very happy that u could consider this, I love to keep everything simple and remove things that I don't need.

**Comment by BigSmoke010** [comment]
still waiting for this

**Comment by Alex313031** [comment]
@People-11 @benstone326 Added to my TODO!
