### ISSUE TITLE
Sync not working : is it a bug ? should I add my google api key ? but how ?

### ISSUE THREAD

**Issue by pierro78** [Alex313031/Thorium#38]
just installed the newest build from https://thorium.rocks repo (I am on debian) but google sync doesn t seem to work ... should I add my google api key ? 

can I maybe ask how ? thanks ! :)

**Comment by Alex313031** [comment]
@pierro78 Make sure you are added to https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts as per https://www.chromium.org/developers/how-tos/api-keys/#signing-in-to-chromium-is-restricted

**Comment by pierro78** [comment]
thank you ! I have added the environment variables to my .bashrc file as told and it's syncing now !
