### ISSUE TITLE
TROJ_GEN.R002V01JA23 named trojan file .

### ISSUE THREAD

**Issue by murattahtacii** [Alex313031/thorium#381]
**System Details**
 - OS: Windows 10 Pro 64bit
 - Thorium Version 117.0.5938.157 

**Problem**
Hi, I did a scan through virustotal, there was no problem in the folder, but when I scanned through the .exe file, I encountered this problem. What is the cause?

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/74314181/9c8bc61a-d5ad-4c23-a3d2-a43ab6d7fdf0)

**Comment by gz83** [comment]
#254

**Comment by murattahtacii** [comment]
I couldn't find the reason where you directed me, I found it in the Thorium-Win repo but there was no explanation.
