### ISSUE TITLE
[Feature Request] Clear browsing data on close

### ISSUE THREAD

**Issue by swanknight** [Alex313031/thorium#382]
**Is your feature request related to a problem? Please describe.**
Similar to Edge, Brave, and Slimjet. Add a "Clear browsing data on close" feature.

**Describe the solution you'd like, including relevant patches or source**
![2023-10-31 14_32_41](https://github.com/Alex313031/thorium/assets/46474713/2174ed31-dfef-4f9a-bdcb-4d5bf225baba)

**Additional Notes**
No, Incognito mode is not the answer. Thanks.

**Comment by gz83** [comment]
thanks for your advice
