### ISSUE TITLE
Resize window in height from top not possible

### ISSUE THREAD

**Issue by mugiwaraya** [Alex313031/thorium#383]
**System Details**
 - OS: Windows 11 22H2
 - Thorium Version 117.0.5938.157 (Official Build) (64-bit)

**Problem**
Resizing the browser window from the top is not possible.

**Comment by gz83** [comment]
Local testing does not have this problem, you should check your usage environment

**Comment by kuriandungu** [comment]
Love this browser. have the same challenge of resizing from top. from the actual corners ( top right and left) its possible but anywhere along the top, nada.

**Comment by pixelpicnic** [comment]
I was able to recreate this issue.
Resizing from the top does not work when Thorium Refresh 2023 redesign is enabled

**Comment by mugiwaraya** [comment]
> I was able to recreate this issue. Resizing from the top does not work when Thorium Refresh 2023 redesign is enabled

It seems kinda hotfixed in the new release, but you gotta be pixel perfect with the mouse to resize it. Better than nothing though!
