### ISSUE TITLE
Linux appimage segfault on Void Linux Musl

### ISSUE THREAD

**Issue by xplshn** [Alex313031/thorium#384]
I'm using Void Linux Musl XFCE4 - Its up-to-date.

**Comment by xplshn** [comment]
```
[anto@beef ThoriumBrowser]$ ./Thorium_Browser_117.0.5938.157_x64.AppImage 
Segmentation fault

```

**Comment by binboupan** [comment]
AppImages are not compatible with musl because they are not statically linked. They depend on system libraries. If you really want to run it on Void Musl, you need to use a chroot for it.

**Comment by xplshn** [comment]
That's not the reason, but, binaries compiled using Musl can be run under Glibc systems, binaries made with Glibc cannot run under most standards compliant C libraries. It'd be great if binaries were compiled like this.
I did check if my system had all dependencies installed, and, it does, I even installed chromium from my package manager and then tried to run the appimage, because the libraries installed by chromium should be shared for Thorium too.

**Comment by binboupan** [comment]
> That's not the reason, but, binaries compiled using Musl can be run under Glibc systems, binaries made with Glibc cannot run under most standards compliant C libraries. It'd be great if binaries were compiled like this. I did check if my system had all dependencies installed, and, it does, I even installed chromium from my package manager and then tried to run the appimage, because the libraries installed by chromium should be shared for Thorium too.

No, again, most binaries compiled on musl are not compatible with glibc, even simplest glibc compiled applications will fail to run on musl. See the musl FAQ https://www.musl-libc.org/faq.html , search for binary compatability. If you want to use Thorium on musl you need to compile it by yourself.

**Comment by xplshn** [comment]
I know it isn't compatible with most GlibC binaries, my suggestion is to use Musl for builds, because GlibC does run Musl compiled binaries but its not the other way around...

**Comment by takusuman** [comment]
Just a loose comment --- there wasn't a "wrapper" for GNU C library-dependent AppImages on musl?
