### ISSUE TITLE
Theming support for Windows 10 (Chromium PR #188)

### ISSUE THREAD

**Issue by teknixstuff** [Alex313031/thorium#385]
**Is your feature request related to a problem? Please describe.**
I'm annoyed by chrome, chromium, and most chromium forks, due to the removal of the `--disable-windows10-custom-titlebar` argument.
This argument allowed DWM (or any third-party theming solution is installed) to draw the titlebar, with whatever theme is being used by the system.

**Describe the solution you'd like, including relevant patches or source**
Merge Chromium PR #188 (logoffon/chromium), or another patch to revert Chromium commit `d6581b4` or in some way restore `--disable-windows10-custom-titlebar`

**Additional Notes**
Not really any more notes to say here currently.

**Comment by gz83** [comment]
thanks for your advice
