### ISSUE TITLE
tab cycling like vivaldi browser

### ISSUE THREAD

**Issue by gg-satish** [Alex313031/thorium#387]
when switching browser tab with shift + tab , can you cycle tab according to recently used order, like in vivaldi or firefox

**Comment by gz83** [comment]
Thank you for your suggestion. It is currently unclear whether the shift+tab shortcut keys will conflict with other components.

**Comment by gg-satish** [comment]
sorry my mistake i meant to say ctrl + tab

**Comment by gz83** [comment]
I can switch tabs using ctrl+tab on thorium
