### ISSUE TITLE
Google Meet camera playback broken

### ISSUE THREAD

**Issue by mangkoran** [Alex313031/thorium#388]
**System Details**
 - OS: Windows 10 IoT Enterprise LTSC 21H2 19044.3570
 - Thorium Version: 117.0.5938.157 (vanilla and AVX2)

**Problem**
Google Meet camera playback from other participants are broken. Not an issue on Google Chrome.

**Screenshots**
Thorium (vanilla and AVX2)
![image](https://github.com/Alex313031/thorium/assets/57625126/4932fd3b-b4fc-4e80-b34a-7eb7ac69659b)

Google Chrome
![image](https://github.com/Alex313031/thorium/assets/57625126/c9b53017-7cd7-474e-84a1-02c85654fc61)

**Additional Notes**
-

**Comment by gz83** [comment]
Have you enabled experimental flags in thorium? Also, is hardware acceleration turned on?

**Comment by mangkoran** [comment]
@gz83 HW acceleration is turned on. YouTube and Twitch are fine. May I know what flags to be exact?

**Comment by gz83** [comment]
You can view the experimental flags you are currently using in the chrome://version page

@mangkoran

**Comment by mangkoran** [comment]
Oh if so, I have no experimental flags enabled.

**Comment by gz83** [comment]
Please send a screenshot of the chrome://version page

@mangkoran

**Comment by mangkoran** [comment]
![image](https://github.com/Alex313031/thorium/assets/57625126/95e553d3-1b32-40bb-b682-375eb39d86fd)

**Comment by gz83** [comment]
I will investigate in my spare time

**Comment by Mazdoor101** [comment]
> I will investigate in my spare time

Did you get around to a fix? New to Thorium and experiencing the same issue. Wanted to troubleshoot before calling it quits.

**Comment by gz83** [comment]
> > I will investigate in my spare time
> 
> Did you get around to a fix? New to Thorium and experiencing the same issue. Wanted to troubleshoot before calling it quits.

Does this problem still exist in version 120?  If the problem still exists, can you provide steps to reproduce the problem?

@Mazdoor101

**Comment by Mazdoor101** [comment]
> > > I will investigate in my spare time
> > 
> > 
> > Did you get around to a fix? New to Thorium and experiencing the same issue. Wanted to troubleshoot before calling it quits.
> 
> Does this problem still exist in version 120? If the problem still exists, can you provide steps to reproduce the problem?
> 
> @Mazdoor101

Version 117.0.5938.157 (Official Build) (64-bit) is what I'm using... how do I get to 120?

To reproduce: Go to your gmail, set up a meeting with anyone, join the meeting, have them turn camera on. Easy.

**Comment by Mazdoor101** [comment]
For Google Meets.

**Comment by gz83** [comment]
> > > > I will investigate in my spare time
> > > 
> > > 
> > > Did you get around to a fix? New to Thorium and experiencing the same issue. Wanted to troubleshoot before calling it quits.
> > 
> > 
> > Does this problem still exist in version 120? If the problem still exists, can you provide steps to reproduce the problem?
> > @Mazdoor101
> 
> Version 117.0.5938.157 (Official Build) (64-bit) is what I'm using... how do I get to 120?
> 
> To reproduce: Go to your gmail, set up a meeting with anyone, join the meeting, have them turn camera on. Easy.

I don't know what system you're using Thorium Browser on, you can find Thorium Browser for different systems and choose the one that suits you under Alex's GitHub account, the latest version is 120 at the moment, with version 121 to be released in the near future.

@Mazdoor101

**Comment by Mazdoor101** [comment]
Are you able to reproduce this on a newer version? I'm using Windows 10.

You can test using two gmail accounts, with a computer and phone. Join the
meeting, turn a video on through your phone, and see how Thorium renders it.

Best Regards,

Waqas Khan

Customer Success Manager, Polymer

***@***.***

polymerhq.io <https://www.polymerhq.io/>
