### ISSUE TITLE
Memory Saver doesn't work

### ISSUE THREAD

**Issue by JadenJSJ** [Alex313031/thorium#389]
**System Details**
 - OS: Manjaro Linux
 - Thorium Version 117.0.5938.157 (Official Build) stable, built on Linux (64-bit) 
 - https://aur.archlinux.org/packages/thorium-browser-bin

**Problem**
Memory saver doesn't work.
Thorium doesn't discard tabs after long period of inactivity
It also doesn't discard them when memory is low

**Additional Notes**
Memory saver works fine in Chrome
I rely on Memory saver working because I open lots of tabs and most of them are left inactive.
My oom (out of memory) killer usually ends up killing a random app or a random thorium process (crashing some tabs)

_Keep up the good work btw, this browser is significantly faster than chrome. (At least in Linux)_

**Comment by gz83** [comment]
What version of Chrome does Memory Saver work properly on?

**Comment by JadenJSJ** [comment]
![2023-11-05_20-26](https://github.com/Alex313031/thorium/assets/44781632/ae45785f-9c8b-4e18-b5c0-c506dd01f9f0)

Actually looks like it worked (basically the first time I spotted it lol)
I think its just just less aggressive on older versions on chromium
or and harder to tell if the tabs have been discarded because they don't have that discarded icon like on Chrome 118
so I didn't really notice them.

I was running Google Chrome Stable 118.0.5993.70 (Official Build) (64-bit)
Will close this issue, would appreciate a 119 build.
Thanks for this good project.
