### ISSUE TITLE
Google Account disconnected

### ISSUE THREAD

**Issue by eddyros** [Alex313031/thorium#390]
**System Details**
 - OS: Windows 10
 - Thorium Version [117.0.5938.157] 64bit

**Problem**
Hi Alex, I installed Thorium yesterday. I got all the configurations and put all I wanna on it. I logged into my Google account (eg Youtube) but when I close thorium tabs and I opened it again, the G account didn't log in. It disconnected. Today I've tried again, making a new profile...same issue. How can I fix it??

**Comment by gz83** [comment]
Try adding the Google account you need to log in to the following groups

https://groups.google.com/u/0/a/chromium.org/g/google-browser-signin-testaccounts

Then try logging in and synchronizing again. The above groups are safe and belong to Google officials.

**Comment by eddyros** [comment]
> Try adding the Google account you need to log in to the following groups
> 
> https://groups.google.com/u/0/a/chromium.org/g/google-browser-signin-testaccounts
> 
> Then try logging in and synchronizing again. The above groups are safe and belong to Google officials.

Hi gz83, I joined the group but the bug continues...any other advice?

**Comment by gz83** [comment]
Where did you install the browser?

@gz83

**Comment by eddyros** [comment]
Here https://thorium.rocks/
clicking on "Windows"

**Comment by eddyros** [comment]
> Where did you install the browser?
> 
> @gz83

Any update or advice gz??

**Comment by gz83** [comment]
> > Where did you install the browser?
> > @gz83
> 
> Any update or advice gz??

I mean which disk did you install Thorium browser to on your computer?

@eddyros

**Comment by eddyros** [comment]
Yes man, on my hard disk! I use Win10

**Comment by gz83** [comment]
Does your computer have partitions (such as C drive, D drive, E drive, etc.)? Or is there just one partition?

I want to make sure you installed the browser in a partition with sufficient permissions.

@eddyros

**Comment by eddyros** [comment]
there's just one drive where i install everything.

**Comment by gz83** [comment]
Uninstall and reinstall the latest version of the browser and see if the problem continues?

**Comment by eddyros** [comment]
Done... continues :(

________________________________

**Comment by eddyros** [comment]
Even if I try logging into circle pic, - near 3 dots settings - the pathway is not correct. @gz83

**Comment by gz83** [comment]
I will try to investigate further in my free time and will get back to you if there is any progress
