### ISSUE TITLE
Cannot cast after disconnecting from VPN

### ISSUE THREAD

**Issue by carere** [Alex313031/thorium#392]
**System Details**
 - OS: EndeavourOS (ArchLinux latest version)
 - Thorium Version 117.0.5938.157

**Problem**
I activated my nordvpn while watching youtube video, then I disconnected from VPN, but now EVEN SO I'm DISCONNECTED from nordvpn, I cannot cast anything from Thorium.
I already launched thorium with `--enable-logging --v=1` in order to inspect the logs located at $HOME/.config/thorium/chrome_debug.log and I don't see anything after clicking on cast icon / menu.
I don't know how to see what happens on Chromium when it cannot detect my ChromeCast...

If anyone has idea how to investigate this, I'll be happy to try it out, but right now I give up...

PS: I can cast from my android phone

**Comment by gz83** [comment]
Do other browsers based on Chromium also have this problem?
