### ISSUE TITLE
cannot unmute on pinned tabs

### ISSUE THREAD

**Issue by gg-satish** [Alex313031/thorium#393]
**System Details**
 - OS: [Windows 11]
 - Thorium Version 117.0.5938.157 (Official Build) (64-bit)

**Problem**
on pinned tab when i mistakenly clicked mute button cause pinned tabs are so small , i cannot unmute it. every time i have unpin tab and unmute it and repin it.

**Comment by gz83** [comment]
You can right-click on the pinned tab you want to mute and click mute site
