### ISSUE TITLE
Adding a CI pipeline to the project

### ISSUE THREAD

**Issue by omagdy7** [Alex313031/thorium#394]
**Is your feature request related to a problem? Please describe.**
I opened the project and I don't see any CI(Continuous Integration) files whether it being Jenkins, circleCI or GitHub actions

**Describe the solution you'd like, including relevant patches or source**
It would be very beneficial to have a CI pipeline to make sure the project is correctly building on all of 3 major OSs (Linux, Windows, MAC). and using GitHub actions is free for open source projects so you might as well use it.

**Additional Notes**
 I can try to contribute a PR, but I just want to make sure that you guys are not using a CI pipeline on Gitlab or something else I am not aware of

**Comment by gz83** [comment]
We currently use the method of building on the local computer. If you are willing to contribute CI-related code, you are welcome to submit one or more PRs related to this.

**Comment by gauranshkumar** [comment]
Hey @gz83 I can work on this but as I checked there are different forks for different versions like Mac, Win, Rasp, etc. So, is it better to merge the build process to a single repo? 

Also, due to geographical server locations, the current repo for Debian https://dl.thorium.rocks/ is very slow. So I guess it would be better to have mirrors of our repo at several different geographical locations.

**Comment by omagdy7** [comment]
I would just like to point out that the fact that at least 75GB is required to build won't be feasible with free tier Github actions so put that in mind the best we could do is set up some kind of local runner with enough space

**Comment by gz83** [comment]
> Hey @gz83 I can work on this but as I checked there are different forks for different versions like Mac, Win, Rasp, etc. So, is it better to merge the build process to a single repo?
> 
> Also, due to geographical server locations, the current repo for Debian https://dl.thorium.rocks/ is very slow. So I guess it would be better to have mirrors of our repo at several different geographical locations.

I think your idea about CI is very good. You can try to merge different platforms and versions of CI into one repo, but currently we need to have ready-made instances for various tests (including code pulling, compilation, release, etc.), and I think the relevant modifications are not trivial, and may take you a long time to make adjustments in various aspects.

As for the apt repository issue, talk to midzer, he has the most context on this.

@gauranshkumar @midzer

**Comment by midzer** [comment]
@gauranshkumar yes, current thorium debian repo is hosted on a rather small VPS in Europe.
I can't reproduce slow download speeds from my location (Germany). Perhaps from another continent things are different. IPv6 should have been enabled, but latency could be an issue.

Right now, I can't set up another mirror in other location due costs, maintainance effort and lack of technical knowledge on how to set up a decentralized apt repo cluster.
