### ISSUE TITLE
New tab with most visited sites (like Firefox)

### ISSUE THREAD

**Issue by ags1234** [Alex313031/thorium#398]
Congratulations on your work on Thorium. I just found out about it and I think it looks like a well-thought out project.
I am testing Thorium coming from decades of Firefox and I miss the perfect New Tab layout and functionality.
Please add configuration options so the users can recreate it in Thorium, specifically:
- the possibility to choose between specific links and most visited sites (already done)
- the number of rows
- the number of columns
- the size and shape of buttons

If you can implement this to simulate Firefox' Net Tab perfectly, I think many users like me will feel at home in Thorium and that would increase the chance of adoption.

**Comment by CryoRenegade** [comment]
Heyo! Kinda of an aside for this, but there are browser plugins that have much the same functionality as firefox's new ran page. However. Alex does have his own Firefox fork in the same thread of reason (compiler optimization flags, patches from other popular forks and more!) that thorium was created with. Check it out at [link](https://github.com/Alex313031/Mercury)

**Comment by ags1234** [comment]
Thanks for the info @CryoRenegade, I didn't know about Alex's Firefox fork, Mercury. I downloaded it and ran JetStream 2 browser test and it scored worse than official Firefox and way worse than Thorium:

115992 - mercury_115.4.0_win64
131866 - Firefox 119.0
181506 - Thorium_AVX2_117.0.5938.157

So maybe a good strategy would be to transfer over to Thorium some good parts of Firefox, like customizable new tab with most visited sites or separate search bar.

**Comment by ags1234** [comment]
@gz83 Thank you, in the new page we now have 8 icons that automatically fill with the most used sites
