### ISSUE TITLE
Linked files in docs missing mac_arm64.md

### ISSUE THREAD

**Issue by n006** [Alex313031/thorium#399]
I would like to support building arm mac versions of thorium.
Unfortunetely I get errors, which might cause of compiling and/or setup issues.

BUILDING_MAC.md says:
Building Chromium for arm Macs requires [additional setup](https://github.com/Alex313031/thorium/blob/main/docs/mac_arm64.md).

Unfortunately this file is missing.

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/issues/362#issuecomment-1792027713
