### ISSUE TITLE
Additional apt dependency

### ISSUE THREAD

**Issue by midzer** [Alex313031/Thorium#4]
Hi Alex,

great project first of all! :+1: 

After installation of release ` .deb` file via `dpkg -i` I wonder why there is an `thorium-browser-unstable.list` file in my `/etc/apt/sources.list.d/` now containing:

> deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main

Currenty, I have Chrome stable from official sources installed. So there is a conflict now. Why Thorium needs this additional apt dependency?

Have a nice week
midzer

**Comment by Alex313031** [comment]
@midzer It doesn't, this is a stupid quirk in the chromium source code. I am going to release a patch soon. It is perfectly safe to delete this.

**Comment by Alex313031** [comment]
@midzer This is now fixed in the latest release. It is the regular release though, so I will make an AVX only again for you. It would be good to sudo apt purge thorium-browser-unstable before installing this next one, to make sure no stale files are left behind.

**Comment by midzer** [comment]
Thanks for your effort, @Alex313031 :+1: 

But you don't **have** to release an AVX only (extra for me) so often. Current release is fine for me :)

Let's keep the project growing and spread the word.

**Comment by Alex313031** [comment]
Well I cant promise any frequency, but when me and my machine arent doing anything intensive (im just watching youtube), I just set the jobs to 7 to leave one core for my use. I just let it compile in the background so its really no big deal and I want everyone that uses thorium to have the latest stuff. If its just a minor version increase I might not make an AVX only build, but this one has upstream patches and has the changes outlined here https://github.com/Alex313031/Thorium/releases/tag/M98.0.4757.0 and I'm not busy so it's no trouble at all. Im building it right now as we speak and will update you here when it's done.

Also, did you read my thing about chromiumos i posted on your other issue?

**Comment by midzer** [comment]
Okay, just do how you like for release. I am plenty of happy already, because chromium is not maintained in debian any more...

For chromium, I've openen an issue there, see https://github.com/Alex313031/ChromiumOS/issues/2

**Comment by Alex313031** [comment]
I KNOW. SO FUCKING SAD. Im seriously considering contacting the www section and chromium maintainers for debian and offer to continue building for them.

**Comment by Alex313031** [comment]
@midzer Also the chromiumos thing is an issue with etcher not chromiumos, I noticed this too. Please use https://github.com/balena-io/etcher/releases/tag/v1.5.122

**Comment by midzer** [comment]
I just tried latest release and this is fixed now. Awesome!

**Comment by Alex313031** [comment]
Wait are you talking about chromiumos or thorium?

**Comment by midzer** [comment]
Thorium, we're in Thorium repo here :)

**Comment by Alex313031** [comment]
@midzer Going to close this now.
