### ISSUE TITLE
On-startup setting not working on Linux

### ISSUE THREAD

**Issue by faxotherapy** [Alex313031/thorium#403]
**System Details**
 - OS: TUXEDO OS
 - Thorium 117.0.5938.157

**Problem**
I set Thorium to open one specific page right on start-up. It only persists showing a dashboard containing little squares of bookmarks. The “open a specific page” under the start-up section does not obviously work.

Thank you

**Comment by gz83** [comment]
It is recommended to uninstall and reinstall the latest version of the browser and then check again to see if the problem continues to occur
