### ISSUE TITLE
[BUG] Intel Xe Graphics (i7 1360p)

### ISSUE THREAD

**Issue by sirxsniper** [Alex313031/thorium#404]
**System Details**
 - OS: Windows 11
 - Thorium Version: 117.0.5938.157 
 - Intel NUC 13 PRO
 - CPU: 1360p
 - Intel Xe Graphics

**Problem**
Use hardware acceleration when available if is checked screen starts to flickering (for some reason on my LG C1 is changing colors/profiles of sounds I tried to deactivate what Intel and LG is saying about [old bug probably] nothing worked. ) If you deactivate it and restart it everything starts to work without it.

**Screenshots**
N/A

**Additional Notes**
Any suggestions to fix it?
Thank you.

OFF: Best browser ever mate, I love it <3

**Comment by gz83** [comment]
Please check whether the graphics card driver is normal and the latest version.

In addition, please provide the URL of the webpage with the flickering problem and the screen recording when the problem occurred. I will try to reproduce the problem after receiving the information you provide.

**Comment by cojo1989** [comment]
You can try it on youtube, you just need to try with hardware acceleration.
Driver Details
Up to date
Provider
Intel Corporation
Version
31.0.101.4952
Date
10/31/2023
Device Details
Adapter Compatibility
Intel Corporation
Video Processor
Intel® Iris® Xe Graphics Family
Resolution
3840 x 2160
Bits Per Pixel
32
Number of Colors
4294967296
Refresh Rate - Current
60 Hz
Refresh Rate - Maximum
120 Hz
Refresh Rate - Minimum
23 Hz
Adapter DAC Type
Internal
Availability
Running at full power
Status
This device is working properly.
Location
PCI bus 0, device 2, function 0
Device Id
PCI\VEN_8086&DEV_A7A0&SUBSYS_30378086&REV_04\3&11583659&0&10

Thank you.

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Win/issues/103#issuecomment-1795802443

https://github.com/Alex313031/Thorium-Win-AVX2/issues/112#issuecomment-1795843646

Please see my test results. No abnormalities were found during the test.

**Comment by cojo1989** [comment]
https://github.com/Alex313031/thorium/assets/36346905/955d20bf-acd1-41b7-b1d3-40671df370c9


https://github.com/Alex313031/thorium/assets/36346905/91f0735e-0e04-4e52-b1c6-38b6aee0b204

Let me know if you need anything else.

**Comment by gz83** [comment]
Thanks for the screen recording video, can you provide the url of youtube that appears in the screen recording video? I'll take the time to test it.

**Comment by cojo1989** [comment]
Does not matter what video, any video you would load on youtube or any website with video will do that if you have hardware acceleration on.
