### ISSUE TITLE
Spotify issue

### ISSUE THREAD

**Issue by mertgoksel** [Alex313031/thorium#405]
**System Details**
 - OS: Windows 11
 - Thorium Version 117.0.5938.157

**Problem**
Open spotify on browser, use "spotify playback speed" extention for chrome, click on any song, says "spotify cannot play this song".

**Additional Notes**
Use chrome instead with same extentions, works fine.

**Comment by sydist** [comment]
This happens to me, except even without the extension

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Win-AVX2/issues/84#issuecomment-1627702006
