### ISSUE TITLE
Closing the browser after several hours of use causes the entire operating system to freeze

### ISSUE THREAD

**Issue by KMatuszak** [Alex313031/thorium#406]
**System Details**
 - OS: Debian 12 6.1.0-13-amd64
 - DE: KDE Plasma 5.27.5 (X11)
 - Thorium: 117.0.5938.157
 - CPU: 11th Gen Intel Core i7-1165G7 (8) @ 4.700GHz
 - RAM: 2x16 GB DDR4 3200 MHz

**Problem**
Closing the entire browser window after several hours of use causes the entire operating system to freeze for a period of several seconds to several minutes, I can only move the mouse cursor. This does not happen if the browser is only open for a few minutes.

**Additional Notes**
This doesn't happen with Chromium & Google Chrome.

**Comment by gz83** [comment]
Unable to reproduce the issue you are experiencing, keep this issue open for more information

**Comment by richard-austin** [comment]
I've had this occur after running fragmented mp4 streams using MSE for a while.  I'm using Ubuntu 23.10 on an HP OMEN laptop with VAAPI  using the Intel GPU. This is not a problem with MS Edge, Chromium and Brave which all use the GPU.
