### ISSUE TITLE
Netflix Issue

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [Alex313031/thorium#407]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]

**Problem**
Netflix on the browser doesn't work and give an error when launching a video.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
(https://i.imgur.com/HGptjzd.jpeg)
it says : sorry for interruption.
This title can't be streamed. Try another one - 1044
Error code M7121-1331

**Additional Notes**
You are doing a good job, very satisfied, gonna fund you.

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Win-AVX2/issues/84#issuecomment-1627702006
