### ISSUE TITLE
Error during build of Thorium

### ISSUE THREAD

**Issue by strangetheproot** [Alex313031/thorium#408]
**System Details**
 - OS: Windows 11
 - Thorium Version [e.g.107.0.5347.0]

**Problem**
Can't build due the setup.bat not working, any solutions?

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/84677793/5c847d8e-9834-4306-b825-ae083de688ef)

**Additional Notes**

**Comment by gz83** [comment]
Do not use the bat files in repo to compile Thorium (those bat files have not been updated for a long time). Currently, most of the Windows versions of Thorium are compiled by me. I manually execute the commands in trunk.sh, version.sh, setup.sh, and build_win.sh (Minus the commands that are not related to Windows and modify the usage of the commands to adapt to the usage of Windows) to compile the Thorium browser

**Comment by gz83** [comment]
Follow #551
