### ISSUE TITLE
can't uninstall extension Google Hangouts

### ISSUE THREAD

**Issue by LinuxOpa** [Alex313031/thorium#410]
**System Details**
 - OS: Ubuntu 22.04
 - Thorium Version 117.0.5938.157 (Offizieller Build) stable, built on Linux (64-Bit)

**Problem**
can't uninstall extension Google Hangouts

**Screenshots**
[![Bildschirmfoto-vom-2023-11-07-08-53-20.png](https://i.postimg.cc/zBvNJYVr/Bildschirmfoto-vom-2023-11-07-08-53-20.png)](https://postimg.cc/67kg0Srj)

**Additional Notes**
If I click **delete**, nothing happens. The extension "nkeimhogjdpnpccoofpliimaahmaaome" is also not found in the file system. The extension seems to be stuck in a thorium database.

**Comment by gz83** [comment]
This extension cannot be uninstalled and is a Google built-in extension.

**Comment by LinuxOpa** [comment]
Google Hangouts no longer exists, Google Hangouts has been replaced by Google Chat; see "https://hangouts.google.com/"

**Comment by gz83** [comment]
Google should update this extension in subsequent versions. Thorium does not actively embed this extension, we just display them all to the outside world.

**Comment by LinuxOpa** [comment]
ok.
