### ISSUE TITLE
Weather.com "Search City or Zip Code" doesn't accept input

### ISSUE THREAD

**Issue by IanBullard** [Alex313031/thorium#414]
OS: Windows 11 Pro 22H2
Thorium Version: 117.0.5938.157 (Official Build) (64-bit)

Reproduction steps:

1. Visit https://weather.com/
2. Click on the text entry box "Search City or Zip Code" at the top of the page
3. Note that you cannot type anything into the input box

**Comment by gz83** [comment]
I used Thorium for testing and did not find any problems during the process. Can you enter content in the search box provided on the webpage in incognito mode?

**Comment by IanBullard** [comment]
I cannot.  Incognito mode doesn't work either.  I cannot even get a cursor to input text on the search box.

**Comment by gz83** [comment]
Can you record a video on this issue? I will refer to your video and try again to reproduce the problem you encountered.

**Comment by IanBullard** [comment]
https://github.com/Alex313031/thorium/assets/3155698/1837cec8-25e1-4c70-82d6-f61377440291

**Comment by gz83** [comment]
Will this also happen with chrome/chromium?

**Comment by gz83** [comment]
Okay, I'm going to run more tests and let you know if I have the results.
