### ISSUE TITLE
Downloading the page source when clicking on a link instead of opening it in the browser

### ISSUE THREAD

**Issue by epicmet** [Alex313031/thorium#415]
**System Details**
 - OS: Linux archlinux 6.5.7-arch1-1
 - Thorium Version: 117.0.5938.157 (Official Build) (64-bit)

**Problem**
When Thorium is my system's default browser and I click on a hyperlink (in a text editor for example) the source page of the corresponding web page starts to download and then Thorium opens that file in a raw form. 

**Screenshots**
![Screenshot_20231108_153212-1](https://github.com/Alex313031/thorium/assets/75490189/d7448178-7540-4b02-9fdb-52282b09c0dc)

**Additional Notes**
I don't have much experience in c++ but I would be happy to help on this issue and contribute to this project if possible.

**Comment by gz83** [comment]
Does Chrome/Chromium also have this issue?

**Comment by MahdiAghaei1** [comment]
Right, is there any more information I can provide?
Also worth mentioning the 116 version on my Mac machine works just fine. I have to test different versions on my Linux machine.

**Comment by gz83** [comment]
You can use the dichotomy method to troubleshoot which version the problem occurs, or wait for Thorium to be updated to a version that does not have this problem (a version consistent with Chrome/Chromium that does not have this problem)
