### ISSUE TITLE
Anyone else getting NET::ERR_CERT_AUTHORITY_INVALID?  with websites?

### ISSUE THREAD

**Issue by Username23453** [Alex313031/thorium#416]
I am also concerned a hacker is trying to hack into my web traffic & accounts/personal data.  Maybe its just Thorium glitching?
Anyone else get this problem?   I get this issue with various websites, rarely, it started happening a month ago, has happened to about 6 different legit websites. 

![image](https://github.com/Alex313031/thorium/assets/105397593/f1c06b55-0c8c-41dd-8258-394f63239db7)

**Comment by gz83** [comment]
The problem you encountered cannot be reproduced. Please check whether your computer time is correct and try in incognito mode to see if the problem you encountered still occurs.
