### ISSUE TITLE
Thorium update list ignored

### ISSUE THREAD

**Issue by craigccfl** [Alex313031/thorium#417]
**System Details**
 - OS: Debian 12
 - Thorium Version 117.0.5938.157-1

**Problem**
https://dl.thorium.rocks/debian stable InRelease "ignored" Cleared  apt cache, issue persists. 

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/38798834/566cb265-c987-4c35-acec-88affac8864a)

**Additional Notes**
Arch systems via AUR updated as expected; however, does not seem to be the case with Debian package managers. Liking the browser, hope to make it work going forward. Thank you!

**Comment by gz83** [comment]
@midzer Please take a look

**Comment by craigccfl** [comment]
> @midzer Please take a look

Will do this evening and get back. Thanks for the quick response.

**Comment by craigccfl** [comment]
After checking
![image](https://github.com/Alex313031/thorium/assets/38798834/358b16f9-588a-444c-833f-c3dd5138a4b2)

**Comment by gz83** [comment]
Please wait for the midzer to reply to you. After he replies to you, you can test again, or pay attention to whether there are the same or similar problems in the issue or discussion.

**Comment by midzer** [comment]
Related https://github.com/Alex313031/thorium/issues/298#issuecomment-1811349878
