### ISSUE TITLE
Bookmark bar icons only.

### ISSUE THREAD

**Issue by davefl67** [Alex313031/thorium#421]
I know "Edge" is probably a thing we don't discuss. 😏

There is one feature I like from Edge. On the bookmarks bar, you can right click individual entries and select "Show Icon Only." This saves space to allow bookmark hoarders like myself to really pack 'em in. Although for Chrome, I could simply remove the title, it makes it tough when moving them to "Other Bookmarks" later, as I would have to try to remember what the hell the bookmark was!

Like to see this in Thorium, as this is sure to become my daily driver.

Thanks!
[/dave]

**Comment by gz83** [comment]
Thanks for the advice

**Comment by diomed** [comment]
good idea for us bookmark hoarders out there
