### ISSUE TITLE
Video error for encrypted videos on Udemy platform 

### ISSUE THREAD

**Issue by Rolands71** [Alex313031/thorium#423]
I tried to watch my videos on the Udemy.com learning platform, but I received a video error. 
This error doesn't occur with Vivaldi, Firefox or Brave browser. 
I checked all settings and I also checked with google for a solution, without success. 

This is the system-check Webpage from Udemy. 
This shows that normal videos can be played with Thorium, but for encrypted Videos I get a Video error. 

https://www.udemy.com/support/system-check/?persist_locale=&locale=en_US

**System Details**
 - OS: Windows 11 22H2
 - Thorium Version 117.0.5938.157 (Official Build) (64-bit)

**Comment by gz83** [comment]
mark as duplicate
