### ISSUE TITLE
Case of scrollbar

### ISSUE THREAD

**Issue by diomed** [Alex313031/thorium#424]
XP CSS
https://botoxparty.github.io/XP.css/#window-contents

Water CSS
https://watercss.kognise.dev

Could Thorium be modified so it would have custom scrollbar by default 
such as examples shown in css above?

I'd very much like for it to differ from other browsers in this way,
since  I find default scrollbar on browsers unatractive and outdated.

**Comment by gz83** [comment]
thanks for your advice
