### ISSUE TITLE
Prime Video 1080p HD Unavailable

### ISSUE THREAD

**Issue by arvind2109** [Alex313031/thorium#426]
System Details
 - OS: Windows 11
 - Thorium Version 117.0.5938.157

Problem
Browser does not support High-Definition playback in Amazon Prime Video

Screenshots
![Screenshot (35)](https://github.com/Alex313031/thorium/assets/87494094/131bc17f-5722-4804-8d2e-7b43df247325)

**Comment by gz83** [comment]
Are other Chromium-based browsers working fine? (Do not test browsers such as chrome and brave)

**Comment by arvind2109** [comment]
Yes, It's working fine in Google Chrome and Firefox

**Comment by gz83** [comment]
As stated in the previous reply, do not test on Chrome, and do not use Firefox for testing either.

**Comment by fernandofig** [comment]
Edge works. I think this is the same as [this issue](https://github.com/Alex313031/Thorium-Win-AVX2/issues/84#issuecomment-1627702006), only Primevideo doesn't completely block the user, but instead falls back to lower quality.

Btw (and I know it's sorta offtopic, but it's another data point I guess), on HBO Max some random error is spewed and the user is effectively blocked from watching from Thorium just like on Netflix. And again, Edge works fine here.
