### ISSUE TITLE
Frequent black screens if hardware acceleration is enabled

### ISSUE THREAD

**Issue by ste1eee** [Alex313031/thorium#428]
**System Details**
 - OS: Windows 10
 - Thorium Version 117.0.5938.157

**Problem**
Getting frequent black screens that last for about half-second if hardware acceleration is enabled.
When hardware acceleration is disabled the problem disappears.

**Comment by ms178** [comment]
On which GPU and driver? Have you tried a clean installation of the latest GPU driver?

**Comment by ste1eee** [comment]
I have Manli RTX 3070 Ti on newest driver (546.01).
My settings are all on default and I haven't touched anything in "about:flags".
I will try clean installation now and will post if it helps

**Comment by ste1eee** [comment]
Seems like clean install fixed the issue. Thanks for help!
