### ISSUE TITLE
poor youtube 4k60fps performance compared to FF Nightly

### ISSUE THREAD

**Issue by PcChip** [Alex313031/thorium#43]
Love the project!

Just wanted to report my test against FireFox Nightly:  
using the following video: https://www.youtube.com/watch?v=LXb3EKWsInQ   
Thorium shows Render/3D at 100% and Video at 0% in intel_gpu_top, and the video drops frames  
FF Nightly shows Render/3D at 25% and Video at 25% in intel_gpu_top,  and the video is smooth  
  
12th gen Intel CPU on Kubuntu 22.04

**Comment by PcChip** [comment]
should be the latest version of Thorium and the latest version of Kubuntu 22.04  
  
does this help? - https://i.imgur.com/VgSqijU.png

**Comment by Alex313031** [comment]
@PcChip Yes thanks. What is your CPU?

**Comment by PcChip** [comment]
12th gen core i5

**Comment by Alex313031** [comment]
Try latest release and see if it persists. https://github.com/Alex313031/Thorium/releases/tag/M105.0.5183.0

**Comment by Alex313031** [comment]
@PcChip Hows it coming.

**Comment by PcChip** [comment]
it seems that both Thorium and regular FireFox render youtube videos as "Render/3D", whereas Firefox Nightly renders it as "Video" according to intel_gpu_top.  When rendered as "Render/3D", it is not as smooth and stutters and drops frames.  
  
I assume that's related to FireFox Nightly recently enabling VAAPI by default?

**Comment by Alex313031** [comment]
@PcChip Thorium has patches to enable VAAPI and VDPAU by default as well as it can. This is strange that it is not working on a new chip on ubuntu.

**Comment by goosesima** [comment]
Same issue.
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Graphics Processor: Mesa Intel® UHD Graphics 620

It uses CPU +50% when decoding video and 0% intel-gpu-top video.

**Comment by slimx** [comment]
This package works fine, x11 and wayland. is it possible to use the patches?
[chromium-wayland-vaapi-next(for archlinux)](https://build.opensuse.org/projects/home:zhmars:arch/packages/chromium-wayland-vaapi-next/repositories/Arch/binaries)

**Comment by JadenJSJ** [comment]
I fixed hardware decoding on my instance by clearing the flags on `~/.config/thorium-flags.conf` (copied from chrome)
and also resetting all thorium flags on `chrome://flags`

**Comment by PcChip** [comment]
so on a fresh thorium install on linux, you had to change flags or a config file to make Thorium use hardware video decoding?

**Comment by gz83** [comment]
I used the latest Intel graphics driver on the Kubutnu 22.04 system to test the browser's hardware acceleration and found that it was normal.

I'm using X11 instead of wayland.

**Comment by JadenJSJ** [comment]
> so on a fresh thorium install on linux, you had to change flags or a config file to make Thorium use hardware video decoding?

No, it works out of the box. I made some changes to the flags at some point or copied it over from my chrome install.

**Comment by JadenJSJ** [comment]
I can confirm HW Accel doesn't work if `--ozone-platform=wayland`

![2023-11-12_09-42.png](https://github.com/Alex313031/thorium/assets/44781632/f5d130b2-5d5e-4dc4-aa2c-735532e671f8)

![2023-11-12_09-41.png](https://github.com/Alex313031/thorium/assets/44781632/7e1d5c4a-0485-4654-874b-c5320004df72)

**Comment by gz83** [comment]
> I can confirm HW Accel doesn't work if `--ozone-platform=wayland`
> 
> [![2023-11-12_09-42.png](https://user-images.githubusercontent.com/44781632/282276659-f5d130b2-5d5e-4dc4-aa2c-735532e671f8.png)](javascript:void(0))
> 
> [![2023-11-12_09-41.png](https://user-images.githubusercontent.com/44781632/282276660-7e1d5c4a-0485-4654-874b-c5320004df72.png)](javascript:void(0))

try to use X11

**Comment by JadenJSJ** [comment]
> try to use X11 @JadenJSJ
I accidentally deleted my previous comment.

HW video Accel works fine in X11. But 2 finger pinch zoom still doesn't work @gz83

![2023-11-12_11-18](https://github.com/Alex313031/thorium/assets/44781632/0a91c70d-a83f-44c6-9c5d-65b15e2c2093)

**Comment by gz83** [comment]
> > try to use X11 @JadenJSJ
> 
> I accidentally deleted my previous comment.
> 
> HW video Accel works fine out of the box in X11. But 2 finger pinch zoom still doesn't work @gz83
> 
> [![2023-11-12_11-18](https://user-images.githubusercontent.com/44781632/282277711-0a91c70d-a83f-44c6-9c5d-65b15e2c2093.png)](javascript:void(0))

Hardware acceleration on the Linux platform is currently not available out of the box, and turning on hardware acceleration inevitably requires sacrificing something.

@JadenJSJ
