### ISSUE TITLE
X86 support

### ISSUE THREAD

**Issue by mohammad5305** [Alex313031/thorium#432]
**Is your feature request related to a problem? Please describe.**
I know x86 is not longer used but there isn't a good (fast) browser for old PCs

**Describe the solution you'd like, including relevant patches or source**
An x86 binary

**Comment by gz83** [comment]
Please use the version in thorium-win7 repo for now. It is still unclear whether the x86 version will be provided in the future.

**Comment by mohammad5305** [comment]
Sure, but for most old PCs we use linux instead

**Comment by p7r0x7** [comment]
All chips powerful enough to run Thorium properly have 64-bit support.
32-bit poses security concerns and generally cannot use more than 4GiB of RAM, so it's very unlikely 32-bit support will continue for such a complex and security-critical application as your daily-driven web browser.
@Alex313031 the OP has been directed towards https://github.com/Alex313031/Thorium-Win7 so you may close this if you wish.
