### ISSUE TITLE
CTRL + SPACE -> brings up hotkey search query. Possible to disable?

### ISSUE THREAD

**Issue by patdngo** [Alex313031/thorium#433]
Unsure if using "ctrl + space" for hotkey search is able to be changed to another set of keys or disabled. 

![image](https://github.com/Alex313031/thorium/assets/151068895/bcc2be96-8765-44f6-8aaf-dbddd217da9e)

Can be annoying when using website software that uses those keys like FXreplay since it will interrupt action constantly. 

Probably unhelpful if there is already a way to disable but I couldn't find anything searching through settings. 
Would be nice to have an obvious page where can change browser hotkeys to avoid certain conflicts.

**Comment by Aedon** [comment]
You can disable it on the chrome flags page. Enter the followng url in the address bar: [chrome://flags/#quick-commands](chrome://flags/#quick-commands) . Set the highlighted option to disabled and restart your browser.

**Comment by glyh** [comment]
Nothing is highlighted on my end. There's no such flag. I'm on
```
The fastest browser on Earth.
Thorium 121.0.6167.204 stable, built on Linux
```

**Comment by Alex313031** [comment]
@glyh @Aedon  This flag was indeed present in M121 and M122.

However, the quick commands UI was completely removed in M123, so now it won't do this anymore.
