### ISSUE TITLE
Thorium tab crashes every time I try to open Discord after logging in. 

### ISSUE THREAD

**Issue by Kame03** [Alex313031/thorium#442]
**System Details**
 - OS: Windows 7
 - Thorium Version: 109.0.5414.172

**Problem**
Thorium tab crashes every time I try to open Discord after logging in. 

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/98698826/2e1b135e-aef8-4dd5-8dff-148ab7e7fcc5)

**Comment by Alex313031** [comment]
@Kame03 This was fixed in the latest M122 version over in the Thorium-Win7 repo.
