### ISSUE TITLE
Patches from ungoogled-chromium?

### ISSUE THREAD

**Issue by toooonyy** [Alex313031/Thorium#45]
[add-flag-to-hide-side-panel-button.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/ec75c03e2555ab060abb534a9b0d34d39aabdbe9/patches/extra/ungoogled-chromium/add-flag-to-hide-side-panel-button.patch)
[add-flag-to-show-avatar-button.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/ec75c03e2555ab060abb534a9b0d34d39aabdbe9/patches/extra/ungoogled-chromium/add-flag-to-show-avatar-button.patch)
[add-flag-to-disable-sharing-hub.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/0218ef1e21cd13b9c81baa726b28da749d20fa6c/patches/extra/ungoogled-chromium/add-flag-to-disable-sharing-hub.patch)
[add-flag-for-qr-generator.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/ec75c03e2555ab060abb534a9b0d34d39aabdbe9/patches/extra/ungoogled-chromium/add-flag-for-qr-generator.patch)
Just some UI tweaks that I really like

[disable-download-quarantine.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/ec75c03e2555ab060abb534a9b0d34d39aabdbe9/patches/extra/ungoogled-chromium/disable-download-quarantine.patch) This one is also useful, but may not be desired.

**Comment by Alex313031** [comment]
@toooonyy It already has the hide side panel patch. I will probably add the download quarantine patch. I will probably not add the others.

**Comment by toooonyy** [comment]
Ok, I'll wait for the next release then.

**Comment by Alex313031** [comment]
@toooonyy I added the download quarantine patch, and the unexpire flags patch. I will go ahead and add the show/hide avatar patch too. I will not be adding the sharing hub or qr generator patches, however.
