### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by Altoyda** [Alex313031/thorium#451]
**System Details**
 - OS: [ Windows 11 Pro]
 - Thorium Version [117.0.5938.157 (Official Build) (64-bit)]

**Problem**
Not able to play any of Netflix. I have tryed clean and still not netflix. I know its a setting not sure what setting it is. Disney, Hulu and paramountplus, Play fine. Just Netflix is my problem child here.

**Screenshots**

**Additional Notes**
Any steps to try open to try. I have gone as far as reinstalling it with not a thing and still problem.

**Comment by blindmodz** [comment]
In Youtube also some videos arent possible to be played because Thorium is too old :(

**Comment by ionutbortis** [comment]
@blindmodz Can you provide an URL? Thanks!

**Comment by blindmodz** [comment]
> @blindmodz Can you provide an URL? Thanks!

https://www.youtube.com/watch?v=Be5ssrg5xws (might be my account because if i open it on incognito mode works fine)

**Comment by ionutbortis** [comment]
> > @blindmodz Can you provide an URL? Thanks!
> 
> https://www.youtube.com/watch?v=Be5ssrg5xws (might be my account because if i open it on incognito mode works fine)

Hmm, seems to work fine on my side. I also checked by using "Open New Window with a temporary profile" and it works.

Maybe you have some chrome extensions that are causing the issue.

**Comment by pixelpicnic** [comment]
Prime Video has issues as well - namely a banner saying that HD video can't be played as the browser is incompatible.
![XtlPsa1](https://github.com/Alex313031/thorium/assets/32919664/ad47ab1c-1683-4477-9162-948c4044ac1f)

**Comment by rubyFeedback** [comment]
This may also have something to do with some codecs and some websites. Not all these checks always
seem to be true. For instance, on certain websites - you know the educational ones about girls - I may
insta-skip to the middle of the video, and it will tell me that my browser can not play this video. But
then I refresh the page, and simply click on the play button, then it begins to play, and THEN I can
jump to e. g. the middle of the video and it plays fine. Makes no real sense to me, other than something
in the video-check being awkward. Speaking of which, I think thorium should get bundled with a 
default but simple video downloader too, such as yt-tdlp or what was the name again.

**Comment by Masterioz** [comment]
There are also other video platforms that have the same issue such as F1 tv. I have to open Chrome to watch either F1 or Netflix.

**Comment by LYNK-INCUU** [comment]
adding 
![image](https://github.com/Alex313031/thorium/assets/83987610/625d4ec6-5e30-448b-8e31-7ab2a89d8715)

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/blob/main/docs/FAQ.md
