### ISSUE TITLE
hardware acceleration AMD

### ISSUE THREAD

**Issue by JB63134** [Alex313031/thorium#455]
**System Details**
 - OS: Debian testing
 - Thorium  Version 117.0.5938.157 (Official Build) stable, built on Linux (64-bit)
 - AMD Ryzen 7 3700u vega 10 graphics
 - 
**Problem**
Hardware acceleration is broken.

**Screenshots**

**Additional Notes**
HW Acceleration was working before most recent OS update.

**Comment by ms178** [comment]
This is a known problem on Linux. Further Info to get it to work: https://bbs.archlinux.org/viewtopic.php?pid=2125225#p2125225

But you'd need to compile Mesa with a couple of MR's that weren't merged yet yourself.

**Comment by JB63134** [comment]
Hardware acceleration still works fine in other browsers.
