### ISSUE TITLE
Linux x265 support?

### ISSUE THREAD

**Issue by lovelytwo** [Alex313031/Thorium#46]
I've read the other ticket regarding supporting x265 on linux. However I came across another build that does manage to support x265 on linux.

https://github.com/macchrome/linchrome/releases/tag/v103.0.5060.68-r1002911-portable-ungoogled-Lin64

it requires the --enable-clear-hevc-for-testing command line argument, but it does work.

I've also tried the same command line argument with thorium without success.

Just thought this might be an interesting development.

**Comment by Alex313031** [comment]
@lovelytwo I can confirm this. Tried that build, and tried my latest build, with both cmdline patches applied. Ungoogled h265 worked, in thorium it didn't.
I can't find any h265 patches in ungoogled chromium.
Perhaps this has something to do with my vaapi/vdpau patches? I got them from debian, so im going to run debians latest chromium and see if h265 works in it or not.

**Comment by Alex313031** [comment]
@lovelytwo Debians Chromium doesn't work with h265.

So it looks like I can either have it play h265 content, or have hardware acceleration for other content on more systems.

**Comment by Alex313031** [comment]
@lovelytwo Adding to [BUGS.md](https://github.com/Alex313031/Thorium/commit/8190365263174b65c2aad1ffc7de149ba1e7993c)

**Comment by Alex313031** [comment]
@lovelytwo Turns out Thorium DOES support H.265, but only if you have hardware acceleration. I.E. your OS, GPU, and graphics driver all have to support it. Ungoogled Chromium is using a patch to enable software HEVC decoding. I will look into it.
