### ISSUE TITLE
RAM Limiter

### ISSUE THREAD

**Issue by Lukas-drz** [Alex313031/thorium#460]
Hello,
I noticed that Thorium and other Chromium based browsers use more RAM the more there is available on the system.
Would it be possible to limit the RAM quantity that the browser can use ?
Maybe with just a command line argument like --memory-limit=300M ? 
Thanks

**Comment by trimechee** [comment]
chrome://flags/
Enable the multi-state option for Memory Saver Mode.

**Comment by sachinchaudhary1808** [comment]
dev needs someone to close issues

**Comment by Alex313031** [comment]
@Lukas-drz Yup, what @trimechee said.
