### ISSUE TITLE
why is there furry porn

### ISSUE THREAD

**Issue by No1129** [Alex313031/thorium#463]
[chrome://yiff](chrome://theme/IDR_PRODUCT_YIFF)
i got to it from chrome://about/
why is this here
kids use web browsers

**Comment by Strangebeingyt** [comment]
skill issue

**Comment by No1129** [comment]
i don't think that a good thing to say back to me telling me not to show porn to kids

**Comment by No1129** [comment]
17 year olds

**Comment by Strangebeingyt** [comment]
idk bro

**Comment by docrR** [comment]
This discovery by the wrong eyes ought to get one shipped off on a one-way trip to the Ambassador Brig. I also find it rather distasteful for a browser client to contain NSFW. A browser should only contain such content if the content is consumed by an external website.

![bridge_waifu2x_noise3_scale2x](https://github.com/Alex313031/thorium/assets/68521531/2e09cf60-a6df-4a30-89bc-517c13e4d3f9)

**Comment by K4sum1** [comment]
I installed latest Thorium for Windows, and I get ERR_INVALID_URL navigating to chrome://yiff

**Comment by No1129** [comment]
go to it form 
chrome://about/

**Comment by No1129** [comment]
look like the real url is 
chrome://theme/IDR_PRODUCT_YIFF

**Comment by No1129** [comment]
https://github.com/Alex313031/thorium/blob/main/src/chrome/browser/ui/webui/about_ui.cc
its here

**Comment by K4sum1** [comment]
based dev

**Comment by Strangebeingyt** [comment]
> based dev 

honestly

**Comment by No1129** [comment]
:|

**Comment by opticblu** [comment]
> chrome://yiff i got to it from chrome://about/ why is this here kids use web browsers

If you think this is troubling, wait until you find out what they’re being taught in school

**Comment by Drakonas** [comment]
Personally, since Thorium is very much not user-friendly to install, I find that only adults would be using it anyway. It honestly doesn't bother me. Is it odd? Yes. But I doubt software like this would run issues being scrutinized with its super small userbase.

It's not even easy to find. I'm sure most people here wouldn't have found it on their own without reading these threads talking about it. If you didn't find it yourself, I don't really think you can be concerned about your kid finding it, IMO.

**Comment by freedom7341** [comment]
https://thorium.rocks/chromiumstory
![image](https://github.com/Alex313031/thorium/assets/36094486/1f26dcba-a805-4f0f-bb8c-dfe6648876c7)
Click this button at the bottom of this page for something genuinely NSFW on the official Thorium website. Not sure why any developer would include something like this. I first came across this browser when I was 17, lol.

**Comment by Strangebeingyt** [comment]
> https://thorium.rocks/chromiumstory
> 
> ![image](https://github.com/Alex313031/thorium/assets/36094486/1f26dcba-a805-4f0f-bb8c-dfe6648876c7)
> 
> Click this button at the bottom of this page for something genuinely NSFW on the official Thorium website. Not sure why any developer would include something like this. I first came across this browser when I was 17, lol.

I NEVER KNEW ABOUT THAT

**Comment by No1129** [comment]
https://github.com/Alex313031/Alex313031.github.io/tree/main/misc/sexuallymutilatedchild.org
um

**Comment by docrR** [comment]
> Personally, since Thorium is very much not user-friendly to install, I find that only adults would be using it anyway. It honestly doesn't bother me. Is it odd? Yes. But I doubt software like this would run issues being scrutinized with its super small userbase.
> 
> Seriously, what 17 year old would know how to find this browser? The only ones that do should have their parents more concerned about them being into other types of things regarding computers.
> 
> It's not even easy to find. I'm sure most people here wouldn't have found it on their own without reading these threads talking about it. If you didn't find it yourself, I don't really think you can be concerned about your kid finding it, IMO.
> 
> Also I believe he said he would remove it once it was found... it was a dev joke, and the feature was barely noticed at all. The more you post about it, though, of course it's gonna get publicity and kids will find it.
> 
> Also, imo it's sketchy, borderline NSFW. It doesn't show any bits, so ruling wouldn't probably have any court case.

I'm 25, but I've been using niche software projects like this since I was 14. Also, other users have outlined on this thread that they were under 18 when they discovered this browser. I don't expect many pre pubescent children to be using this sort of software, but the laws in most jurisdictions, most importantly the one the developer is located in, does not differentiate it. Most NSFW content legally requires the viewer to be of age to consume it. It's as simple as that. I'm sure the developer just has it here as a cheeky Easter Egg, with no harm intended. However, it's still rather inappropriate. It's also a rather foolish to assume people under 18 aren't using FOSS software.
Just my 2 cents.

**Comment by TiZmSpectrum** [comment]
e621 browser.


Never in my life did I expect that to be a thing...

**Comment by fernandofig** [comment]
> [link removed because I don't want that on my history]
> um

whiskey, tango, foxtrot.

I mean, I had mixed feelings about the furry thing - it's distasteful and unprofessional to have it on a web browser, and at the same time I disagreed with the "think of the children" angle, and thought it somewhat funny to leave it as easter eggs, maybe as a one time thing.

But this? Why? What kind of sick mind hoards stuff like this?

**Comment by Strangebeingyt** [comment]
> https://github.com/Alex313031/Alex313031.github.io/tree/main/misc/sexuallymutilatedchild.org
> 
> um

WHAT. THE. FUCK...

**Comment by gz83** [comment]
It will be removed in subsequent versions

**Comment by SethbotStar** [comment]
I was shocked to learn that this existed. WTF? This kind of thing should never be considered to ever be in a browser. I'm glad it's being removed but how did this kind of thing even happen in the first place? ALSO WHAT THE FUCK IS THAT OTHER LINK. Yeah, i don't think I'm going to continue to use this browser.

**Comment by returnofblank** [comment]
I'm gonna be real, but this is grounds to leave this browser.

This is really unprofessional, I did NOT want to see furry spreaded cheeks in a public environment.

**Comment by earthsound** [comment]
@No1129 @fernandofig @Strangebeingyt @SethbotStar looks like the repository for an anti-circumcision website

**Comment by thisislvca** [comment]
> It will be removed in subsequent versions

@gz83 how the actual F can you say it will be removed in subsequent versions like that - after the link shared? If I had to guess stuff like that is 110% against GitHub's user agreement.

I heard rumors that the guy behind the project was a bit nuts, but this is so bad I just don't get it.

Plus, your whole worshipping-like attitude (yes I'm talking 'bout you @gz83) when it comes to contributing, like "alex needs to decide, ask alex before creating a PR" etc, I considered it just unusual... but after this I gotta question you too, considering how much work you put into the project yourself...

Get a hold of yourself, guys. If it was a joke, ok based dev, but at one point yall need to take this whole thing seriously...

**Comment by fernandofig** [comment]
> Plus, your whole worshipping-like attitude (yes I'm talking 'bout you @gz83) when it comes to contributing, like "alex needs to decide, ask alex before creating a PR" etc, I considered it just unusual... but after this I gotta question you too, considering how much work you put into the project yourself...

Ok, calm down, let's not start a witch hunt here. As a developer myself (though not on this project), the deferrals I've seen @gz83 do came across to me as more in the sense that he doesn't have the autonomy or privileges on the repository to make decisions or approve code / commits. Although I have to agree that his response ("it will be removed on the next release") is rather poor - it would have been smarter to keep silent and let Alex deal with the backlash, since this is his' mess in the first place.

**Comment by thisislvca** [comment]
> Ok, calm down, let's not start a witch hunt here. As a developer myself (though not on this project), the deferrals I've seen @gz83 do came across to me as more in the sense that he doesn't have the autonomy or privileges on the repository to make decisions or approve code / commits.

Yeah that's fair haha... I just find it very strange cuz when I asked about the option of making an org so that it was easier to contribute, the reply wasn't what you expect from an open-source project. Dunno man, it felt strange even before knowing about all this stuff...

**Comment by fernandofig** [comment]
> @No1129 @fernandofig @Strangebeingyt @SethbotStar looks like the repository for an anti-circumcision website

I did some browsing on that website (yuck) and honestly it doesn't paint a better picture of Alex at all. A church "that believes in the likelihood of time-travel and offers assistance to those traveling in time"? Ok pal. I read a little more and can't decide if this is a very elaborate joke or just plain nuts. Whatever the case may be, it hardly justifies having tons of pictures of mutilated babies. A couple, to ilustrate a point? _Maybe_. Dozens, maybe hundreds? No.

**Comment by alexandreteles** [comment]
Bet the yiff is responsible for *at least* 50% of Thorium's speed-ups.

**Comment by thisislvca** [comment]
> Bet the yiff is responsible for *at least* 50% of Thorium's speed-ups.

Bruh. Btw now chrome is faster 🗿

**Comment by alexandreteles** [comment]
> Bruh. Btw now chrome is faster 🗿

Just need to add more yiff for *more powa*

**Comment by speediegq** [comment]
This is absolutely disgusting. Is Thorium a serious project with a serious goal or is this just a stupid joke? I must say the author is 22 years old, so I expected better from someone of that age. If this is a real project, I don't get what you were thinking. If this is a joke, that should've been made more clear. A browser should not come bundled with pornography, that's just common sense.  Gross.

**Comment by everythingeeb** [comment]
As a Thorium user, this is absolutely disgusting and horrifying. I was initially drawn to this browser for it's speed, however I will no longer continue to use it now in light of this recent discovery. I've seen many replies saying that most users of the browser in question won't be minors, however I myself am 16 years old and was going to recommend this browser to my friends similar in age. It seems I won't be doing that now.

@Alex313031 Get your shit together. Nobody thinks this is funny. You are 22 years old and doing immature shit like this. I pity you.

And for those who are parroting "based": Get a life. If you truly think this is "based" behavior there is something seriously wrong with you as well.

**Comment by K4sum1** [comment]
Holy fucking shit quit fucking coping over bullshit that doesn't fucking matter at all

**Comment by everythingeeb** [comment]
It's the principle that matters. If right now he is "bundling" furry p*rn into the browser, what's stopping him from including child p*rn in the browser later? As far as I'm concerned, this incident is taking it too far already. Better safe than sorry.

**Comment by K4sum1** [comment]
Anyone could integrate anything into anything at any point.

**Comment by returnofblank** [comment]
And that's not a good thing lol, I do not want any porn bundled with my software except my porn software

**Comment by everythingeeb** [comment]
> And that's not a good thing lol, I do not want any porn bundled with my software except my porn software

^^^^

**Comment by speediegq** [comment]
Pornography does not belong in a free software project. Simple as. And if it should, then no one should use the project. @Alex313031 as a developer you should be ashamed. I know if someone added porn to my software I would be furious.

**Comment by SethbotStar** [comment]
> @No1129 @fernandofig @Strangebeingyt @SethbotStar looks like the repository for an anti-circumcision website

Still that's very concerning, both the name and content of that. That's really what makes me want to never come back to this browser, i do not feel i can trust the developer at all. It would be great for somebody else to remake this kind of project, but the lead developer is inherently the issue right now.

**Comment by earthsound** [comment]
> > @No1129 @fernandofig @Strangebeingyt @SethbotStar looks like the repository for an anti-circumcision website
> 
> Still that's very concerning, both the name and content of that. That's really what makes me want to never come back to this browser, i do not feel i can trust the developer at all. It would be great for somebody else to remake this kind of project, but the lead developer is inherently the issue right now.

Leaving aside the furry issue, which I agree shouldn't be in a browser repository, which is concerning? Circumcision or a snapshot of a website - that someone else published 23 years ago - which Alex backed up on github (aside from copyright infringement)? Alex mentions that he's an intactivist in his About Me. 

See the copyright note at the bottom of the backup:

>John A. Erickson
>March 1998
>qsmd[@]datasync.com [To send me email, omit the SPAM-deflecting brackets from my email address.]
>Continually in progress.
>Last modified October 26, 2000.

**Comment by gz83** [comment]
Sorry for bringing you a bad experience.  In addition, I need to explain: please maintain the most basic respect for everyone.

**Comment by Alex313031** [comment]
The chrome://yiff page was intentional. The stuff on the site was in my own local copy when I was f**king around with stuff and got accidently commited. I'll remove all of the stuff from both thorium and the site, but the anti-circ shit is going to stay because the original site lost its hoster.
