### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Drakonas** [Alex313031/thorium#464]
There haven't been any updates in any repo in weeks, 2 months for Windows. If the dev is dealing with life stuff, I understand, but an update would be nice while certain things are starting to break like site data being lost randomly and RAM leak issues popping up.

If it is abandoned, it'd be nice to state if you have no plans to develop it further so I can move to something else.

Hope Alex is ok, regardless.

**Comment by pixelpicnic** [comment]
I sure hope not - I'm late to the party, and I love this browser.
I hope all is well!

**Comment by ms178** [comment]
@Drakonas This project is notorious for late updates to new releases or skipping several releases alltogether, sadly. Hence the period of time without committs is nothing new. While this doesn't mean that the project is dead, it also speaks for itself that the current team might not be up to the task of maintaining such a big project.

As Youtubers recently made quite a splash to push Thorium and that Google increased its release cadence, I fear that it collapses under the burden. No timely releases are a major security concern. And as I love Thorium, and its current state saddens me just as well as you.

What this project is in dire need of:

1) automated builds and releases
2) timely updates

From the answers I've seen before, it comes down to costs and time issues. The builds are made manually at the moment.

**Comment by elmuz** [comment]
If you look at the author page you can see almost zero activity recently, not just about this project. Let's hope he'll come back.

**Comment by fernandofig** [comment]
> If you look at the author page you can see almost zero activity recently, not just about this project. Let's hope he'll come back.

If you look into his activity back in 2022, it seems that, much like this year, he was mostly inactive from november. Activity picked up again by January. Maybe he's on vacation?

Honestly I don't care at this point. I've been watching this project and feeling pretty much the same as @ms178 , and now from what is transpiring from #463 , I think I'll jump ship altogether.

**Comment by SethbotStar** [comment]
I hope somebody remakes a similar project so it's under a significantly less concerning developer.

**Comment by Xmetalfanx** [comment]
yeah ... i am going to have to go back to FIrefox ... the "furry porn" stuff i think should be removed and has no place in a project like this (not even "offended" or "think of the children!" about it) ... the other stuff i saw just now ... figuring some people were going overboard BUT THEN seeing proof ... I cant have anything by this dev on my PC ... i am done .... and this was the first non-bloated (looking at Brave and Vivaldi) Chromium based browser i liked ... ever ... but yeah ... forget all the good stuff .... now maybe if another dev does the same sort of work, removes all that crap and takes OVER the project ... I may come back 

this dev may do great coding work but this content i have seen on his/her repos is not acceptable to me ... and yes i admit again i thought some users were going overboard ... just seeing one "furry porn" pic at first.

**Comment by SethbotStar** [comment]
> yeah ... i am going to have to go back to FIrefox ... the "furry porn" stuff i think should be removed and has no place in a project like this (not even "offended" or "think of the children!" about it) ... the other stuff i saw just now ... figuring some people were going overboard BUT THEN seeing proof ... I cant have anything by this dev on my PC ... i am done .... and this was the first non-bloated (looking at Brave and Vivaldi) Chromium based browser i liked ... ever ... but yeah ... forget all the good stuff .... now maybe if another dev does the same sort of work, removes all that crap and takes OVER the project ... I may come back
> 
> this dev may do great coding work but this content i have seen on his/her repos is not acceptable to me ... and yes i admit again i thought some users were going overboard ... just seeing one "furry porn" pic at first.

Yeah, honestly the furry porn shit was bad on its own, and that in it of itself got me to start pulling it from computers i installed it on. Even still, at that point i would have been willing to give it another shot in the future.

When somebody archives a site titled the way that repo was titled, and has those types of images for _any_ reason, I no longer trust the main dev of this project, and so far i don't really trust any of the other devs I've seen so far, while i don't recall that they have done much to lose trust, they haven't done much to regain trust from a currently tainted project.

It would be nice if somebody else remakes a similar project, but with everything that has come out, it cannot be under the current main dev.

**Comment by Alex313031** [comment]
@Drakonas @fernandofig @Xmetalfanx @elmuz @ms178 @pixelpicnic No it is NOT dead. Im going to be completely honest, I was in inpatient rehab for alcohol, something I have struggled with since 15 years old.

I also happen to have covid right now too (i caught it at the facility, as did 10 others), but I will get a release out as soon as I can (because I want a new version too for tha security fixes)

I will be making a note on the previous release and upcoming release to explain why I was "dead" for a month.

**Comment by Alex313031** [comment]
@Xmetalfanx @SethbotStar You guys do know it was an archive of an anti circumcision website that was around for over a decade until the hosters shut down > https://web.archive.org/web/20210416033739/https://sexuallymutilatedchild.org/

**Comment by pixelpicnic** [comment]
@Alex313031 
Appreciate you and hope you're doing better. Thanks for sharing - that's big of you.
fortify!

**Comment by Drakonas** [comment]
Truly.. I had no intention of sharing ill contempt.. I was honestly more worried something has happened to you.

I hope you recover well... Sounds like such an awful thing to have to deal with during the holiday season.

Wishing you well mate. Rooting for you.
