### ISSUE TITLE
Can't launch Thorium

### ISSUE THREAD

**Issue by NguyenDangLinh-hello** [Alex313031/thorium#465]
**System Details**
 - OS: Windows 10 22H2
 - System: Pentium G3240 😳, 4GB Ram 😳, HDD 😳 

**Problem**
Can't launch Thorium

https://github.com/Alex313031/thorium/assets/133625935/55cc5666-b5a7-4a0d-8ffe-07df94287fe8

**Comment by NguyenDangLinh-hello** [comment]
BRUH

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1

try to use this version

@NguyenDangLinh-hello
