### ISSUE TITLE
On closing issue #463 

### ISSUE THREAD

**Issue by thisislvca** [Alex313031/thorium#468]
What are you going to solve by closing issue #463? You're going to hide the problem from the rest of the users...?

The heat and discussion is the only way to solve the problem.

It's not about a bad experience @gz83, it's about talking. What IS a bad experience is closing it and blocking it as too heated, that way it feels like censorship even when you're trying to be helpful.

Besides, most heat was from memers and anime people saying that it's ok to have furry porn in an OSS...

Nobody likes the idea of having porn shipped with a browser. Other than that, the real problem is that it goes against GitHub's Community Guidelines and ToS.

**Comment by Boberttt** [comment]
https://github.com/Alex313031/Alex313031.github.io/tree/main/misc/hidden - Furry porn
https://github.com/Alex313031/Alex313031.github.io/tree/main/misc/sexuallymutilatedchild.org - I don't even know
https://github.com/Alex313031/atom-ng/tree/db318f9eefd9458b1121dd895f6c95eeb3a4355a/packages/yiff/assets - more porn
https://github.com/Alex313031/beaker-ng/tree/master/app/userland/yiff/imgs - more porn
https://github.com/Alex313031/quark-player/blob/master/src/ui/imgs/catgirl_fridge.png - you know at this point
https://github.com/Alex313031/thorium/blob/main/src/chrome/app/theme/default_100_percent/chromium/yiff.png

this isn't a one time thing

**Comment by Xmetalfanx** [comment]
this is one of the only chromium forks i find usable (usually a FIrefox user for my main browsing) ... in a sense I am an adult and i dont care about this sort of thing ... it's stupid but I dont see the images so in that way I dont care ... HOWEVER I agree this stuff should be removed.   It has no place in a browser ... I am not even "offended" by it... just that I think the project would be better without this sort of content ANYWHERE in the project.    Some may question the hard work of the developer(s?)  do to make things more secure with this sort of content in the code 

Again I am not "offended" per-say ... but I just think this project has so much potential .. heck i finally am on a non-Firefox Browser that I like a bit ...just a "yeah .. .this stuff should be removed" view from me

**Comment by MeFinity** [comment]
this is very much a nothing burger, while i do agree it should be removed, basically no one but a select few would see it

**Comment by nonetrix** [comment]
> https://github.com/Alex313031/Alex313031.github.io/tree/main/misc/hidden - Furry porn xxxxxxxxxxxxxxx- I don't even know https://github.com/Alex313031/atom-ng/tree/db318f9eefd9458b1121dd895f6c95eeb3a4355a/packages/yiff/assets - more porn https://github.com/Alex313031/beaker-ng/tree/master/app/userland/yiff/imgs - more porn https://github.com/Alex313031/quark-player/blob/master/src/ui/imgs/catgirl_fridge.png - you know at this point https://github.com/Alex313031/thorium/blob/main/src/chrome/app/theme/default_100_percent/chromium/yiff.png
> 
> this isn't a one time thing

Did they put fucking CP in the browser? The actual fuck?! Probably best to avoid even sending the link more, but I guess it could be a edgy link name but I am not clicking that shit. If it's CP someone should report to authorities

**Comment by finnurthorisson** [comment]
## We will not tolerate harassment of any kind, including but not limited to:
* Inappropriate sexual content

https://github.com/Alex313031/thorium/blob/main/CODE_OF_CONDUCT.md

**Comment by BrodieRobertson** [comment]
I see the repo owner is deleting comments about this now. Deleting comments doesn't make the porn go away

**Comment by Alex313031** [comment]
@MeFinity Gonna remove all the shit. The one in the browser was an easter egg. The shit on the site was when I was messing around with shit and should never have been committed.

**Comment by Alex313031** [comment]
@Xmetalfanx @MeFinity @BrodieRobertson @thisislvca Fixed now.

**Comment by SethbotStar** [comment]
> I see the repo owner is deleting comments about this now. Deleting comments doesn't make the porn go away

I still have found the other github link much more concerning honestly. Check the other issue if you're not aware already.

**Comment by nonetrix** [comment]
> @MeFinity @BrodieRobertson Gonna remove all the shit. The one in the browser was an easter egg. The shit on the site was when I was messing around with shit and should never have been committed.

Can you at least answer why there was a link named "child sexual mutilation"?

**Comment by returnofblank** [comment]
> > @MeFinity @BrodieRobertson Gonna remove all the shit. The one in the browser was an easter egg. The shit on the site was when I was messing around with shit and should never have been committed.
> 
> Can you at least answer why there was a link named "child sexual mutilation"?

I think it was some anti-circumcision thing. Didn't fully look through it.

**Comment by SethbotStar** [comment]
> > > @MeFinity @BrodieRobertson Gonna remove all the shit. The one in the browser was an easter egg. The shit on the site was when I was messing around with shit and should never have been committed.
> > 
> > 
> > Can you at least answer why there was a link named "child sexual mutilation"?
> 
> I think it was some anti-circumcision thing. Didn't fully look through it.

I don't even know how one is allowed to have those kinds of images for any reason.

**Comment by nonetrix** [comment]
> > > > @MeFinity @BrodieRobertson Gonna remove all the shit. The one in the browser was an easter egg. The shit on the site was when I was messing around with shit and should never have been committed.
> > > 
> > > 
> > > Can you at least answer why there was a link named "child sexual mutilation"?
> > 
> > 
> > I think it was some anti-circumcision thing. Didn't fully look through it.
> 
> I don't even know how one is allowed to have those kinds of images for any reason.

It likely was just text to be fair

**Comment by thisislvca** [comment]
> It likely was just text to be fair


No bro, images. Look at the commit history lol...

**Comment by nonetrix** [comment]
> > It likely was just text to be fair
> 
> No bro, images. Look at the commit history lol...

Again, not clicking that shit if it's the case

**Comment by thisislvca** [comment]
@Alex313031 thanks for removing. I still believe this whole thing is kinda sus, especially with the amount of stuff you had.

Mistakenly committed? Mmmh...

Only question I have is why don't you want to remove the anti circ stuff?

It's totally against GitHub's terms/community guidelines, so just host it locally if the old website isn't live anymore.

No need to upload it here, especially to the thorium website repo.

Also, not cool deleting comment. Can't you face some heat bro? Let them be, they contribute and are worried people - and rightly so.

**Comment by speediegq** [comment]
Glad the issue was resolved, but you have definitely broken the trust you had from users, so I hope you handle future issues better than you did here. I don't believe you when you say you commited by accident, but I suppose it *could* happen.
I think it is 100% warranted to be angry and frustrated about this situation, given the issue at hand and I'm disappointed you resorted to censoring users by removing their comments.

**Comment by finnurthorisson** [comment]
Deleting comments, locking threads, "accidentally" committing porn across at least 3 different repos (evidence of which you then try and delete), nobody is buying that
https://archive.is/github.com
