### ISSUE TITLE
On closing 463

### ISSUE THREAD

**Issue by Boberttt** [Alex313031/thorium#470]
https://github.com/Alex313031/atom-ng/tree/master/packages/yiff/assets
https://github.com/Alex313031/beaker-ng/tree/master/app/userland/yiff/imgs
https://github.com/Alex313031/quark-player/blob/master/src/ui/imgs/catgirl_fridge.png

Can you remove your “Easter eggs” from the rest of your repos? I appreciate you removing the one from thorium and the website after about 20 people complained, but when you don’t remove it from the rest it makes it seem like you’re trying to hide something rather then fix it

**Comment by gz83** [comment]
Unrelated content
