### ISSUE TITLE
Please replace the Windows icon

### ISSUE THREAD

**Issue by Commenter25** [Alex313031/thorium#478]
The Windows logo currently used in READMEs and websites is a distorted animation of the classic Windows logo.
![the windows logo in question](https://raw.githubusercontent.com/Alex313031/thorium/a5539e4127eea6701731ea6ae1719c7129a0f220/logos/STAGING/winflag_animated.gif)
It does not respect the pixels of this very low resolution, essentially pixel art. The animation is also less of a waving flag and more of a still image bouncing. And at very small sizes, there is shimmering from the white outline around it.

As such, I was motivated to find something better. This is a modified version of the official `wi_busy.ani` cursor from Microsoft Plus! 95's "More Windows" theme. The original had some jankiness to its animation, so I cleaned it up to be a seamless loop. I freely encourage you, or anyone else in need of an animated Windows logo, to use this instead. I have provided 8x integer scaled and 1x scale versions.

![my custom windows logo animation in 8x scale](https://github.com/Alex313031/thorium/assets/35016761/81694271-9d64-4e84-95d0-0c776ec82c90)
![my custom windows logo animation in 1x scale](https://github.com/Alex313031/thorium/assets/35016761/c4d6afb4-1112-46d7-bb8f-c30b690b6000)

**Comment by Alex313031** [comment]
@Commenter25 Will replace these in the repo and website!

Gonna keep the old one as .bak

**Comment by Commenter25** [comment]
This is what it looked like before my changes. It's quite jumpy and inconsistent. Truth be told, I made this long before actually posting about it, so I forget all the details.

![old version of the animation](https://github.com/Alex313031/thorium/assets/35016761/593e0cff-0f8c-40e2-ad8b-70a8c6d73927)
