### ISSUE TITLE
Y Remove the Yiff?

### ISSUE THREAD

**Issue by Bioblaze** [Alex313031/thorium#479]
not trolling, I found the 9947421 commit funny. Lol
No idea why everyone being mean about it. Should be left in LoL

**Comment by rubyFeedback** [comment]
What is the yiff picture?

**Comment by DavidRLTG** [comment]
I need to see the silly yiff theme and the yiff image, smh

**Comment by Bioblaze** [comment]
> I need to see the silly yiff theme and the yiff image, smh

It wasn't even NFSW people whining cause they can.
