### ISSUE TITLE
New release before end of 2023?

### ISSUE THREAD

**Issue by rubyFeedback** [Alex313031/thorium#481]
Last one was from start of october 2023. Can we carve out a final release for this year before the end of the year?

**Comment by NewsonUpreti** [comment]
@Alex313031  Keep this browser alive, It doesn't matter what people think. It doesn't matter the chromium version is not latest. Other browsers using latest can never beat this browser. Waiting for update sooner. Thanks.

**Comment by Kamey2024** [comment]
> @Alex313031 Keep this browser alive, It doesn't matter what people think. It doesn't matter the chromium version is not latest. Other browsers using latest can never beat this browser. Waiting for update sooner. Thanks.

At this point we should just have LTS builds if there's such variant of Chromium, would be better to focus just on it.

**Comment by pazza2234** [comment]
@Alex313031 This browser, was the best browser I ever used. It would be a real shame if it falls apart due to you leaving. I wish you a Mary Christmas and the best of luck. I genuinely don't care about "images in the files" if I don't got to mess with it. It did not effect me. Mary Christmas or whatever holiday you wish to celibate, or even none and all. And take your time. Be in a good head space before returning. Please and thank you.

**Comment by ilyabumblebee** [comment]
LOL, bro just abandoned the project due to one stupid Chris Titus video, FINE XD

**Comment by NewsonUpreti** [comment]
@ilyabumblebee  And we are here using it until it works. Almost 2 months without an update for a browser, still rocks.

**Comment by DMW007** [comment]
The owner/main dev said in [this issue](https://github.com/Alex313031/thorium/issues/464#issuecomment-1855133359), that he unforatunately has health problems and for that reasons, he currently can't update the browser. But the project is **not dead**, he wants to take care of an update when he feels better again. We shouldn't rush him and give him time to recover.

**Comment by Alex313031** [comment]
@DMW007 @rubyFeedback @pazza2234 @NewsonUpreti @ilyabumblebee Project is NOT dead. Just rebased for M119! Building releases now.

**Comment by Kamey2024** [comment]
> @DMW007 @rubyFeedback @pazza2234 @NewsonUpreti @ilyabumblebee Project is NOT dead. Just rebased for M119! Building releases now.

Finally, Can't wait to update!

**Comment by pazza2234** [comment]
I am so happy to hear this even If I am late. I will be switching back soon.
