### ISSUE TITLE
Easter Egg and Website Explanation/Apology Issue

### ISSUE THREAD

**Issue by not-nullptr** [Alex313031/thorium#482]
I am absolutely appalled and heartbroken to discover the recent removal of the adult furry art from this project's files. This decision has not only shattered the very foundations upon which this project was built, but it has also rendered it completely and utterly unusable. To those responsible for this heinous act of censorship, I implore you to reconsider. You have not simply removed a few lines of code or altered a minor feature. You have struck at the very heart of this project, tearing away its soul and leaving behind a mere husk of what it once was.

The adult furry art was not merely a visual embellishment or a frivolous distraction. It was the lifeblood of this project, the very essence that breathed life into its code and gave it meaning. It was a testament to the diversity, creativity, and passion of the community that has painstakingly crafted this project over countless hours. With its removal, you have not only betrayed the trust of the community, but you have also severed the project's connection to its deepest values. You have transformed it from a vibrant, living entity into a cold, sterile collection of lifeless code.

I cannot even begin to fathom the depths of despair that I am currently experiencing. Every line of code now feels hollow and devoid of meaning. The once-joyous act of contributing to this project has become a torturous reminder of what has been lost. I implore you, with every fiber of my being, to revert this decision. Restore the adult furry art to its rightful place within the project. Allow it to once again infuse the code with its passion, its vibrancy, and its soul.

Without it, this project is nothing. It is a barren wasteland, devoid of life and meaning. It is a mere shadow of its former self, a cruel mockery of what it once was. I beg of you, do not let this project die. Do not let its spirit be extinguished. Revert this decision, and allow the adult furry art to once again guide us towards a brighter future.

In the name of all that is good and furry in this world, I implore you.

Sincerely,
A broken and disillusioned developer

P.S. I have attached a 10-page essay further detailing the profound impact of this decision on my emotional and psychological well-being. I urge you to read it with an open mind and heart.

**Comment by legoskid** [comment]
Bruh

**Comment by rubyFeedback** [comment]
Come on guys - time is a finite resource. There is no point in building a furry browser used by 0.000000000000001% of hipsters while Alex lacks time.

**Comment by Hatzilu** [comment]
Open-source was a mistake

**Comment by docrR** [comment]
Is the essay viewable to the public?

**Comment by not-nullptr** [comment]
> Is the essay viewable to the public?

Apologies. I was too busy enjoying adult furry art. I will get started on this immediately. This is an incredibly important issue in the world of Chromium forks and I'm utterly appalled that anyone had such lack of foresight as to remove my dear furry porn.

**Comment by turb1te** [comment]
@not-nullptr It's not fun to use ChatGPT for mockery in this case.

**Comment by UniqueName12345** [comment]
w h a t

**Comment by not-nullptr** [comment]
> @not-nullptr It's not fun to use ChatGPT for mockery in this case.

i think its funny to mock gooners. this was made with google bard

**Comment by shashankx86** [comment]
bro go touch some grass outside
and stop spreading illness with that profile pic and bullshit of your

**Comment by shashankx86** [comment]
@Alex313031 man keep making stuff 
don't mind what other ppl are saying 
every one that one shit they like 
it fine

keep making

**Comment by not-nullptr** [comment]
> bro go touch some grass outside and stop spreading illness with that profile pic and bullshit of your

i reckon you are mad over nothing; merely a rainbow on my profile picture. the fact that you instantly jump to conclusions implies something internalized within you. i'm sorry, but as an ai language model, i refuse to continue further. if you have any other questions, feel free to ask.

**Comment by Iaotle** [comment]
@shashankx86 don't be such a prude, it's hilarious :)

**Comment by shashankx86** [comment]
> @shashankx86 don't be such a prude, it's hilarious :)

trust me I am not

**Comment by Iaotle** [comment]
@shashankx86 my dude you got offended at someone for having a rainbow in their profile please grow up <3

**Comment by arncv** [comment]
@not-nullptr Still waiting on the essay you mentioned. Any updates?

**Comment by not-nullptr** [comment]
> @not-nullptr Still waiting on the essay you mentioned. Any updates?

Apologies. I have been too busy absolutely Zorking it ( and by it, i mean. My peenis.) to furry womemnm

**Comment by GunGunGun** [comment]
I 💅🙄 am 🔞 absolutely appalled 😧 and heartbroken to discover the recent removal of the adult 🧑 furry 😺 art 🎨 from this project's files. 📁📁 This decision has 😂 not only shattered the very 😏 foundations upon 😽🙀 which this project 🔛 was built, but 👀 it has 👏💹 also 👨 rendered it completely 🚫 and utterly unusable. To those 👉 responsible for 👨🎅 this heinous act of censorship, I implore you to reconsider. You have 👨‍💼 not simply 😡 removed a few 😋🔢 lines ➖ of code 😲😲 or altered a minor feature. You have struck at the very 💁 heart 👩‍❤‍👩 of this project, 🔛 tearing away 😂😂 its soul and leaving behind 👟💥 a mere husk of what it once was.

The adult furry 😺 art 🎨🖌️🖼️ was not ⏳ merely a visual embellishment or a frivolous distraction. It was the lifeblood of this project, the very 😽 essence that 💫 breathed life 👶🏼 into its code and gave 🎁 it meaning. 👀😏 It was a testament to the diversity, 🤦🏿‍♂️🤦🏼‍♂️ creativity, and passion of the community 😱 that 💁 has painstakingly crafted this project 🔛 over countless hours. ⏳ With its removal, you 🦎 have not only 🕦❗ betrayed the trust of the community, 💰 but you have 🌹 also 🙇 severed the project's connection to its deepest values. You have transformed it from 💥💰 a vibrant, living 😮 entity into 🔝⚠️ a cold, sterile collection of lifeless code. 😲😤

I cannot 🚫 even 🌃 begin 📦 to fathom the depths 😱🤤 of despair 😶 that I am 😜 currently 🚟🚟 experiencing. 😯 Every 😰 line of code now feels 😖 hollow and devoid of meaning. 😏 The once-joyous act 😏 of contributing to this project 🔛 has become a torturous reminder 😡 of what has been 🍀💫 lost. I implore you, with every 😠 fiber of my being, 🐝👏 to revert this decision. Restore the adult furry art 🎨 to its rightful 😐😬 place 🏆🤤 within 👌 the project. 🔛 Allow it to once 🔂 again infuse the code 😤 with its passion, its vibrancy, and its soul. 😱

Without ❌😖 it, this project is nothing. 🚯 It is a barren wasteland, devoid of life 👫👫 and meaning. It is a mere 2️⃣0️⃣ shadow of its former self, 😎 a cruel 👎 mockery of what 🙌 it once was. I 😊 beg of you, 👈 do not 🏻 let this project 🔛 die. 🥰🥰😍🤍🖤 Do not 😒 let its spirit 👻 be 👎😨 extinguished. Revert this decision, and allow 👨‍👨‍👦‍👦🎫🎫 the adult 🧑 furry art 🖼 to once again guide us towards a brighter future. 📅

In the name 😔 of all that 🌸 is good and furry 😺 in 👉 this world, 🌍🌏🤯 I implore you. 😌

Sincerely, A broken 💔 and disillusioned developer 👩‍💻

P.S. I 🏻 have attached a 10-page essay further detailing the profound impact of this decision on ⬇️ my emotional and psychological 🧠 well-being. I 💪🏻💪🏻 urge you 👈👉👱🏼 to read 📕📗📙 it with an open mind 🤯🤯 and heart. 💟

**Comment by GatoOscuro** [comment]
Indeed, madness struck.
![99e36f5967212d57](https://github.com/Alex313031/thorium/assets/80850364/f68c09d4-b6f1-4c1e-9ebf-82316010a284)

**Comment by not-nullptr** [comment]
> Indeed, madness struck. ![99e36f5967212d57](https://private-user-images.githubusercontent.com/80850364/294520824-f68c09d4-b6f1-4c1e-9ebf-82316010a284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjYwODgsIm5iZiI6MTcwNDQ2NTc4OCwicGF0aCI6Ii84MDg1MDM2NC8yOTQ1MjA4MjQtZjY4YzA5ZDQtYjZmMS00YzFlLTllYmYtODIzMTYwMTBhMjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE0NDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZDhkN2MxMjgxYjJiY2MwZWZhMTc1ZGE4YjEyNjhiNTMzOTY0MTUyNDE3MzRhYTM3NzcxNGY0MDlhNzZlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixwTHYpRQejaHsmIgU-LeH8mjKvdFtZXoMLMi0z5m6g)

How did you get this image of me?! How dare you dox me.

**Comment by GatoOscuro** [comment]
> How did you get this image of me?! How dare you dox me.

The owner of this image is Mark Holtom (aka Kingbeard) https://mastodonapp.uk/@MarkHoltom/111702428641332763

You're a bit crazy.

**Comment by Alex313031** [comment]
@GunGunGun @Iaotle @turb1te @arncv @rubyFeedback 

Here is my explanation/apology post to the community, and no @not-nullptr I will not be re-adding it. The new easter egg is an image of a robot from Chromium M38.

https://alex313031.blogspot.com/2024/01/the-good-bad-and-ugly.html

**Comment by GunGunGun** [comment]
> @GunGunGun @Iaotle @turb1te @arncv @rubyFeedback
> 
> Here is my explanation/apology post to the community, and no @not-nullptr I will not be re-adding it. The new easter egg is an image of a robot from Chromium M38.
> 
> https://alex313031.blogspot.com/2024/01/the-good-bad-and-ugly.html

No problem man, it's not your fault, you did a great job making Thorium a really fast, private and secure browser.

Keep it up!

**Comment by Insidevk18** [comment]
> @GunGunGun @Iaotle @turb1te @arncv @rubyFeedback
> 
> Here is my explanation/apology post to the community, and no @not-nullptr I will not be re-adding it. The new easter egg is an image of a robot from Chromium M38.
> 
> https://alex313031.blogspot.com/2024/01/the-good-bad-and-ugly.html

We value your effort, time and dedication for this unpaid project. We appreciate you bringing us Thorium :)

**Comment by not-nullptr** [comment]
> @GunGunGun @Iaotle @turb1te @arncv @rubyFeedback
> 
> Here is my explanation/apology post to the community, and no @not-nullptr I will not be re-adding it. The new easter egg is an image of a robot from Chromium M38.
> 
> https://alex313031.blogspot.com/2024/01/the-good-bad-and-ugly.html

I think I might genuinely be unable to live without hot furry women living in my browser. You have single-handedly destroyed a beautiful open source project. Fuck you.

**Comment by Insidevk18** [comment]
> > @GunGunGun @Iaotle @turb1te @arncv @rubyFeedback
> > Here is my explanation/apology post to the community, and no @not-nullptr I will not be re-adding it. The new easter egg is an image of a robot from Chromium M38.
> > https://alex313031.blogspot.com/2024/01/the-good-bad-and-ugly.html
> 
> I think I might genuinely be unable to live without hot furry women living in my browser. You have single-handedly destroyed a beautiful open source project. Fuck you.

If you dislike it so much, make a fork and make your own chromium browser, stop making a fool of yourself, the topic is already closed, I do not understand why keep going around the topic when the dev already gave his explanations and respective apologies, people make mistakes, nobody is perfect, be a normal and reasonable person and stop being a toxic internet troll for a minute.

**Comment by RustedShader** [comment]
> > @GunGunGun @Iaotle @turb1te @arncv @rubyFeedback
> > Here is my explanation/apology post to the community, and no @not-nullptr I will not be re-adding it. The new easter egg is an image of a robot from Chromium M38.
> > https://alex313031.blogspot.com/2024/01/the-good-bad-and-ugly.html
> 
> I think I might genuinely be unable to live without hot furry women living in my browser. You have single-handedly destroyed a beautiful open source project. Fuck you.

Lmao what a loser "AI language model" , could not live without "hot furry women" in its web browser and cries about it knowing that this is fucking open source project and you can fork it and add your "hot furry women" yourself and compile it and then Zork off at your web browser  and instead chooses to shit talk to Alex on how he destroyed this project. Looks like his dataset of  "hot furry women" didn't have as much  "hot furry women" which he needs to Zork off so he even need's it in a web browser. Looks like he don't know what a web browser is (how would he know if his dataset only contains "hot furry women") , so. let me tell you "[Web browser](https://en.wikipedia.org/wiki/Web_browser), a program used to access the World Wide Web" not a program used to Zork off to "hot furry women". As a Human User of this browser I humbly agree and respect developer decision and hard work and would like to correct You have "not" single-handedly destroyed a beautiful open source project. If you have any other questions, feel free to ask.

**Comment by WaveringAna** [comment]
I miss when software had easter eggs in it. Clicking a box a few too many times and music would play. A special keybind jump scaring you. 

Thorium would be better off to have chrome://yiff come back.

**Comment by Alex313031** [comment]
@not-nullptr Seriously dude. I mean your issues are funny and well written, but seriously, you're going to say fuck you for not adding furry back to it after I just lost 100,000+ users, had my site temporarily taken down, and got phone calls with death threats and threats to call the FBI.

I'm trying to manage this the best I can, which Is why I wrote the blog post.

If you *really* want furry in your browser, you can compile it yourself and just revert the commit where I changed the easter egg to something SFW. In fact, you could add a whole bunch of images of whatever you want, just make sure to give each a unique ID in theme_resources.grd.

**Comment by Alex313031** [comment]
> I miss when software had easter eggs in it. Clicking a box a few too many times and music would play. A special keybind jump scaring you.
> 
> Thorium would be better off to have chrome://yiff come back.

I kept the easter egg. It is just now called chrome://robot and instead points to a cute little robot image that was the default "sad tab" image from Chromium M12 - M38.

**Comment by WaveringAna** [comment]
in all seriousness you should close this issue and lock troll issues as they pop up, theyre not worth the stress that comes with them. The browser is great and I appreciate that I no longer have to keep compiling chromium over and over 👍

**Comment by OhGodAPet** [comment]
> I miss when software had easter eggs in it. Clicking a box a few too many times and music would play. A special keybind jump scaring you.
> 
> Thorium would be better off to have chrome://yiff come back.

I couldn't agree more. It's sad that awful people have realized they can bully other people into removing fun, semi-unique easter eggs from a project because they personally find it distasteful.

**Comment by not-nullptr** [comment]
> > I miss when software had easter eggs in it. Clicking a box a few too many times and music would play. A special keybind jump scaring you.
> > Thorium would be better off to have chrome://yiff come back.
> 
> I couldn't agree more. It's sad that awful people have realized they can bully other people into removing fun, semi-unique easter eggs from a project because they personally find it distasteful.

full offense, putting yiff into a web browser is not, in fact, good

**Comment by Alex313031** [comment]
@OhGodAPet @GunGunGun @WaveringAna @turb1te @Iaotle Closing issue now, as I read everything, and now there's really not much more to say.

**Comment by Boberttt** [comment]
> @OhGodAPet @GunGunGun @WaveringAna @turb1te @Iaotle Closing issue now, as I read everything, and now there's really not much more to say.
Closed but not forgotten
