### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by sbushmanov** [Alex313031/thorium#484]
**System Details**
Ubutnu 22.04
Version 117.0.5938.157 (Official Build) stable, built on Linux (64-bit)

Youtube navigation is unusable. Only keyboard shortcuts.

**Comment by Alex313031** [comment]
@sbushmanov Strange. What is your hardware? And are you using FOSS or proprietary drivers?

Because I am running M117 on 22.04 as my daily OS, and it doesn't have this issue.

**Comment by NewsonUpreti** [comment]
> **System Details** Ubutnu 22.04 Version 117.0.5938.157 (Official Build) stable, built on Linux (64-bit)
> 
> Youtube navigation is unusable. Only keyboard shortcuts.

@Alex313031 I am also using the same LTS . @sbushmanov It might be yours specific issue related to your system.

**Comment by Chaython** [comment]
Are you using any extensions? Lots of adblocks have added additional blocking to youtube that are more cosmetic

**Comment by NewsonUpreti** [comment]
@Chaython Thats true. @sbushmanov I recommend disabling extensions and see it it works, so you find out the cause.
