### ISSUE TITLE
Install Thorium as a system app on windows

### ISSUE THREAD

**Issue by Tarek-Hasan** [Alex313031/thorium#486]
Is there's a way to install Thorium as a system app on windows?
If not, can you add this option, please.

**Comment by Alex313031** [comment]
@Tarek-Hasan You can do exactly that by running the installer from the command line with.

`thorium_mini_installer.exe --system-level`

**Comment by Tarek-Hasan** [comment]
Thanks.
But, a system level installer would have been nice. Or, triggering system level install by running the installer as administrator.

**Comment by Alex313031** [comment]
@Tarek-Hasan Changing the installer means re-linking the main executable, which takes a long time. Making it do it if it is run as administrator poses problems for people with User Account Control turned off (like me), where user processes are run with Administrative levels.
