### ISSUE TITLE
All saved passwords are suddenly gone...

### ISSUE THREAD

**Issue by mezhgano** [Alex313031/thorium#487]
**System Details**
 - OS: Windows 10
 - Thorium Version: 117.0.5938.157 (Official Build) (64-bit)

**Problem**
Just browsing as usual, nothing special, not performing any changes to OS or browser, and for some moment realize that Thorium loose access to any known website and all passwords are just disappear from password manager...

Rebooting PC and restarting Thorium did nothing.

I have 2 profiles and second profile also affected.
I'm using local Thorium account with "Allow Thorium sign-in" option turned off, so i signed to Google account, but not syncing it with Thorium. 

Found "Login Data" files inside User Data folder for both profiles, they sized around 100 kb each, pretty sure it contains all my passwords but somehow Thorium just stop recognized them. 

There is something i can do to restore access to my passwords and how to prevent such pain in future?

**Comment by quadbyte** [comment]
You might want to use a proper password manager, BitWarden is great, open source and runs as an extension.  Saving passwords in the browser is not a great idea security-wise.

**Comment by mezhgano** [comment]
> You might want to use a proper password manager, BitWarden is great, open source and runs as an extension. Saving passwords in the browser is not a great idea security-wise.

Thanks for reply, yeah, of course i am using KeePassDX, i have all my passwords, they doesn't lost completely :) 
But now i forced to manually signing in a lot of websites... 
The point is not how to store passwords, rather: why this is happens with Chrome-based browsers?

**Comment by CodingWithAnxiety** [comment]
KeePassXC has an extension; Isn't KeePassDX an android PM though? Correct me if wrong. 

https://chromewebstore.google.com/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk?pli=1

Can connect KeePassXC to chrome and chromium browsers such as thorium however.
