### ISSUE TITLE
Apps aren't associated with their respective icons

### ISSUE THREAD

**Issue by Draic** [Alex313031/thorium#495]
**System Details**
 - OS: EndevourOS
 - Thorium Version 119.0.6045.214-2

**Problem**
Installing a website as PWA does not associate the .desktop with the apps/websites icon.

**Screenshots**
https://i.imgur.com/idG395v.png

**Additional Notes**
Using the standard chromium from the arch repository installing a PWA will correctly insert the appropriate icon to the .desktop. Thorium saves it with it's generic icon.

**Comment by midzer** [comment]
So, according to linked screenshot, you've installed PWA from YouTube.

I don't want to unblock YouTube, so I cannot try to reproduce this issue on Linux. Any1 else can?

But: I can install PWA from https://feed-dachau.de/ perfectly fine. Appropriate icon is showing on Desktop.

**Comment by gz83** [comment]
I am unable to reproduce this problem.
