### ISSUE TITLE
AVX2 & Personal Build

### ISSUE THREAD

**Issue by dbonner** [Alex313031/thorium#496]
**Add all the stuffz here**
1) 80% of the time I'm using Windows. I need to use Windows for work and I also like gaming, which is possible on Linux, but still a lot easier on Windows.  I work in healthcare.  Although we use computers all the time to record information, my work is not directly related to computers.
- Operating System: Windows 11 23H2 10.0.22631.2861 as of today.
- Hardware: Razer Blade 18 laptop, early 2023 edition.  Intel Core i9-13950HX processor, 64 gigabytes of DDR5 RAM running at 5,200 MHz, NVidia RTX 4090 Laptop GPU (16 GB GDDR6 VRAM).

2) 10% of the time, I like playing around with Linux and I find that running Linux in WSL (under Windows) is the most convenient option. I write Python and build a few programs from source.  I have Ubuntu 23.10 installed in WSL and I added Thorium to my source list so I can use apt to update it.  i.e. I use the same laptop to run Thorium for Linux amd64.
I can run Thorium in a Window using WSL (or technically WSLg), which I think is Wayland and XWayland based.  However, I get better results running graphical apps through an X server, so I'm currently running Thorium through an X server called "x410".  So when I'm downloading or searching for stuff that is Linux related, I use the Linux (.deb) version of Thorium on the same laptop, basically running it in VM (i.e. WSL) while Windows is running.  WSL does a pretty good job at exposing the hardware (the number of threads, the GPU and the processor compiler options) to the user.  e.g. I can use WSL to compile a linux program using all available threads with 100% CPU usage, and thehe Nvidia GPU, including Cuda, is usable from WSL. I had a look at the work Alex put in to compile an optimized Chromium and I'm nowhere near as technically proficient as Alex.

3) 10% of the time, I actually run Thorium on (almost) the equivalent of a Raspberry Pi, that runs under Termux and Proot on my Android Phone.  It's a Samsung Z Fold 5 so I actually get a usable screen when its unfolded.  Thorium for Raspi works perfectly.
All the best !

**Comment by dbonner** [comment]
Thanks @Alex313031 , much appreciated.

**Comment by Alex313031** [comment]
@dbonner OK, so I couldn't use -march=raptorlake because it implies -mavxvnni which causes compilation errors in ffmpeg and libaom. However, I did use the AVX2 files and I can use -mtune=raptorlake. So it essentially will be an AVX2 build except the scheduling and SIMD dispatch will be tuned and optimized for 13th gen intel. I would be interested to see what performance gains it gets.

@ms178 After this, the plan is to compile AVX2 Linux release (which @dbonner you will probably also want for your 10% linux time), and then the Windows on ARM release, and finally the 32 Bit Windows 7 releases (which I screwed up by messing up a single line of code lol)

**Comment by dbonner** [comment]
Sounds good. Happy to benchmark the 13th gen intel tuned Windows build too.

**Comment by Alex313031** [comment]
@dbonner @ms178 Your personal build and the AVX2 Linux build are ready!

I made a new repo called "thorium other" for builds that dont fit into any of the other repo's release sections.

@dbonner Here is your Raptorlake Windows release > https://github.com/Alex313031/Thorium-Other/releases/tag/119.0.6045.214-1

@ms178 Here is your AVX2 Linux release > https://github.com/Alex313031/Thorium-Other/releases/tag/119.0.6045.214

**Comment by dbonner** [comment]
@Alex313031 Thanks so much. They are both working well.

**Comment by Alex313031** [comment]
@dbonner Can you run a speedometer and let me know what the raptorlake scores compared to vanilla thorium-win?

**Comment by ms178** [comment]
@Alex313031 I've benched the AVX2 vs the AVX build with Speedometer on my Haswell-Xeon, the scores are similar on both (around 154 - 156), albeit a little better and with less variance on the AVX2 build.

**Comment by dbonner** [comment]
@Alex313031 Here's the Speedometer 2.1 scores.  These were done on a new profile with all optional extensions removed.  Raptorlake scored the same as Vanilla (approx 425). This probably means that everyone running the AVX2 build gets the benefit of Thorium's speed (which is good). :)

Thorium_RaptorLake M119.0.6045.214:
-------------------------------------------
Summary: 423 +- 14
Detailed Results:
Iteration 1	387.8 runs/min
Iteration 2	407.2 runs/min
Iteration 3	416.1 runs/min
Iteration 4	427.3 runs/min
Iteration 5	416.9 runs/min
Iteration 6	417.9 runs/min
Iteration 7	432.3 runs/min
Iteration 8	432.3 runs/min
Iteration 9	435.5 runs/min
Iteration 10	459.5 runs/min
Arithmetic Mean:423 ± 14 (3.2%)

===================================

Thorium-Win-AVX2 M119.0.6045.214:
-----------------------------------------
Summary: 425 +- 12
Detailed Results:
Iteration 1	390.8 runs/min
Iteration 2	433.3 runs/min
Iteration 3	402.2 runs/min
Iteration 4	430.4 runs/min
Iteration 5	425.1 runs/min
Iteration 6	432.0 runs/min
Iteration 7	443.0 runs/min
Iteration 8	435.7 runs/min
Iteration 9	437.5 runs/min
Iteration 10	418.3 runs/min
Arithmetic Mean:425 ± 12 (2.8%)

**Comment by Alex313031** [comment]
@dbonner Interesting. However, it is tuned for Raptorlake (meaning it takes advantage of the pipeline design and big.LITTLE architecture), so even though it achieved the same score, it is probably using less CPU to do so.
