### ISSUE TITLE
We are happy that Mr Alex is well and we express our solidarity with him in the face of unfair criticism and lies while having an objection because circumcision surgery is useful to fight illness and have good health.

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#497]
Hello, I read the article on Mr Alex's blog and we are happy that Mr Alex @Alex313031  is well and we express our solidarity with him in the face of unfair criticism and lies while having an objection because circus surgery is useful to fight illness and have good health.

It is a religious practice to do circumcision so there is wisdom and it is instinctive things that we must do, if the baby has not given his consent, then the baby has not given his consent. consent to drink one's mother's milk....in addition without circumcision the intimate system is really ugly, circumcision must become obligatory for everyone and science has demonstrated its effectiveness against diseases, if babies died during circumcision, then when doing surgery on the heart, there are also deaths and no one says surgery on the heart should be banned, circumcision must be done by competent people

**Comment by n6ufal** [comment]
Seek help.

**Comment by SectorV5** [comment]
I'm not Circumcised and will never be..
As for the rest, this is a GitHub page for the issues regarding thorium browser not politics, and as such your post has nothing to do here, you're trying to spark rage and drama within the community again, I advise that this issue gets closed.

**Comment by trimechee** [comment]
@SectorV5 You are very rude, ungrateful defamator liar, my post is to express my joy that Mr Alex is doing well after falling ill and to express my solidarity with him in the face of the criticism he faces, I am talking about circumcision for his good and the good of his children and humanity because circumcision is beneficial for health, the objective of my post is to support Mr Alex and get news of him and that he is doing well, did you make a post to thank Mr Alex and him express your support? I made several posts before this post where I expressed my solidarity with him in the face of a YouTube video which criticizes Thorium browser and I was attacked for having defended Mr Alex, did you make such a post of support for Thorium or did you Are you just enjoying the software without making donations or expressing your support to Mr Alex? My posts are the fruit of long research with concrete technical suggestions to improve Thorium and other Mr Alex software, and if Mr Alex no longer talks about circumcision, this controversy which penalizes him will disappear so I talk about it for the good of Mr Alex, ungrateful liar SectorV5 photo of a manga or video game, you attack one of Mr Alex's greatest defenders, you are a traitor, we are waiting for your screenshots of thanks solidarity and your joy as the health of Mr Alex is improving, we wait otherwise I call on Mr Alex to ban heretical hypocrites like you

**Comment by rubyFeedback** [comment]
> My posts are the fruit of long research with concrete technical suggestions

That is clearly not the case here. There is not even a point to insinuate otherwise -
ultimately this is just spamming an issue tracker with non-technical aspects, so
you contribute to your own claims made here negatively.

**Comment by trimechee** [comment]
once again you continue to lie and manipulate people, my account is public and Mr Alex and everyone can see my posts and confirm that I made proposals, technical ideas which were appreciated by Mr Alex and other developers , I am free to make the posts I wish and I wanted to express my solidarity and joy that Mr Alex's health is improving, what is your problem?!! did you make such a post to get news of Mr Alex's health? M the ungrateful one who doesn't hear from Mr Alex and doesn't let others hear from him?!!

I am a believer, so while congratulating Mr Alex that his health is improving and I express my solidarity with him in the face of criticism, I must at the same time express my reservations concerning the refusal of circumcision otherwise my post may be perceived as encouragement to abandon circumcision fundamental element of life and there is day of judgment in the afterlife, you are a spammer troller, do not mention me when I do not mention you, I only speak to Mr Alex,  so mind your own business , I'm going to invoke against you, don't provoke me, go your way, I don't talk to ungrateful trollers

**Comment by trytip** [comment]
remember that time your ah, snap page said ah, FUCK?  would you please not post furry pussies in the future and just be a developer.  do you have nothing better to do?  how old are you?

**Comment by trimechee** [comment]
@trytip Speak with respect and gratitude to Mr Alex, no one is forcing you to use Thorium, you can use chrome, you are free and Mr Alex is free too and he has already responded to these allegations

**Comment by ibay770** [comment]
> I'm not Circumcised and will never be.. As for the rest, this is a GitHub page for the issues regarding thorium browser not politics, and as such your post has nothing to do here, you're trying to spark rage and drama within the community again, I advise that this issue gets closed.
> 
> If you're so religious go use **Pure Browser** It's made for religious freaks like you, and leave this project alone.

I found an app by that name, thanks for posting it! Wish they made a version for PC
