### ISSUE TITLE
Will Chromium's high resource usage be resolved at all?

### ISSUE THREAD

**Issue by MagmaBro123** [Alex313031/thorium#502]
Title.

Pretty much all Chromium-based browsers use a little over 1 gig.

Even Firefox has this issue.

**Comment by gz83** [comment]
This is related to Chromium's multi-threaded architecture and factors such as the number of tabs you currently have open, whether the tabs are awakened, and the type of content currently carried by the tabs.

You can use Chromium's built-in memory saving feature to control memory usage.

@MagmaBro123

**Comment by drimisssss** [comment]
@MagmaBro123 Here some gifts : in chrome flags
smooth scrolling
Auto-disable Accessibility


secret command line to improve speed,  battery , security 

--enable-low-end-device-mode -enable-low-res-tiling

--js-flags=--noexpose_wasm --js-flags=--jitless --disable-webgl --disable-webgl2 --disable-3d-apis --disable-features=WebAssembly,AsmJsToWebAssembly

**Comment by Alex313031** [comment]
@gz83 @MagmaBro123 @drimisssss Yeah, this is just how it is. Firefox is starting to get up there too with resource usage. Plus web pages get larger and larger. It is not uncommon to find websites that download 50Mb of data, and take 250+Mb of memory for the renderer process hosting the tab.

All browsers nowdays except for Palemoon and Internet Explorer use a multi process architecture, with a central, main "host process" that acts as a delegate and supervisor for child processes that It spawns as needed. Usually each child process will host a tab, a GPU context (like a WebGL Canvas surface), or in the case of Chromium, extensions are also sandboxed and get their own process.

Also, this is not reddit, so In case you were thinking about it, please don't turn this into a Chromium versus Firefox flame war. Both browsers have good things and bad things about them. Thats why I maintain forks of both! If you wanna use firefox, maybe try my compiler optimized, and privacy tweaked firefox fork, Mercury > https://github.com/Alex313031/Mercury

**Comment by drimisssss** [comment]
@Alex313031 Great ! Thank you for these advices end Mercury :) 

about multi process architecture, can these flags disable multi process in Thorium ? 

--single-process --process-per-site  --process-per-tab

**Comment by midzer** [comment]
I second previous two answers.

Not Thorium related, so closing for good.

P.S.: Use an ad-blocker to minimize (unnecessary) JavaScript runtimes.
