### ISSUE TITLE
Use the VC-LTL toolchain to optimize software.

### ISSUE THREAD

**Issue by Malus-risus** [Alex313031/thorium#503]
https://github.com/Chuyu-Team/VC-LTL5

The VC-LTL can make your project using the built-in msvcrt.dll in the Windows. It solves the C runtime deployment problem and the fiber local storage (FLS) limitation problem effectively, and greatly reduce the binaries size.

**Comment by Malus-risus** [comment]
@Alex313031

**Comment by gz83** [comment]
This project does not appear to be of any help to Thorium Browser and the development workflow of Thorium Browser does not use these technologies.

@Malus-risus
