### ISSUE TITLE
Need Assistance

### ISSUE THREAD

**Issue by oDecent** [Alex313031/thorium#504]
Web discord refuses to run on thorium. It gives the 'Aww Fuck' (Error code: STATUS_ACCESS_VIOLATION) every single time.
![Capture](https://github.com/Alex313031/thorium/assets/124597964/cf03fa65-7d65-46a3-a18a-b5b65c043be3)
I am running the second latest version of thorium as the latest doesn't have support for win32.
thorium_WIN32_SSE3
win 7 ultimate 32bit

**Comment by Alex313031** [comment]
@oDecent Don't worry, we fixed it, and are building the 32 bit builds as we speak! Also, please file Win7 issues over in the win7 repo, not here.

**Comment by Alex313031** [comment]
@oDecent Here you go > https://github.com/Alex313031/thorium-win7/releases/tag/M119.0.6045.214-1
