### ISSUE TITLE
[Linux] [Improvement] - Faster scroll

### ISSUE THREAD

**Issue by Apogeum12** [Alex313031/Thorium#51]
Patch for faster scroll web content in the browser

**Comment by Alex313031** [comment]
@Apogeum12 Modifying this would affect all platforms, and would make it too fast on Windows and Mac. I understand your frustration. What you can do is install extensions to speed or slow scrolling. I reccomend https://chrome.google.com/webstore/detail/fast-scroll/ecnjcglleblahonnenpaiofkabfakgdi . You can also enable the flag chrome://flags/#smooth-scrolling

**Comment by Apogeum12** [comment]
For now the best extension what I found is: scrollAnywhere
Maybe in future on wayland doesn't that errors with scrolling. For now I must using X11 :( 

https://user-images.githubusercontent.com/35242996/181363673-bfb0f8f6-f4b5-4f8c-bfa0-6fac7952c951.mp4

**Comment by Alex313031** [comment]
@Apogeum12 I made this extension, because Ive gotten multiple things about this on linux, the only OS where it tends to be a problem.
https://chrome.google.com/webstore/detail/thorium-scroll-tweaker/dgnjhkngmbcdbdmpbeechgihgijlajkf
Feel free to try it, and if it is not as good as the above one, or some feature that's missing, don't hesitate to tell me.

**Comment by Apogeum12** [comment]
sure, I will tests it ;)

**Comment by Alex313031** [comment]
@Apogeum12 Hows it goin

**Comment by Apogeum12** [comment]
@Alex313031  Hello.
Unfortunate for now the best working scrollAnywhere, but I think it is caused by click left button of mouse and move like in smartphone. All other's extension like your,  when I scroll too fast then the picture jump. Or they are not smoothly like in above shortly movie.

**Comment by Alex313031** [comment]
@Apogeum12 I will look into improving my extension to make it less "choppy"
