### ISSUE TITLE
strange github bug

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#510]
Hello, I make new issues with my other new account, but i don't see my issues when i use this account !!! @github ?!!! why ? @Alex313031 @gz83  just to check, have you seen my issues made by my other account?

https://github.com/Alex313031/Mercury/issues/101

https://github.com/Alex313031/thorium/issues/506

https://github.com/Alex313031/thorium/issues/507

![image](https://github.com/Alex313031/thorium/assets/76402212/7c3e6a0c-4289-48b5-9e21-ba055410e1f1)

**Comment by gz83** [comment]
It seems that these issues do not exist

**Comment by trimechee** [comment]
@gz83  it's a serious and regrettable bug of @github, it's wasting my time and fortunately I noticed it, my issue exists but only me I can see my 3 issues with my other account :( I'm going to have to copy and paste this that I wrote and open new issues with another account :(


![image](https://github.com/Alex313031/thorium/assets/76402212/94e36ddd-2062-474c-8d63-f5cb1b2869b9)

**Comment by rollsicecream** [comment]
Maybe your account got shadowbanned or something like that?

**Comment by trimechee** [comment]
I use a web browser with a lot of modified flags and added command line and special dns....github sent me an email to my censored account telling me github cannot determine your geographic location and suspects potential hacking... .yet I don't use VPN....disgusted and angry I went to the settings of my new account to delete it and but the delete account button is grayed out and github tells me your account has been reported so I have to contact github support and I have to enable 2-factor authentication, so I gave up....I still have this account to be able to contact the developers and try to post exclusive ideas to improve the software....anyway Thank you @rollsicecream  for caring about my serious problem :)

**Comment by rollsicecream** [comment]
Also, I had this issue before. It was because I used an alias e-mail which is "suspicious" for GitHub.....

**Comment by trimechee** [comment]
Ohh very important information ! Thank you so much Mr @rollsicecream  for your great advise, i will try to change my alias !
