### ISSUE TITLE
Just started using Thorium. Thanks a lot for your hard work!

### ISSUE THREAD

**Issue by kepler2** [Alex313031/thorium#513]
Hello!

First of all, thanks for your hard work!

The browser is snappier than any browser I have used!

I have some questions, mate:

1 - is this browser safe to use (security-wise) - as in browsing, personal stuff etc? I see that it's updated but for the AVX2 version last update is kinda old? (2 weeks ago)

2 - Which version should I install on a modern PC (Ryzen 5800x3d) - SSE3 or AVX2?
Thanks!

**Comment by kepler2** [comment]
> @kepler2 Your Ryzen is capable of both AVX, and AVX2. The latest M119 AVX2 Linux release is here > https://github.com/Alex313031/Thorium-Other/releases/tag/119.0.6045.214

Hello Alex!

Thanks but I'm on Windows. Is there any updated build here?

Thanks!

**Comment by Kamey2024** [comment]
Does thorium work on Windows Vista?

**Comment by TiLopes** [comment]
@kepler2 here are the Windows builds: https://github.com/Alex313031/Thorium-Win-AVX2

**Comment by kepler2** [comment]
@TiLopes 

Thanks but I have found this:

https://github.com/Alex313031/Thorium-Win-AVX2/releases

Isn't this the correct link?

@Alex313031 Is there any way to update to the latest build? This is 2 weeks old :(

Thanks!

**Comment by Alex313031** [comment]
@kepler2 @TiLopes I decided to merge the AVX2 and SSE3 repos into the main Thorium-Win repo, since we are always making these builds now and it makes sense to conglomerate.

Latest M120 releases for SSE3, AVX, and AVX2 can now be found here > https://github.com/Alex313031/Thorium-Win/releases

**Comment by kepler2** [comment]
@Alex313031 
Thanks a lot!
