### ISSUE TITLE
Add thorium to nix pkg

### ISSUE THREAD

**Issue by sachinchaudhary1808** [Alex313031/thorium#518]
**so imma  using nixos and there is no pkg of thorium for nix**

**we can't make more then one pkg request lol they just give a flag of duplicate**

**
![image](https://github.com/Alex313031/thorium/assets/138745629/fb0ce4fb-7d2c-44e6-80f2-2e8916ed2068)
**
plsssss i was using this on fedora, debian, opensuse but can't on nixos, i don't wannna compile.......

**Comment by p7r0x7** [comment]
@sachinchaudhary1808 setting up a thorium-browser package for various package managers is not up to nor the responsibility @Alex313031; please close this.

**Comment by midzer** [comment]
As @p7r0x7 wrote, any1 can maintain a nix pkg.

No need to set more load on main maintainer.
