### ISSUE TITLE
[Linux] [Improvement] - adblocker

### ISSUE THREAD

**Issue by Apogeum12** [Alex313031/Thorium#52]
Build into web browser default some adblocker like in brave. You can use probably https://github.com/brave/adblock-rust because it is open source.

**Comment by Alex313031** [comment]
@Apogeum12 This is a long term goal, especially since they are deprecating manifest v2 (Although thorium will have patches to extend support as long as possible). I won't be adding this super soon, but it is not needed for now, because you can still install ublock origin.
