### ISSUE TITLE
wondering if possible to block ads on thor shell. 

### ISSUE THREAD

**Issue by pennybanks** [Alex313031/thorium#520]
i love how barebones and light the shell browser is. i tend to use it if im lets say gaming or multitasking and just keep it in the back. but i cant seem to be able to stop ads. im not a dev or anything so im somewhat limited in this kind of knowledge. so im sorry if its an easy fix im just dummy. or if even possible. thanks.

**Comment by Alex313031** [comment]
@pennybanks Not really possible, as thorium shell doesn't have extensions support. You could maybe use a network wide ad blocker like Pi Hole. That's what I use. It notably doesn't work on youtube. If that is your goal, then we are out of luck
