### ISSUE TITLE
Netflix not working, always gets error when trying to play something.

### ISSUE THREAD

**Issue by WintechX** [Alex313031/thorium#523]
**System Details**
 - OS: Windows 11 23H2
 - Thorium Version 119.0.6045.214 (Official Build) (64-bit)

*Problem*
Netflix keeps showing the error this title is not available to watch instantly. Please try another title. - 1044

It happens on all movies, shows etc.

Is there any fix or is it just a drm incompatibility?
![Screenshot 2024-01-23 113105](https://github.com/Alex313031/thorium/assets/110907663/ba2311d6-50af-4135-a2f6-fa8fe5dd8da4)

**Comment by Blasg2** [comment]
Netflix doesnt work on thorium, DRM-stuff, some topics explain it in detail. It seem thorium creator will not add support for this. I wish there was a fork that did...

**Comment by Alex313031** [comment]
@Blasg2 @WintechX Adding support means paying widevine.org 1000's of dollars for a VMP signature license. Widevine still works on sites like Hulu and Apple Music. It all depends on whether the site decides to enforce VMP signatures. Netflix used to not to. But now they do. @Blasg2 The only forks that will be able to do that are large forks that get alot of money. Brave is an example. Bromite, Ungoogled, Iridium, and Thorium are examples of browsers that can't. We ain't rich ya know lol and most of those are made by small groups.

**Comment by Blasg2** [comment]
Damn, i didn't knew that. Yeah, thats a lot of money :x

**Comment by TheDanikReal** [comment]
You can try getting the Widevine DRM module from Google Chrome binaries and move them to Thorium (this should work on ungoogled chromium, also i don't use thorium, i use ungoogled chromium, but plugin should work on all chromium based browsers), there's guide on how to do that: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-install-widevine-cdm

**Comment by Alex313031** [comment]
@Blasg2 @TheDanikReal @WintechX I already add signed widevine binaries from google chrome to all the releases, it uses a .sig file. The problem is the browser binary also has to be signed with the private key to generate a .sig file. If you look at mainstream browsers like firefox and chrome, there is a chrome.sig and firefox.sig side by side with the .exe or main binary.

**Comment by anta40** [comment]
Ah, just experienced this issue on MacOS Monterey. Other browsers like Safari, Firefox, Opera work fine.
I guess this is another reason keeping them.
