### ISSUE TITLE
Ultimate solution for the disappearance of manifest v2 for ad blockers : Adhost-adblocker

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#524]
Hello, ad blockers risk becoming weak with the introduction of manifest v3, here is an exceptional revolutionary solution to overcome this: we would like Mr @Alex313031 to analyze the extension and if he finds it good, i think it will be good for Thorium to replace ublock origin with this extension when ublock origin uses manifest v3, thanks!

https://add0n.com/adhost.html

https://github.com/ray-lothian/adhost-adblocker/

"An open-source DNS-based ad-blocker that operates based on host filtering to block ads, malware, phishing hostnames

The "adHost" extension uses hostname matching to block ads on all web pages except those that are whitelisted. In this method, a predefined list of hostnames for known advertisers or analytic providers is being blocked. Since text matching is all that is done to block or allow a hostname, this method is faster and less memory bloat compared to RegExp method that add-ons like uBlock, Adblock, or Adblock Plus use. You can use the options page to whitelist a domain (no resource is blocked in tabs with this hostname) or add more hostnames to the blacklist."

**Comment by People-11** [comment]
Do you mean [ADGuard](adguard.com)?

**Comment by trimechee** [comment]
@People-11 No i speak about new type of adblock extension that use hostname : the extension is called Adhost-adblocker : an ad-blocker extension that uses hostname filtering , and it seems it is more speed and use less cpu that other adblockers , you can talk to Mr @ray-lothian to have more informations about thise awesome great extension
