### ISSUE TITLE
YouTube keeps on making a weird crring sound randomly.

### ISSUE THREAD

**Issue by WintechX** [Alex313031/thorium#527]
**System Details**
 - OS: Windows 11
 - Thorium Version AppData\Local\Discovery\Saved\Config\WindowsClient

**Problem**
On any youtube video, from time to time during the video, a sound will randomly be heard, a crring sound, kinda sounds like it just..bugs out completely and makes that sound.

Anybody else have this issue?

**Comment by rubyFeedback** [comment]
One example I had this was on sandroman's video (he narrates
historic battle, and in one video I had ping-like sounds that were
super-annoying; when I closed the tab it went away. I should say
that I listen to videos mostly, so I don't even know what happens
in the main video; I thought it was an integral part of the video).
