### ISSUE TITLE
Repost "Remove captive portal patch" 

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#528]
Hello, my issue was deleted so i repost the issue that Mr Alex gave its agreement to integrate it into Thorium:

(remove spaces in url adress) : 

https:// github.com/ uazo/cromite/blob/master/ build/patches/Remove-detection-of-captive-portals.patch

"Subject: Remove detection of captive portals

---
 chrome/browser/net/profile_network_context_service.cc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/chrome/browser/net/profile_network_context_service.cc b/chrome/browser/net/profile_network_context_service.cc
--- a/chrome/browser/net/profile_network_context_service.cc
+++ b/chrome/browser/net/profile_network_context_service.cc
@@ -360,7 +360,7 @@ void ProfileNetworkContextService::UpdateAdditionalCertificates() {
 void ProfileNetworkContextService::RegisterProfilePrefs(
     user_prefs::PrefRegistrySyncable* registry) {
   registry->RegisterBooleanPref(embedder_support::kAlternateErrorPagesEnabled,
-                                true);
+                                false);
   registry->RegisterBooleanPref(prefs::kQuicAllowed, true);
   registry->RegisterBooleanPref(prefs::kGloballyScopeHTTPAuthCacheEnabled,
                                 false);
--

**Comment by Alex313031** [comment]
@trimechee Added! > https://github.com/Alex313031/thorium/commit/8beeee7b09ea242a3d8408d7ee565a75a39b1143

**Comment by trimechee** [comment]
Great !! Thank you so much Mr @Alex313031 :) 💯 🥇
