### ISSUE TITLE
ipfs support similar to Brave's builtin abilities.

### ISSUE THREAD

**Issue by federerfanatic** [Alex313031/thorium#529]
Brave browser allows opening up of ipfs links. I believe they are using somekind of extension from elsewhere. Would be nice if thorium could accomodate this.  See https://brave.com/ipfs-support/

**Comment by midzer** [comment]
Thorium core team is rather small right now.

This looks like a bigger feature. If the code is publically available, it is doable ofc someday.

**Comment by federerfanatic** [comment]
No worries.
