### ISSUE TITLE
ubuntu 20.04 hardware video decode is not working.

### ISSUE THREAD

**Issue by chenzaichun** [Alex313031/Thorium#53]
Thorium info: Version 105.0.5183.0 (Official Build) unstable, built on Ubuntu 22.04, running on bullseye/sid (64-bit) 
system info: ubuntu 20.04 x64
CPU: Intel(R) Core(TM) i5-8350U

1. from setting page, hardware acceleration is enabled.

![image](https://user-images.githubusercontent.com/127616/181168978-6efcfd60-c460-4baa-9b0d-e9aab6f61652.png)

2. from chrome://gpu page, hardware video decode is enabled.

![image](https://user-images.githubusercontent.com/127616/181169090-5c87642b-2a70-4dba-bef0-148ea5ede858.png)

3. use enhanced-h264ify only enable h264.

![image](https://user-images.githubusercontent.com/127616/181169172-070b754d-f6f8-4e5c-9d54-377e2bc176c2.png)

4. checked the media info while playing video, FFMpegVideoDecoder used.

![image](https://user-images.githubusercontent.com/127616/181170034-c5c9be04-03f5-46af-ad58-037fbb4c5daf.png)

5. monitored with intel_gpu_top, Video decode always 0.00%

6. confirmed Firefox hardware video decoding is working.

Any suggestions? Thanks in advanced.

**Comment by Alex313031** [comment]
@chenzaichun  Do you have chrome://flags/#ignore-gpu-blocklist and chrome://flags/#enable-gpu-rasterization enabled. What GPU do you have, and are you using X11 or wayland.

**Comment by Apogeum12** [comment]
@chenzaichun 
On intel igpu you must have installed non-free driver, install from official intel page https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html
Also, if you don't have installed, install `va-driver-all` from default ubuntu repository.
It should be work out of the box. Thorium is the first browser based on chromium when the hardware accelerate(ubuntu 20.04 X11) working without combinable with flags for me. On the amd gpu you don't need official driver.

**Comment by chenzaichun** [comment]
> @chenzaichun Do you have chrome://flags/#ignore-gpu-blocklist and chrome://flags/#enable-gpu-rasterization enabled. 
yes, both `ignore-gpu-blocklist` and `enable-gpu-rasterization are enable.

![image](https://user-images.githubusercontent.com/127616/182057748-c84a02d7-1c01-4606-9add-86784780e32e.png)

![image](https://user-images.githubusercontent.com/127616/182057779-e45b4443-91f5-47d3-896d-9be6e1624220.png)

> What GPU do you have, and are you using X11 or wayland.

```
#  sudo lshw -C display
  *-display
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:137 memory:eb000000-ebffffff memory:a0000000-afffffff ioport:f000(size=64) memory:c0000-dffff
``` 

Ubuntu 20.04 with x11.

**Comment by chenzaichun** [comment]
> @chenzaichun On intel igpu you must have installed non-free driver, install from official intel page https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html Also, if you don't have installed, install `va-driver-all` from default ubuntu repository. It should be work out of the box. Thorium is the first browser based on chromium when the hardware accelerate(ubuntu 20.04 X11) working without combinable with flags for me. On the amd gpu you don't need official driver.

Already installed.

```sh
# sudo apt install va-driver-all
Reading package lists... Done
Building dependency tree
Reading state information... Done
va-driver-all is already the newest version (2.7.0-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Still cannot get hardware video decoding working. (Firefox works perfect)

**Comment by Apogeum12** [comment]
@chenzaichun 
What version `intel-media-va-driver-non-free` you have installed?
```sh
$ sudo apt list --installed |grep intel-media-va-driver-non-free

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

intel-media-va-driver-non-free/focal,now 22.4.3+i755~u20.04 amd64 [zainstalowany]

```

**Comment by chenzaichun** [comment]
> @chenzaichun What version `intel-media-va-driver-non-free` you have installed? For me this look like below:
> 
> ```shell
> $ sudo apt list --installed |grep intel-media-va-driver-non-free
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> intel-media-va-driver-non-free/focal,now 22.4.3+i755~u20.04 amd64 [zainstalowany]
> ```

@Apogeum12 Thanks a lot. It's working now after installed `intel-media-va-driver-non-free
`.
