### ISSUE TITLE
[This project] turned to an example of what not to do on the internet

### ISSUE THREAD

**Issue by sycam0r-e** [Alex313031/thorium#530]
"[This project] turned to an example of what not to do on the internet"

https://y.com.sb/watch?v=Q-02fW-n4qg

**Comment by sachinchaudhary1808** [comment]
ok i got it, most of the people knows this, now what's the point ? posting this on issues ?
it's a good project, i know dev has done some bad things, but he apologies for that.... so pls don't post this type things on issues

**Comment by RocGod** [comment]
Everyone might make some mistakes in the life, but @Alex313031 already post a blog and indicate his point and also apologies. We do need to know what to do and not to do.

This is already been almost 1 month and people knew what happened.  Why do you take this up again... I don't understand what's  your point...

**Comment by sachinchaudhary1808** [comment]
Pls Close this...

**Comment by midzer** [comment]
Closing due not related to technical issues.
