### ISSUE TITLE
Download and save image to desktop

### ISSUE THREAD

**Issue by NefierShishmakov** [Alex313031/thorium#531]
**System Details**
 - OS: [Windows 10 22H2]
 - Thorium Version [120.0.6099.235]

**Problem**
When i try to save image to desktop via "save image as" the image doesn't appear on desktop, i have to press f5 to refresh desktop and then it appears. I tried in vanilla chrome, everything is working correctly.

**Comment by midzer** [comment]
AFAIK Thorium doesn't modify code which involves image saves. It should work as in every other Chrom* based browser.

Can some1 on Windows 10 22H2 reproduce this?
