### ISSUE TITLE
Make an installer that downloads the correct version. 

### ISSUE THREAD

**Issue by ibay770** [Alex313031/thorium#534]
Instead of manually combing github for the right version of thorium to install, maybe make an installer that download the right one,  depending on the OS, bitness and CPU type/features.

**Comment by midzer** [comment]
Miserably, Chrome's Auto-Updater code is not open source.

Right now, we don't have the resources to develop such a feature.

**Comment by ibay770** [comment]
Does this require code from chrome? I was thinking more of a script that downloads the builds from github instead if that works. Unless it's more complicated then I think.

**Comment by midzer** [comment]
Another `.exe` for an installer that downloads builds is probably not what most users want.

They want the browser to auto-update itself automagically.

A possibility would be to insert an addiitional link to /releases on GitHub for respective OS right from the Thorium about page.

This would be a temporary solution to check for new releases more easily.

**Comment by OttCS** [comment]
At least for Linux, this would have to be put into each distrobution's official repo (which still doesn't take into account hardware features), or packaging it for Flatpak (which would negate the system-specific optimizations). Not worth it for Linux.
