### ISSUE TITLE
Windows binaries missing

### ISSUE THREAD

**Issue by pleomati** [Alex313031/thorium#537]
Hello ,the last binaries for windows was 117, please release windows binaries. Thanks

**Comment by Alex313031** [comment]
@pleomati WDYM? The M120 binaries are here and in the thorium-win repo.

If you're looking for avx2 releases, see the latest release in that repo, I am conglomerating the windows repos, and so now the SSE3, AVX, and AVX2 releases will all be released in the same normal Thorium-Win repo > https://github.com/Alex313031/Thorium-Win/releases/tag/M120.0.6099.235
