### ISSUE TITLE
A build with all ungoogled chromium patches 

### ISSUE THREAD

**Issue by radiumatic** [Alex313031/thorium#539]
**Is your feature request related to a problem? Please describe.**

Google services are known to be a real privacy nightmare.

**Describe the solution you'd like, including relevant patches or source**

I understand that applying all the patches causes inconvenience for the average user, but it would be absolutely great if you could apply them in a special build, if it doesn't conflict with other modifications. 

**Additional Notes**

**Comment by xanthisafk** [comment]
+1. I also think that if there was an option to turn off Google things in Chrome flags, it would work.

**Comment by OttCS** [comment]
Some of the Features section of the ungoogled chromium (https://github.com/ungoogled-software/ungoogled-chromium?tab=readme-ov-file#feature-overview) repo might be good to enable even for all. Specifically (copied from the Ungoogled chromium repo):

- Disable functionality specific to Google domains (e.g. Google Host Detector, Google URL Tracker, Google Cloud Messaging, Google Hotwording, etc.) This includes disabling [Safe Browsing](https://en.wikipedia.org/wiki/Google_Safe_Browsing). Consult [the FAQ for the rationale](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-is-safe-browsing-disabled).
- Disable automatic formatting of URLs in Omnibox (e.g. stripping http://, hiding certain parameters)
- Disable intranet redirect detector (extraneous DNS requests. This breaks captive portal detection, but captive portals still work.)
- (Iridium Browser feature change) Prevent URLs with the trk: scheme from connecting to the Internet
Also prevents any URLs with the top-level domain qjz9zk (as used in domain substitution) from attempting a connection.

**Comment by gz83** [comment]
We don't plan to do this, plus Thorium already has some patches from ungoogled-chromium
