### ISSUE TITLE
Chocolatey Package Manager for Thorium Windows Updates

### ISSUE THREAD

**Issue by gregzme17** [Alex313031/thorium#542]
**Is your feature request related to a problem? Please describe.**
You have the third-party standalone updater for windows that has broken before.  Packaging everything in Chocolatey makes updates easy.

**Describe the solution you'd like, including relevant patches or source**
https://docs.chocolatey.org/en-us/features/create-packages
Please create a package in chocolatey that will update with each new release.

**Additional Notes**

**Comment by hapnan** [comment]
already added to [chocolatey](https://community.chocolatey.org/packages/thorium)

**Comment by RocGod** [comment]
I think winget and choco both can find Thorium
