### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by MahtoSujeet** [Alex313031/thorium#546]
Is it possible to add Vertical Tabs UI.

Here is a screenshot of Brave Browser with vertical tabs enabled.
![Screenshot from 2024-02-11 00-40-06](https://github.com/Alex313031/thorium/assets/87647921/ec1a5014-6e17-44cd-a8fc-02161e63426d)

**Comment by MahtoSujeet** [comment]
oops! Found duplicate issue.
https://github.com/Alex313031/thorium/issues/141#issue-1665450108

**Comment by zodman** [comment]
same as https://github.com/Alex313031/thorium/issues/419
