### ISSUE TITLE
Restore previously closed tab: Context menu on tab

### ISSUE THREAD

**Issue by Kol9yN** [Alex313031/thorium#549]
Add this feature please, as FireFox have, because its so confusing when you close a tab, but cant roll it back! :(

**Comment by XP1** [comment]
Right click on new tab button or title bar.

![Reopen closed tab](https://github.com/Alex313031/thorium/assets/776585/36121bfb-0c3f-4f70-9b35-4e1957ff83c7)

**Comment by Kol9yN** [comment]
![not exists restore tab](https://github.com/Alex313031/thorium/assets/10098740/a21d3993-73d2-43a4-9671-8a6fc090726f)

**Comment by XP1** [comment]
I have added the reopen menu item:

![Reopen closed tab feature](https://github.com/Alex313031/thorium/assets/776585/21e3b190-90dd-4500-a2f7-888414568282)

See my commit "Add feature: Reopen closed tab/window in tab context menu.":
https://github.com/XP1/thorium/commit/3b070e187c14118f949c036651b12c461840f18b

@Alex313031 @gz83, review and pull request?

**Comment by gz83** [comment]
> I have added the reopen menu item:
> 
> ![Reopen closed tab feature](https://private-user-images.githubusercontent.com/776585/304764511-21e3b190-90dd-4500-a2f7-888414568282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjI4MDIsIm5iZiI6MTcwNzkyMjUwMiwicGF0aCI6Ii83NzY1ODUvMzA0NzY0NTExLTIxZTNiMTkwLTkwZGQtNDUwMC1hMmY3LTg4ODQxNDU2ODI4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxNDU1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjQ1MjAyZGM1YTI3MTNlZDIxYWQ5ZTk0ZjE5OTNiNGZlZDIwMDIxYjI5MDU0MTY1YWZkNmU4MDUyMDUwNDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._jakkE-RfkE5-Iwb5mrzxWdjUBGlZaB4Qmjs1BASyXs)
> 
> See my commit "Add feature: Reopen closed tab/window in tab context menu.": [XP1@3b070e1](https://github.com/XP1/thorium/commit/3b070e187c14118f949c036651b12c461840f18b)
> 
> @Alex313031 @gz83, review and pull request?

Thank you for your work. At first glance, there seems to be no problem. After you add this option to the context menu, will the entire tabstrip and related context menus function normally?

Also, this feature can actually be achieved using the method described in your previous comment. I think this may be a duplicate, but I will leave it to Alex to make the final decision.

Finally, can you submit your PR to the Thorium repo?

@XP1 @Alex313031

**Comment by XP1** [comment]
Other menu items should function normally. I didn't delete any code. I only added the code for the reopen menu item.

Feature should make the reopen tab more accessible (also implemented in Firefox, Opera, Vivaldi, Brave). Users tend to right click on a tab rather than the button or title bar.

PR: https://github.com/Alex313031/thorium/pull/558

**Comment by gz83** [comment]
> Other menu items should function normally. I didn't delete any code. I only added the code for the reopen menu item.
> 
> Feature should make the reopen tab more accessible (also implemented in Firefox, Opera, Vivaldi, Brave). Users tend to right click on a tab rather than the button or title bar.
> 
> PR: #558

Tabstrip is the main and commonly used interactive component. Any type of modification may cause exceptions. Please make sure to combine it with Thorium's code and conduct sufficient testing (you need to compile Thorium browser yourself) to avoid unnecessary trouble.

@XP1
