### ISSUE TITLE
[Linux] Question - Thorium shell

### ISSUE THREAD

**Issue by Apogeum12** [Alex313031/Thorium#55]
What is Thorium shell?
Is possible to delete it? In system applications I don't see it.

![photo_th](https://user-images.githubusercontent.com/35242996/181713006-d8c07d86-19da-402f-8cf3-959e06efbb40.jpg)

**Comment by Alex313031** [comment]
It is a minimal browser shell, useful for web dev/testing, or if you want a single minimal browser instance to run over the top of something, for example to watch a youtube video while gaming and having it just sit there in a little window in the corner. It is possible to delete it, but it will require some command line stuff. It doesn't take up much space, but if you just want the icon gone, you can delete the .desktop file for it.
`sudo rm -rfv /usr/share/applications/thorium-shell.desktop`

Although I recommend you try it before you decide to remove it lol.
If you really want to totally remove it, I can guide you on that.

**Comment by Apogeum12** [comment]
@Alex313031 
Is it possible to run like app mode with this?
For example youtube by thorium shell in app mode, or any others app by use only url for example from web or localy on the own server using url for frontend.

**Comment by Alex313031** [comment]
@Apogeum12 Yes, simply append the full path or filename.
For example I can open thorium.rocks like

`thorium-shell https://thorium.rocks/`

or locally like

`thorium-shell /home/alex/git/Alex313031.github.io/index.html`

This is one of the strengths of thorium shell, its great for development or opening a single page in a small window. It will also show any page errors on the command line, unlike thorium. You can also inspect with right click > inspect. Only thing that isn't working is I would like to add a full right click context menu like thorium. Copy/paste still works, you just gotta use Ctrl + C for example.

You can also write/run web tests, including ones straight from the chromium project, or ones that you have written yourself for i.e. chromedriver (which is also included with the thorium installation in `/usr/bin/chromedriver`.  See > https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/testing/web_tests_in_content_shell.md#run-web-tests-directly-with-content-shell
