### ISSUE TITLE
Is there any way to get an Arm64 Release for Linux?

### ISSUE THREAD

**Issue by ironyee** [Alex313031/Thorium#56]
Hello.

Is there any way to get an Arm64 Release for Linux?
It will be great on AWS Arm64 linux.

**Comment by Alex313031** [comment]
I already do, although it has been compiled for raspberry pi, so it wont work on anything older than armv8.1 with NEON instructions, which shouldn't be of concern for AWS or any modern arm based board. They are in thorium-special > https://github.com/Alex313031/Thorium-Special/releases/tag/M105.0.5174.0
