### ISSUE TITLE
Did your certificate expire?

### ISSUE THREAD

**Issue by Templayer** [Alex313031/thorium#560]
**System Details**
Linux Mint

**Problem**
dl.thorium.rocks doesn't seem to have a proper certificate at the moment.
Synaptic dies with "Connection refused". HTTPS fails, only HTTP is available.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/11728067/85b53f72-17ec-4d37-bb4b-f3e5af5013a0)
![image](https://github.com/Alex313031/thorium/assets/11728067/fbdc5a5e-3da8-4b45-bfe3-774e7bd62385)

**Comment by midzer** [comment]
@Templayer Please re-download `thorium.list` 

```
sudo rm -fv /etc/apt/sources.list.d/thorium.list && \
sudo wget --no-hsts -P /etc/apt/sources.list.d/ \
http://dl.thorium.rocks/debian/dists/stable/thorium.list && \
sudo apt update

sudo apt install thorium-browser
```
