### ISSUE TITLE
Thorium freezes when I try to edit a bookmark

### ISSUE THREAD

**Issue by LinuxOpa** [Alex313031/thorium#565]
**System Details**
 - OS: Ubuntu 22.04.04
 - Thorium Version M121.0.6167.204

**Problem**
When I try to edit a bookmark, the thorium window shakes and thorium freezes. only a pkill -f thorium can end thorium. 

**Screenshots**

see little Video:
https://github.com/Alex313031/thorium/assets/41851582/ef6c8116-12c0-42ec-83b0-1b339695734b

**Additional Notes**

The same effect is also in Google Chrome!

**Comment by LinuxOpa** [comment]
Tested:
With M120.0.6099.235 there's no Problem with editing a bookmark.

**Comment by gz83** [comment]
If chrome also has this problem, it might be a bug from upstream

@LinuxOpa

**Comment by LinuxOpa** [comment]
see here:
https://issues.chromium.org/issues/325307460

**Comment by Alex313031** [comment]
@LinuxOpa So it's an upstream thing.

**Comment by LinuxOpa** [comment]
Fixed in Google Chrome and Chromium, when in Thorium?

**Comment by gz83** [comment]
From the problem report link you provided, I don't see any patch links related to this issue, so I'm not sure on which branch they fixed this issue, maybe the M122 version, maybe the TOT version.
