### ISSUE TITLE
Virtual background doesn't work on Google Meet

### ISSUE THREAD

**Issue by matheorism** [Alex313031/thorium#566]
**System Details**
 - OS: Ubuntu 22.04.4
 - Thorium Version 120.0.6099.235 
 - Kernel: 6.5.0-18-generic

**Problem**
Whenever I use a virtual background, the masking is visible. I have tested it on Google Chrome, and it works perfectly fine.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/58302519/bec6e3af-9e00-4a5c-8047-3c0cdb8b2f4c)

**Additional Notes**
N/A

**Comment by MarceloEmmerich** [comment]
Same here. Arch linux with latest gnome under wayland. Also google maps is broken:

![image](https://github.com/Alex313031/thorium/assets/177960/170699ca-3968-48ef-b645-c5892fed2116)
