### ISSUE TITLE
Thorium crashes on trying anythin related to user profiles.

### ISSUE THREAD

**Issue by winpower21** [Alex313031/thorium#572]
**System Details**
 - OS: Linux Mint 21.2
 - Thorium Version : 121.0.6167.204

**Issue**
Thorium crashes on trying to do anything related to user profiles. Trying to create a new profile or managing existing profiles leads to the browser crashing.

It gives the following error on crash:
`[59783:59783:0222/165930.227546:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[0222/165945.932599:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0222/165945.932895:ERROR:elf_dynamic_array_reader.h(64)] tag not found
`
**Note**
The previous version, i.e., version 120.0.6099.235, does not have this issue.

**Comment by catbabylon** [comment]
Getting same issue here

**Comment by gz83** [comment]
This crash is a known bug and is a duplicate issue. This crash will be fixed in the next version.
