### ISSUE TITLE
Crashing when adding a new profile

### ISSUE THREAD

**Issue by RIRafi** [Alex313031/thorium#575]
**System Details**
 - OS: Ubuntu 23.10
 - Thorium Version: 121.0.6167.204

**Problem**
When I try to add a new google account using the add button on the profile menu located in the top right corner, thorium immediately crashes.

**Screenshots**
here is a little recording:-
[Screencast from 2024-02-25 08-08-23.webm](https://github.com/Alex313031/thorium/assets/83538321/6bc16f12-8e24-4c0d-b832-47d368a0ad12)

**Additional Notes**
The issue also happens if I click the gear icon beside Other profiles

**Comment by gz83** [comment]
This is a known bug and this issue is a duplicate

**Comment by Alex313031** [comment]
@gz83 @RIRafi Fixed in latest M122 version.
