### ISSUE TITLE
Thorium not remember my wallpaper/Wallpaper bug

### ISSUE THREAD

**Issue by hugthecats87871** [Alex313031/thorium#580]
**System Details**
 - OS: [Windows 10]
 - Thorium Version [Lastest, M121.0.6167.204]

**Problem**
So, i try to change my wallpaper but after open the new tab the wallpaper just show the white blank picture.. I hope you fix this soon, and sorry for my bad english

Edit : Doesn't fix when i reinstall it

![Screenshot (233)](https://github.com/Alex313031/thorium/assets/155767365/de841767-0074-4abb-be15-3fbe53764976)
This is when i set the wallpaper
![Screenshot (232)](https://github.com/Alex313031/thorium/assets/155767365/7226bd21-c164-4bba-ac7a-e78a8129bba4)
This is the new tab

**Comment by gz83** [comment]
Does this issue exist on the M121 version of Chrome/Chromium?

**Comment by hugthecats87871** [comment]
> Does this issue exist on the M121 version of Chrome/Chromium?

Uh... yep.

**Comment by gz83** [comment]
If Chrome/Chromium also has this problem, it is more likely related to some bugs in the upstream.

It may also be related to your network environment, installed browser extensions, user data, etc. It is recommended that you check one by one.

**Comment by hugthecats87871** [comment]
> If Chrome/Chromium also has this problem, it is more likely related to some bugs in the upstream.
> 
> It may also be related to your network environment, installed browser extensions, user data, etc. It is recommended that you check one by one.

Yeah, using Chrome also like this, maybe some bugs.

![Screenshot (236)](https://github.com/Alex313031/thorium/assets/155767365/6e6ad579-eea7-490b-934c-275df3fb203d)
![Screenshot (239)](https://github.com/Alex313031/thorium/assets/155767365/dd200c3a-b63d-49d7-9c27-b26336f4ef33)
