### ISSUE TITLE
[How to fix] Thorium customized background doesn't saved

### ISSUE THREAD

**Issue by hugthecats87871** [Alex313031/thorium#584]
**System Details**
 - OS: [Windows 10]
 - Thorium Version [lastest]

**Problem**
The Thorium background doesnt save after launching the new tab like my previous problem
Changing to original Chrome doesn't solve the problem
[https://github.com/Alex313031/thorium/issues/580](url)

Anddd thank god! I know how to fix it!

**How to fix**
1. Go to Thorium/Chrome Flag 
[chrome://flags/](url)
2. Disable [#customize-chrome-side-panel] and [#customize-chrome-side-panel-extensions-card]
![Screenshot (251)](https://github.com/Alex313031/thorium/assets/155767365/847e9a26-3ee6-48e0-bf83-939040e079dd)

3. Save it

Then your new tab should using the your custom background
![Screenshot (252)](https://github.com/Alex313031/thorium/assets/155767365/273977c0-e2a8-4fee-a9d1-8c4a0cf2f0cc)

I dunno why this is happen but hey i hope you have a nice day!

**Comment by gz83** [comment]
This question is doubtful and is a duplicate. Close it
