### ISSUE TITLE
Thorium Browser doesn't open M121.0.6167.204

### ISSUE THREAD

**Issue by matheorism** [Alex313031/thorium#586]
**System Details**
 - OS: Ubuntu 22.04.4 and Linux Mint 21.3
 - Kernel 6.5.0-21-generic
 - Thorium Version M121.0.6167.204

**Problem**
I've upgraded my Thorium browser to the latest version but it doesn't open on my machine so I had to downgrade to the previous release.

**Screenshots**
N/A

**Additional Notes**
N/A

**Comment by Nickeron-dev** [comment]
This issue is probably related to #564. 
In my case, on the Arch machine, it did not start either. But the segmentation fault was shown when I opened it from the terminal.

**Comment by Alex313031** [comment]
@matheorism @Nickeron-dev Fixed in latest M122 version.

**Comment by matheorism** [comment]
Thanks @Alex313031 , it works fine now!
