### ISSUE TITLE
Can't create a new profile

### ISSUE THREAD

**Issue by laam-la4m** [Alex313031/thorium#596]
After install Thorium and login my Google accout, I can't add more profile.
I was try restart my laptop but nothing change.
When I click to add profile, Thorium will shutdown immediately.

**Comment by sohanglal** [comment]
Facing the same issue on `M121.0.6167.204 - 56th Release`

**Comment by Alex313031** [comment]
@sohanglal @laam-la4m Fixed in latest M122 version.
