### ISSUE TITLE
Taskbar Shortcurt isn't working after update from 120.0.6099.235 to 121.0.6167.204 

### ISSUE THREAD

**Issue by rorar** [Alex313031/thorium#599]
**System Details**
 - OS: [11]
 - Thorium Version [121.0.6167.204 ]

**Problem**
After a software update from 120.0.6099.235 to 121.0.6167.204  the taskbar icon shortcut isn't executable anymore. (no flags applied to the shortcut)
Running the shortcut it with the `--profile-directory="Default"` flag works just fine.

**Comment by Alex313031** [comment]
@rorar Fixed in latest M122 version.
