### ISSUE TITLE
Invalid 'Date' entry warning when updating sources on Ubuntu

### ISSUE THREAD

**Issue by OliverKreitmeyer** [Alex313031/thorium#608]
**System Details**
 - OS: Ubuntu 22.04.4 LTS
 - Thorium Version 121.0.6167.204 (Official Build) stable, built on Linux (64-bit)

**Problem**
When using the command `sudo apt update` in my terminal, I get the following warning after updating all the sources: `W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/dl.thorium.rocks_debian_dists_stable_Release`.

**Additional Notes**
I have looked online for some answers and came upon this post on StackExchange https://serverfault.com/questions/834808/when-updating-on-ubuntu-i-get-invalid-date-entry-in-release which might be helpful. Everything seemingly works fine even with this error so it is nothing urgent, but it would be a better experience if this weren't to show up every time I go to update my sources.

**Comment by midzer** [comment]
Thanks for filing @OliverKreitmeyer 

I've edited the Date entry to fix it. Please try again :)

**Comment by OliverKreitmeyer** [comment]
Fixed, after updating and upgrading there is no longer any warnings and it all goes smoothly. Thank you for solving this so quickly!
