### ISSUE TITLE
Unexpired flags?

### ISSUE THREAD

**Issue by daijro** [Alex313031/thorium#617]
**System Details**
 - OS: Windows 11
 - Thorium Version: 122.0.6261.132

**Problem**
How can I enable expired flags? The "Unexpire Flags By Default" patch was added from Ungoogled Chromium, [as listed here](https://github.com/Alex313031/thorium/blob/cfea19496156abbcb6a985909f6a91a63551e692/infra/PATCHES.md?plain=1#L154), but I am unable to find the same expired flags as I can on Ungoogled Chromium, for example, the "Elastic Overscroll" flag that expired in M99:

**Screenshots**

![image](https://github.com/Alex313031/thorium/assets/72637910/bf215957-f412-47f2-9b01-22cf07cc46a9)

**Additional Notes**

**Comment by sudosign** [comment]
i forget but isn't there some flags that also unexpire other flags

**Comment by sudosign** [comment]
chrome://flags/#temporary-unexpire-flags-m120
chrome://flags/#temporary-unexpire-flags-m121

maybe this?

**Comment by daijro** [comment]
Chromium by default allows you to reenable the flags expired by the last 2 versions, but Ungoogled Chromium's patch reenables all expired flags. I can't seem to find this functionality in Thorium.

**Comment by Alex313031** [comment]
@daijro This is normal for Thorium. Alot of those flags don't even work anymore, that why normally only the last 2 versions flags are enabled again.

**Comment by Alex313031** [comment]
@daijro I can confirm I am using the ungoogled patch, and I have applied the patch correctly.
