### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#62]
Hello, here some suggestions of features which can make our favorite browser Thorium Browser even more faster and more efficient, maybe it will be a good idea to add options in the settings to activate/deactivate them quickly with one click, I ask this because I tried to activate some of these flags but it doesn't work :(

secret flag apparently not documented reserved to chrome os:

--enable-native-gpu-memory-buffers

disable complete prefetch to save data date battery:

Back forward cache

Closed Tab Cache

Persistent client hints

option to enable low mode for weak notebook

  --enable-low-end-device-mode

increase buffer or media source extension (MSE):

--mse-video-buffer-size-limit-mb=300 --mse-audio-buffer-size-limit-mb=300

increase cache size beyond limit 1.8Gb

--disk-cache-size=5147483647

increase media cache beyond limit 1.8Gb

--media-cache-size=3147483647

disable completely disk cache and memory cache because the flag

--disk-cache-size=0

do not work !

Thanks a lot !

**Comment by Alex313031** [comment]
@trimechee --enable-native-gpu-memory-buffers is available for all OSes. I will make a chrome://flag to turn this on/off in the UI

Back forward cache is enabled by default as of M108.

Closed tab cache is probably not something you want.

Low end device mode should only be used on chromeos with less than 4GB RAM

Disk cache should not be messed with.

The media cache flags, I do not have experience with. You can experiment with them and see what works for you.

**Comment by trimechee** [comment]
I have made many many experiments with media cache , nothing change, but with palemoon browser, i can full buffer full video in sibnet streaming platform ans uqload platform and many others streaming platform,  but in chromium browsers, only little amount of video is buffered, in this site voiranime, the first player "mytv", there a litte mount of buffer video, but in the second player "moon", i can buffer many minutes of video, i think video platforms decide how much mount of video will be buffered  : 


https://v3.voiranime.com/anime/dragon-ball-z-vf/dragon-ball-z-139-vf/

https://video.sibnet.ru/video5128213-Dead_Mount_Death_Play_01_VF/?utm_source=player&utm_medium=video&utm_campaign=EMBED
