### ISSUE TITLE
How do I install Thorium on Windows with SSE3?

### ISSUE THREAD

**Issue by marino2-2** [Alex313031/thorium#622]
Sorry if this is a noob question, but I just can't figure out where the SSE3 .exe releases are for Windows. Is there something else that has happened that I haven't seen like a new way to install it on Windows or...?

Thanks.

**Comment by Alex313031** [comment]
@marino2-2 They are here (along with AVX and AVX2 builds) > https://github.com/Alex313031/Thorium-Win/releases
