### ISSUE TITLE
twitch and udemy players are not working. 

### ISSUE THREAD

**Issue by goatedpenguin** [Alex313031/thorium#630]
**System Details**
 - OS: Windows
 - 120.0.6099.235

**Problem**
Twitch used to play streams fine until a few days ago it stopped working and the Udemy player has never worked since installation. For some reason the twitch players works fine in incognito... 

**Screenshots**
N/A 

**Additional Notes**
Just a black screen on the twitch player I can see chat and everything else etc. A black screen on the udemy player too.

**Comment by etil2jz** [comment]
`120.0.6099.235` outdated build, did you try a more recent one?

**Comment by goatedpenguin** [comment]
Seems to work fine now on my current build strange... How do I update my build?

**Comment by etil2jz** [comment]
https://github.com/Alex313031/Thorium-Win/releases

Be sure to download the build corresponding to your CPU instructions set (AVX2, AVX, SSE…)
With a modern CPU, you most likely have AVX2.

**Comment by goatedpenguin** [comment]
So do I need to uninstall my current thorium browser?

**Comment by etil2jz** [comment]
Executing the new installer is enough

**Comment by goatedpenguin** [comment]
Alright thanks man have a good one :)
