### ISSUE TITLE
Disable directwrite

### ISSUE THREAD

**Issue by SnowSquire** [Alex313031/thorium#632]
**Is your feature request related to a problem? Please describe.**
Since chromium 51, the font api used is DirectWrite instead of GDI. This is a problem because while GDIs rendering engine can be replaced, DirectWrite's cannot. The DirectWrite rendering engine is worse than alternative engines such as [MacType](https://github.com/snowie2000/mactype/. Which allow for proper subpixel rendering on nonstandard pixel layouts like those QD-OLED panels.

**Describe the solution you'd like, including relevant patches or source**
https://github.com/snowie2000/mactype/wiki/Google-Chrome
Apparently CentBrowser has a flag to disable directwrite.

**Additional Notes**

**Comment by Alex313031** [comment]
@SnowSquire The version for Windows XP - 8.1 has the option for GDI > https://github.com/Alex313031/thorium-legacy

**Comment by SnowSquire** [comment]
> @SnowSquire The version for Windows XP - 8.1 has the option for GDI > https://github.com/Alex313031/thorium-legacy

Oh cool, is there any downside to using the legacy version on windows 11?

**Comment by Alex313031** [comment]
@SnowSquire No. You could use the builds for Windows 7+. The XP/Vista builds do have a performance penalty when trying to run them on modern Windows. But they all have the flag to disable directwrite.
