### ISSUE TITLE
Disable Search Suggestions

### ISSUE THREAD

**Issue by jonrielle** [Alex313031/thorium#635]
Still cant find an option to disable search suggestion as when searching it always saves it then when adding a tab it says what my previous search is

maybe add an setting for not saving searches?

**Comment by Alex313031** [comment]
@jonrielle Chromium already has an option for this.

Go to `chrome://settings/syncSetup` and then disable the "Improve search suggestions" option.

**Comment by jonrielle** [comment]
weird, it still records what i previously searched even if the option is "off"
