### ISSUE TITLE
Add flag to turn off download warning when Safe Browsing is off

### ISSUE THREAD

**Issue by People-11** [Alex313031/thorium#636]
**System Details**
 - OS: Windows 11
 - Thorium Version 122.0.6261.132

**Problem**
If the Safe Browsing is fully off, Thorium will block downloads and says 'Thorium blocked this download because you turned Safe Browsing off and the file can't be verified'

**Screenshots**
<img width="251" alt="Snipaste_2024-04-18_20-19-33" src="https://github.com/Alex313031/thorium/assets/41558215/53914756-4e13-44b2-be32-bb0218847e50">
<img width="890" alt="Snipaste_2024-04-18_20-20-01" src="https://github.com/Alex313031/thorium/assets/41558215/e5de08c1-d569-4c93-b9d9-22782da692cb">

**Additional Notes**
Maybe add a flag to turn of thid warning?

**Comment by gz83** [comment]
Try turning on Allow Insecure Downloads in chrome://flags and see if you can download the files you need.

**Comment by People-11** [comment]
> Try turning on Allow Insecure Downloads in chrome://flags and see if you can download the files you need.

not working, this setting is for mixed origin/cross origin content, not for "Google think it's unsafe" files.
