### ISSUE TITLE
Revert Chrome Refresh 2023 or keep it avoidable

### ISSUE THREAD

**Issue by highbaser** [Alex313031/thorium#644]
This is a **feature request** about handling **Chrome Refresh 2023** in the future.

Google started to introduce a UI refresh, starting from M115. The change is called "Chrome Refresh 2023". There are many bug reports, UX issues and negative feedback about this change and Google seems to be stubborn enough not to pay attention and force it upon all of its users, like they did with DirectWrite, however this change has already received even more negative feedback. With M125 release, Google is expiring (and later removing) the flags that can disalbe the changes of Chrome Refresh 2023.

Chrome Refresh 2023 is already in latest Thorium (now: 122.0.6261.132) as it's based on M122 but the feature is turned off by default via flags. From a desktop user point of view it's an anti-feature that ruins the classic desktop experience (with mouse and keyboard), wastes vertical real estate, replaces icons to colorless unrecognizable ones. These changes are even visually incompatible with a conventional desktop.

My suggestions are the following, whichever is easier to implement.
- Completely remove Chrome Refresh 2023 and keep the old looks.
I don't think any desktop user would miss a change that makes their browser look like a dumb tablet.
- Keep flags related to Chrome Refresh 2023 so Thorium users can turn them on/off.
- Introduce a configuration option under **Settings > Appearance** to turn on/off the whole (or parts of this) UI change.

**Chrome Refresh 2023 flags**

- `#chrome-refresh-2023` Chrome Refresh 2023
- `#chrome-refresh-2023-ntb` Chrome Refresh 2023 New Tab Button
- `#chrome-refresh-2023-top-chrome-font` Chrome Refresh 2023 Top Chrome Font Style
- `#chrome-webui-refresh-2023` Chrome WebUI Refresh 2023
- `#customize-chrome-side-panel` Customize Chrome Side Panel
This may not be necessary. It's about a bug that if you don't turn this flag to Disabled, Chrome Refresh 2023 flags are all ignored. See: https://issues.chromium.org/issues/330756862

**Issues**

Issues related to Chrome Refresh 2023, from the Chromium Bug Tracker.

- https://issues.chromium.org/issues/335553327
- https://issues.chromium.org/issues/332574933
- https://issues.chromium.org/issues/332081796
- https://issues.chromium.org/issues/330842283
- https://issues.chromium.org/issues/330743875
- https://issues.chromium.org/issues/330753883
- https://issues.chromium.org/issues/330589210
- https://issues.chromium.org/issues/330443177
- https://issues.chromium.org/issues/330373923
- https://issues.chromium.org/issues/329953462
- https://issues.chromium.org/issues/327022941
- https://issues.chromium.org/issues/41490387
- https://issues.chromium.org/issues/40947720

**Negative user feedback**

Negative feedback from mostly advanced users who suffered a UX degradation because of Chrome Refresh 2023.

- https://support.google.com/chrome/thread/269780757
- https://support.google.com/chrome/thread/269812926
- https://support.google.com/chrome/thread/269774466
- https://support.google.com/chrome/thread/269868881
- https://support.google.com/chrome/thread/269982965
- https://support.google.com/chrome/thread/269956094
- https://support.google.com/chrome/thread/269946774
- https://support.google.com/chrome/thread/269800018
- https://www.reddit.com/r/chrome/comments/1c5jgmu/icons_in_chrome_tabs_are_misplaced/
- https://www.reddit.com/r/chrome/comments/1c695ef/how_to_get_tab_favicons_back_to_normal/
- https://www.reddit.com/r/chrome/comments/1c5zvnx/disabled_chrome_refresh_2023_and_customize_chrome/
- https://www.reddit.com/r/chrome/comments/1c5xeja/broken_icon_placements_after_update_how_to_fix/
- https://www.reddit.com/r/chrome/comments/1c6ette/why_are_my_tab_icons_higher_up_than_normal/

**Comment by Alex313031** [comment]
@highbaser Already did it!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Alex313031/thorium/issues/644#issuecomment-2073935659

@Alex313031, how did you do it? I ask because, per https://github.com/electron/electron/issues/42262#issuecomment-2544981851, I presume you had to diverge from upstream Chromium?

**Comment by Alex313031** [comment]
@RokeJulianLockhart Yes, and in fact I noticed the annoying menus and other CR23 bullcrap that has made its way into Electron. Fixing it would be very easy. Especially the menus. Just four files, a couple of lines. 

And well, there is a large patch called Thorium-2024.patch in the //other dir of this repo that restores alot of the pre-cr23 UI.
