### ISSUE TITLE
What should I do to install Thorium on my Windows 11?

### ISSUE THREAD

**Issue by MuerteRoja** [Alex313031/thorium#650]
Hello, good morning, I noticed that they have uploaded a new Thorium update, I have extracted the folder with the .zip extension with both the Winrar program and 7zip and, however, in the extracted folder I do not see any .exe file, so, What should I do if I want to continue using Thorium in Windows 11?

**Comment by gz83** [comment]
We have already prepared the mini_installer and portable version compressed packages, you do not need to unzip the browser files again.

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Win/releases/tag/M123.0.6312.133
