### ISSUE TITLE
`chrome://flags/#disable-thorium-icons` - not all icons are grey

### ISSUE THREAD

**Issue by turb1te** [Alex313031/thorium#651]
**System Details**
 - OS: Windows 11]
 - Thorium Version 123.0.6312.133

**Problem**
Not all icons are gray as I expect from this flag.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/44940748/dfdc4e4f-d533-4e37-b5ce-de0b7dafaf2e)
![image](https://github.com/Alex313031/thorium/assets/44940748/1db4fed7-910b-40ac-8f46-37184c1fb695)
![image](https://github.com/Alex313031/thorium/assets/44940748/9f823c4f-c718-4eec-af6b-c4a9855bbadd)
![image](https://github.com/Alex313031/thorium/assets/44940748/870124ba-97b6-48de-9dc2-5d98bbf7a609)

**Additional Notes**

**Comment by gz83** [comment]
duplicate

**Comment by rakincw** [comment]
Same problem, anyway to make all of the icons grey?
