### ISSUE TITLE
Some mistakes about the TopBar icon.

### ISSUE THREAD

**Issue by wuxian425** [Alex313031/thorium#654]
**System Details**
 - OS: Xubuntu 22.04.4 LTS
 - Thorium Version: 123.0.6312.133 

**Problem**
In the latest update (123.0.6312.133), when I enable `#chrome://flags/#chrome-refresh-2023`, **`#customize-chrome-side-panel`** and **`#disable-thorium-icons`** flags, the size and thickness of the top bar icon will become inharmonious and it will look too different from other official Google Material icons.

I think with `#disable-thorium-icons` flag enabled, all icons should be reverted to the original Chrome icons, it would look much better :-)

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/82699919/af382bd5-aa26-444f-b604-39a7625ae923)
![image](https://github.com/Alex313031/thorium/assets/82699919/75035721-100f-4984-aebb-57d39c3dfc7b)

**Additional Notes**
Thank you for all your hard work! :100:

**Comment by gz83** [comment]
Duplicate

**Comment by wuxian425** [comment]
> Duplicate

Is Thorium considering fixing it?
