### ISSUE TITLE
AppArmor Error

### ISSUE THREAD

**Issue by tr-j** [Alex313031/thorium#655]
**System Details**
 - OS: Ubuntu 24.04
 - Thorium 123.0.6312.133

**Problem**
After upgrading from Ubuntu 23.10 to 24.04 Thorium can no longer launch. Reinstalling thorium through the .deb package doesn't help.

kern.log:
kernel: audit: type=1400 audit(1714303978.272:325): apparmor="DENIED" operation="userns_create" class="namespace" info="User namespace creation restricted" error=-13 profile="unconfined" pid=9228 comm="thorium" requested="userns_create" denied="userns_create"

**Comment by Alex313031** [comment]
@tr-j Yup. Lots of Chromium based stuff is breaking on 24.04.

**Comment by tr-j** [comment]
Is there a fix for this?

**Comment by Alex313031** [comment]
@tr-j Waiting on a fix from Ubuntu or Chromium. It's kinda out of my hands.

As a temporary workaround, can you try running 

`sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`

and then launching Thorium from the same terminal.
