### ISSUE TITLE
Detected: Trojan:Win32/Acll in chrome_proxy.exe

### ISSUE THREAD

**Issue by Ymetro** [Alex313031/thorium#656]
**System Details**
 - OS: Windows 11 Pro Build 22621.3447
 - Thorium Version 123.0.6312.133 (Official build) (64-bits)

**Problem**
Windows Defender detected next to the Win32/Znyonm trojan mentioned in issue #645 for Thorium version 123.0.6312.132 the Trojan:Win32/Acll. 
Probably a false positive, but annoying, while Thorium desktop apps links will be removed from the desktop, start menu and the taskbar by Defender because of it. 

**Screenshots**
In Dutch: 
![image](https://github.com/Alex313031/thorium/assets/30724400/12972f22-ba54-4593-a281-c87a14cc8d72)

**Additional Notes**
BTW: clearing the cached detections and obtaining the latest malware definitions for Windows Defender did not work for me,
and both virus were still detected afterward. 

Could this be another false-positive error, which can be reported to Microsoft for investigation?

**Comment by Alex313031** [comment]
@Ymetro Yeah, sometimes Thorium triggers windows Defender. It seems to happen at random, and everytime its a different "threat". It would help the more people can report it as a false positive, but I'm not sure it will do anything.
