### ISSUE TITLE
update to 124.0.6367.119

### ISSUE THREAD

**Issue by k2662** [Alex313031/thorium#658]
version 124.0.6367.119 has security fixes that 123 doesn't have.

**Comment by gz83** [comment]
We haven't started working on version 124 yet, please be patient and wait for the next update.

**Comment by Enderteck** [comment]
> version 124.0.6367.119 has security fixes that 123 doesn't have.

It also has big Wayland issues so that's not a great update:

https://issues.chromium.org/issues/329678163?pli=1

**Comment by Alex313031** [comment]
@Enderteck @k2662 See number 3. in the FAQ > https://github.com/Alex313031/thorium/blob/main/docs/FAQ.md
