### ISSUE TITLE
scaling problem

### ISSUE THREAD

**Issue by tloc241** [Alex313031/thorium#664]
this is thorium 
![screen](https://github.com/Alex313031/thorium/assets/112869206/c3f988ad-4443-43ba-8cb3-20ee69f99f5b)
2 below is random other app
![legacy](https://github.com/Alex313031/thorium/assets/112869206/f60f16d6-12ca-482b-9b42-565fff4d80e2)
![librewolf](https://github.com/Alex313031/thorium/assets/112869206/c4bd6039-b70d-4e08-a131-eceeb8d28cc6)
 idk why url bar on thorium just so oversize like that, so weird
OS: lubuntu 22.04
kernal: 6.5
i just install it today so obviously it on the newest verstion: 123.0.6312.133 (05/05/2024)
just thanks for helping me first <3

**Comment by Alex313031** [comment]
@tloc241 Right click in the tabstrip, and select "Use system titlebar and borders".
