### ISSUE TITLE
I have a SERIOUS Issue

### ISSUE THREAD

**Issue by adsactly** [Alex313031/thorium#667]
**System Details**
 - OS: Windows 10
 - Thorium Version Thorium_SSE3_123.0.6312.133

**Problem**
All I did was download the latest Thorium for my Windows 10 and now my Data Folder is not being recognized. I didn't delete anything from the old USER DATA Folder so please help me fix this!

**Screenshots**

**Additional Notes**
This should NOT have happened!

**Comment by adsactly** [comment]
Thorium | 122.0.6261.132 (Official Build) (64-bit)
-- | --
Revision | 61945b53637674b1590956ea108d51e4734661a7-refs/branch-heads/6261@{#1062}
OS | Windows 10 Version 22H2 (Build 19045.4355)
JavaScript | V8 12.2.281.23
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Command Line | "D:\Downloads\Thorium_SSE3_122.0.6261.132\BIN\thorium.exe" --user-data-dir="D:\Downloads\Thorium_SSE3_122.0.6261.132\\USER_DATA" --allow-outdated-plugins --disable-logging --disable-breakpad --flag-switches-begin --enable-gpu-rasterization --force-dark-mode --ignore-gpu-blocklist --prominent-active-tab-titles --enable-smooth-scrolling --enable-features=ChromeRefresh2023,ChromeWebuiRefresh2023,CustomizeChromeSidePanel,ScrollableTabStrip,TabGroupsSave,Vulkan,WebRtcHideLocalIpsWithMdns --flag-switches-end
Executable Path | D:\Downloads\Thorium_SSE3_122.0.6261.132\BIN\thorium.exe
Profile Path | D:\Downloads\Thorium_SSE3_122.0.6261.132\USER_DATA\Default
Variations Seed Type | Null
Active Variations | 22a53a00-70ea8f255e3a236d-59e286d0dc62934a-70ea8f25

You can see above that is pointing to the right USER_DATA I have no idea why its not loading my Profile!

**Comment by adsactly** [comment]
I even tried going back to the old version which I backed up and its still not loading my USER DATA this is a Very Serious Issue!

**Comment by adsactly** [comment]
I even tried going back to the previous release and still isn't recognizing my profile!

**Comment by Alex313031** [comment]
@adsactly Can you show me a screenshot of the contents of USER_DATA?

**Comment by midzer** [comment]
> <adsactly> thank God for Sync!
<adsactly> it looks like it was all saved and synced
<adsactly> I just had to login and it redownloaded everything

Solved on IRC I guess @adsactly?

**Comment by rubyFeedback** [comment]
Can someone explain the issue? I am mostly using Linux, but I have a Win10 machine to my left side, a few meters away from my main workspace. I don't fully understand the problem described. Why did things have to be re-downloaded? Can't thorium simply be downloaded manually too?

**Comment by midzer** [comment]
@rubyFeedback Author had problems with Thorium profile. Sync helped to recover everything.

@adsactly Is your issue solved then?

**Comment by adsactly** [comment]
Yes my issue has been resolved thank The God of Thor!
