### ISSUE TITLE
hide elements

### ISSUE THREAD

**Issue by creisey** [Alex313031/thorium#668]
**Add all the stuffz here**
is it possible to give hide this elements? 
<img width="970" alt="image" src="https://github.com/Alex313031/thorium/assets/19647655/a55ee3bb-7eb3-4f25-a797-ba264dd782b6">

this would give a cleaner experience

**Comment by Alex313031** [comment]
You can use these flags:

`chrome://flags/#disable-thorium-icons` to disable colors.

`chrome://flags/#chrome-labs` Set to "Disabled"

`chrome://flags/#hide-sidepanel-button`

Note that the Extensions icon can't be removed.

**Comment by creisey** [comment]
thx
