### ISSUE TITLE
password manager can't save the password of YouTube or google services

### ISSUE THREAD

**Issue by ahmeteid7** [Alex313031/thorium#670]
**System Details**
 - OS: [ubuntu 20.04 xfce]
 - Thorium Version [Version 123.0.6312.133 (Official Build) stable, built on Ubuntu (64-bit)]

**Problem**
the password manager can save the user name and password authentication(sign in) for all sites , but can't do that for youtube and google , each time i use the browser i should enter the user name and the password and google give me code in mobile to sign in

**Additional Notes**
i think that related to google company , which it consider brave and thorium as not compatible browser

**Comment by Pleusch** [comment]
I got a smiliar issue with my password manager, too.

https://github.com/Alex313031/Thorium-Win/issues/220

I hope it will get fixed soon. Would make it much more convinient.

Greetings.

**Comment by ahmeteid7** [comment]
i signed in the browser profile and go to sync and made the sync on , and that solved the problem with google apps like youtube and google and gimini etc.
