### ISSUE TITLE
Need a feature/option to turn off requiring user password to see the password they have on thorium.

### ISSUE THREAD

**Issue by glyh** [Alex313031/thorium#674]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
`Linux mechrevo 6.8.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000 x86_64 GNU/Linux`

 - Thorium Version [e.g.107.0.5347.0]
Thorium 123.0.6312.133 stable, built on Ubuntu

**Problem**
I have password saved and I can use them in autofill but I don't see them in password managers.

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/12870742/bca49d9d-8e8e-4717-b1e7-6c8082e3362a)

**Additional Notes**

**Comment by wuxian425** [comment]
This works fine for me (M123.0.6312.133/Xubuntu 22.04.4), we should be using the same version of the package.

**Comment by glyh** [comment]
I don't know if that matters but I use Hyprland WM rather than a Desktop Environment

```
Hyprland, built from branch main at commit e4e84064f2d07810e0c150bce1369a0a00503e9a  (xdg-activation: keep tokens after the resource is dead).
Date: Thu May 9 05:17:17 2024
Tag: v0.40.0-32-ge4e84064, commits: 4638

flags: (if any)
```

Also I tried to login with Gnome a few days ago. I don't know what gnome will do on my computer but when I'm logging in with gnome, thorium is constantly asking my password.

**Comment by glyh** [comment]
Looks like that was it, I just login to gnome and provides my password, thorium can display password from then on. Is there an option that I can use to disable this feature?

**Comment by gz83** [comment]
Please use wayland or x11 if possible

**Comment by glyh** [comment]
Hyprland is on Wayland, what do you mean?

**Comment by gz83** [comment]
I mean using wayland or x11 by default or with only a little customization, hyprland is not included.

@glyh

**Comment by glyh** [comment]
Didn't get it. I didn't tweak anything on X11 or Wayland itself.

**Comment by gz83** [comment]
It seems that you can't understand what I mean. Let me say this: give up Hyprland and return to the original Wayland or X11.

@glyh
