### ISSUE TITLE
Future of Mainfest V2 for Adblockers?

### ISSUE THREAD

**Issue by youself64github** [Alex313031/thorium#677]
**Is your feature request related to a problem? Please describe.**
Most chromium browsers seems to remove support for Mainfest V2 starting with June-July 2024. as most adblockers doesn't even install or work on browsers without mainfest v2.

**Describe the solution you'd like, including relevant patches or source**
We will need to keep mainfest v2 support to in order to continue working adblock extensions and older extensions on chromium browsers in future.

**Additional Notes**

**Comment by gz83** [comment]
We should be able to extend the use of mv2 through local policies. In addition, the impact of mv2 deprecation on extensions needs further investigation.

**Comment by Alex313031** [comment]
@youself64github @gz83 Yeah. I plan to force enable MV2 support for as long as possible, and then when they finally remove the code for it, I plan to revert it and continue MV2 support.
