### ISSUE TITLE
Built-in Tor Bridge Pluggable Transports, Snowflake WebTunnel | i2pd

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [Alex313031/thorium#693]
**Is your feature request related to a problem? Please describe.**
Built-in Tor Bridge Pluggable Transports, Snowflake WebTunnel | i2pd. user chat anonymously by installing thorium, No need to download additional apps insecure VPN proxy

**Describe the solution you'd like, including relevant patches or source**
Built-in  [Tor Bridge Pluggable Transports, Snowflake WebTunnel](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports) and [i2pd](https://github.com/PurpleI2P)

**Additional Notes**

**Comment by gz83** [comment]
Thanks for your suggestions, but we have no current plans to implement these features.
