### ISSUE TITLE
cant pass cloudflare check

### ISSUE THREAD

**Issue by truong0235** [Alex313031/thorium#694]
**System Details**
 - OS: Windows 10 Enterprise LTSC 21H2
 - Thorium Version: Windows Thorium_SSE3_124.0.6367.218

**Problem**
A verify box should appear in the middle, but nothing there and im stuck at cloudflare bot check menu

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/53035575/fd914005-ea67-460d-946b-3fd69379f1db)

**Additional Notes**
Do test on my phone, works like normal
(havent tested another browser on my Windows os)

**Comment by gomster** [comment]
> Been having this issue on the latest build, regardless of the IP I use (infinite cloudflare captcha). Can someone tell me if it works for you? => https://retroachievements.org/

just tested now and yes it works with the latest build .

![Image](https://github.com/user-attachments/assets/c78c977e-8ef9-4080-9987-7c1a8b208c4b)
