### ISSUE TITLE
bug: HW Accelerated HEVC decoding leading to inaccurate colors being displayed

### ISSUE THREAD

**Issue by ThaUnknown** [Alex313031/thorium#70]
**System Details**
 - OS: Windows 10 21H2
 - Thorium Version [M106.0.5237.0](https://github.com/Alex313031/Thorium-Win/tree/M106.0.5237.0)

**Problem**
HEVC Videos inaccurately calculate their color profiles leading to color inaccuracy, or simply making the video look more washed out than it actually is.

**Screenshots**
Left: actual
Right: expected
![image](https://user-images.githubusercontent.com/6506529/185963885-2f54a4f8-1a2e-4af0-9f02-380641eb1374.png)
![image](https://user-images.githubusercontent.com/6506529/185964376-d790d753-d1c7-4f49-8ef1-957ff9ac7f99.png)

Devtools media tab:
![image](https://user-images.githubusercontent.com/6506529/185965034-d7412f46-0ff7-43b9-9082-d564cecaeb6c.png)

**Additional Notes**
For comparison I used [Muril's patch](https://github.com/Muril-o/electron-chromium-codecs) which doesn't enable hardware accelerated HEVC decoding for this very reason. This issue is effectively asking to stop using [StaZhu's patch](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/blob/main/add-hevc-ffmpeg-decoder-parser.patch)  and instead switch to Muril's patch, which also includes EAC-3/AC-3

**Comment by Alex313031** [comment]
@ThaUnknown Thanks, I will look into it.

**Comment by Alex313031** [comment]
@ThaUnknown Updated ffmpeg patch and made minor adjustment. It should play HEVC with software decoding now, which is good for everyone, but it also might have resolved your color issue. Can you test latest release?

**Comment by ThaUnknown** [comment]
using https://github.com/Alex313031/Thorium-Win/releases/tag/M109.0.5362.0
the issue doesn't seem fixed:
![image](https://user-images.githubusercontent.com/6506529/196379883-1622cc44-8afe-4ef7-af61-a5337f5c127e.png)
![image](https://user-images.githubusercontent.com/6506529/196380013-0e650aa2-e4fd-4de0-8fe6-8d32aceccaba.png)

**Comment by ThaUnknown** [comment]
@gz83 ah yes. url.

**Comment by ThaUnknown** [comment]
> > @gz83 ah yes. url.
> 
> @ThaUnknown sorry i didn't see the url you sent

yes, because it was a sarcastic stab at the fact that one didn't exist, but here, 24h to download then it expires:
https://wormhole.app/a4blj#mgEcOYPFL1OKUb-gb9Tu_g

**Comment by ThaUnknown** [comment]
woah we have a 3rd result which also isnt correct
I'll make a gradient here:
![image](https://user-images.githubusercontent.com/6506529/196419631-124d8cce-ad4f-4e45-afe2-0051bffe7bfc.png)
order is windows/linux/target

**Comment by ThaUnknown** [comment]
@Alex313031 seems this was fixed in StaZhu's patches, I don't know exactly when as I wasn't keeping a pulse on this.

**Comment by Alex313031** [comment]
@ThaUnknown Cool.
