### ISSUE TITLE
How to disable to addresses

### ISSUE THREAD

**Issue by Ygarr** [Alex313031/thorium#702]
While starting thorium goes without asking here. How to stop this?
![image](https://github.com/Alex313031/thorium/assets/14309871/774eedcb-30f8-4916-b852-63f53eea205a)

**Comment by gz83** [comment]
It may be that some Google services in the browser are connecting to Google. In order to ensure availability, we will not handle it.

**Comment by Ygarr** [comment]
you sell your users to monopolists?
