### ISSUE TITLE
Response delay

### ISSUE THREAD

**Issue by nihalawasthi** [Alex313031/thorium#706]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]

**Problem**
- Touchpad Response Delay
A noticeable lag when using the touchpad. Actions such as cursor movement, clicking, and dragging are not immediate, causing a delay of approximately 0.5-1 seconds. This affects the overall user experience, making the interface feel sluggish and unresponsive. This issue is consistent across different devices and operating systems, indicating a potential software-related cause.
- Smooth Scroll Delay
Smooth scrolling, using the touchpad gestures, is not functioning as expected. There is a delay of 1-2 seconds before scrolling actions are reflected on the screen. This delay disrupts the fluidity of navigation, especially on long web pages or documents. The lag in scrolling response impacts usability, making it difficult for users to interact efficiently with content.

**Screen recordings**
- Thorium Browser
https://github.com/Alex313031/thorium/assets/137594290/dd7d33f7-e101-49bd-972a-192c13567096

- Microsoft Edge
https://github.com/Alex313031/thorium/assets/137594290/cf9ce713-7cd6-43e9-aa68-4ac28fdd5ba1

**Comment by gz83** [comment]
Duplicate

**Comment by nihalawasthi** [comment]
> Duplicate

Yeah I created the same issue in both repos thorium and thorium-win
