### ISSUE TITLE
[Linux] 2-finger pinch-zoom is not work

### ISSUE THREAD

**Issue by icepie** [Alex313031/Thorium#71]
**System Details**
 - OS: ArchLinux
 - Thorium Version [107.0.5253.0]

**Problem**
2-finger pinch-zoom is not work, but it can srolling..

**Comment by Alex313031** [comment]
@icepie Have you tried it in vanilla chromium. If it doesn't work there, or in chrome, then it is a chromium thing and most likely not something I can fix on my end.

**Comment by icepie** [comment]
my touchpad with chrome and wayland is work fine

**Comment by Alex313031** [comment]
@icepie Hmm strange. It might be an upstream thing. I am about to make a new release, so test that. If it continues into M108, then i will look more into it.

**Comment by icepie** [comment]
Sorry, I was wrong... I tesed chrome again, it dose not work! sorry...
