### ISSUE TITLE
Heavy ads, crypto mining, captive portal

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium#72]
Hello, I know that Thorium Browser has integrated some Ungoogled chromium options but ungoogled chromum has removed an important option: that of the native chromium ad blocker which blocks heavy ads and also blocks crypto currency mining, I asked ungoogled chromium d 'enable the native ad blocker but I was told using ublock extension is enough, the problem is that there are new ads and new crypto mining technique which uses a small amount of the cpu to do crypto mining , which the ad blocker can't detect, but the native chromium ad blocker

"Chrome sets limits on the resources an ad may use and unloads that ad if the limits are exceeded."

additionally, chromium will apparently migrate to manifest v3 and ad blockers will be less effective.

https://blog.chromium.org/2020/05/resource-heavy-ads-in-chrome.html

a user told me ad blocking is enabled by default in ungoogled chromium

https://source.chromium.org/chromium/chromium/src/+/refs/tags/101.0.4951.54:components/heavy_ad_intervention/heavy_ad_features.cc

https://github.com/ungoogled-software/ungoogled-chromium/issues/1944

 but I tested with this test site and ungoogled chromium did not block heavy ads:

https://heavy-ads.glitch.me/

did Thorium Browser remove this native heavy ads blocker, and does Thorium Browser disable the captive portal ?

Thanks a lot !

**Comment by Alex313031** [comment]
@trimechee Thorium does NOT use these patches. It has the heavy ad blocker and captive portal, just like upstream chromium, for the reasons you outlined above.

**Comment by trimechee** [comment]
Interesting, thank you very much :)
