### ISSUE TITLE
Scaling does not change with monitor scaling change

### ISSUE THREAD

**Issue by WesleyBryie** [Alex313031/thorium#721]
**System Details**
 - OS: KDE Neon 6.0 running Plasma 6.1 Wayland
 - Thorium Version 124.0.6367.218 (Official Build) stable, built on Ubuntu (64-bit)

**Problem**
I use an external monitor at my desk, and set my laptop to use the external monitor only when plugged in. When unplugging my laptop, Thorium's scale does not change. I have to fully restart Thorium for the correct scale to be used. 

**Screenshots**

**Additional Notes**
What I see: 
![image](https://github.com/Alex313031/thorium/assets/93141203/e4c732f6-ac66-46dd-b34f-94456cdac098)

What I should see:
![image](https://github.com/Alex313031/thorium/assets/93141203/36129d7c-e8b1-4514-9a9f-2a4e2c9a37a7)

**Comment by gz83** [comment]
Do other browsers have this problem?

**Comment by WesleyBryie** [comment]
> Do other browsers have this problem?

After reviewing other applications, I think this is just a general Wayland scaling issue, not just a Thorium issue.
