### ISSUE TITLE
Can't join the website

### ISSUE THREAD

**Issue by thomlunnguyen1111** [Alex313031/thorium#722]
- OS: Windows 11 Home Version 23H2
 - Thorium Version 124.0.6367.218 

I can't access a few websites in Thorium, while I can access them in another browser.

![image](https://github.com/Alex313031/thorium/assets/137971475/6abf423f-0f7d-4cb4-95d5-79518dcac158)

I want to listen to the explanation of why the problem occurred and fix it soon.

**Comment by midzer** [comment]
The site on the screenshot works for me using Thorium on Linux.

**Comment by gz83** [comment]
Please check if you have secure DNS set up in Thorium. Please also try opening it in incognito mode and check if you have any custom DNS settings outside of your browser.

@thomlunnguyen1111

**Comment by thomlunnguyen1111** [comment]
Oh, thanks. I could join the website. I wish you could improve your browser to have a better experience. See you soon.

**Comment by gz83** [comment]
This doesn't seem to be directly related to the browser
