### ISSUE TITLE
thorium + ungoogled-chromium?

### ISSUE THREAD

**Issue by stokebreakup** [Alex313031/thorium#724]
**Is your feature request related to a problem? Please describe.**
A lightweight approach to removing Google web service dependency

**Describe the solution you'd like, including relevant patches or source**
Without signing in to a Google Account, Chromium does pretty well in terms of security and privacy. However, Chromium still has some dependency on Google web services and binaries. In addition, Google designed Chromium to be easy and intuitive for users, which means they compromise on transparency and control of internal operations.

**Additional Notes**
ungoogled-software/ungoogled-chromium(https://github.com/ungoogled-software/ungoogled-chromium): Google Chromium, sans integration with Google

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/blob/main/docs/FAQ.md

Won't fix
