### ISSUE TITLE
What does scripts batch Pack and Unpack do in Thorium?

### ISSUE THREAD

**Issue by SifcaeIT** [Alex313031/thorium#729]
Hello I would like to know what functioned performs these scripts batch in thorium operation or what can we do with them?.

![Pack$Unpack](https://github.com/Alex313031/thorium/assets/168949201/6f72677d-f2e5-4e44-b4f4-f811edb76beb)

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/tree/main/pak_src

**Comment by SifcaeIT** [comment]
In these files . pak all Thorium icons are stored?

**Comment by Alex313031** [comment]
@SifcaeIT Not all, but many. .png and .jpg assets are stored in it.
