### ISSUE TITLE
Question about FAQ # 4

### ISSUE THREAD

**Issue by viasux** [Alex313031/thorium#730]
**Add all the stuffz here**
When I sign into google to use youtube/etc. I just want to sign in on the website I'm using, but it appears that it signs in on the browser itself, and signing out from the browser signs me out on the website. Does this transmit any information about the browser im using or anything in excess of what, say ungoogled-chromium would send in the same instance?

**Comment by gz83** [comment]
This is true for all browsers that include Google services, even Edge, which will handle Microsoft accounts the same way. In addition, Thorium browser is not ungoogled-chromium, we choose to keep Google services for usability.

At the same time, there is no absolute privacy protection. When you connect to the Internet, information may be uploaded, and the system you are using may have backdoors.

**Comment by viasux** [comment]
> @viasux You need chrome://settings/syncSetup and then turn off "Allow Thorium sign-in"

Thanks!

**Comment by viasux** [comment]
I do just want to add that I think it might be worth considering turning that off by default, as anyone who isn't using sync probably doesn't expect or really want that behavior. IMO it's a 'dark pattern' - and maybe turning on sync could just turn on that feature. I don't see why it's a separate thing really.
