### ISSUE TITLE
chrome://flags/#enable-desktop-pwas-remove-status-bar not found

### ISSUE THREAD

**Issue by littleblack111** [Alex313031/thorium#737]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]
 - OS: Arch Linux(rolling release)
 - Thorium Version: 124.0.6367.218

**Problem**
chrome://flags/#enable-desktop-pwas-remove-status-bar is not there. I would like my PWAs to not show the title / status bar

**Screenshots**
![Screenshot_2024-07-09-12-23-34_3840x2160](https://github.com/Alex313031/thorium/assets/97672521/d4415a37-2180-4db0-8d7d-dc12fe748867)

**Additional Notes**

**Comment by gz83** [comment]
Which browser did you originally use chrome://flags/#enable-desktop-pwas-remove-status-bar in? Also, what version of that browser was it?

**Comment by littleblack111** [comment]
https://beebom.com/remove-status-bar-from-google-chrome-pwas/

**Comment by gz83** [comment]
This is an outdated article and the experimental flag has been removed. Please do not refer to outdated content.

**Comment by littleblack111** [comment]
then how do i remove titlebar/statusbar from pwas?
