### ISSUE TITLE
Thorium does not open on Fedora 40

### ISSUE THREAD

**Issue by OliverKreitmeyer** [Alex313031/thorium#742]
**System Details**
 - OS: Fedora Linux 40 (Workstation Edition)
 - Thorium Version M124.0.6367.218 - 59th Release

**Problem**
The Thorium Browser does not start. When I try and open it, it makes a little dot under the thorium icon, as if there is a window of it open, but it just stays that way for a minute before disappearing. (the dot disappears, the window itself never opens) It works if I select `open new window with temp profile`. The Thorium Shell also works. 

**Additional Notes**
I tried on both Wayland and X11 with no differences. I also tried all rpms and appleimages available in the newest release as well as the release M123.0.6312.133. All the same. I hope I'm just misunderstanding something because I really want to use thorium on this new PC of mine...

**Comment by breathless19** [comment]
I have the same issue.   Started not right after upgrading to F40, but some time after.    I have tried reinstalling, etc, can't get it to open.

**Comment by sabamdarif** [comment]
> I have the same issue. Started not right after upgrading to F40, but some time after. I have tried reinstalling, etc, can't get it to open.

I am also using it on my Fedora 40 , but i don't have any problem .
I have this same kind of issue in chrome but i never faced it in thorium

i think it might be some dependencies issue ,  launch it from terminal you will see the errors 
type :- `/usr/bin/thorium-browser`

**Comment by breathless19** [comment]
I ended up having to: 

1) Uninstall Thorium
2) After uninstalling, deleting the thorium folder within home/.config

Just uninstalling / reinstalling thorium was not good enough, I had to delete the thorium folder within .config and then reinstall.   Working again....

**Comment by OliverKreitmeyer** [comment]
> > I have the same issue. Started not right after upgrading to F40, but some time after. I have tried reinstalling, etc, can't get it to open.
> 
> I am also using it on my Fedora 40 , but i don't have any problem . I have this same kind of issue in chrome but i never faced it in thorium
> 
> i think it might be some dependencies issue , launch it from terminal you will see the errors type :- `/usr/bin/thorium-browser`

I tried to do so and it gave some weird errors like thorium is already used in another profile...


> I ended up having to:
> 
> 1. Uninstall Thorium
> 2. After uninstalling, deleting the thorium folder within home/.config
> 
> Just uninstalling / reinstalling thorium was not good enough, I had to delete the thorium folder within .config and then reinstall. Working again....

...however, this fixed it. Not sure what happened but I did just need to uninstall it and delete the thorium folder inside .config. Thanks a bunch!
