### ISSUE TITLE
Remove legacy Google hangouts extension

### ISSUE THREAD

**Issue by s1nistr4** [Alex313031/thorium#743]
**System Details**
 - OS: Debian 12 (though affects all instances of Thorium
 - Thorium Version  124.0.6367.218

**Problem**
All versions of Chrome / Chromium ship a legacy extension that people refer to as the "Google hangouts" extension. The extension gives google.com domains unfair privileges over other websites such as access to information like system resources, cpu, and other resources and is likely in violation of anti-trust laws.

There are several other videos covering the topic linked as such:
https://youtube.com/watch?v=fSZsmJkPpYA
https://youtube.com/watch?v=k8zFani09ok
https://youtube.com/watch?v=2d6oPq73svY

**Solution**
It would be helpful to either have it removed or give the ability to toggle it off/on. That way it doesn't break compatibility with google sites that use it.

**Comment by gz83** [comment]
Duplicate
