### ISSUE TITLE
WebRTC removal

### ISSUE THREAD

**Issue by kiufta** [Alex313031/thorium#75]
Dear Alex,

thank you for your work!

Until a few years ago I was using a Chromium version with WebRTC not disabled, but patched out to avoid getting my real IP address [STUNed](https://en.wikipedia.org/wiki/STUN). Then the patch stopped working and I was told that it would be too complicated to _remove_ WebRTC anymore, just disable with a browser extension.

Since you seem to have mastered quite a lot of patching in the Chrome sources: Would it be theoretically possible to remove WebRTC again (not for everyone, just for me)?

**Comment by Alex313031** [comment]
@kiufta I can look into it. And maybe make you a special build. But I cant promise anything.

**Comment by Alex313031** [comment]
@kiufta While it may be possible, this is not something within my knowledge to know how to do. My advice would just be to not use pages that use webrtc, or use those pages in another browser.

However, if you point me to where you got the releases/source code, I may be able to make a patch to avoid getting STUNed.

I would be happy to apply a patch like that to increase privacy. However, even if I *could* figure out how to completely remove webrtc from chromium, I would not apply this to thorium, as one of the goals of thorium is to increase privacy and security, *without* impacting usability. This would impact usability. This is why thorium uses patches from ungoogled chromium, but does not include patches that remove google services and browser functionality like the web store, google sync, and google search.
