### ISSUE TITLE
Cannot change to 2023 new style

### ISSUE THREAD

**Issue by LFRon** [Alex313031/thorium#750]
**System Details**
 - OS: Ubuntu 24.04
 - Thorium Version 124.0.6367.218
 - Desktop Environment:KDE Plasma 5.27.11
 - IsWayland:True

**Problem**
I found though I open the experimental 2023 new style in thorium,it still shows as old style.But I preferred the new style look,Could developer fix the problem?Thanks!

**Additional Notes**
No

**Comment by sabamdarif** [comment]
i have the same issue

**Comment by LouShy** [comment]
After settings some flags in [chrome://flags](chrome://flags) and adding **--disable-features=CustomizeChromeSidePanelNoChromeRefresh2023** to launch parameters 2023 Refresh Style works fine for me on Windows.
![image](https://github.com/user-attachments/assets/5079174c-336f-4aba-a546-90c81eb3e14e)

**Comment by sabamdarif** [comment]
> After settings some flags in chrome://flags and adding **--disable-features=CustomizeChromeSidePanelNoChromeRefresh2023** to launch parameters 2023 Refresh Style works fine for me on Windows. ![image](https://private-user-images.githubusercontent.com/46421458/354563716-5079174c-336f-4aba-a546-90c81eb3e14e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDk1MzAsIm5iZiI6MTcyMjYwOTIzMCwicGF0aCI6Ii80NjQyMTQ1OC8zNTQ1NjM3MTYtNTA3OTE3NGMtMzM2Zi00YWJhLWE1NDYtOTBjODFlYjNlMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NzI0MzUxMmE4ZWYxNTY0YTQ0MWM5MzVjNTM2Mzg5MzAwZTg1NmYzNGIwMDFlZjQxMmU4YTFiZjhlZWI1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qyjsBh14M4HSZqJI0y7ljQLqvqQFzR7S0UBcUGMnyXs)

yes it fixed altough some icons are missing in side panel

**Comment by LFRon** [comment]
I found Thorium have used new style now,but I preferred Original Chromium style that Tab button is on the left,how could I change it?Thanks!

**Comment by sabamdarif** [comment]
> After settings some flags in chrome://flags and adding **--disable-features=CustomizeChromeSidePanelNoChromeRefresh2023** to launch parameters 2023 Refresh Style works fine for me on Windows. ![image](https://private-user-images.githubusercontent.com/46421458/354563716-5079174c-336f-4aba-a546-90c81eb3e14e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjkwMDYsIm5iZiI6MTcyNjMyODcwNiwicGF0aCI6Ii80NjQyMTQ1OC8zNTQ1NjM3MTYtNTA3OTE3NGMtMzM2Zi00YWJhLWE1NDYtOTBjODFlYjNlMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE1NDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNjg2MjVlZDk2OGU4NGE2Yzc0NWYyYzAwOGViZDUzNmNmY2I3YTE4YzVmNWQ5ZDgwOTdlOTJlMjE3M2RmZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8fCLwel3j8kC3RIEu2t_09k_wVt4GUYWYZH8VdCVLeg)

when i change my de from gnome to kde it fixed automatically

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/releases/tag/M126.0.6478.251

You can try these versions, we have made further adjustments to the interface

**Comment by LFRon** [comment]
> https://github.com/Alex313031/thorium/releases/tag/M126.0.6478.251
> 
> You can try these versions, we have made further adjustments to the interface

Can all subsequent versions be transferred back to Google's native style?

**Comment by gz83** [comment]
CR23 and its previous interface style are all Google's native style. I don't know whether it will be completely switched back to the previous interface style, which is not something I can decide.

@LFRon
