### ISSUE TITLE
Tab Bar offset

### ISSUE THREAD

**Issue by KyusaiWorkshop** [Alex313031/thorium#757]
**System Details**
 - OS: Windows 11
 - Thorium Version 124.0.6367.218

**Problem**
How can I get back the default offset like in Google Chrome at the top of the tab bar?

**Screenshots**
![image](https://github.com/user-attachments/assets/a21e7cd7-095a-4a07-bef6-b25d7d79eac4)

**Additional Notes**
Trying to search that in flags, but didnt find it

**Comment by Alex313031** [comment]
@KyusaiWorkshop Update to M126, it has the new "Cr23" UI, and I am making a flag to restore the old UI, for people who want it like me.
