### ISSUE TITLE
Unable to use sidebar due to color of all the component of sidebar change to red.

### ISSUE THREAD

**Issue by coderj001** [Alex313031/thorium#758]
**System Details**
 - OS: Arch (linux v6.10.2)
 - Thorium Version  124.0.6367.218 stable

**Problem**
Out of no where after installing thorium browser the sidebar color is red.

**Screenshots**
![image](https://github.com/user-attachments/assets/33abc692-bcaf-4741-88b9-0e784daeda1b)

**Comment by coderj001** [comment]
More context it only happening when I open sidebar with bookmarks options, others work more of less fine.

**Comment by ferretosan** [comment]
also happening with macos - ive experienced

**Comment by Malus-risus** [comment]
me too

**Comment by coderj001** [comment]
New update from thorium fix this issue
