### ISSUE TITLE
bilibili.com laggy response

### ISSUE THREAD

**Issue by escapezn** [Alex313031/thorium#760]
**System Details**
 - OS: [Windows 10]
 - Thorium Version [124.0.6367.218]

**Problem**
The animation is laggy when the mouse moves over the banner in Thorium, but smooth in chrome. CPU usage is high and hardware acceleration doesn't seem to be working properly.

**Screenshots**

https://github.com/user-attachments/assets/5a5d24b3-f8e9-4fe6-9016-5da2d1e5ed0b

https://github.com/user-attachments/assets/05abb025-3723-46ab-a5cf-3c95af394d9f

**Additional Notes**

**Comment by gz83** [comment]
Have you tested it with other browsers? If so, please upload the results.

**Comment by escapezn** [comment]
In fact I just tested in incognito mode, without any extension on.

**Comment by InspoOnU** [comment]
> **System Details**
> 
> * OS: [Windows 10]
> * Thorium Version [124.0.6367.218]
> 
> **Problem** The animation is laggy when the mouse moves over the banner in Thorium, but smooth in chrome. CPU usage is high and hardware acceleration doesn't seem to be working properly.
> 
> **Screenshots**
> 
>  -.-Bilibili.-.Thorium.2024-08-06.21-27-12.mp4 
>  -.-Bilibili.-.Google.Chrome.2024-08-06.21-27-35.mp4 
> **Additional Notes** Add any other context about the problem here.

This animation runs smoothly on mine, same version.

**Comment by escapezn** [comment]
This problem may only occur on AMD graphics. There is no such problem on my other machines. Can anyone with AMD graphics help reproduce this problem?

**Comment by gz83** [comment]
I cannot reproduce the problem you encountered locally, and version 126 will be released soon. Please test again after version 126 is released.

Unless there are special circumstances, please try not to artificially limit the performance of the device.

**Comment by escapezn** [comment]
Good news! This has been fixed in 126 release.
