### ISSUE TITLE
Rounded corners for Right Click menu, 3 dots menu etc. as an optional feature or flag.

### ISSUE THREAD

**Issue by rakincw** [Alex313031/thorium#763]
Exactly what the title says. If not possible as default then at least through a flag or optional feature.

Some examples taken from Brave Browser:

![image](https://github.com/user-attachments/assets/7075e2e1-82ba-47e8-a131-054e06f6d3a6)
![image](https://github.com/user-attachments/assets/a433ea44-ec4d-43eb-8649-4751d27c7c06)

Thanks in advance.

**Comment by Alex313031** [comment]
@rakincw Now it has it.
