### ISSUE TITLE
Installed extensions crashed

### ISSUE THREAD

**Issue by RocGod** [Alex313031/thorium#766]
**System Details**
 - OS: Windows 11
 - Thorium Version 124.0.6367.218

**Problem**
one or more installed extensions randomly crashed, which need reinstall to work.
Then in next few days, some of the other extensions will be crashed and also needs to reinstalled(might or might not be same extension)

**Screenshots**

**Additional Notes**

**Comment by gz83** [comment]
Please try with fresh user data

**Comment by RocGod** [comment]
> Please try with fresh user data

May I know how to do that?

**Comment by gz83** [comment]
> > Please try with fresh user data
> 
> May I know how to do that?

https://knowledge.workspace.google.com/kb/how-to-recreate-a-user-data-folder-000006491
