### ISSUE TITLE
Side Menu icon is not consist with CR23

### ISSUE THREAD

**Issue by RoyRao2333** [Alex313031/thorium#778]
**System Details**
 - OS: macOS 14.5
 - Thorium Version 126.0.6478.231 (Official Build) (arm64)

**Problem**

Side Menu icon looks old and not fit with other icons in CR23

**Screenshots**

![image](https://github.com/user-attachments/assets/cead7bd5-53d8-4f5d-b5a8-6e8ca2e4d7a7)

![image](https://github.com/user-attachments/assets/a82c2023-7352-4760-911d-c543e50098d0)

**Comment by RoyRao2333** [comment]
@Alex313031 

Yes please.

Actually, can you expose an flag to control whether to use Chrome's original icons?

https://github.com/Alex313031/Thorium-MacOS/issues/48

Thanks you very much! :)

**Comment by Alex313031** [comment]
@RoyRao2333 Can do.
