### ISSUE TITLE
Crashed when browsing firebase firestore database console

### ISSUE THREAD

**Issue by angryLid** [Alex313031/thorium#78]
The firestore admin webpage, whose url is https://console.firebase.google.com/project/<project_id>/firestore/ , could not be loaded.

it told me "Aw F**k" and error code 11 even after I rebooted my laptop.

However, then I tried open it with Safari, everything works well.

**Comment by Alex313031** [comment]
@angryLid So you are on Mac? In the future, would you please file issues in the Thorium-Special repo. Although this hosts the source code, I have seperate repos for linux, windows, avx2, and specia (which includes MacOS and Raspberry Pi builds).

Anyway, alot of people have been having issues with google sites that use google cloud services as a backend, i.e. google sheets, google console, google docs. And now this. And the issues always seem to be on MacOS.

What MacOS version are you using, and is it x64 or Arm version (and are you using the x64 or arm version of thorium for macos)?

**Comment by angryLid** [comment]
@Alex313031 Excuse me. I'm using MacBook Air (M1, 2020) macOS Monterey 12.6, Thorium 107.0.5253.0 (arm64)

**Comment by Alex313031** [comment]
@angryLid See if latest release fixes issues.
