### ISSUE TITLE
How may I install thorium on Arch linux?

### ISSUE THREAD

**Issue by Juhayer-Al-Wasif** [Alex313031/thorium#781]
The aur for thorium is not working currently. So how may I manually install thorium on my arch linux?

**Comment by Skxxtz** [comment]
Had the same problem just now. 

Go into `~/.cache/yay/thorium-browser-bin.../` and edit the `PKGBUILD` file. Look for this part: 

```
_source_main() {
  _dl_url="$url/releases/download/M${_pkgver:?}"
  _dl_filename="${_pkgname}_${_pkgver:?}SSE3.deb"
  noextract+=("$_dl_filename")

  source=("$_dl_url/$_dl_filename")
  sha256sums=('SKIP')

  pkgver() {
    echo "${_pkgver:?}"
  }
}

```
Then change this line `_dl_filename="${_pkgname}_${_pkgver:?}SSE3.deb"`  to be `_dl_filename="${_pkgname}_${_pkgver:?}_Th24_SSE4.deb" ` (Was in line 25 for me).

Stay in the directory and run `makepkg -si`. It should install the browser now. Good Luck.

**Comment by SzilvasiPeter** [comment]
You can simply install the binary with Yay or Pacman:

```shell
yay -Sy thorium-browser-bin
```
