### ISSUE TITLE
GeforceNow 1440p

### ISSUE THREAD

**Issue by thnkman** [Alex313031/thorium#782]
Greetings. 

I am wondering what the technical reasons are for chrome/thorium not supporting resolutions higher than 1080p on geforce now on linux? This limitations doesn't exist on windows as far as i know. 
Could it be possible to get around this limitation by spoofing the chrome/thorium user-agent?

**Comment by Alex313031** [comment]
@thnkman Has to do with Widevine. Widevine is used to encrypt game streams. See number 2 in the FAQ > https://github.com/Alex313031/thorium/blob/main/docs/FAQ.md
