### ISSUE TITLE
Enhancement: tabs sequence when doing tabs switching 

### ISSUE THREAD

**Issue by dmitry-kachan-idexx** [Alex313031/thorium#791]
Chrome has simple tab sequence when you do ctrl+tab. 
If you have 1,2,3,4,5,6,7,8 tabs opened and you need to switch tabs with ctrl + tab - you end up with stupid sequence where tabs will be switch one by one. 
Is it possible to add new behavior where tabs will be switched based on visits history?

**Comment by Alex313031** [comment]
@dmitry-kachan-idexx This is possible with extensions like https://chromewebstore.google.com/detail/last-tabs/ehdbaonmnanalnmmlkgdnkkcdlppjhhc
