### ISSUE TITLE
bt4gprx.com doesnt work with thorium anymore

### ISSUE THREAD

**Issue by detyso** [Alex313031/thorium#799]
Windows 11 Last thorium version

https://github.com/user-attachments/assets/d0757cbf-076d-4f36-99ad-b95e77592a61

I tried with chrome browser it works again just thorium and firefox doesnt seem to work 

https://bt4gprx.com/magnet/ZZeftoGTmD8DvzZue8eJYaS9ykZwgoTVF

**Comment by midzer** [comment]
You write "anymore". Did it work before?

**Comment by detyso** [comment]
> You write "anymore". Did it work before?

yea it did before now it just a blank page

**Comment by czrae** [comment]
This script might help
[https://gist.github.com/zhimiaoli/fc7c22a27feaa2cbf9ec4563fe860d30](url)

**Comment by detyso** [comment]
I installed this script on greaysfork this fixed it 
![IMG_1035](https://github.com/user-attachments/assets/608966fa-64ff-448f-b0b7-00d512a34690)

**Comment by gabri25ele** [comment]
> I installed this script on greaysfork this fixed it ![IMG_1035](https://private-user-images.githubusercontent.com/163365484/363413804-608966fa-64ff-448f-b0b7-00d512a34690.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NjE2ODEsIm5iZiI6MTcyOTk2MTM4MSwicGF0aCI6Ii8xNjMzNjU0ODQvMzYzNDEzODA0LTYwODk2NmZhLTY0ZmYtNDQ4Zi1iMGI3LTAwZDUxMmEzNDY5MC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMTY0OTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhlMjAyMGY2ZTMyNmUwYjRmMTI5M2IzNGU5ZDBiNDI1MWUwODE0NDRmYzcwZTJiYzM2NWQ2MzRhZTc0YjJkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S6oZZDeLfoj9TzSiBu0_PmLdwdZMNV8vN_v32H9AW1U)

I don't find it...
only this
https://greasyfork.org/it/scripts/508413-bt4g-limetorrents-enhanced-search
