### ISSUE TITLE
Crash on JetStream 2 benchmark

### ISSUE THREAD

**Issue by 3andero** [Alex313031/thorium#80]
**System Details**
 - OS: OS X Monterey 12.4 (21F79)
 - Thorium Version: Version 107.0.5279.0 (Official Build) (arm64)
 - MacBook Air (m1)

**Problem**
1. go to https://thorium.rocks/misc/JetStream2/
2. "Start Test"
3. "AW, Fuck" Error code: 11

**Screenshots**
![image](https://user-images.githubusercontent.com/31029660/191576428-eaaeff9d-2003-4b21-85c7-c155217f135c.png)

**Additional Notes**
Thank you for your help!

**Comment by Alex313031** [comment]
@3andero Interesting. I keep seeing more and more bugs on the MacOS M1 versions of Thorium. Its annoying lol. Because especially since there are not many other places to get a chromium build for M1.

**Comment by Alex313031** [comment]
@3andero See if latest release fixes issues.

**Comment by 3andero** [comment]
> @3andero See if latest release fixes issues.

Unfortunately it's still crashing:
Version 109.0.5361.0 (Official Build) (arm64)
