### ISSUE TITLE
Netflix will not work with Thorium

### ISSUE THREAD

**Issue by shanyssys** [Alex313031/thorium#802]
**System Details**
 - OS:  Windows 11
 - Thorium Version 126.0.6478.251

**Problem**
Netflix Error playing content: tvq-pb-101 (E100)

**Screenshots**
![image](https://github.com/user-attachments/assets/d139ed87-c308-42c6-baa1-87615ad7e338)

**Comment by hapnan** [comment]
is drm issue, read this [#523](https://github.com/Alex313031/thorium/issues/523)

**Comment by Alex313031** [comment]
@hapnan @shanyssys Yup, or better explanation here in the FAQ > https://thorium.rocks/faq
