### ISSUE TITLE
Restore being able to click at the very top of the tab as a registered click.

### ISSUE THREAD

**Issue by rohitsaha29** [Alex313031/thorium#804]
- OS: [Windows 11]
 - Thorium Version [126.0.6478.251]

**Problem**
With the new update, you are no longer able to click the very top of the tap (or the edge of your screen) to register a click to switch to that tab. Im sure this a bug and was wondering if it could be restored.
Also please keep the #force-disable-tab-outlines flag along with the TH2024 Ui flag. I use the two in combination and its so good

Thank you in advance : )

**Comment by Alex313031** [comment]
@rohitsaha29 Fixed in latest BETA 2 release! >
