### ISSUE TITLE
Black bar on top

### ISSUE THREAD

**Issue by iLagTooMuch** [Alex313031/thorium#810]
**System Details**
 - OS: [Fedora 40]
 - Thorium Version [126.0.6478.251]

**Problem**
Black bar on top taking up space especially on lower res displays. In chrome and other browsers it is used for placing the tabs.

![image](https://github.com/user-attachments/assets/f2b6396c-18f1-4177-9f31-a8e05029d58e)
Thorium

![image](https://github.com/user-attachments/assets/691e5023-2a7e-4af7-89b4-410403e0c512)
Chrome

**Comment by Alex313031** [comment]
@iLagTooMuch Right click on empty part of the tabstrip, and uncheck "Use system titlebar and borders".

Thorium defaults to this, to provide consistent experience across distros and desktop environments, but it does add the extra space of the window managers titlebar. You can toggle between them as needed.

**Comment by iLagTooMuch** [comment]
> @iLagTooMuch Right click on empty part of the tabstrip, and uncheck "Use system titlebar and borders".
> 
> Thorium defaults to this, to provide consistent experience across distros and desktop environments, but it does add the extra space of the window managers titlebar. You can toggle between them as needed.

My bad, new to Linux and chrome had choppy video playback, thanks.
