### ISSUE TITLE
Google is removing MV2 extensions from the Store

### ISSUE THREAD

**Issue by anatasiajp** [Alex313031/thorium#813]
**Is your feature request related to a problem? Please describe.**
Google is removing MV2 extensions from the Store, we should build our own store.

**Describe the solution you'd like, including relevant patches or source**
We should do something about this before it's too late, to reduce workload, focus on important extensions, like top 1000 and probably give the rest up, because many of them are dangerous anyway.

**Comment by Alex313031** [comment]
@anatasiajp Duplicate. Yes, I will keep MV2 support. See > https://github.com/Alex313031/thorium/issues/677
