### ISSUE TITLE
Thorium 126 crashes on Tegra Linux

### ISSUE THREAD

**Issue by vgrechin** [Alex313031/thorium#818]
**System Details**
 - OS: Tegra Linux, 5.15.136 (Ubuntu 22.04) aarch64
 - Thorium Version 126.0.6478.246

**Problem**
Thorium browser crashes on start, a regression since 124.0.6367.218

**Did you read the FAQ?**
https://thorium.rocks/faq
yes

**Additional Notes**
Attaching dump of the crash
[_opt_chromium.org_thorium_thorium.1000.crash.zip](https://github.com/user-attachments/files/16985510/_opt_chromium.org_thorium_thorium.1000.crash.zip)

**Comment by Alex313031** [comment]
@vgrechin Thanks for the dump.

**Comment by vgrechin** [comment]
No worries, I dumped it from my Jetson Orin Nano box

**Comment by vgrechin** [comment]
Thanks, in latest Thorium 128 the problem is gone. Closing
