### ISSUE TITLE
Request for AVX2

### ISSUE THREAD

**Issue by NewsonUpreti** [Alex313031/thorium#820]
I had installed avx2 version of rpm package of thorium browser. When will the next one come with AVX2? 
All runs well, But I found a slight edge on AVX2 on overall performance on my recently bought pc.

Thanks.

**Comment by Alex313031** [comment]
@NewsonUpreti WDYM? Each release has SSE3, SSE4, AVX, and AVX2 builds in .deb, .rpm, .appimage, and .zip formats.

**Comment by NewsonUpreti** [comment]
Yeah. My bad. I got it now. I was looking for it in BETA. 
Thanks.

**Comment by jhebert8** [comment]
I've looked everywhere and I cannot find the AVX2 .deb or windows packages anywhere. It's usually easy to find, but now only SSE4 are available. Am I not looking in the right place?

**Comment by NewsonUpreti** [comment]
Everything is here @jhebert8 

https://github.com/Alex313031/thorium/releases
![Screenshot from 2024-09-18 23-33-29](https://github.com/user-attachments/assets/8ca4c09e-5feb-44c6-82c9-fc17cee012ef)

**Comment by NewsonUpreti** [comment]
@jhebert8 
for windows. 
https://github.com/Alex313031/Thorium-Win/releases

**Comment by jhebert8** [comment]
Thanks. I meant the Avx2 for Linux. Unsure if it's available while you guys work on the beta project. Which is okay!

**Comment by gz83** [comment]
If you want to use the Th24 Beta AVX2 version, please continue to wait until the next major version is released.

@jhebert8

**Comment by jhebert8** [comment]
Sounds good, thanks for your reply! Love the project, you guys are awesome.
