### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by Clepash** [Alex313031/thorium#821]
**System Details**
 - OS: [e.g.  Ubuntu 22.04]
 - Thorium Version [e.g.126.0.6478.246]

**Problem**
Hello, I just started using linux, there was a problem with installing thorium. 
Tried to install using these instructions - https://thorium.rocks/docs/building.html
Stuck on this step:
![изображение](https://github.com/user-attachments/assets/1db5200b-2a85-4570-9a64-a203cd67012a)
I get this response:
![изображение](https://github.com/user-attachments/assets/fb798e6b-299b-4f92-8a22-fd9139efae50)
It says that there is no such file or directory at this path.
Can you please tell me where I got it wrong?

**Did you read the FAQ?**
Yes

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/releases

Please download the ready-made installation package from the above webpage without compiling it (unless you want to spend a lot of time and resources to do so)

**Comment by Clepash** [comment]
Thank you very much.
