### ISSUE TITLE
AVX Builds

### ISSUE THREAD

**Issue by JesusMaxim** [Alex313031/thorium#825]
I would first like to thank you for continuing the project.

This is a problem that I could see reported in Thorium, but because the problem does not exist in Mercury I decided to report it here, the AVX builds in Thorium do not work in thorium it just opens and closes, but in Mercury these builds work without problems.

**Comment by JesusMaxim** [comment]
> Please provide your processor information and Thorium version.

this is the processor: 
https://www.intel.la/content/www/xl/es/products/sku/53442/intel-core-i32370m-processor-3m-cache-2-40-ghz/specifications.html

The Thorium version is the latest stable version (126.0.6478.231)

**Comment by gz83** [comment]
Your processor does not seem to support AES, please use the SSE3 version instead

**Comment by JesusMaxim** [comment]
> Your processor does not seem to support AES, please use the SSE3 version instead

thank you.
