### ISSUE TITLE
Http3 not working 

### ISSUE THREAD

**Issue by bhunter234** [Alex313031/thorium#827]
**System Details**
 - OS: Windows 11
 - Thorium Version: latest

**Problem**
Even after enabling http3 through `chrome://flags/#enable-quic`  all request are going from http2 protocol. Tested on chrome  http3 is  working  fine there and  have  `alt-svc: h3=":443"; ma=86400` header in all responses if server support http3.

Chrome:
![image](https://github.com/user-attachments/assets/9d1ae74b-2d43-457a-b062-12e020ae1b64)

Thorium

![image](https://github.com/user-attachments/assets/4909a152-c0fa-4007-9ccb-63e719df7ec7)

Visit https://cloudflare-quic.com/ to test http3

**Comment by gz83** [comment]
FYI

https://github.com/Alex313031/thorium/issues/824#issuecomment-2358467879

**Comment by bhunter234** [comment]
Dns  resolution have nothing to do with the protocols its a bug in thorium  tested http3 on brave ,edge and chrome  working fine on all those try to open like I mentioned on my previous comment.

**Comment by hocheung-chromium** [comment]
Have you tried the solution I provided? In addition, I found that you and the user in #824 are using similar websites and software, and seem to be trying to bypass network restrictions. You also need to check their settings.

**Comment by gz83** [comment]
It may also be due to version differences, which may result in different levels of support for QUIC.

**Comment by joshbali** [comment]
> Dns resolution have nothing to do with the protocols its a bug in thorium tested http3 on brave ,edge and chrome working fine on all those try to open website I mentioned on my previous comment.
> Have you tried the solution I provided? In addition, I found that you and the user in #824 are using similar websites and software, and seem to be trying to bypass network restrictions. You also need to check their settings.

@bhunter234
I can confirm that the solution given in #824 works (both on Debian 12 and Windows 11 using Th24 Beta 2 build M126.0.6478.251). As I run Unbound as my DNS resolver with forced secure DNS forwarding on my local network, I don't need any custom secure DNS configuration in my browser. Enabling the "Disable Thorium Custom DNS Config" flag made HTTP3 work on the Cloudflare test page. Enabling or disabling the "Experimental QUIC protocol" flag makes no difference.
