### ISSUE TITLE
how to make it run in Win10?

### ISSUE THREAD

**Issue by falltree** [Alex313031/thorium#830]
I have been using Thorium_AVX2_122.0.6261.132 for months, there is a thorium.bat file.
Now I downloaded the latest thorium-browser_TH24_126.0.6478.251_SSE4.zip and have no idea how it works in Win10.
No .exe file, no .bat file, and the file tree doesn't seem to be a normal browser's file tree.
I am not a linux user and don't how to build a executable version for Win10.
Any help on how to do now?

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Win/releases
