### ISSUE TITLE
FDM extension doesnt work.

### ISSUE THREAD

**Issue by Xeo23** [Alex313031/thorium#862]
**System Details**
 - OS: Arch (Hyprland)
 - Thorium Version [128.0.6613.189]

**Problem**
FDM extension doesnt work on thorium, its stuck on this loading menu and cant seems to connect with the FDM application on my desktop.

![image](https://github.com/user-attachments/assets/26cd9c0b-b3af-4858-99a2-b1a3ebfd0688)
It is workng just fine on other browsers like brave or firefox.
I thinks maybe thorium is blocking it to communicate with app outside the browser. I m not sure but it's just a hunch. 
It will ne helpful if anyone could help as I am planning to use thorium as daily driver.

**Comment by Xeo23** [comment]
@Alex313031

**Comment by Alex313031** [comment]
@Xeo23 Does this use Native Messaging Hosts

**Comment by Xeo23** [comment]
> @Xeo23 Does this use Native Messaging Hosts

Yup, it does.

**Comment by Xeo23** [comment]
okay i got it working by just copying the json file of fdm from `~/.config/BraveBrowser/NativeMessagingHost/` to `~/.config/Thorium/NativeMessagingHost/`.
@Alex313031 Thanks for the clue. I will be closing this issue now.
