### ISSUE TITLE
When the bookmark is too much, open the stuck

### ISSUE THREAD

**Issue by a81n9** [Alex313031/thorium#870]
**System Details**
 - OS: Windows 10 Version 22H2
 - Thorium Version: 128.0.6613.189

**Problem**
When the bookmark is too much, open the stuck

Such as
There are only 10 bookmarks under my `Workspace` folder, which is very smooth to open.
But I have 500+ bookmarks under my `Issues` folder, which is a bit stuck when it is opened.

https://github.com/user-attachments/assets/937b76da-1571-4207-8b28-adcdafd64160

**Comment by Alex313031** [comment]
@gz83 @a81n9 Yeah, I mean. The reason is you have too many bookmarks in one folder. It's not a prob with Thorium.
