### ISSUE TITLE
Frame rate limited to 60 FPS

### ISSUE THREAD

**Issue by merll002** [Alex313031/thorium#879]
**System Details**
 - OS: [Mabox Linux (Manjaro based) - X11, Linux mint, Pop! OS]
 - Thorium Version [M128.0.6613.189]

**Problem**
There is a framerate limit of 60 FPS globally. 

**Did you read the FAQ?**
Yes!

I tried enabling GPU based flags: [#num-raster-threads](chrome://flags/#num-raster-threads), [#force-gpu-mem-available-mb](chrome://flags/#force-gpu-mem-available-mb), [#ignore-gpu-blocklist](chrome://flags/#ignore-gpu-blocklist), [#enable-gpu-rasterization](chrome://flags/#enable-gpu-rasterization), [#ozone-platform-hint](chrome://flags/#ozone-platform-hint), [#enable-drdc](chrome://flags/#enable-drdc), [#canvas-oop-rasterization](chrome://flags/#canvas-oop-rasterization) and [#use-gpu-scheduler-dfs](chrome://flags/#use-gpu-scheduler-dfs).

With and without flags makes no difference.

**Comment by merll002** [comment]
Unfortunately not. My screen is at 165hz and thorium is the only app which is capped at 60. Tried and tested on three distros

**Comment by james-1987** [comment]
Feels like something with you GPU, Driver, Screen or lack of proper settings in the Distro. I run CachyOS with Wayland, KDE, Nvidia (1080ti). I have 3840x1600 144hz screen WITH config to refresh rate of 144hz (i hope you change that setting). In F12 -> Console -> Hamburger Meny -> Rendering -> TICK Frame Rendering Stats. I get 144fps when something moves (using VRR on auto).

**Comment by merll002** [comment]
I have an AMD GPU and the display is set correctly on every distro, I have not heard of the rendering page in dev tools. Will check this tomorrow.

**Comment by james-1987** [comment]
Please do: `xrandr | grep '*'` Give output. 
If you want help, you need to give us info. Do you run display protocol Wayland (if wayland activate ozone) Or X? GTK or Qt based? Are you using AMDGPU or AMDGPU-PRO drivers? What generation of GPU?

**Comment by merll002** [comment]
I am using an Rx 6600 with non pro drivers. I tried mabox, linuxmint, elementaryos and pop os. I will upload the output of that command in a short while

**Comment by tr1xem** [comment]
do xrandr -r 165.00
then reboot and try
or install autorandr (better way) it would automatically do its thing

**Comment by merll002** [comment]
I will try this, but how would this be anything to do with it if my refresh rate is already set 165 in the settings of each distro and everything else is running at 165hz?

**Comment by merll002** [comment]
This hack doesn't seem to work with another monitor though.

**Comment by tr1xem** [comment]
Well No as i can see u had ur refresh rate set to 60 for everything (also idk why ur not on full resolution it is still fhd) 
For other monitors u can either use autorandr or set refresh rate for every monitor seprately (that depends on ur wm)

**Comment by merll002** [comment]
"Well its just i can see u had ur refresh rate set to 60 for everything" Definitely not! It's a known chrome issue apparently:
https://forum.manjaro.org/t/all-chromium-based-programs-are-running-only-at-60-fps/68175/2
https://forums.linuxmint.com/viewtopic.php?t=379670
annoying... 
I might switch to firefox
