### ISSUE TITLE
ceno network vpn 

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#90]
Hello, i find CENO (Censorship.No!) is a mobile web browser, built on Mozilla's Firefox for Android (Fennec). It uses peer-to-peer technology to deliver websites to your phone and caches popular content with cooperating peers. CENO can be used to bypass Internet censorship and help others retrieve blocked pages.

Sadly, there is no desktop version of this browser and Ouinet is an open source library enabling third party developers to incorporate the CENO network into their apps for peer-to-peer connectivity, so if t is possible, it will be awesome to take advantage of this vpn when using a computer via a web browser desktop and it will be great if this vpn can be integrated or used with Thorium browser desktop to avoid increasingly powerful censorship, thank you so much!

https://github.com/censorship-no/ceno-browser

https://github.com/equalitie/ouinet

**Comment by trimechee** [comment]
May be it seems my suggestion is stupid, i suggest that because i have seen that tor network is used by brave browser, tor browser, and even by extension browser for firefox, ok no problem  and even there is extension for firefox to be able to use i2p network...big brother is watching us son i sugeest tricks to bypss censorship...

**Comment by trimechee** [comment]
Yes, but we shoud have the choice, some users live in dictatorships that monitor and oppress them...

**Comment by Alex313031** [comment]
@trimechee Yeah, I wouldn't know how to do that. And any browser-only VPN like the one in brave or opera is of limited effect. It is best to use a full VPN that runs at the OS level.
