### ISSUE TITLE
[Error/Warning] Update repository needs some extra work to get the hash check working (w: the release file has no hash entry)

### ISSUE THREAD

**Issue by SoulInfernoDE** [Alex313031/thorium#91]
**System Details**
 - OS: Linux
 - Version 109.0.5361.0 (Official build) unstable, built on Ubuntu 22.04, running on bookworm/sid (64-Bit)

**Problem**
while doing` sudo apt update` i get this warning `no hash entry in Release-File /var/lib/apt/lists/dl.thorium.rocks_debian_dists_stable_Release`

**Screenshots**
![image](https://user-images.githubusercontent.com/3682343/197807716-5bb789c9-d42a-4d0c-9c3c-bde74693a269.png)

**Additional Notes**
It would be also nice if we can remove the ignored lines from apt for `apt update` for thorium:
```
Ign:8 https://dl.thorium.rocks/debian stable InRelease                         
Ign:9 https://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com vanessa InRelease
OK:10 https://repo.steampowered.com/steam stable InRelease                     
OK:11 https://dl.thorium.rocks/debian stable Release                           
OK:12 https://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com vanessa Release
OK:13 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease                 
Ign:14 https://dl.thorium.rocks/debian stable Release.gpg                      
OK:15 http://ppa.launchpad.net/jonmagon/kdiskmark/ubuntu jammy InRelease       
Ign:16 https://dl.thorium.rocks/debian stable/main Translation-de              
OK:17 https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04  InRelease
OK:18 https://apt.enpass.io stable InRelease                                   
Ign:19 https://dl.thorium.rocks/debian stable/main Translation-de_DE           
OK:20 https://repo.skype.com/deb stable InRelease                              
Ign:21 https://dl.thorium.rocks/debian stable/main Translation-en              
OK:22 http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu jammy InRelease         
Ign:23 https://dl.thorium.rocks/debian stable/main amd64 DEP-11 Metadata       
Ign:24 https://dl.thorium.rocks/debian stable/main DEP-11 48x48 Icons          
Ign:25 https://dl.thorium.rocks/debian stable/main DEP-11 64x64 Icons
Ign:26 https://dl.thorium.rocks/debian stable/main DEP-11 64x64@2 Icons
Ign:27 https://dl.thorium.rocks/debian stable/main DEP-11 128x128 Icons
Ign:28 https://dl.thorium.rocks/debian stable/main amd64 c-n-f Metadata
Ign:16 https://dl.thorium.rocks/debian stable/main Translation-de
Ign:19 https://dl.thorium.rocks/debian stable/main Translation-de_DE
Ign:21 https://dl.thorium.rocks/debian stable/main Translation-en
Ign:23 https://dl.thorium.rocks/debian stable/main amd64 DEP-11 Metadata
Ign:24 https://dl.thorium.rocks/debian stable/main DEP-11 48x48 Icons
Ign:25 https://dl.thorium.rocks/debian stable/main DEP-11 64x64 Icons
Ign:26 https://dl.thorium.rocks/debian stable/main DEP-11 64x64@2 Icons
Ign:27 https://dl.thorium.rocks/debian stable/main DEP-11 128x128 Icons
Ign:28 https://dl.thorium.rocks/debian stable/main amd64 c-n-f Metadata
Ign:16 https://dl.thorium.rocks/debian stable/main Translation-de
Ign:19 https://dl.thorium.rocks/debian stable/main Translation-de_DE
Ign:21 https://dl.thorium.rocks/debian stable/main Translation-en
OK:29 https://packages.teejeetech.com/ukuu/g6YLZAWavG/ubuntu/focal/amd64 stable InRelease
Ign:23 https://dl.thorium.rocks/debian stable/main amd64 DEP-11 Metadata
Ign:24 https://dl.thorium.rocks/debian stable/main DEP-11 48x48 Icons
Ign:25 https://dl.thorium.rocks/debian stable/main DEP-11 64x64 Icons
Ign:26 https://dl.thorium.rocks/debian stable/main DEP-11 64x64@2 Icons
Ign:27 https://dl.thorium.rocks/debian stable/main DEP-11 128x128 Icons
Ign:28 https://dl.thorium.rocks/debian stable/main amd64 c-n-f Metadata
Ign:16 https://dl.thorium.rocks/debian stable/main Translation-de
Ign:19 https://dl.thorium.rocks/debian stable/main Translation-de_DE
Ign:21 https://dl.thorium.rocks/debian stable/main Translation-en
Ign:23 https://dl.thorium.rocks/debian stable/main amd64 DEP-11 Metadata
Ign:24 https://dl.thorium.rocks/debian stable/main DEP-11 48x48 Icons
Ign:25 https://dl.thorium.rocks/debian stable/main DEP-11 64x64 Icons
Ign:26 https://dl.thorium.rocks/debian stable/main DEP-11 64x64@2 Icons
Ign:27 https://dl.thorium.rocks/debian stable/main DEP-11 128x128 Icons
Ign:28 https://dl.thorium.rocks/debian stable/main amd64 c-n-f Metadata
Ign:16 https://dl.thorium.rocks/debian stable/main Translation-de
Ign:19 https://dl.thorium.rocks/debian stable/main Translation-de_DE
Ign:21 https://dl.thorium.rocks/debian stable/main Translation-en
Ign:23 https://dl.thorium.rocks/debian stable/main amd64 DEP-11 Metadata
Ign:24 https://dl.thorium.rocks/debian stable/main DEP-11 48x48 Icons
Ign:25 https://dl.thorium.rocks/debian stable/main DEP-11 64x64 Icons
Ign:26 https://dl.thorium.rocks/debian stable/main DEP-11 64x64@2 Icons
Ign:27 https://dl.thorium.rocks/debian stable/main DEP-11 128x128 Icons
Ign:28 https://dl.thorium.rocks/debian stable/main amd64 c-n-f Metadata
Ign:16 https://dl.thorium.rocks/debian stable/main Translation-de
Ign:19 https://dl.thorium.rocks/debian stable/main Translation-de_DE
Ign:21 https://dl.thorium.rocks/debian stable/main Translation-en
Ign:23 https://dl.thorium.rocks/debian stable/main amd64 DEP-11 Metadata
Ign:24 https://dl.thorium.rocks/debian stable/main DEP-11 48x48 Icons
Ign:25 https://dl.thorium.rocks/debian stable/main DEP-11 64x64 Icons
Ign:26 https://dl.thorium.rocks/debian stable/main DEP-11 64x64@2 Icons
Ign:27 https://dl.thorium.rocks/debian stable/main DEP-11 128x128 Icons
Ign:28 https://dl.thorium.rocks/debian stable/main amd64 c-n-f Metadata
Ign:16 https://dl.thorium.rocks/debian stable/main Translation-de
Ign:19 https://dl.thorium.rocks/debian stable/main Translation-de_DE
Ign:21 https://dl.thorium.rocks/debian stable/main Translation-en
Ign:23 https://dl.thorium.rocks/debian stable/main amd64 DEP-11 Metadata
Ign:24 https://dl.thorium.rocks/debian stable/main DEP-11 48x48 Icons
Ign:25 https://dl.thorium.rocks/debian stable/main DEP-11 64x64 Icons
Ign:26 https://dl.thorium.rocks/debian stable/main DEP-11 64x64@2 Icons
Ign:27 https://dl.thorium.rocks/debian stable/main DEP-11 128x128 Icons
Ign:28 https://dl.thorium.rocks/debian stable/main amd64 c-n-f Metadata
```

This seems to be the Release file i guess:
![image](https://user-images.githubusercontent.com/3682343/197809139-8283e37b-645e-4abc-9753-341e213d4896.png)

And this is how it should kind of look like i guess: (taken from another repository for an example)
![image](https://user-images.githubusercontent.com/3682343/197809451-379bf11e-9a16-4b0f-a437-1e96161075f1.png)

**Comment by midzer** [comment]
Hi @SoulInfernoDE and thx for filing!

I am going to include those `md5`, `sha1` and `sha256` for upcoming release.

Have a nice week
midzer

**Comment by SoulInfernoDE** [comment]
Could you also please update your Readme on the githubfrontpage  to include easy installation instructions for your repo like you wrote it on the thorium webpage ?  Thanks @midzer  :heart_decoration: 

![image](https://user-images.githubusercontent.com/3682343/211159997-336e0b17-7d2d-464e-8b53-c8aa55c12486.png)

**Comment by LinuxOpa** [comment]
W: Kein Hash-Eintrag in Release-Datei /var/lib/apt/lists/dl.thorium.rocks_debian_dists_stable_Release

> @midzer Can you update the Release file with hashes of the packages.gz to avoid this warning.

please an example:

Architectures: amd64
Codename: stable
Components: main
Date: Sun, 26 Mar 2023 08:50:52 +0000
Description: Thorium Browser packages
Label: thorium
Origin: dl.thorium.rocks
Suite: stable

and now what to add here?

Thank you.

**Comment by midzer** [comment]
I've just added `md5`, `sha1` and `sha256` to the `Release` file. Please try again.

**Comment by LinuxOpa** [comment]
> I've just added `md5`, `sha1` and `sha256` to the `Release` file. Please try again.

done, it works. so far so good.

but now i get  constantly 
"Aktualisierung für 1 Paket verfügbar. Führen Sie »apt list --upgradable« aus, um es anzuzeigen."
every apt update, 
apt-upgrade install it, 
after apt-upgrade again
 "Aktualisierung für 1 Paket verfügbar. Führen Sie »apt list --upgradable« aus, um es anzuzeigen."

damned loop

**Comment by dmig** [comment]
There is something wrong with versioning, but I can't get what:
```
~> sudo apt show thorium-browser -a
Package: thorium-browser
Version: 111.0.5563.111-1
Priority: optional
Section: web
Maintainer: Thorium Linux Maintainers <alex313031@gmail.com>
Installed-Size: 613 MB
Provides: www-browser
Pre-Depends: dpkg (>= 1.14.0)
Depends: ca-certificates, fonts-liberation, libasound2 (>= 1.0.17), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.17), libcairo2 (>= 1.6.0), libcups2 (>= 1.6.0), libcurl3-gnutls | libcurl3-nss | libcurl4 | libcurl3, libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.75), libexpat1 (>= 2.0.1), libgbm1 (>= 17.1.0~rc2), libglib2.0-0 (>= 2.39.4), libgtk-3-0 (>= 3.9.10) | libgtk-4-1, libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.26), libpango-1.0-0 (>= 1.14.0), libu2f-udev, libvulkan1, libx11-6 (>= 2:1.4.99.1), libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.4-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.5.0), libxrandr2, wget, xdg-utils (>= 1.0.2)
Recommends: unrar, vdpau-driver-all, exo | exo-utils
Conflicts: thorium-browser-unstable
Replaces: thorium-browser-unstable, thorium-browser-stable
Download-Size: 115 MB
APT-Sources: https://dl.thorium.rocks/debian stable/main amd64 Packages
Description: The web browser from The Thorium Authors
 Thorium is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.

Package: thorium-browser
Version: 111.0.5563.111-1
Status: install ok installed
Priority: optional
Section: web
Maintainer: Thorium Linux Maintainers <alex313031@gmail.com>
Installed-Size: 613 MB
Provides: www-browser
Pre-Depends: dpkg (>= 1.14.0)
Depends: ca-certificates, fonts-liberation, libasound2 (>= 1.0.17), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.17), libcairo2 (>= 1.6.0), libcups2 (>= 1.6.0), libcurl3-gnutls | libcurl3-nss | libcurl4 | libcurl3, libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.75), libexpat1 (>= 2.0.1), libgbm1 (>= 17.1.0~rc2), libglib2.0-0 (>= 2.39.4), libgtk-3-0 (>= 3.9.10) | libgtk-4-1, libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.26), libpango-1.0-0 (>= 1.14.0), libu2f-udev, libvulkan1, libx11-6 (>= 2:1.4.99.1), libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.4-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.5.0), libxrandr2, wget, xdg-utils (>= 1.0.2)
Recommends: unrar, vdpau-driver-all, exo | exo-utils
Conflicts: thorium-browser-unstable
Replaces: thorium-browser-unstable
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: The web browser from The Thorium Authors
 Thorium is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
 ```

**Comment by LinuxOpa** [comment]
synaptic reports:
"This change is not coming from a source that supports changelogs.
Failed to fetch the changelog for thorium-browser
URI was: http://dl.thorium.rocks/dists/stable/main/binary-amd64/thorium-browser_111.0.5563.111-1_amd64.changelog"

"404 Not Found
nginx"

is there a "/debian" missing? -> http://dl.thorium.rocks/debian/dists/.....

maybe it helps

**Comment by LinuxOpa** [comment]
another one:

"Package: thorium-browser
Version: 111.0.5563.111-1
Architecture: amd64
Maintainer: Thorium Linux Maintainers <alex313031@gmail.com>
Installed-Size: 598544
Pre-Depends: dpkg (>= 1.14.0)
Depends: ca-certificates, fonts-liberation, libasound2 (>= 1.0.17), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.17), libcairo2 (>= 1.6.0), libcups2 (>= 1.6.0), libcurl3-gnutls | libcurl3-nss | libcurl4 | libcurl3, libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.75), libexpat1 (>= 2.0.1), libgbm1 (>= 17.1.0~rc2), libglib2.0-0 (>= 2.39.4), libgtk-3-0 (>= 3.9.10) | libgtk-4-1, libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.26), libpango-1.0-0 (>= 1.14.0), libu2f-udev, libvulkan1, libx11-6 (>= 2:1.4.99.1), libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.4-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.5.0), libxrandr2, wget, xdg-utils (>= 1.0.2)
Recommends: unrar, vdpau-driver-all, exo | exo-utils
Conflicts: thorium-browser-unstable
Replaces: thorium-browser-unstable, thorium-browser-stable
Provides: www-browser
Filename: dists/stable/main/binary-amd64/thorium-browser_111.0.5563.111-1_amd64.deb
Size: 114579536
MD5sum: 5e53dd928fb9e8442d4204d578d9de2b
SHA1: 388e8964719272325b607883ff38e4e317fd0262
SHA256: a5c33494ecd28aaf42a593ef5dac2cc2a686057005f633932808dc7dbaefb963
**Section: web**
Priority: optional
Description: The web browser from The Thorium Authors
 Thorium is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier."

thorium Section: web ?
in firefox Section: Internet
in chrome Section: Internet

maybe it helps

**Comment by SoulInfernoDE** [comment]
> Same here:
> 
> ```
> ~> sudo apt list --upgradable -a
> Listing... Done
> thorium-browser/stable 111.0.5563.111-1 amd64 [upgradable from: 111.0.5563.111-1]
> thorium-browser/now 111.0.5563.111-1 amd64 [installed,upgradable to: 111.0.5563.111-1]
> ```

could you check your added repositories as for me i dont get that versioning trouble:

`cat /etc/apt/sources.list.d/thorium*`

For me it shows only this:
`deb [trusted=yes arch=amd64] https://dl.thorium.rocks/debian/ stable main`

**Comment by LinuxOpa** [comment]
done:

sudo apt list --upgradable -a :
thorium-browser/stable 111.0.5563.111-1 amd64 [aktualisierbar von: 111.0.5563.111-1]
thorium-browser/now 111.0.5563.111-1 amd64  [Installiert,aktualisierbar auf: 111.0.5563.111-1]

cat /etc/apt/sources.list.d/thorium* :
deb [trusted=yes arch=amd64] https://dl.thorium.rocks/debian/ stable main

**Comment by LinuxOpa** [comment]
apt list --upgradable
Auflistung... Fertig
thorium-browser/stable 111.0.5563.111-1 amd64 [aktualisierbar von: 111.0.5563.111-1]
N: Es gibt 1 zusätzliche Version. Bitte verwenden Sie die Option »-a«, um sie anzuzeigen.

but this version is installed:
dpkg -l|grep thorium
ii  thorium-browser                                   111.0.5563.111-1                               amd64        The web browser from The Thorium Authors

**Comment by LinuxOpa** [comment]
> @LinuxOpa Try to `apt purge thorium*`, remove the `thorium.list` from your apt source, then `apt update`. Then re-add the `thorium.list` and install `thorium` package again.
> 
> Somehow apt caches things. Maybe there's some hicup.

all done, and:

"sudo apt upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete werden aktualisiert (Upgrade):
  thorium-browser
1 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 0 B von 115 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n]
Entpacken von thorium-browser (111.0.5563.111-1) über (111.0.5563.111-1) ..."

every time i do  sudo apt upgrade...

**Comment by LinuxOpa** [comment]
may be the reason is the same why i can't find thorium in synaptic...

**Comment by SoulInfernoDE** [comment]
Ah i see i have installed thorium-browser-unstable. Not tested the thorium-browser package.
![grafik](https://user-images.githubusercontent.com/3682343/230158495-c2f2f59c-e27f-4401-83b6-7522df323bf1.png)
![grafik](https://user-images.githubusercontent.com/3682343/230158627-4257d4a8-39e0-4339-b2e9-8813f33c112c.png)

**Comment by jstdk** [comment]
Still an issue, I created an issue for it here https://github.com/Alex313031/thorium/issues/145 as I was unaware of this discussion

**Comment by midzer** [comment]
I finally uploaded M112 to the debian repo.

**Comment by dmig** [comment]
Now apt reports:
```
Err:19 https://dl.thorium.rocks/debian stable/main amd64 Packages                                        
  File has unexpected size (1113 != 1006). Mirror sync in progress? [IP: 2a01:4f8:1c0c:4340::1 443]
  Hashes of expected file:
   - Filesize:1006 [weak]
   - SHA256:9d31bd6bc3b4102b5c7a784ee74f62545ad2f5ffb80e4cd70a0d61a22315937a
   - SHA1:55cc84e187ebdf20266c5ebc1ffb4e736e2d471e [weak]
   - MD5Sum:95c3ef653f5c7f9868cc9046ea5ce36d [weak]
  Release file created at: Sun, 14 May 2023 22:16:52 +0000
```

**Comment by midzer** [comment]
Thanks for reporting, @dmig.

I hope it's fixed now. Please try again.

**Comment by SoulInfernoDE** [comment]
Hey @midzer getting this now after trying to fresh install from the same repo:

``
Err:1 https://dl.thorium.rocks/debian stable/main amd64 thorium-browser amd64 112.0.5615.166-1
  404  Not Found [IP: 2a01:4f8:1c0c:4340::1 443]
E: Fehlschlag beim Holen von https://dl.thorium.rocks/debian/./thorium-browser_112.0.5615.166-1_amd64.deb 404  Not Found [IP: 2a01:4f8:1c0c:4340::1 443]
``

**Comment by midzer** [comment]
Please, try again @SoulInfernoDE 
I've fixed the paths...

**Comment by Alex313031** [comment]
@dmig @SoulInfernoDE @LinuxOpa @midzer Looks like the repo is fixed now.

**Comment by SoulInfernoDE** [comment]
@Alex313031 @dmig @LinuxOpa @midzer can confirm it works for me, too.

Thank you midzer for your work and patience with us :heart:

**Comment by midzer** [comment]
Good, @SoulInfernoDE :)

I hope I get it done correctly next time (saved those commands in a .txt file). Feel free to reopen, if something is not working again.

Thanks and have a nice week!
