### ISSUE TITLE
[Linux] Wayland text_input_manager_v3 support

### ISSUE THREAD

**Issue by icepie** [Alex313031/thorium#92]
**Is your feature request related to a problem? Please describe.**

support text_input_manager_v3 for wayland users, especially CJK users

**Describe the solution you'd like, including relevant patches or source**

https://chromium-review.googlesource.com/c/chromium/src/+/3750452

**Additional Notes**

 maybe the patch will work for it, I didn't test.

**Comment by chenzaichun** [comment]
Would this patch be merged?

**Comment by chenzaichun** [comment]
> > Would this patch be merged?
> 
> @chenzaichun According to the link given above, this patch is still in WIP status, and the person who uploaded the patchset is still modifying the code

Thanks.

**Comment by Alex313031** [comment]
@icepie @chenzaichun @icepie @yochananmarqos Will probably not merge this, since the original was rejected by the chrome team, and this one is a WIP.
