### ISSUE TITLE
Disable cups printf functions on build flags if can build .

### ISSUE THREAD

**Issue by meleehao** [Alex313031/thorium#95]
As for as know , cups that print server for like-unix system , but now we could not  need it ,Hope you choose enable or disable it , for web browser , cups is unuseal for many people that use browse world wide web  contents .
                                                                                          Thanks!

**Comment by funymeleehao** [comment]
when i not install cups and run thorimum it depend on libcups that cups software .

**Comment by Alex313031** [comment]
@funymeleehao @meleehao Chromium based browsers will not run without cups installed. The code inside it for printing expects it to be there.
